/*
 * Generates css/tokens.css (CSS custom properties) from src/index.ts.
 *   node scripts/build-css.ts          write the file
 *   node scripts/build-css.ts --check  exit 1 if the file is out of date
 */
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";

import { tokens, type ColorScheme, type Fluid } from "../src/index.ts";

const OUT = fileURLToPath(new URL("../css/tokens.css", import.meta.url));
const MIN_VW = 360;
const MAX_VW = 1280;

const kebab = (s: string) => s.replace(/[A-Z]/g, (c) => `-${c.toLowerCase()}`);
const num = (n: number) => String(Number(n.toFixed(4)));
const rem = (px: number) => (px === 0 ? "0" : `${num(px / 16)}rem`);

// Linear interpolation between MIN_VW and MAX_VW, clamped at both ends.
function fluid({ min, max }: Fluid): string {
  const slope = (max - min) / (MAX_VW - MIN_VW);
  const intercept = min - slope * MIN_VW;
  return `clamp(${rem(min)}, ${rem(intercept)} + ${num(slope * 100)}vw, ${rem(max)})`;
}

const size = (v: number | Fluid) => (typeof v === "number" ? rem(v) : fluid(v));

function colorVars(scheme: ColorScheme, shadow: Record<string, string>): string[] {
  return [
    ...Object.entries(scheme).map(([k, v]) => `--color-${kebab(k)}: ${v};`),
    ...Object.entries(shadow).map(([k, v]) => `--shadow-${k}: ${v};`),
  ];
}

function changedOnly(base: ColorScheme, scheme: ColorScheme): ColorScheme {
  return Object.fromEntries(
    Object.entries(scheme).filter(([k, v]) => base[k as keyof ColorScheme] !== v),
  ) as ColorScheme;
}

const t = tokens;
const bp = t.breakpoint;

const rootVars = [
  "/* Color */",
  ...colorVars(t.color.light, t.shadow.light),
  "",
  "/* Typography */",
  `--font-sans: var(--font-geist-sans), ${t.font.sans};`,
  `--font-mono: var(--font-geist-mono), ${t.font.mono};`,
  ...Object.entries(t.fontSize).map(([k, v]) => `--text-${k}: ${size(v)};`),
  ...Object.entries(t.fontWeight).map(([k, v]) => `--weight-${k}: ${v};`),
  ...Object.entries(t.leading).map(([k, v]) => `--leading-${k}: ${v};`),
  ...Object.entries(t.tracking).map(([k, v]) => `--tracking-${k}: ${v === 0 ? 0 : `${v}em`};`),
  `--measure: ${t.measure};`,
  "",
  "/* Spacing */",
  ...Object.entries(t.space).map(([k, v]) => `--space-${k}: ${rem(v)};`),
  `--gutter: ${fluid(t.gutter)};`,
  `--section-space: ${fluid(t.sectionSpace)};`,
  "",
  "/* Containers */",
  ...Object.entries(t.container).map(([k, v]) =>
    k === "default" ? `--container: ${rem(v)};` : `--container-${k}: ${rem(v)};`,
  ),
  "",
  "/* Radius & borders */",
  ...Object.entries(t.radius).map(([k, v]) => `--radius-${k}: ${k === "pill" ? `${v}px` : rem(v)};`),
  "--radius-round: 50%;",
  `--border-width: ${t.borderWidth}px;`,
  "--border: var(--border-width) solid var(--color-border);",
  "--border-strong: var(--border-width) solid var(--color-border-strong);",
  "",
  "/* Motion */",
  ...Object.entries(t.duration).map(([k, v]) => `--duration-${k}: ${v}ms;`),
  ...Object.entries(t.easing).map(([k, v]) => `--ease-${k}: cubic-bezier(${v.join(", ")});`),
  "",
  "/* Focus, layering, controls */",
  "--focus-ring: 0 0 0 2px var(--color-bg), 0 0 0 4px var(--color-focus);",
  ...Object.entries(t.zIndex).map(([k, v]) => `--z-${k}: ${v};`),
  ...Object.entries(t.control).map(([k, v]) => `--control-${k}: ${rem(v)};`),
  "",
  "color-scheme: light;",
];

const darkVars = [
  ...colorVars(changedOnly(t.color.light, t.color.dark), t.shadow.dark),
  "color-scheme: dark;",
];

const indent = (lines: string[], n: number) =>
  lines.map((l) => (l ? " ".repeat(n) + l : "")).join("\n");

const css = `/*
 * GENERATED by shared/design-tokens/scripts/build-css.ts — do not edit.
 * Source of truth: shared/design-tokens/src/index.ts
 *
 * Breakpoints (literals in media queries; CSS variables can't be used there):
 *   sm ${rem(bp.sm)} (${bp.sm}px) · md ${rem(bp.md)} (${bp.md}px) · lg ${rem(bp.lg)} (${bp.lg}px) · xl ${rem(bp.xl)} (${bp.xl}px)
 */

@layer tokens {
  :root {
${indent(rootVars, 4)}
  }

  @media (prefers-color-scheme: dark) {
    :root:not([data-theme="light"]) {
${indent(darkVars, 6)}
    }
  }

  :root[data-theme="dark"] {
${indent(darkVars, 4)}
  }
}
`;

if (process.argv.includes("--check")) {
  let current = "";
  try {
    current = readFileSync(OUT, "utf8");
  } catch {
    // missing file counts as stale
  }
  if (current !== css) {
    console.error("css/tokens.css is out of date. Run: npm run build (in shared/design-tokens)");
    process.exit(1);
  }
  console.log("css/tokens.css is up to date.");
} else {
  writeFileSync(OUT, css);
  console.log(`Wrote ${OUT}`);
}
