"""Contract every candidate generator implements, plus its data gate."""
from pathlib import Path
from typing import Protocol


class CandidateModel(Protocol):
    name: str

    def fit(self, data: object) -> None: ...
    def candidates(self, subject: str, k: int) -> list[tuple[str, float]]: ...
    def save(self, path: Path) -> None: ...
    def load(self, path: Path) -> None: ...
