// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: content.sql

package store

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

const contentGetHelp = `-- name: ContentGetHelp :one
select id, site, topic, slug, title, body, status, published_at, created_at, updated_at from content.help_articles where site = $1 and slug = $2 and status = 'published'
`

type ContentGetHelpParams struct {
	Site string `json:"site"`
	Slug string `json:"slug"`
}

func (q *Queries) ContentGetHelp(ctx context.Context, arg ContentGetHelpParams) (ContentHelpArticle, error) {
	row := q.db.QueryRow(ctx, contentGetHelp, arg.Site, arg.Slug)
	var i ContentHelpArticle
	err := row.Scan(
		&i.ID,
		&i.Site,
		&i.Topic,
		&i.Slug,
		&i.Title,
		&i.Body,
		&i.Status,
		&i.PublishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const contentGetPage = `-- name: ContentGetPage :one
select id, site, slug, title, body, status, published_at, updated_by, approved_by, created_at, updated_at from content.cms_pages where id = $1
`

func (q *Queries) ContentGetPage(ctx context.Context, id uuid.UUID) (ContentCmsPage, error) {
	row := q.db.QueryRow(ctx, contentGetPage, id)
	var i ContentCmsPage
	err := row.Scan(
		&i.ID,
		&i.Site,
		&i.Slug,
		&i.Title,
		&i.Body,
		&i.Status,
		&i.PublishedAt,
		&i.UpdatedBy,
		&i.ApprovedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const contentGetPublishedPage = `-- name: ContentGetPublishedPage :one

select id, site, slug, title, body, status, published_at, updated_by, approved_by, created_at, updated_at from content.cms_pages where site = $1 and slug = $2 and status = 'published'
`

type ContentGetPublishedPageParams struct {
	Site string `json:"site"`
	Slug string `json:"slug"`
}

// Content: CMS pages, banners, help articles.
func (q *Queries) ContentGetPublishedPage(ctx context.Context, arg ContentGetPublishedPageParams) (ContentCmsPage, error) {
	row := q.db.QueryRow(ctx, contentGetPublishedPage, arg.Site, arg.Slug)
	var i ContentCmsPage
	err := row.Scan(
		&i.ID,
		&i.Site,
		&i.Slug,
		&i.Title,
		&i.Body,
		&i.Status,
		&i.PublishedAt,
		&i.UpdatedBy,
		&i.ApprovedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const contentListBanners = `-- name: ContentListBanners :many
select id, site, placement, title, image_file_id, link_url, starts_at, ends_at, position, status, created_at, updated_at from content.banners order by site, placement, position
`

func (q *Queries) ContentListBanners(ctx context.Context) ([]ContentBanner, error) {
	rows, err := q.db.Query(ctx, contentListBanners)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ContentBanner{}
	for rows.Next() {
		var i ContentBanner
		if err := rows.Scan(
			&i.ID,
			&i.Site,
			&i.Placement,
			&i.Title,
			&i.ImageFileID,
			&i.LinkUrl,
			&i.StartsAt,
			&i.EndsAt,
			&i.Position,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const contentListHelp = `-- name: ContentListHelp :many
select id, site, topic, slug, title, published_at from content.help_articles where site = $1 and status = 'published' order by topic, title
`

type ContentListHelpRow struct {
	ID          uuid.UUID  `json:"id"`
	Site        string     `json:"site"`
	Topic       string     `json:"topic"`
	Slug        string     `json:"slug"`
	Title       string     `json:"title"`
	PublishedAt *time.Time `json:"publishedAt"`
}

func (q *Queries) ContentListHelp(ctx context.Context, site string) ([]ContentListHelpRow, error) {
	rows, err := q.db.Query(ctx, contentListHelp, site)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ContentListHelpRow{}
	for rows.Next() {
		var i ContentListHelpRow
		if err := rows.Scan(
			&i.ID,
			&i.Site,
			&i.Topic,
			&i.Slug,
			&i.Title,
			&i.PublishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const contentListPages = `-- name: ContentListPages :many
select id, site, slug, title, body, status, published_at, updated_by, approved_by, created_at, updated_at from content.cms_pages where ($1::text is null or site = $1) order by site, slug
`

func (q *Queries) ContentListPages(ctx context.Context, site *string) ([]ContentCmsPage, error) {
	rows, err := q.db.Query(ctx, contentListPages, site)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ContentCmsPage{}
	for rows.Next() {
		var i ContentCmsPage
		if err := rows.Scan(
			&i.ID,
			&i.Site,
			&i.Slug,
			&i.Title,
			&i.Body,
			&i.Status,
			&i.PublishedAt,
			&i.UpdatedBy,
			&i.ApprovedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const contentLiveBanners = `-- name: ContentLiveBanners :many
select id, site, placement, title, image_file_id, link_url, starts_at, ends_at, position, status, created_at, updated_at from content.banners
where site = $1 and ($2::text is null or placement = $2) and status = 'live'
  and (starts_at is null or starts_at <= now()) and (ends_at is null or ends_at > now())
order by placement, position
`

type ContentLiveBannersParams struct {
	Site      string  `json:"site"`
	Placement *string `json:"placement"`
}

func (q *Queries) ContentLiveBanners(ctx context.Context, arg ContentLiveBannersParams) ([]ContentBanner, error) {
	rows, err := q.db.Query(ctx, contentLiveBanners, arg.Site, arg.Placement)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ContentBanner{}
	for rows.Next() {
		var i ContentBanner
		if err := rows.Scan(
			&i.ID,
			&i.Site,
			&i.Placement,
			&i.Title,
			&i.ImageFileID,
			&i.LinkUrl,
			&i.StartsAt,
			&i.EndsAt,
			&i.Position,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const contentSetBannerStatus = `-- name: ContentSetBannerStatus :one
update content.banners set status = $2 where id = $1 returning id, site, placement, title, image_file_id, link_url, starts_at, ends_at, position, status, created_at, updated_at
`

type ContentSetBannerStatusParams struct {
	ID     uuid.UUID `json:"id"`
	Status string    `json:"status"`
}

func (q *Queries) ContentSetBannerStatus(ctx context.Context, arg ContentSetBannerStatusParams) (ContentBanner, error) {
	row := q.db.QueryRow(ctx, contentSetBannerStatus, arg.ID, arg.Status)
	var i ContentBanner
	err := row.Scan(
		&i.ID,
		&i.Site,
		&i.Placement,
		&i.Title,
		&i.ImageFileID,
		&i.LinkUrl,
		&i.StartsAt,
		&i.EndsAt,
		&i.Position,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const contentSetPageStatus = `-- name: ContentSetPageStatus :one
update content.cms_pages set status = $2, approved_by = $3,
  published_at = case when $2 = 'published' then now() else published_at end
where id = $1 returning id, site, slug, title, body, status, published_at, updated_by, approved_by, created_at, updated_at
`

type ContentSetPageStatusParams struct {
	ID         uuid.UUID  `json:"id"`
	Status     string     `json:"status"`
	ApprovedBy *uuid.UUID `json:"approvedBy"`
}

func (q *Queries) ContentSetPageStatus(ctx context.Context, arg ContentSetPageStatusParams) (ContentCmsPage, error) {
	row := q.db.QueryRow(ctx, contentSetPageStatus, arg.ID, arg.Status, arg.ApprovedBy)
	var i ContentCmsPage
	err := row.Scan(
		&i.ID,
		&i.Site,
		&i.Slug,
		&i.Title,
		&i.Body,
		&i.Status,
		&i.PublishedAt,
		&i.UpdatedBy,
		&i.ApprovedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const contentUpsertBanner = `-- name: ContentUpsertBanner :one
insert into content.banners (site, placement, title, image_file_id, link_url, starts_at, ends_at, position, status)
values ($1, $2, $3, $4, $5, $6, $7, $8, $9)
returning id, site, placement, title, image_file_id, link_url, starts_at, ends_at, position, status, created_at, updated_at
`

type ContentUpsertBannerParams struct {
	Site        string     `json:"site"`
	Placement   string     `json:"placement"`
	Title       string     `json:"title"`
	ImageFileID *uuid.UUID `json:"imageFileId"`
	LinkUrl     string     `json:"linkUrl"`
	StartsAt    *time.Time `json:"startsAt"`
	EndsAt      *time.Time `json:"endsAt"`
	Position    int32      `json:"position"`
	Status      string     `json:"status"`
}

func (q *Queries) ContentUpsertBanner(ctx context.Context, arg ContentUpsertBannerParams) (ContentBanner, error) {
	row := q.db.QueryRow(ctx, contentUpsertBanner,
		arg.Site,
		arg.Placement,
		arg.Title,
		arg.ImageFileID,
		arg.LinkUrl,
		arg.StartsAt,
		arg.EndsAt,
		arg.Position,
		arg.Status,
	)
	var i ContentBanner
	err := row.Scan(
		&i.ID,
		&i.Site,
		&i.Placement,
		&i.Title,
		&i.ImageFileID,
		&i.LinkUrl,
		&i.StartsAt,
		&i.EndsAt,
		&i.Position,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const contentUpsertHelp = `-- name: ContentUpsertHelp :one
insert into content.help_articles (site, topic, slug, title, body, status, published_at)
values ($1, $2, $3, $4, $5, $6, case when $6 = 'published' then now() end)
on conflict (site, slug) do update set topic = excluded.topic, title = excluded.title, body = excluded.body, status = excluded.status,
  published_at = case when excluded.status = 'published' then now() else content.help_articles.published_at end
returning id, site, topic, slug, title, body, status, published_at, created_at, updated_at
`

type ContentUpsertHelpParams struct {
	Site   string          `json:"site"`
	Topic  string          `json:"topic"`
	Slug   string          `json:"slug"`
	Title  string          `json:"title"`
	Body   json.RawMessage `json:"body"`
	Status string          `json:"status"`
}

func (q *Queries) ContentUpsertHelp(ctx context.Context, arg ContentUpsertHelpParams) (ContentHelpArticle, error) {
	row := q.db.QueryRow(ctx, contentUpsertHelp,
		arg.Site,
		arg.Topic,
		arg.Slug,
		arg.Title,
		arg.Body,
		arg.Status,
	)
	var i ContentHelpArticle
	err := row.Scan(
		&i.ID,
		&i.Site,
		&i.Topic,
		&i.Slug,
		&i.Title,
		&i.Body,
		&i.Status,
		&i.PublishedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const contentUpsertPage = `-- name: ContentUpsertPage :one
insert into content.cms_pages (site, slug, title, body, status, updated_by) values ($1, $2, $3, $4, 'draft', $5)
on conflict (site, slug) do update set title = excluded.title, body = excluded.body, status = 'draft', updated_by = excluded.updated_by, approved_by = null
returning id, site, slug, title, body, status, published_at, updated_by, approved_by, created_at, updated_at
`

type ContentUpsertPageParams struct {
	Site      string          `json:"site"`
	Slug      string          `json:"slug"`
	Title     string          `json:"title"`
	Body      json.RawMessage `json:"body"`
	UpdatedBy *uuid.UUID      `json:"updatedBy"`
}

func (q *Queries) ContentUpsertPage(ctx context.Context, arg ContentUpsertPageParams) (ContentCmsPage, error) {
	row := q.db.QueryRow(ctx, contentUpsertPage,
		arg.Site,
		arg.Slug,
		arg.Title,
		arg.Body,
		arg.UpdatedBy,
	)
	var i ContentCmsPage
	err := row.Scan(
		&i.ID,
		&i.Site,
		&i.Slug,
		&i.Title,
		&i.Body,
		&i.Status,
		&i.PublishedAt,
		&i.UpdatedBy,
		&i.ApprovedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
