// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: copyfrom.go

package store

import (
	"context"
)

// iteratorForPersonalisationInsertEvent implements pgx.CopyFromSource.
type iteratorForPersonalisationInsertEvent struct {
	rows                 []PersonalisationInsertEventParams
	skippedFirstNextCall bool
}

func (r *iteratorForPersonalisationInsertEvent) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForPersonalisationInsertEvent) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].OccurredAt,
		r.rows[0].AnonymousID,
		r.rows[0].UserID,
		r.rows[0].SessionID,
		r.rows[0].EventType,
		r.rows[0].App,
		r.rows[0].Surface,
		r.rows[0].ProductID,
		r.rows[0].ListingID,
		r.rows[0].CategoryID,
		r.rows[0].QueryNorm,
		r.rows[0].ResultsCount,
		r.rows[0].Position,
		r.rows[0].RecRequestID,
		r.rows[0].Strategy,
		r.rows[0].StateCode,
		r.rows[0].DeviceClass,
		r.rows[0].Properties,
	}, nil
}

func (r iteratorForPersonalisationInsertEvent) Err() error {
	return nil
}

// Behaviour events and identity links (docs/recommendations.md; consent-gated).
func (q *Queries) PersonalisationInsertEvent(ctx context.Context, arg []PersonalisationInsertEventParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"personalisation", "user_events"}, []string{"occurred_at", "anonymous_id", "user_id", "session_id", "event_type", "app", "surface", "product_id", "listing_id", "category_id", "query_norm", "results_count", "position", "rec_request_id", "strategy", "state_code", "device_class", "properties"}, &iteratorForPersonalisationInsertEvent{rows: arg})
}
