// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: finance.sql

package store

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const financeAccountBalance = `-- name: FinanceAccountBalance :one
select coalesce(sum(e.amount_kobo), 0)::bigint from finance.ledger_entries e join finance.ledger_accounts a on a.id = e.account_id where a.code = $1
`

func (q *Queries) FinanceAccountBalance(ctx context.Context, code string) (int64, error) {
	row := q.db.QueryRow(ctx, financeAccountBalance, code)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const financeAccountBalances = `-- name: FinanceAccountBalances :many
select a.id, a.code, a.name, a.kind, coalesce(sum(e.amount_kobo), 0)::bigint as balance_kobo
from finance.ledger_accounts a left join finance.ledger_entries e on e.account_id = a.id
group by a.id order by a.code
`

type FinanceAccountBalancesRow struct {
	ID          uuid.UUID `json:"id"`
	Code        string    `json:"code"`
	Name        string    `json:"name"`
	Kind        string    `json:"kind"`
	BalanceKobo int64     `json:"balanceKobo"`
}

func (q *Queries) FinanceAccountBalances(ctx context.Context) ([]FinanceAccountBalancesRow, error) {
	rows, err := q.db.Query(ctx, financeAccountBalances)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FinanceAccountBalancesRow{}
	for rows.Next() {
		var i FinanceAccountBalancesRow
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Name,
			&i.Kind,
			&i.BalanceKobo,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const financeAccountLedger = `-- name: FinanceAccountLedger :many
select e.id, e.amount_kobo, e.created_at, j.id as journal_id, j.kind, j.posting_key, j.reference_type, j.reference_id, j.memo
from finance.ledger_entries e join finance.ledger_journals j on j.id = e.journal_id
join finance.ledger_accounts a on a.id = e.account_id
where a.code = $1 and ($3::timestamptz is null or e.created_at < $3)
order by e.created_at desc limit $2
`

type FinanceAccountLedgerParams struct {
	Code   string     `json:"code"`
	Limit  int32      `json:"limit"`
	Before *time.Time `json:"before"`
}

type FinanceAccountLedgerRow struct {
	ID            uuid.UUID `json:"id"`
	AmountKobo    int64     `json:"amountKobo"`
	CreatedAt     time.Time `json:"createdAt"`
	JournalID     uuid.UUID `json:"journalId"`
	Kind          string    `json:"kind"`
	PostingKey    string    `json:"postingKey"`
	ReferenceType string    `json:"referenceType"`
	ReferenceID   uuid.UUID `json:"referenceId"`
	Memo          *string   `json:"memo"`
}

func (q *Queries) FinanceAccountLedger(ctx context.Context, arg FinanceAccountLedgerParams) ([]FinanceAccountLedgerRow, error) {
	rows, err := q.db.Query(ctx, financeAccountLedger, arg.Code, arg.Limit, arg.Before)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FinanceAccountLedgerRow{}
	for rows.Next() {
		var i FinanceAccountLedgerRow
		if err := rows.Scan(
			&i.ID,
			&i.AmountKobo,
			&i.CreatedAt,
			&i.JournalID,
			&i.Kind,
			&i.PostingKey,
			&i.ReferenceType,
			&i.ReferenceID,
			&i.Memo,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const financeClosePeriod = `-- name: FinanceClosePeriod :one
insert into finance.accounting_periods (month, status, closed_by, closed_at) values ($1, 'closed', $2, now())
on conflict (month) do update set status = 'closed', closed_by = excluded.closed_by, closed_at = now()
where finance.accounting_periods.status <> 'closed'
returning month, status, closed_by, closed_at
`

type FinanceClosePeriodParams struct {
	Month    time.Time  `json:"month"`
	ClosedBy *uuid.UUID `json:"closedBy"`
}

func (q *Queries) FinanceClosePeriod(ctx context.Context, arg FinanceClosePeriodParams) (FinanceAccountingPeriod, error) {
	row := q.db.QueryRow(ctx, financeClosePeriod, arg.Month, arg.ClosedBy)
	var i FinanceAccountingPeriod
	err := row.Scan(
		&i.Month,
		&i.Status,
		&i.ClosedBy,
		&i.ClosedAt,
	)
	return i, err
}

const financeDashboard = `-- name: FinanceDashboard :one
select
  coalesce(sum(e.amount_kobo) filter (where a.code like 'clearing:%'), 0)::bigint as clearing_kobo,
  coalesce(sum(e.amount_kobo) filter (where a.code like 'bank:%'), 0)::bigint as bank_kobo,
  coalesce(-sum(e.amount_kobo) filter (where a.code like 'seller_payable:%'), 0)::bigint as owed_to_sellers_kobo,
  coalesce(-sum(e.amount_kobo) filter (where a.code = 'liability:vat'), 0)::bigint as vat_kobo,
  coalesce(-sum(e.amount_kobo) filter (where a.kind = 'revenue'), 0)::bigint as revenue_kobo,
  coalesce(-sum(e.amount_kobo) filter (where a.code = 'liability:customer_refunds'), 0)::bigint as refunds_owed_kobo,
  coalesce(sum(e.amount_kobo) filter (where a.kind = 'expense'), 0)::bigint as expenses_kobo
from finance.ledger_entries e join finance.ledger_accounts a on a.id = e.account_id
`

type FinanceDashboardRow struct {
	ClearingKobo      int64 `json:"clearingKobo"`
	BankKobo          int64 `json:"bankKobo"`
	OwedToSellersKobo int64 `json:"owedToSellersKobo"`
	VatKobo           int64 `json:"vatKobo"`
	RevenueKobo       int64 `json:"revenueKobo"`
	RefundsOwedKobo   int64 `json:"refundsOwedKobo"`
	ExpensesKobo      int64 `json:"expensesKobo"`
}

func (q *Queries) FinanceDashboard(ctx context.Context) (FinanceDashboardRow, error) {
	row := q.db.QueryRow(ctx, financeDashboard)
	var i FinanceDashboardRow
	err := row.Scan(
		&i.ClearingKobo,
		&i.BankKobo,
		&i.OwedToSellersKobo,
		&i.VatKobo,
		&i.RevenueKobo,
		&i.RefundsOwedKobo,
		&i.ExpensesKobo,
	)
	return i, err
}

const financeEnsureAccount = `-- name: FinanceEnsureAccount :one

insert into finance.ledger_accounts (code, name, kind, seller_id, user_id) values ($1, $2, $3, $4, $5)
on conflict (code) do update set code = excluded.code
returning id, code, name, kind, seller_id, user_id, created_at
`

type FinanceEnsureAccountParams struct {
	Code     string     `json:"code"`
	Name     string     `json:"name"`
	Kind     string     `json:"kind"`
	SellerID *uuid.UUID `json:"sellerId"`
	UserID   *uuid.UUID `json:"userId"`
}

// Finance: chart of accounts, double-entry journals, periods (docs/payments-finance.md §4).
// Get-or-create an account by code (seller payables and store credit accounts are created on first use).
func (q *Queries) FinanceEnsureAccount(ctx context.Context, arg FinanceEnsureAccountParams) (FinanceLedgerAccount, error) {
	row := q.db.QueryRow(ctx, financeEnsureAccount,
		arg.Code,
		arg.Name,
		arg.Kind,
		arg.SellerID,
		arg.UserID,
	)
	var i FinanceLedgerAccount
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.Kind,
		&i.SellerID,
		&i.UserID,
		&i.CreatedAt,
	)
	return i, err
}

const financeGetAccountByCode = `-- name: FinanceGetAccountByCode :one
select id, code, name, kind, seller_id, user_id, created_at from finance.ledger_accounts where code = $1
`

func (q *Queries) FinanceGetAccountByCode(ctx context.Context, code string) (FinanceLedgerAccount, error) {
	row := q.db.QueryRow(ctx, financeGetAccountByCode, code)
	var i FinanceLedgerAccount
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.Kind,
		&i.SellerID,
		&i.UserID,
		&i.CreatedAt,
	)
	return i, err
}

const financeGetJournal = `-- name: FinanceGetJournal :one
select id, posting_key, kind, reference_type, reference_id, period, reverses_journal_id, memo, posted_by, posted_at from finance.ledger_journals where id = $1
`

func (q *Queries) FinanceGetJournal(ctx context.Context, id uuid.UUID) (FinanceLedgerJournal, error) {
	row := q.db.QueryRow(ctx, financeGetJournal, id)
	var i FinanceLedgerJournal
	err := row.Scan(
		&i.ID,
		&i.PostingKey,
		&i.Kind,
		&i.ReferenceType,
		&i.ReferenceID,
		&i.Period,
		&i.ReversesJournalID,
		&i.Memo,
		&i.PostedBy,
		&i.PostedAt,
	)
	return i, err
}

const financeGetJournalByKey = `-- name: FinanceGetJournalByKey :one
select id, posting_key, kind, reference_type, reference_id, period, reverses_journal_id, memo, posted_by, posted_at from finance.ledger_journals where posting_key = $1
`

func (q *Queries) FinanceGetJournalByKey(ctx context.Context, postingKey string) (FinanceLedgerJournal, error) {
	row := q.db.QueryRow(ctx, financeGetJournalByKey, postingKey)
	var i FinanceLedgerJournal
	err := row.Scan(
		&i.ID,
		&i.PostingKey,
		&i.Kind,
		&i.ReferenceType,
		&i.ReferenceID,
		&i.Period,
		&i.ReversesJournalID,
		&i.Memo,
		&i.PostedBy,
		&i.PostedAt,
	)
	return i, err
}

const financeGetPeriod = `-- name: FinanceGetPeriod :one
select month, status, closed_by, closed_at from finance.accounting_periods where month = $1
`

func (q *Queries) FinanceGetPeriod(ctx context.Context, month time.Time) (FinanceAccountingPeriod, error) {
	row := q.db.QueryRow(ctx, financeGetPeriod, month)
	var i FinanceAccountingPeriod
	err := row.Scan(
		&i.Month,
		&i.Status,
		&i.ClosedBy,
		&i.ClosedAt,
	)
	return i, err
}

const financeInsertEntry = `-- name: FinanceInsertEntry :exec
insert into finance.ledger_entries (journal_id, account_id, amount_kobo) values ($1, $2, $3)
`

type FinanceInsertEntryParams struct {
	JournalID  uuid.UUID `json:"journalId"`
	AccountID  uuid.UUID `json:"accountId"`
	AmountKobo int64     `json:"amountKobo"`
}

func (q *Queries) FinanceInsertEntry(ctx context.Context, arg FinanceInsertEntryParams) error {
	_, err := q.db.Exec(ctx, financeInsertEntry, arg.JournalID, arg.AccountID, arg.AmountKobo)
	return err
}

const financeInsertJournal = `-- name: FinanceInsertJournal :one
insert into finance.ledger_journals (posting_key, kind, reference_type, reference_id, reverses_journal_id, memo, posted_by)
values ($1, $2, $3, $4, $5, $6, $7)
on conflict (posting_key) do nothing
returning id, posting_key, kind, reference_type, reference_id, period, reverses_journal_id, memo, posted_by, posted_at
`

type FinanceInsertJournalParams struct {
	PostingKey        string     `json:"postingKey"`
	Kind              string     `json:"kind"`
	ReferenceType     string     `json:"referenceType"`
	ReferenceID       uuid.UUID  `json:"referenceId"`
	ReversesJournalID *uuid.UUID `json:"reversesJournalId"`
	Memo              *string    `json:"memo"`
	PostedBy          *uuid.UUID `json:"postedBy"`
}

// Idempotent by posting_key: returns no row when the key was already posted.
func (q *Queries) FinanceInsertJournal(ctx context.Context, arg FinanceInsertJournalParams) (FinanceLedgerJournal, error) {
	row := q.db.QueryRow(ctx, financeInsertJournal,
		arg.PostingKey,
		arg.Kind,
		arg.ReferenceType,
		arg.ReferenceID,
		arg.ReversesJournalID,
		arg.Memo,
		arg.PostedBy,
	)
	var i FinanceLedgerJournal
	err := row.Scan(
		&i.ID,
		&i.PostingKey,
		&i.Kind,
		&i.ReferenceType,
		&i.ReferenceID,
		&i.Period,
		&i.ReversesJournalID,
		&i.Memo,
		&i.PostedBy,
		&i.PostedAt,
	)
	return i, err
}

const financeJournalEntries = `-- name: FinanceJournalEntries :many
select e.id, e.journal_id, e.account_id, e.amount_kobo, e.currency, e.created_at, a.code as account_code, a.name as account_name, a.kind as account_kind
from finance.ledger_entries e join finance.ledger_accounts a on a.id = e.account_id
where e.journal_id = $1 order by e.amount_kobo desc
`

type FinanceJournalEntriesRow struct {
	ID          uuid.UUID `json:"id"`
	JournalID   uuid.UUID `json:"journalId"`
	AccountID   uuid.UUID `json:"accountId"`
	AmountKobo  int64     `json:"amountKobo"`
	Currency    string    `json:"currency"`
	CreatedAt   time.Time `json:"createdAt"`
	AccountCode string    `json:"accountCode"`
	AccountName string    `json:"accountName"`
	AccountKind string    `json:"accountKind"`
}

func (q *Queries) FinanceJournalEntries(ctx context.Context, journalID uuid.UUID) ([]FinanceJournalEntriesRow, error) {
	rows, err := q.db.Query(ctx, financeJournalEntries, journalID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FinanceJournalEntriesRow{}
	for rows.Next() {
		var i FinanceJournalEntriesRow
		if err := rows.Scan(
			&i.ID,
			&i.JournalID,
			&i.AccountID,
			&i.AmountKobo,
			&i.Currency,
			&i.CreatedAt,
			&i.AccountCode,
			&i.AccountName,
			&i.AccountKind,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const financeJournalsForReference = `-- name: FinanceJournalsForReference :many
select id, posting_key, kind, reference_type, reference_id, period, reverses_journal_id, memo, posted_by, posted_at from finance.ledger_journals where reference_type = $1 and reference_id = $2 order by posted_at
`

type FinanceJournalsForReferenceParams struct {
	ReferenceType string    `json:"referenceType"`
	ReferenceID   uuid.UUID `json:"referenceId"`
}

func (q *Queries) FinanceJournalsForReference(ctx context.Context, arg FinanceJournalsForReferenceParams) ([]FinanceLedgerJournal, error) {
	rows, err := q.db.Query(ctx, financeJournalsForReference, arg.ReferenceType, arg.ReferenceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FinanceLedgerJournal{}
	for rows.Next() {
		var i FinanceLedgerJournal
		if err := rows.Scan(
			&i.ID,
			&i.PostingKey,
			&i.Kind,
			&i.ReferenceType,
			&i.ReferenceID,
			&i.Period,
			&i.ReversesJournalID,
			&i.Memo,
			&i.PostedBy,
			&i.PostedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const financeListJournals = `-- name: FinanceListJournals :many
select id, posting_key, kind, reference_type, reference_id, period, reverses_journal_id, memo, posted_by, posted_at from finance.ledger_journals
where ($2::text is null or kind = $2)
  and ($3::timestamptz is null or posted_at < $3)
order by posted_at desc limit $1
`

type FinanceListJournalsParams struct {
	Limit  int32      `json:"limit"`
	Kind   *string    `json:"kind"`
	Before *time.Time `json:"before"`
}

func (q *Queries) FinanceListJournals(ctx context.Context, arg FinanceListJournalsParams) ([]FinanceLedgerJournal, error) {
	rows, err := q.db.Query(ctx, financeListJournals, arg.Limit, arg.Kind, arg.Before)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FinanceLedgerJournal{}
	for rows.Next() {
		var i FinanceLedgerJournal
		if err := rows.Scan(
			&i.ID,
			&i.PostingKey,
			&i.Kind,
			&i.ReferenceType,
			&i.ReferenceID,
			&i.Period,
			&i.ReversesJournalID,
			&i.Memo,
			&i.PostedBy,
			&i.PostedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const financeListPeriods = `-- name: FinanceListPeriods :many
select month, status, closed_by, closed_at from finance.accounting_periods order by month desc limit 24
`

func (q *Queries) FinanceListPeriods(ctx context.Context) ([]FinanceAccountingPeriod, error) {
	rows, err := q.db.Query(ctx, financeListPeriods)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FinanceAccountingPeriod{}
	for rows.Next() {
		var i FinanceAccountingPeriod
		if err := rows.Scan(
			&i.Month,
			&i.Status,
			&i.ClosedBy,
			&i.ClosedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const financeSucceededPaymentsWithoutSale = `-- name: FinanceSucceededPaymentsWithoutSale :many
select p.id, p.provider, p.provider_reference, p.amount_kobo from payments.payments p
where p.status = 'succeeded' and p.order_id is not null
  and not exists (select 1 from finance.ledger_journals j where j.posting_key = 'payment:' || p.id::text || ':captured')
limit 100
`

type FinanceSucceededPaymentsWithoutSaleRow struct {
	ID                uuid.UUID `json:"id"`
	Provider          string    `json:"provider"`
	ProviderReference *string   `json:"providerReference"`
	AmountKobo        int64     `json:"amountKobo"`
}

// Nightly check: every succeeded order payment has exactly one sale journal.
func (q *Queries) FinanceSucceededPaymentsWithoutSale(ctx context.Context) ([]FinanceSucceededPaymentsWithoutSaleRow, error) {
	rows, err := q.db.Query(ctx, financeSucceededPaymentsWithoutSale)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FinanceSucceededPaymentsWithoutSaleRow{}
	for rows.Next() {
		var i FinanceSucceededPaymentsWithoutSaleRow
		if err := rows.Scan(
			&i.ID,
			&i.Provider,
			&i.ProviderReference,
			&i.AmountKobo,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const financeTrialBalance = `-- name: FinanceTrialBalance :one
select coalesce(sum(amount_kobo), 0)::bigint as total, count(*)::bigint as entries from finance.ledger_entries
`

type FinanceTrialBalanceRow struct {
	Total   int64 `json:"total"`
	Entries int64 `json:"entries"`
}

// Must always be zero: every journal balances.
func (q *Queries) FinanceTrialBalance(ctx context.Context) (FinanceTrialBalanceRow, error) {
	row := q.db.QueryRow(ctx, financeTrialBalance)
	var i FinanceTrialBalanceRow
	err := row.Scan(&i.Total, &i.Entries)
	return i, err
}
