// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: fulfilment.sql

package store

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const fulfilmentAddManifestParcel = `-- name: FulfilmentAddManifestParcel :exec
insert into fulfilment.manifest_parcels (manifest_id, parcel_id, scanned_at) values ($1, $2, now())
`

type FulfilmentAddManifestParcelParams struct {
	ManifestID uuid.UUID `json:"manifestId"`
	ParcelID   uuid.UUID `json:"parcelId"`
}

func (q *Queries) FulfilmentAddManifestParcel(ctx context.Context, arg FulfilmentAddManifestParcelParams) error {
	_, err := q.db.Exec(ctx, fulfilmentAddManifestParcel, arg.ManifestID, arg.ParcelID)
	return err
}

const fulfilmentAddPickItem = `-- name: FulfilmentAddPickItem :one
insert into fulfilment.pick_list_items (pick_list_id, fulfilment_id, order_line_id, bin_id, quantity) values ($1, $2, $3, $4, $5) returning id, pick_list_id, fulfilment_id, order_line_id, bin_id, quantity, picked_qty, device_unit_id, scanned_at
`

type FulfilmentAddPickItemParams struct {
	PickListID   uuid.UUID  `json:"pickListId"`
	FulfilmentID uuid.UUID  `json:"fulfilmentId"`
	OrderLineID  uuid.UUID  `json:"orderLineId"`
	BinID        *uuid.UUID `json:"binId"`
	Quantity     int32      `json:"quantity"`
}

func (q *Queries) FulfilmentAddPickItem(ctx context.Context, arg FulfilmentAddPickItemParams) (FulfilmentPickListItem, error) {
	row := q.db.QueryRow(ctx, fulfilmentAddPickItem,
		arg.PickListID,
		arg.FulfilmentID,
		arg.OrderLineID,
		arg.BinID,
		arg.Quantity,
	)
	var i FulfilmentPickListItem
	err := row.Scan(
		&i.ID,
		&i.PickListID,
		&i.FulfilmentID,
		&i.OrderLineID,
		&i.BinID,
		&i.Quantity,
		&i.PickedQty,
		&i.DeviceUnitID,
		&i.ScannedAt,
	)
	return i, err
}

const fulfilmentCreateManifest = `-- name: FulfilmentCreateManifest :one
insert into fulfilment.manifests (warehouse_id, rider_id, carrier_id, created_by) values ($1, $2, $3, $4) returning id, warehouse_id, rider_id, carrier_id, signed_by_name, signed_at, created_by, created_at
`

type FulfilmentCreateManifestParams struct {
	WarehouseID uuid.UUID  `json:"warehouseId"`
	RiderID     *uuid.UUID `json:"riderId"`
	CarrierID   *uuid.UUID `json:"carrierId"`
	CreatedBy   uuid.UUID  `json:"createdBy"`
}

func (q *Queries) FulfilmentCreateManifest(ctx context.Context, arg FulfilmentCreateManifestParams) (FulfilmentManifest, error) {
	row := q.db.QueryRow(ctx, fulfilmentCreateManifest,
		arg.WarehouseID,
		arg.RiderID,
		arg.CarrierID,
		arg.CreatedBy,
	)
	var i FulfilmentManifest
	err := row.Scan(
		&i.ID,
		&i.WarehouseID,
		&i.RiderID,
		&i.CarrierID,
		&i.SignedByName,
		&i.SignedAt,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const fulfilmentCreatePackRecord = `-- name: FulfilmentCreatePackRecord :one
insert into fulfilment.pack_records (fulfilment_id, parcel_id, weight_grams, expected_weight_grams, packed_by) values ($1, $2, $3, $4, $5) returning id, fulfilment_id, parcel_id, weight_grams, expected_weight_grams, flagged, packed_by, packed_at
`

type FulfilmentCreatePackRecordParams struct {
	FulfilmentID        uuid.UUID `json:"fulfilmentId"`
	ParcelID            uuid.UUID `json:"parcelId"`
	WeightGrams         int32     `json:"weightGrams"`
	ExpectedWeightGrams *int32    `json:"expectedWeightGrams"`
	PackedBy            uuid.UUID `json:"packedBy"`
}

func (q *Queries) FulfilmentCreatePackRecord(ctx context.Context, arg FulfilmentCreatePackRecordParams) (FulfilmentPackRecord, error) {
	row := q.db.QueryRow(ctx, fulfilmentCreatePackRecord,
		arg.FulfilmentID,
		arg.ParcelID,
		arg.WeightGrams,
		arg.ExpectedWeightGrams,
		arg.PackedBy,
	)
	var i FulfilmentPackRecord
	err := row.Scan(
		&i.ID,
		&i.FulfilmentID,
		&i.ParcelID,
		&i.WeightGrams,
		&i.ExpectedWeightGrams,
		&i.Flagged,
		&i.PackedBy,
		&i.PackedAt,
	)
	return i, err
}

const fulfilmentCreateParcel = `-- name: FulfilmentCreateParcel :one
insert into fulfilment.parcels (fulfilment_id, label_code, box_code, weight_grams) values ($1, $2, $3, $4) returning id, fulfilment_id, label_code, box_code, weight_grams, scanned_at, created_at
`

type FulfilmentCreateParcelParams struct {
	FulfilmentID uuid.UUID `json:"fulfilmentId"`
	LabelCode    string    `json:"labelCode"`
	BoxCode      *string   `json:"boxCode"`
	WeightGrams  *int32    `json:"weightGrams"`
}

func (q *Queries) FulfilmentCreateParcel(ctx context.Context, arg FulfilmentCreateParcelParams) (FulfilmentParcel, error) {
	row := q.db.QueryRow(ctx, fulfilmentCreateParcel,
		arg.FulfilmentID,
		arg.LabelCode,
		arg.BoxCode,
		arg.WeightGrams,
	)
	var i FulfilmentParcel
	err := row.Scan(
		&i.ID,
		&i.FulfilmentID,
		&i.LabelCode,
		&i.BoxCode,
		&i.WeightGrams,
		&i.ScannedAt,
		&i.CreatedAt,
	)
	return i, err
}

const fulfilmentCreatePickList = `-- name: FulfilmentCreatePickList :one
insert into fulfilment.pick_lists (warehouse_id, wave_at, zone) values ($1, now(), $2) returning id, warehouse_id, wave_at, zone, status, picker_id, created_at, updated_at
`

type FulfilmentCreatePickListParams struct {
	WarehouseID uuid.UUID `json:"warehouseId"`
	Zone        *string   `json:"zone"`
}

func (q *Queries) FulfilmentCreatePickList(ctx context.Context, arg FulfilmentCreatePickListParams) (FulfilmentPickList, error) {
	row := q.db.QueryRow(ctx, fulfilmentCreatePickList, arg.WarehouseID, arg.Zone)
	var i FulfilmentPickList
	err := row.Scan(
		&i.ID,
		&i.WarehouseID,
		&i.WaveAt,
		&i.Zone,
		&i.Status,
		&i.PickerID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const fulfilmentCreateShipment = `-- name: FulfilmentCreateShipment :one
insert into fulfilment.shipments (fulfilment_id, carrier_id, carrier_name, tracking_number, label_file_id) values ($1, $2, $3, $4, $5) returning id, fulfilment_id, carrier_id, carrier_name, tracking_number, label_file_id, status, created_at, updated_at
`

type FulfilmentCreateShipmentParams struct {
	FulfilmentID   uuid.UUID  `json:"fulfilmentId"`
	CarrierID      *uuid.UUID `json:"carrierId"`
	CarrierName    *string    `json:"carrierName"`
	TrackingNumber string     `json:"trackingNumber"`
	LabelFileID    *uuid.UUID `json:"labelFileId"`
}

func (q *Queries) FulfilmentCreateShipment(ctx context.Context, arg FulfilmentCreateShipmentParams) (FulfilmentShipment, error) {
	row := q.db.QueryRow(ctx, fulfilmentCreateShipment,
		arg.FulfilmentID,
		arg.CarrierID,
		arg.CarrierName,
		arg.TrackingNumber,
		arg.LabelFileID,
	)
	var i FulfilmentShipment
	err := row.Scan(
		&i.ID,
		&i.FulfilmentID,
		&i.CarrierID,
		&i.CarrierName,
		&i.TrackingNumber,
		&i.LabelFileID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const fulfilmentExpectedWeight = `-- name: FulfilmentExpectedWeight :one
select coalesce(sum(coalesce(v.weight_grams, 0) * ol.quantity), 0)::int
from sales.order_lines ol join catalog.product_variants v on v.id = ol.variant_id
where ol.fulfilment_id = $1 and ol.cancelled_at is null
`

func (q *Queries) FulfilmentExpectedWeight(ctx context.Context, fulfilmentID uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, fulfilmentExpectedWeight, fulfilmentID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const fulfilmentGetCarrierByCode = `-- name: FulfilmentGetCarrierByCode :one
select id, code, name, is_active, created_at from fulfilment.carriers where code = $1
`

func (q *Queries) FulfilmentGetCarrierByCode(ctx context.Context, code string) (FulfilmentCarrier, error) {
	row := q.db.QueryRow(ctx, fulfilmentGetCarrierByCode, code)
	var i FulfilmentCarrier
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const fulfilmentGetManifest = `-- name: FulfilmentGetManifest :one
select id, warehouse_id, rider_id, carrier_id, signed_by_name, signed_at, created_by, created_at from fulfilment.manifests where id = $1
`

func (q *Queries) FulfilmentGetManifest(ctx context.Context, id uuid.UUID) (FulfilmentManifest, error) {
	row := q.db.QueryRow(ctx, fulfilmentGetManifest, id)
	var i FulfilmentManifest
	err := row.Scan(
		&i.ID,
		&i.WarehouseID,
		&i.RiderID,
		&i.CarrierID,
		&i.SignedByName,
		&i.SignedAt,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const fulfilmentGetManifestForUpdate = `-- name: FulfilmentGetManifestForUpdate :one
select id, warehouse_id, rider_id, carrier_id, signed_by_name, signed_at, created_by, created_at from fulfilment.manifests where id = $1 for update
`

func (q *Queries) FulfilmentGetManifestForUpdate(ctx context.Context, id uuid.UUID) (FulfilmentManifest, error) {
	row := q.db.QueryRow(ctx, fulfilmentGetManifestForUpdate, id)
	var i FulfilmentManifest
	err := row.Scan(
		&i.ID,
		&i.WarehouseID,
		&i.RiderID,
		&i.CarrierID,
		&i.SignedByName,
		&i.SignedAt,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const fulfilmentGetParcel = `-- name: FulfilmentGetParcel :one
select id, fulfilment_id, label_code, box_code, weight_grams, scanned_at, created_at from fulfilment.parcels where id = $1
`

func (q *Queries) FulfilmentGetParcel(ctx context.Context, id uuid.UUID) (FulfilmentParcel, error) {
	row := q.db.QueryRow(ctx, fulfilmentGetParcel, id)
	var i FulfilmentParcel
	err := row.Scan(
		&i.ID,
		&i.FulfilmentID,
		&i.LabelCode,
		&i.BoxCode,
		&i.WeightGrams,
		&i.ScannedAt,
		&i.CreatedAt,
	)
	return i, err
}

const fulfilmentGetPickList = `-- name: FulfilmentGetPickList :one
select id, warehouse_id, wave_at, zone, status, picker_id, created_at, updated_at from fulfilment.pick_lists where id = $1
`

func (q *Queries) FulfilmentGetPickList(ctx context.Context, id uuid.UUID) (FulfilmentPickList, error) {
	row := q.db.QueryRow(ctx, fulfilmentGetPickList, id)
	var i FulfilmentPickList
	err := row.Scan(
		&i.ID,
		&i.WarehouseID,
		&i.WaveAt,
		&i.Zone,
		&i.Status,
		&i.PickerID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const fulfilmentGetPickListForUpdate = `-- name: FulfilmentGetPickListForUpdate :one
select id, warehouse_id, wave_at, zone, status, picker_id, created_at, updated_at from fulfilment.pick_lists where id = $1 for update
`

func (q *Queries) FulfilmentGetPickListForUpdate(ctx context.Context, id uuid.UUID) (FulfilmentPickList, error) {
	row := q.db.QueryRow(ctx, fulfilmentGetPickListForUpdate, id)
	var i FulfilmentPickList
	err := row.Scan(
		&i.ID,
		&i.WarehouseID,
		&i.WaveAt,
		&i.Zone,
		&i.Status,
		&i.PickerID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const fulfilmentInsertSLAEvent = `-- name: FulfilmentInsertSLAEvent :exec
insert into fulfilment.seller_sla_events (seller_id, fulfilment_id, kind) values ($1, $2, $3) on conflict do nothing
`

type FulfilmentInsertSLAEventParams struct {
	SellerID     uuid.UUID `json:"sellerId"`
	FulfilmentID uuid.UUID `json:"fulfilmentId"`
	Kind         string    `json:"kind"`
}

func (q *Queries) FulfilmentInsertSLAEvent(ctx context.Context, arg FulfilmentInsertSLAEventParams) error {
	_, err := q.db.Exec(ctx, fulfilmentInsertSLAEvent, arg.SellerID, arg.FulfilmentID, arg.Kind)
	return err
}

const fulfilmentInsertShipmentEvent = `-- name: FulfilmentInsertShipmentEvent :one
insert into fulfilment.shipment_events (shipment_id, carrier_event_id, status, location, occurred_at) values ($1, $2, $3, $4, $5)
on conflict (shipment_id, carrier_event_id) do nothing returning id, shipment_id, carrier_event_id, status, location, occurred_at, received_at
`

type FulfilmentInsertShipmentEventParams struct {
	ShipmentID     uuid.UUID `json:"shipmentId"`
	CarrierEventID *string   `json:"carrierEventId"`
	Status         string    `json:"status"`
	Location       *string   `json:"location"`
	OccurredAt     time.Time `json:"occurredAt"`
}

func (q *Queries) FulfilmentInsertShipmentEvent(ctx context.Context, arg FulfilmentInsertShipmentEventParams) (FulfilmentShipmentEvent, error) {
	row := q.db.QueryRow(ctx, fulfilmentInsertShipmentEvent,
		arg.ShipmentID,
		arg.CarrierEventID,
		arg.Status,
		arg.Location,
		arg.OccurredAt,
	)
	var i FulfilmentShipmentEvent
	err := row.Scan(
		&i.ID,
		&i.ShipmentID,
		&i.CarrierEventID,
		&i.Status,
		&i.Location,
		&i.OccurredAt,
		&i.ReceivedAt,
	)
	return i, err
}

const fulfilmentListCarriers = `-- name: FulfilmentListCarriers :many
select id, code, name, is_active, created_at from fulfilment.carriers order by name
`

func (q *Queries) FulfilmentListCarriers(ctx context.Context) ([]FulfilmentCarrier, error) {
	rows, err := q.db.Query(ctx, fulfilmentListCarriers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FulfilmentCarrier{}
	for rows.Next() {
		var i FulfilmentCarrier
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Name,
			&i.IsActive,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const fulfilmentListManifests = `-- name: FulfilmentListManifests :many
select id, warehouse_id, rider_id, carrier_id, signed_by_name, signed_at, created_by, created_at from fulfilment.manifests where warehouse_id = $1 order by created_at desc limit 100
`

func (q *Queries) FulfilmentListManifests(ctx context.Context, warehouseID uuid.UUID) ([]FulfilmentManifest, error) {
	rows, err := q.db.Query(ctx, fulfilmentListManifests, warehouseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FulfilmentManifest{}
	for rows.Next() {
		var i FulfilmentManifest
		if err := rows.Scan(
			&i.ID,
			&i.WarehouseID,
			&i.RiderID,
			&i.CarrierID,
			&i.SignedByName,
			&i.SignedAt,
			&i.CreatedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const fulfilmentListPickLists = `-- name: FulfilmentListPickLists :many
select pl.id, pl.warehouse_id, pl.wave_at, pl.zone, pl.status, pl.picker_id, pl.created_at, pl.updated_at, (select count(*) from fulfilment.pick_list_items i where i.pick_list_id = pl.id)::int as items,
       (select count(*) from fulfilment.pick_list_items i where i.pick_list_id = pl.id and i.picked_qty = i.quantity)::int as items_done
from fulfilment.pick_lists pl
where pl.warehouse_id = $1 and ($2::text is null or pl.status = $2)
order by pl.wave_at desc limit 100
`

type FulfilmentListPickListsParams struct {
	WarehouseID uuid.UUID `json:"warehouseId"`
	Status      *string   `json:"status"`
}

type FulfilmentListPickListsRow struct {
	ID          uuid.UUID  `json:"id"`
	WarehouseID uuid.UUID  `json:"warehouseId"`
	WaveAt      time.Time  `json:"waveAt"`
	Zone        *string    `json:"zone"`
	Status      string     `json:"status"`
	PickerID    *uuid.UUID `json:"pickerId"`
	CreatedAt   time.Time  `json:"createdAt"`
	UpdatedAt   time.Time  `json:"updatedAt"`
	Items       int32      `json:"items"`
	ItemsDone   int32      `json:"itemsDone"`
}

func (q *Queries) FulfilmentListPickLists(ctx context.Context, arg FulfilmentListPickListsParams) ([]FulfilmentListPickListsRow, error) {
	rows, err := q.db.Query(ctx, fulfilmentListPickLists, arg.WarehouseID, arg.Status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FulfilmentListPickListsRow{}
	for rows.Next() {
		var i FulfilmentListPickListsRow
		if err := rows.Scan(
			&i.ID,
			&i.WarehouseID,
			&i.WaveAt,
			&i.Zone,
			&i.Status,
			&i.PickerID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Items,
			&i.ItemsDone,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const fulfilmentManifestParcels = `-- name: FulfilmentManifestParcels :many
select p.id, p.fulfilment_id, p.label_code, p.box_code, p.weight_grams, p.scanned_at, p.created_at, mp.scanned_at as manifest_scanned_at from fulfilment.manifest_parcels mp join fulfilment.parcels p on p.id = mp.parcel_id
where mp.manifest_id = $1 order by p.label_code
`

type FulfilmentManifestParcelsRow struct {
	ID                uuid.UUID  `json:"id"`
	FulfilmentID      uuid.UUID  `json:"fulfilmentId"`
	LabelCode         string     `json:"labelCode"`
	BoxCode           *string    `json:"boxCode"`
	WeightGrams       *int32     `json:"weightGrams"`
	ScannedAt         *time.Time `json:"scannedAt"`
	CreatedAt         time.Time  `json:"createdAt"`
	ManifestScannedAt *time.Time `json:"manifestScannedAt"`
}

func (q *Queries) FulfilmentManifestParcels(ctx context.Context, manifestID uuid.UUID) ([]FulfilmentManifestParcelsRow, error) {
	rows, err := q.db.Query(ctx, fulfilmentManifestParcels, manifestID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FulfilmentManifestParcelsRow{}
	for rows.Next() {
		var i FulfilmentManifestParcelsRow
		if err := rows.Scan(
			&i.ID,
			&i.FulfilmentID,
			&i.LabelCode,
			&i.BoxCode,
			&i.WeightGrams,
			&i.ScannedAt,
			&i.CreatedAt,
			&i.ManifestScannedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const fulfilmentMarkParcelScanned = `-- name: FulfilmentMarkParcelScanned :exec
update fulfilment.parcels set scanned_at = now() where id = $1
`

func (q *Queries) FulfilmentMarkParcelScanned(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, fulfilmentMarkParcelScanned, id)
	return err
}

const fulfilmentParcelByLabel = `-- name: FulfilmentParcelByLabel :one
select id, fulfilment_id, label_code, box_code, weight_grams, scanned_at, created_at from fulfilment.parcels where label_code = $1
`

func (q *Queries) FulfilmentParcelByLabel(ctx context.Context, labelCode string) (FulfilmentParcel, error) {
	row := q.db.QueryRow(ctx, fulfilmentParcelByLabel, labelCode)
	var i FulfilmentParcel
	err := row.Scan(
		&i.ID,
		&i.FulfilmentID,
		&i.LabelCode,
		&i.BoxCode,
		&i.WeightGrams,
		&i.ScannedAt,
		&i.CreatedAt,
	)
	return i, err
}

const fulfilmentParcelsForFulfilment = `-- name: FulfilmentParcelsForFulfilment :many
select id, fulfilment_id, label_code, box_code, weight_grams, scanned_at, created_at from fulfilment.parcels where fulfilment_id = $1 order by created_at
`

func (q *Queries) FulfilmentParcelsForFulfilment(ctx context.Context, fulfilmentID uuid.UUID) ([]FulfilmentParcel, error) {
	rows, err := q.db.Query(ctx, fulfilmentParcelsForFulfilment, fulfilmentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FulfilmentParcel{}
	for rows.Next() {
		var i FulfilmentParcel
		if err := rows.Scan(
			&i.ID,
			&i.FulfilmentID,
			&i.LabelCode,
			&i.BoxCode,
			&i.WeightGrams,
			&i.ScannedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const fulfilmentPickItems = `-- name: FulfilmentPickItems :many
select i.id, i.pick_list_id, i.fulfilment_id, i.order_line_id, i.bin_id, i.quantity, i.picked_qty, i.device_unit_id, i.scanned_at, ol.product_name, ol.variant_name, ol.sku, ol.variant_id, ol.condition, ol.seller_id, v.is_serialised, b.code as bin_code
from fulfilment.pick_list_items i
join sales.order_lines ol on ol.id = i.order_line_id
join catalog.product_variants v on v.id = ol.variant_id
left join inventory.bin_locations b on b.id = i.bin_id
where i.pick_list_id = $1 order by b.code nulls last, ol.sku
`

type FulfilmentPickItemsRow struct {
	ID           uuid.UUID  `json:"id"`
	PickListID   uuid.UUID  `json:"pickListId"`
	FulfilmentID uuid.UUID  `json:"fulfilmentId"`
	OrderLineID  uuid.UUID  `json:"orderLineId"`
	BinID        *uuid.UUID `json:"binId"`
	Quantity     int32      `json:"quantity"`
	PickedQty    int32      `json:"pickedQty"`
	DeviceUnitID *uuid.UUID `json:"deviceUnitId"`
	ScannedAt    *time.Time `json:"scannedAt"`
	ProductName  string     `json:"productName"`
	VariantName  string     `json:"variantName"`
	Sku          string     `json:"sku"`
	VariantID    uuid.UUID  `json:"variantId"`
	Condition    string     `json:"condition"`
	SellerID     uuid.UUID  `json:"sellerId"`
	IsSerialised bool       `json:"isSerialised"`
	BinCode      *string    `json:"binCode"`
}

func (q *Queries) FulfilmentPickItems(ctx context.Context, pickListID uuid.UUID) ([]FulfilmentPickItemsRow, error) {
	rows, err := q.db.Query(ctx, fulfilmentPickItems, pickListID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FulfilmentPickItemsRow{}
	for rows.Next() {
		var i FulfilmentPickItemsRow
		if err := rows.Scan(
			&i.ID,
			&i.PickListID,
			&i.FulfilmentID,
			&i.OrderLineID,
			&i.BinID,
			&i.Quantity,
			&i.PickedQty,
			&i.DeviceUnitID,
			&i.ScannedAt,
			&i.ProductName,
			&i.VariantName,
			&i.Sku,
			&i.VariantID,
			&i.Condition,
			&i.SellerID,
			&i.IsSerialised,
			&i.BinCode,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const fulfilmentPickListOpenItems = `-- name: FulfilmentPickListOpenItems :one
select count(*)::int from fulfilment.pick_list_items where pick_list_id = $1 and picked_qty < quantity
`

func (q *Queries) FulfilmentPickListOpenItems(ctx context.Context, pickListID uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, fulfilmentPickListOpenItems, pickListID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const fulfilmentScanItem = `-- name: FulfilmentScanItem :one
update fulfilment.pick_list_items set picked_qty = picked_qty + $1::int, scanned_at = now(),
  device_unit_id = coalesce($2, device_unit_id)
where pick_list_id = $3 and order_line_id = $4 and picked_qty + $1::int <= quantity
returning id, pick_list_id, fulfilment_id, order_line_id, bin_id, quantity, picked_qty, device_unit_id, scanned_at
`

type FulfilmentScanItemParams struct {
	Qty          int32      `json:"qty"`
	DeviceUnitID *uuid.UUID `json:"deviceUnitId"`
	PickListID   uuid.UUID  `json:"pickListId"`
	OrderLineID  uuid.UUID  `json:"orderLineId"`
}

// Conditional: never picks more than ordered.
func (q *Queries) FulfilmentScanItem(ctx context.Context, arg FulfilmentScanItemParams) (FulfilmentPickListItem, error) {
	row := q.db.QueryRow(ctx, fulfilmentScanItem,
		arg.Qty,
		arg.DeviceUnitID,
		arg.PickListID,
		arg.OrderLineID,
	)
	var i FulfilmentPickListItem
	err := row.Scan(
		&i.ID,
		&i.PickListID,
		&i.FulfilmentID,
		&i.OrderLineID,
		&i.BinID,
		&i.Quantity,
		&i.PickedQty,
		&i.DeviceUnitID,
		&i.ScannedAt,
	)
	return i, err
}

const fulfilmentSellerSLAStats = `-- name: FulfilmentSellerSLAStats :one
select count(*) filter (where kind = 'late_accept')::int as late_accept, count(*) filter (where kind = 'late_pack')::int as late_pack,
       count(*) filter (where kind = 'seller_cancel')::int as seller_cancel, count(*) filter (where kind = 'late_handover')::int as late_handover
from fulfilment.seller_sla_events where seller_id = $1 and created_at > now() - interval '90 days'
`

type FulfilmentSellerSLAStatsRow struct {
	LateAccept   int32 `json:"lateAccept"`
	LatePack     int32 `json:"latePack"`
	SellerCancel int32 `json:"sellerCancel"`
	LateHandover int32 `json:"lateHandover"`
}

func (q *Queries) FulfilmentSellerSLAStats(ctx context.Context, sellerID uuid.UUID) (FulfilmentSellerSLAStatsRow, error) {
	row := q.db.QueryRow(ctx, fulfilmentSellerSLAStats, sellerID)
	var i FulfilmentSellerSLAStatsRow
	err := row.Scan(
		&i.LateAccept,
		&i.LatePack,
		&i.SellerCancel,
		&i.LateHandover,
	)
	return i, err
}

const fulfilmentSetPickListStatus = `-- name: FulfilmentSetPickListStatus :one
update fulfilment.pick_lists set status = $2, picker_id = coalesce($3, picker_id) where id = $1 returning id, warehouse_id, wave_at, zone, status, picker_id, created_at, updated_at
`

type FulfilmentSetPickListStatusParams struct {
	ID       uuid.UUID  `json:"id"`
	Status   string     `json:"status"`
	PickerID *uuid.UUID `json:"pickerId"`
}

func (q *Queries) FulfilmentSetPickListStatus(ctx context.Context, arg FulfilmentSetPickListStatusParams) (FulfilmentPickList, error) {
	row := q.db.QueryRow(ctx, fulfilmentSetPickListStatus, arg.ID, arg.Status, arg.PickerID)
	var i FulfilmentPickList
	err := row.Scan(
		&i.ID,
		&i.WarehouseID,
		&i.WaveAt,
		&i.Zone,
		&i.Status,
		&i.PickerID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const fulfilmentSetShipmentStatus = `-- name: FulfilmentSetShipmentStatus :one
update fulfilment.shipments set status = $2 where id = $1 returning id, fulfilment_id, carrier_id, carrier_name, tracking_number, label_file_id, status, created_at, updated_at
`

type FulfilmentSetShipmentStatusParams struct {
	ID     uuid.UUID `json:"id"`
	Status string    `json:"status"`
}

func (q *Queries) FulfilmentSetShipmentStatus(ctx context.Context, arg FulfilmentSetShipmentStatusParams) (FulfilmentShipment, error) {
	row := q.db.QueryRow(ctx, fulfilmentSetShipmentStatus, arg.ID, arg.Status)
	var i FulfilmentShipment
	err := row.Scan(
		&i.ID,
		&i.FulfilmentID,
		&i.CarrierID,
		&i.CarrierName,
		&i.TrackingNumber,
		&i.LabelFileID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const fulfilmentShipmentByTracking = `-- name: FulfilmentShipmentByTracking :one
select id, fulfilment_id, carrier_id, carrier_name, tracking_number, label_file_id, status, created_at, updated_at from fulfilment.shipments where carrier_id = $1 and tracking_number = $2
`

type FulfilmentShipmentByTrackingParams struct {
	CarrierID      *uuid.UUID `json:"carrierId"`
	TrackingNumber string     `json:"trackingNumber"`
}

func (q *Queries) FulfilmentShipmentByTracking(ctx context.Context, arg FulfilmentShipmentByTrackingParams) (FulfilmentShipment, error) {
	row := q.db.QueryRow(ctx, fulfilmentShipmentByTracking, arg.CarrierID, arg.TrackingNumber)
	var i FulfilmentShipment
	err := row.Scan(
		&i.ID,
		&i.FulfilmentID,
		&i.CarrierID,
		&i.CarrierName,
		&i.TrackingNumber,
		&i.LabelFileID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const fulfilmentShipmentEvents = `-- name: FulfilmentShipmentEvents :many
select id, shipment_id, carrier_event_id, status, location, occurred_at, received_at from fulfilment.shipment_events where shipment_id = $1 order by occurred_at
`

func (q *Queries) FulfilmentShipmentEvents(ctx context.Context, shipmentID uuid.UUID) ([]FulfilmentShipmentEvent, error) {
	rows, err := q.db.Query(ctx, fulfilmentShipmentEvents, shipmentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FulfilmentShipmentEvent{}
	for rows.Next() {
		var i FulfilmentShipmentEvent
		if err := rows.Scan(
			&i.ID,
			&i.ShipmentID,
			&i.CarrierEventID,
			&i.Status,
			&i.Location,
			&i.OccurredAt,
			&i.ReceivedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const fulfilmentShipmentsForFulfilment = `-- name: FulfilmentShipmentsForFulfilment :many
select id, fulfilment_id, carrier_id, carrier_name, tracking_number, label_file_id, status, created_at, updated_at from fulfilment.shipments where fulfilment_id = $1 order by created_at
`

func (q *Queries) FulfilmentShipmentsForFulfilment(ctx context.Context, fulfilmentID uuid.UUID) ([]FulfilmentShipment, error) {
	rows, err := q.db.Query(ctx, fulfilmentShipmentsForFulfilment, fulfilmentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FulfilmentShipment{}
	for rows.Next() {
		var i FulfilmentShipment
		if err := rows.Scan(
			&i.ID,
			&i.FulfilmentID,
			&i.CarrierID,
			&i.CarrierName,
			&i.TrackingNumber,
			&i.LabelFileID,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const fulfilmentSignManifest = `-- name: FulfilmentSignManifest :one
update fulfilment.manifests set signed_by_name = $2, signed_at = now() where id = $1 and signed_at is null returning id, warehouse_id, rider_id, carrier_id, signed_by_name, signed_at, created_by, created_at
`

type FulfilmentSignManifestParams struct {
	ID           uuid.UUID `json:"id"`
	SignedByName *string   `json:"signedByName"`
}

func (q *Queries) FulfilmentSignManifest(ctx context.Context, arg FulfilmentSignManifestParams) (FulfilmentManifest, error) {
	row := q.db.QueryRow(ctx, fulfilmentSignManifest, arg.ID, arg.SignedByName)
	var i FulfilmentManifest
	err := row.Scan(
		&i.ID,
		&i.WarehouseID,
		&i.RiderID,
		&i.CarrierID,
		&i.SignedByName,
		&i.SignedAt,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const fulfilmentUnpickedForFulfilment = `-- name: FulfilmentUnpickedForFulfilment :one
select count(*)::int from sales.order_lines ol
where ol.fulfilment_id = $1 and ol.cancelled_at is null
  and not exists (select 1 from fulfilment.pick_list_items i where i.order_line_id = ol.id and i.picked_qty = i.quantity)
`

// Lines of a TechShop fulfilment not fully picked yet (packing waits for all of them).
func (q *Queries) FulfilmentUnpickedForFulfilment(ctx context.Context, fulfilmentID uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, fulfilmentUnpickedForFulfilment, fulfilmentID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const fulfilmentUpsertCarrier = `-- name: FulfilmentUpsertCarrier :one
insert into fulfilment.carriers (code, name, is_active) values ($1, $2, $3)
on conflict (code) do update set name = excluded.name, is_active = excluded.is_active returning id, code, name, is_active, created_at
`

type FulfilmentUpsertCarrierParams struct {
	Code     string `json:"code"`
	Name     string `json:"name"`
	IsActive bool   `json:"isActive"`
}

func (q *Queries) FulfilmentUpsertCarrier(ctx context.Context, arg FulfilmentUpsertCarrierParams) (FulfilmentCarrier, error) {
	row := q.db.QueryRow(ctx, fulfilmentUpsertCarrier, arg.Code, arg.Name, arg.IsActive)
	var i FulfilmentCarrier
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const fulfilmentWaveCandidates = `-- name: FulfilmentWaveCandidates :many

select ol.id as order_line_id, ol.fulfilment_id, ol.quantity, ol.variant_id, ol.product_name, ol.sku, f.order_id
from sales.order_lines ol
join sales.fulfilments f on f.id = ol.fulfilment_id
join sales.orders o on o.id = f.order_id
join inventory.stock_reservations r on r.order_line_id = ol.id and r.status = 'committed'
where f.status = 'pending' and f.fulfilled_by = 'techshop' and o.status in ('paid', 'processing', 'partially_shipped')
  and r.warehouse_id = $1 and ol.cancelled_at is null
  and not exists (select 1 from fulfilment.pick_list_items pi where pi.order_line_id = ol.id)
order by o.placed_at, ol.id
limit $2
`

type FulfilmentWaveCandidatesParams struct {
	WarehouseID *uuid.UUID `json:"warehouseId"`
	Limit       int32      `json:"limit"`
}

type FulfilmentWaveCandidatesRow struct {
	OrderLineID  uuid.UUID `json:"orderLineId"`
	FulfilmentID uuid.UUID `json:"fulfilmentId"`
	Quantity     int32     `json:"quantity"`
	VariantID    uuid.UUID `json:"variantId"`
	ProductName  string    `json:"productName"`
	Sku          string    `json:"sku"`
	OrderID      uuid.UUID `json:"orderId"`
}

// Fulfilment: waves and pick lists, packing, parcels, manifests, carriers, shipments, seller SLAs
// (docs/orders-fulfilment.md §4–§5).
// Paid TechShop-fulfilled lines whose stock was committed in this warehouse and not yet on a pick list.
func (q *Queries) FulfilmentWaveCandidates(ctx context.Context, arg FulfilmentWaveCandidatesParams) ([]FulfilmentWaveCandidatesRow, error) {
	rows, err := q.db.Query(ctx, fulfilmentWaveCandidates, arg.WarehouseID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FulfilmentWaveCandidatesRow{}
	for rows.Next() {
		var i FulfilmentWaveCandidatesRow
		if err := rows.Scan(
			&i.OrderLineID,
			&i.FulfilmentID,
			&i.Quantity,
			&i.VariantID,
			&i.ProductName,
			&i.Sku,
			&i.OrderID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
