// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: identity.sql

package store

import (
	"context"
	"encoding/json"
	"net/netip"
	"time"

	"github.com/google/uuid"
)

const identityAddRolePermissions = `-- name: IdentityAddRolePermissions :exec
insert into identity.role_permissions (role_id, permission_id)
select $1, id from identity.permissions where key = any($2::text[])
on conflict do nothing
`

type IdentityAddRolePermissionsParams struct {
	RoleID uuid.UUID `json:"roleId"`
	Keys   []string  `json:"keys"`
}

func (q *Queries) IdentityAddRolePermissions(ctx context.Context, arg IdentityAddRolePermissionsParams) error {
	_, err := q.db.Exec(ctx, identityAddRolePermissions, arg.RoleID, arg.Keys)
	return err
}

const identityAnonymiseUser = `-- name: IdentityAnonymiseUser :exec
update identity.users
set email = null, phone = null, password_hash = null, first_name = 'Deleted', last_name = 'user',
    status = 'deleted', marketing_opt_in = false
where id = $1
`

func (q *Queries) IdentityAnonymiseUser(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, identityAnonymiseUser, id)
	return err
}

const identityBumpCodeAttempts = `-- name: IdentityBumpCodeAttempts :one
update identity.verification_codes set attempts = attempts + 1 where id = $1 returning attempts
`

func (q *Queries) IdentityBumpCodeAttempts(ctx context.Context, id uuid.UUID) (int16, error) {
	row := q.db.QueryRow(ctx, identityBumpCodeAttempts, id)
	var attempts int16
	err := row.Scan(&attempts)
	return attempts, err
}

const identityCancelPrivacyRequest = `-- name: IdentityCancelPrivacyRequest :execrows
update identity.privacy_requests set status = 'cancelled' where id = $1 and user_id = $2 and status = 'requested'
`

type IdentityCancelPrivacyRequestParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"userId"`
}

func (q *Queries) IdentityCancelPrivacyRequest(ctx context.Context, arg IdentityCancelPrivacyRequestParams) (int64, error) {
	result, err := q.db.Exec(ctx, identityCancelPrivacyRequest, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const identityClearDefaultAddress = `-- name: IdentityClearDefaultAddress :exec
update identity.addresses set is_default = false where user_id = $1 and is_default
`

func (q *Queries) IdentityClearDefaultAddress(ctx context.Context, userID *uuid.UUID) error {
	_, err := q.db.Exec(ctx, identityClearDefaultAddress, userID)
	return err
}

const identityClearRolePermissions = `-- name: IdentityClearRolePermissions :exec
delete from identity.role_permissions where role_id = $1
`

func (q *Queries) IdentityClearRolePermissions(ctx context.Context, roleID uuid.UUID) error {
	_, err := q.db.Exec(ctx, identityClearRolePermissions, roleID)
	return err
}

const identityConfirmTOTP = `-- name: IdentityConfirmTOTP :exec
update identity.user_mfa_factors set confirmed_at = now(), last_used_step = $2 where id = $1
`

type IdentityConfirmTOTPParams struct {
	ID           uuid.UUID `json:"id"`
	LastUsedStep *int64    `json:"lastUsedStep"`
}

func (q *Queries) IdentityConfirmTOTP(ctx context.Context, arg IdentityConfirmTOTPParams) error {
	_, err := q.db.Exec(ctx, identityConfirmTOTP, arg.ID, arg.LastUsedStep)
	return err
}

const identityConsumeCode = `-- name: IdentityConsumeCode :exec
update identity.verification_codes set consumed_at = now() where id = $1 and consumed_at is null
`

func (q *Queries) IdentityConsumeCode(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, identityConsumeCode, id)
	return err
}

const identityCreateAddress = `-- name: IdentityCreateAddress :one
insert into identity.addresses (user_id, business_id, label, recipient_name, phone, line1, line2, landmark, city, lga, state_code, latitude, longitude, is_default)
values ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14)
returning id, user_id, business_id, label, recipient_name, phone, line1, line2, landmark, city, lga, state_code, latitude, longitude, is_default, created_at, updated_at
`

type IdentityCreateAddressParams struct {
	UserID        *uuid.UUID `json:"userId"`
	BusinessID    *uuid.UUID `json:"businessId"`
	Label         *string    `json:"label"`
	RecipientName string     `json:"recipientName"`
	Phone         string     `json:"phone"`
	Line1         string     `json:"line1"`
	Line2         *string    `json:"line2"`
	Landmark      *string    `json:"landmark"`
	City          string     `json:"city"`
	Lga           *string    `json:"lga"`
	StateCode     string     `json:"stateCode"`
	Latitude      *float64   `json:"latitude"`
	Longitude     *float64   `json:"longitude"`
	IsDefault     bool       `json:"isDefault"`
}

func (q *Queries) IdentityCreateAddress(ctx context.Context, arg IdentityCreateAddressParams) (IdentityAddress, error) {
	row := q.db.QueryRow(ctx, identityCreateAddress,
		arg.UserID,
		arg.BusinessID,
		arg.Label,
		arg.RecipientName,
		arg.Phone,
		arg.Line1,
		arg.Line2,
		arg.Landmark,
		arg.City,
		arg.Lga,
		arg.StateCode,
		arg.Latitude,
		arg.Longitude,
		arg.IsDefault,
	)
	var i IdentityAddress
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.BusinessID,
		&i.Label,
		&i.RecipientName,
		&i.Phone,
		&i.Line1,
		&i.Line2,
		&i.Landmark,
		&i.City,
		&i.Lga,
		&i.StateCode,
		&i.Latitude,
		&i.Longitude,
		&i.IsDefault,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const identityCreateCode = `-- name: IdentityCreateCode :one
insert into identity.verification_codes (id, user_id, channel, destination, purpose, code_hash, ip, user_agent, expires_at)
values ($1, $2, $3, $4, $5, $6, $7, $8, $9)
returning id, user_id, channel, destination, purpose, code_hash, attempts, ip, user_agent, expires_at, consumed_at, created_at
`

type IdentityCreateCodeParams struct {
	ID          uuid.UUID   `json:"id"`
	UserID      *uuid.UUID  `json:"userId"`
	Channel     string      `json:"channel"`
	Destination string      `json:"destination"`
	Purpose     string      `json:"purpose"`
	CodeHash    []byte      `json:"codeHash"`
	Ip          *netip.Addr `json:"ip"`
	UserAgent   *string     `json:"userAgent"`
	ExpiresAt   time.Time   `json:"expiresAt"`
}

func (q *Queries) IdentityCreateCode(ctx context.Context, arg IdentityCreateCodeParams) (IdentityVerificationCode, error) {
	row := q.db.QueryRow(ctx, identityCreateCode,
		arg.ID,
		arg.UserID,
		arg.Channel,
		arg.Destination,
		arg.Purpose,
		arg.CodeHash,
		arg.Ip,
		arg.UserAgent,
		arg.ExpiresAt,
	)
	var i IdentityVerificationCode
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Channel,
		&i.Destination,
		&i.Purpose,
		&i.CodeHash,
		&i.Attempts,
		&i.Ip,
		&i.UserAgent,
		&i.ExpiresAt,
		&i.ConsumedAt,
		&i.CreatedAt,
	)
	return i, err
}

const identityCreateInvite = `-- name: IdentityCreateInvite :one
insert into identity.staff_invites (staff_user_id, token_hash, created_by, expires_at) values ($1, $2, $3, $4) returning id, staff_user_id, token_hash, created_by, expires_at, used_at, created_at
`

type IdentityCreateInviteParams struct {
	StaffUserID uuid.UUID `json:"staffUserId"`
	TokenHash   []byte    `json:"tokenHash"`
	CreatedBy   uuid.UUID `json:"createdBy"`
	ExpiresAt   time.Time `json:"expiresAt"`
}

func (q *Queries) IdentityCreateInvite(ctx context.Context, arg IdentityCreateInviteParams) (IdentityStaffInvite, error) {
	row := q.db.QueryRow(ctx, identityCreateInvite,
		arg.StaffUserID,
		arg.TokenHash,
		arg.CreatedBy,
		arg.ExpiresAt,
	)
	var i IdentityStaffInvite
	err := row.Scan(
		&i.ID,
		&i.StaffUserID,
		&i.TokenHash,
		&i.CreatedBy,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const identityCreatePrivacyRequest = `-- name: IdentityCreatePrivacyRequest :one
insert into identity.privacy_requests (user_id, kind, cancel_until) values ($1, $2, $3) returning id, user_id, kind, status, cancel_until, file_id, completed_at, created_at, updated_at
`

type IdentityCreatePrivacyRequestParams struct {
	UserID      uuid.UUID  `json:"userId"`
	Kind        string     `json:"kind"`
	CancelUntil *time.Time `json:"cancelUntil"`
}

func (q *Queries) IdentityCreatePrivacyRequest(ctx context.Context, arg IdentityCreatePrivacyRequestParams) (IdentityPrivacyRequest, error) {
	row := q.db.QueryRow(ctx, identityCreatePrivacyRequest, arg.UserID, arg.Kind, arg.CancelUntil)
	var i IdentityPrivacyRequest
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Kind,
		&i.Status,
		&i.CancelUntil,
		&i.FileID,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const identityCreateSession = `-- name: IdentityCreateSession :one
insert into identity.user_sessions (user_id, family_id, refresh_token_hash, aud, platform, amr, device_id, device_name,
  app_version, user_agent, ip, mfa_at, idle_expires_at, expires_at)
values ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14)
returning id, user_id, family_id, refresh_token_hash, replaced_by, aud, platform, amr, device_id, device_name, app_version, user_agent, ip, mfa_at, last_used_at, idle_expires_at, expires_at, revoked_at, revoked_reason, created_at
`

type IdentityCreateSessionParams struct {
	UserID           uuid.UUID   `json:"userId"`
	FamilyID         uuid.UUID   `json:"familyId"`
	RefreshTokenHash []byte      `json:"refreshTokenHash"`
	Aud              string      `json:"aud"`
	Platform         string      `json:"platform"`
	Amr              []string    `json:"amr"`
	DeviceID         *string     `json:"deviceId"`
	DeviceName       *string     `json:"deviceName"`
	AppVersion       *string     `json:"appVersion"`
	UserAgent        *string     `json:"userAgent"`
	Ip               *netip.Addr `json:"ip"`
	MfaAt            *time.Time  `json:"mfaAt"`
	IdleExpiresAt    time.Time   `json:"idleExpiresAt"`
	ExpiresAt        time.Time   `json:"expiresAt"`
}

func (q *Queries) IdentityCreateSession(ctx context.Context, arg IdentityCreateSessionParams) (IdentityUserSession, error) {
	row := q.db.QueryRow(ctx, identityCreateSession,
		arg.UserID,
		arg.FamilyID,
		arg.RefreshTokenHash,
		arg.Aud,
		arg.Platform,
		arg.Amr,
		arg.DeviceID,
		arg.DeviceName,
		arg.AppVersion,
		arg.UserAgent,
		arg.Ip,
		arg.MfaAt,
		arg.IdleExpiresAt,
		arg.ExpiresAt,
	)
	var i IdentityUserSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.FamilyID,
		&i.RefreshTokenHash,
		&i.ReplacedBy,
		&i.Aud,
		&i.Platform,
		&i.Amr,
		&i.DeviceID,
		&i.DeviceName,
		&i.AppVersion,
		&i.UserAgent,
		&i.Ip,
		&i.MfaAt,
		&i.LastUsedAt,
		&i.IdleExpiresAt,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.RevokedReason,
		&i.CreatedAt,
	)
	return i, err
}

const identityCreateStaffMember = `-- name: IdentityCreateStaffMember :one
insert into identity.staff_members (user_id, employee_no, department, job_title, hired_on)
values ($1, $2, $3, $4, $5)
returning user_id, employee_no, department, job_title, status, hired_on, exited_on, created_at, updated_at
`

type IdentityCreateStaffMemberParams struct {
	UserID     uuid.UUID  `json:"userId"`
	EmployeeNo string     `json:"employeeNo"`
	Department string     `json:"department"`
	JobTitle   string     `json:"jobTitle"`
	HiredOn    *time.Time `json:"hiredOn"`
}

func (q *Queries) IdentityCreateStaffMember(ctx context.Context, arg IdentityCreateStaffMemberParams) (IdentityStaffMember, error) {
	row := q.db.QueryRow(ctx, identityCreateStaffMember,
		arg.UserID,
		arg.EmployeeNo,
		arg.Department,
		arg.JobTitle,
		arg.HiredOn,
	)
	var i IdentityStaffMember
	err := row.Scan(
		&i.UserID,
		&i.EmployeeNo,
		&i.Department,
		&i.JobTitle,
		&i.Status,
		&i.HiredOn,
		&i.ExitedOn,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const identityCreateUser = `-- name: IdentityCreateUser :one
insert into identity.users (email, phone, password_hash, first_name, last_name, phone_verified_at, email_verified_at)
values ($1, $2, $3, $4, $5, $6, $7)
returning id, email, phone, password_hash, first_name, last_name, status, email_verified_at, phone_verified_at, marketing_opt_in, last_login_at, created_at, updated_at
`

type IdentityCreateUserParams struct {
	Email           *string    `json:"email"`
	Phone           *string    `json:"phone"`
	PasswordHash    *string    `json:"passwordHash"`
	FirstName       string     `json:"firstName"`
	LastName        string     `json:"lastName"`
	PhoneVerifiedAt *time.Time `json:"phoneVerifiedAt"`
	EmailVerifiedAt *time.Time `json:"emailVerifiedAt"`
}

func (q *Queries) IdentityCreateUser(ctx context.Context, arg IdentityCreateUserParams) (IdentityUser, error) {
	row := q.db.QueryRow(ctx, identityCreateUser,
		arg.Email,
		arg.Phone,
		arg.PasswordHash,
		arg.FirstName,
		arg.LastName,
		arg.PhoneVerifiedAt,
		arg.EmailVerifiedAt,
	)
	var i IdentityUser
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Phone,
		&i.PasswordHash,
		&i.FirstName,
		&i.LastName,
		&i.Status,
		&i.EmailVerifiedAt,
		&i.PhoneVerifiedAt,
		&i.MarketingOptIn,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const identityDeleteAddress = `-- name: IdentityDeleteAddress :execrows
delete from identity.addresses where id = $1 and user_id = $2
`

type IdentityDeleteAddressParams struct {
	ID     uuid.UUID  `json:"id"`
	UserID *uuid.UUID `json:"userId"`
}

func (q *Queries) IdentityDeleteAddress(ctx context.Context, arg IdentityDeleteAddressParams) (int64, error) {
	result, err := q.db.Exec(ctx, identityDeleteAddress, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const identityDeleteRecoveryCodes = `-- name: IdentityDeleteRecoveryCodes :exec
delete from identity.user_recovery_codes where user_id = $1
`

func (q *Queries) IdentityDeleteRecoveryCodes(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, identityDeleteRecoveryCodes, userID)
	return err
}

const identityDeleteTOTP = `-- name: IdentityDeleteTOTP :exec
delete from identity.user_mfa_factors where user_id = $1
`

func (q *Queries) IdentityDeleteTOTP(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, identityDeleteTOTP, userID)
	return err
}

const identityDuePrivacyDeletions = `-- name: IdentityDuePrivacyDeletions :many
select id, user_id, kind, status, cancel_until, file_id, completed_at, created_at, updated_at from identity.privacy_requests
where kind = 'delete' and status = 'requested' and cancel_until < now()
limit 50
`

func (q *Queries) IdentityDuePrivacyDeletions(ctx context.Context) ([]IdentityPrivacyRequest, error) {
	rows, err := q.db.Query(ctx, identityDuePrivacyDeletions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []IdentityPrivacyRequest{}
	for rows.Next() {
		var i IdentityPrivacyRequest
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Kind,
			&i.Status,
			&i.CancelUntil,
			&i.FileID,
			&i.CompletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const identityGetAddress = `-- name: IdentityGetAddress :one
select id, user_id, business_id, label, recipient_name, phone, line1, line2, landmark, city, lga, state_code, latitude, longitude, is_default, created_at, updated_at from identity.addresses where id = $1 and user_id = $2
`

type IdentityGetAddressParams struct {
	ID     uuid.UUID  `json:"id"`
	UserID *uuid.UUID `json:"userId"`
}

func (q *Queries) IdentityGetAddress(ctx context.Context, arg IdentityGetAddressParams) (IdentityAddress, error) {
	row := q.db.QueryRow(ctx, identityGetAddress, arg.ID, arg.UserID)
	var i IdentityAddress
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.BusinessID,
		&i.Label,
		&i.RecipientName,
		&i.Phone,
		&i.Line1,
		&i.Line2,
		&i.Landmark,
		&i.City,
		&i.Lga,
		&i.StateCode,
		&i.Latitude,
		&i.Longitude,
		&i.IsDefault,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const identityGetCode = `-- name: IdentityGetCode :one
select id, user_id, channel, destination, purpose, code_hash, attempts, ip, user_agent, expires_at, consumed_at, created_at from identity.verification_codes where id = $1 for update
`

func (q *Queries) IdentityGetCode(ctx context.Context, id uuid.UUID) (IdentityVerificationCode, error) {
	row := q.db.QueryRow(ctx, identityGetCode, id)
	var i IdentityVerificationCode
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Channel,
		&i.Destination,
		&i.Purpose,
		&i.CodeHash,
		&i.Attempts,
		&i.Ip,
		&i.UserAgent,
		&i.ExpiresAt,
		&i.ConsumedAt,
		&i.CreatedAt,
	)
	return i, err
}

const identityGetInvite = `-- name: IdentityGetInvite :one
select id, staff_user_id, token_hash, created_by, expires_at, used_at, created_at from identity.staff_invites where token_hash = $1 and used_at is null and expires_at > now() for update
`

func (q *Queries) IdentityGetInvite(ctx context.Context, tokenHash []byte) (IdentityStaffInvite, error) {
	row := q.db.QueryRow(ctx, identityGetInvite, tokenHash)
	var i IdentityStaffInvite
	err := row.Scan(
		&i.ID,
		&i.StaffUserID,
		&i.TokenHash,
		&i.CreatedBy,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const identityGetRoleByKey = `-- name: IdentityGetRoleByKey :one
select id, key, name, description, is_system, created_at, updated_at from identity.roles where key = $1
`

func (q *Queries) IdentityGetRoleByKey(ctx context.Context, key string) (IdentityRole, error) {
	row := q.db.QueryRow(ctx, identityGetRoleByKey, key)
	var i IdentityRole
	err := row.Scan(
		&i.ID,
		&i.Key,
		&i.Name,
		&i.Description,
		&i.IsSystem,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const identityGetServiceClient = `-- name: IdentityGetServiceClient :one
select id, name, secret_hash, scopes, status, rotated_at, created_at from identity.service_clients where name = $1 and status = 'active'
`

func (q *Queries) IdentityGetServiceClient(ctx context.Context, name string) (IdentityServiceClient, error) {
	row := q.db.QueryRow(ctx, identityGetServiceClient, name)
	var i IdentityServiceClient
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.SecretHash,
		&i.Scopes,
		&i.Status,
		&i.RotatedAt,
		&i.CreatedAt,
	)
	return i, err
}

const identityGetSession = `-- name: IdentityGetSession :one
select id, user_id, family_id, refresh_token_hash, replaced_by, aud, platform, amr, device_id, device_name, app_version, user_agent, ip, mfa_at, last_used_at, idle_expires_at, expires_at, revoked_at, revoked_reason, created_at from identity.user_sessions where id = $1
`

func (q *Queries) IdentityGetSession(ctx context.Context, id uuid.UUID) (IdentityUserSession, error) {
	row := q.db.QueryRow(ctx, identityGetSession, id)
	var i IdentityUserSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.FamilyID,
		&i.RefreshTokenHash,
		&i.ReplacedBy,
		&i.Aud,
		&i.Platform,
		&i.Amr,
		&i.DeviceID,
		&i.DeviceName,
		&i.AppVersion,
		&i.UserAgent,
		&i.Ip,
		&i.MfaAt,
		&i.LastUsedAt,
		&i.IdleExpiresAt,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.RevokedReason,
		&i.CreatedAt,
	)
	return i, err
}

const identityGetSessionByToken = `-- name: IdentityGetSessionByToken :one
select id, user_id, family_id, refresh_token_hash, replaced_by, aud, platform, amr, device_id, device_name, app_version, user_agent, ip, mfa_at, last_used_at, idle_expires_at, expires_at, revoked_at, revoked_reason, created_at from identity.user_sessions where refresh_token_hash = $1 for update
`

func (q *Queries) IdentityGetSessionByToken(ctx context.Context, refreshTokenHash []byte) (IdentityUserSession, error) {
	row := q.db.QueryRow(ctx, identityGetSessionByToken, refreshTokenHash)
	var i IdentityUserSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.FamilyID,
		&i.RefreshTokenHash,
		&i.ReplacedBy,
		&i.Aud,
		&i.Platform,
		&i.Amr,
		&i.DeviceID,
		&i.DeviceName,
		&i.AppVersion,
		&i.UserAgent,
		&i.Ip,
		&i.MfaAt,
		&i.LastUsedAt,
		&i.IdleExpiresAt,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.RevokedReason,
		&i.CreatedAt,
	)
	return i, err
}

const identityGetStaffMember = `-- name: IdentityGetStaffMember :one
select user_id, employee_no, department, job_title, status, hired_on, exited_on, created_at, updated_at from identity.staff_members where user_id = $1
`

func (q *Queries) IdentityGetStaffMember(ctx context.Context, userID uuid.UUID) (IdentityStaffMember, error) {
	row := q.db.QueryRow(ctx, identityGetStaffMember, userID)
	var i IdentityStaffMember
	err := row.Scan(
		&i.UserID,
		&i.EmployeeNo,
		&i.Department,
		&i.JobTitle,
		&i.Status,
		&i.HiredOn,
		&i.ExitedOn,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const identityGetTOTPFactor = `-- name: IdentityGetTOTPFactor :one
select id, user_id, kind, secret_encrypted, encryption_key_id, last_used_step, confirmed_at, created_at from identity.user_mfa_factors where user_id = $1 and kind = 'totp'
`

func (q *Queries) IdentityGetTOTPFactor(ctx context.Context, userID uuid.UUID) (IdentityUserMfaFactor, error) {
	row := q.db.QueryRow(ctx, identityGetTOTPFactor, userID)
	var i IdentityUserMfaFactor
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Kind,
		&i.SecretEncrypted,
		&i.EncryptionKeyID,
		&i.LastUsedStep,
		&i.ConfirmedAt,
		&i.CreatedAt,
	)
	return i, err
}

const identityGetUser = `-- name: IdentityGetUser :one

select id, email, phone, password_hash, first_name, last_name, status, email_verified_at, phone_verified_at, marketing_opt_in, last_login_at, created_at, updated_at from identity.users where id = $1
`

// Identity & access queries (docs/identity-access.md).
func (q *Queries) IdentityGetUser(ctx context.Context, id uuid.UUID) (IdentityUser, error) {
	row := q.db.QueryRow(ctx, identityGetUser, id)
	var i IdentityUser
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Phone,
		&i.PasswordHash,
		&i.FirstName,
		&i.LastName,
		&i.Status,
		&i.EmailVerifiedAt,
		&i.PhoneVerifiedAt,
		&i.MarketingOptIn,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const identityGetUserByEmail = `-- name: IdentityGetUserByEmail :one
select id, email, phone, password_hash, first_name, last_name, status, email_verified_at, phone_verified_at, marketing_opt_in, last_login_at, created_at, updated_at from identity.users where email = $1
`

func (q *Queries) IdentityGetUserByEmail(ctx context.Context, email *string) (IdentityUser, error) {
	row := q.db.QueryRow(ctx, identityGetUserByEmail, email)
	var i IdentityUser
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Phone,
		&i.PasswordHash,
		&i.FirstName,
		&i.LastName,
		&i.Status,
		&i.EmailVerifiedAt,
		&i.PhoneVerifiedAt,
		&i.MarketingOptIn,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const identityGetUserByPhone = `-- name: IdentityGetUserByPhone :one
select id, email, phone, password_hash, first_name, last_name, status, email_verified_at, phone_verified_at, marketing_opt_in, last_login_at, created_at, updated_at from identity.users where phone = $1
`

func (q *Queries) IdentityGetUserByPhone(ctx context.Context, phone *string) (IdentityUser, error) {
	row := q.db.QueryRow(ctx, identityGetUserByPhone, phone)
	var i IdentityUser
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Phone,
		&i.PasswordHash,
		&i.FirstName,
		&i.LastName,
		&i.Status,
		&i.EmailVerifiedAt,
		&i.PhoneVerifiedAt,
		&i.MarketingOptIn,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const identityGrantRole = `-- name: IdentityGrantRole :exec
insert into identity.staff_roles (user_id, role_id, granted_by) values ($1, $2, $3) on conflict do nothing
`

type IdentityGrantRoleParams struct {
	UserID    uuid.UUID  `json:"userId"`
	RoleID    uuid.UUID  `json:"roleId"`
	GrantedBy *uuid.UUID `json:"grantedBy"`
}

func (q *Queries) IdentityGrantRole(ctx context.Context, arg IdentityGrantRoleParams) error {
	_, err := q.db.Exec(ctx, identityGrantRole, arg.UserID, arg.RoleID, arg.GrantedBy)
	return err
}

const identityHasConsent = `-- name: IdentityHasConsent :one
select coalesce((
  select granted from identity.consents
  where (user_id = $1 or anonymous_id = $2) and purpose = $3
  order by recorded_at desc limit 1), false)::bool as granted
`

type IdentityHasConsentParams struct {
	UserID      *uuid.UUID `json:"userId"`
	AnonymousID *uuid.UUID `json:"anonymousId"`
	Purpose     string     `json:"purpose"`
}

func (q *Queries) IdentityHasConsent(ctx context.Context, arg IdentityHasConsentParams) (bool, error) {
	row := q.db.QueryRow(ctx, identityHasConsent, arg.UserID, arg.AnonymousID, arg.Purpose)
	var granted bool
	err := row.Scan(&granted)
	return granted, err
}

const identityHasDeviceSession = `-- name: IdentityHasDeviceSession :one
select exists (select 1 from identity.user_sessions where user_id = $1 and device_id = $2) as known
`

type IdentityHasDeviceSessionParams struct {
	UserID   uuid.UUID `json:"userId"`
	DeviceID *string   `json:"deviceId"`
}

func (q *Queries) IdentityHasDeviceSession(ctx context.Context, arg IdentityHasDeviceSessionParams) (bool, error) {
	row := q.db.QueryRow(ctx, identityHasDeviceSession, arg.UserID, arg.DeviceID)
	var known bool
	err := row.Scan(&known)
	return known, err
}

const identityInsertAuthEvent = `-- name: IdentityInsertAuthEvent :exec
insert into identity.auth_events (user_id, kind, ip, user_agent, device_id, meta)
values ($1, $2, $3, $4, $5, $6)
`

type IdentityInsertAuthEventParams struct {
	UserID    *uuid.UUID      `json:"userId"`
	Kind      string          `json:"kind"`
	Ip        *netip.Addr     `json:"ip"`
	UserAgent *string         `json:"userAgent"`
	DeviceID  *string         `json:"deviceId"`
	Meta      json.RawMessage `json:"meta"`
}

func (q *Queries) IdentityInsertAuthEvent(ctx context.Context, arg IdentityInsertAuthEventParams) error {
	_, err := q.db.Exec(ctx, identityInsertAuthEvent,
		arg.UserID,
		arg.Kind,
		arg.Ip,
		arg.UserAgent,
		arg.DeviceID,
		arg.Meta,
	)
	return err
}

const identityInsertConsent = `-- name: IdentityInsertConsent :exec
insert into identity.consents (user_id, anonymous_id, purpose, granted, policy_version, source)
values ($1, $2, $3, $4, $5, $6)
`

type IdentityInsertConsentParams struct {
	UserID        *uuid.UUID `json:"userId"`
	AnonymousID   *uuid.UUID `json:"anonymousId"`
	Purpose       string     `json:"purpose"`
	Granted       bool       `json:"granted"`
	PolicyVersion string     `json:"policyVersion"`
	Source        string     `json:"source"`
}

func (q *Queries) IdentityInsertConsent(ctx context.Context, arg IdentityInsertConsentParams) error {
	_, err := q.db.Exec(ctx, identityInsertConsent,
		arg.UserID,
		arg.AnonymousID,
		arg.Purpose,
		arg.Granted,
		arg.PolicyVersion,
		arg.Source,
	)
	return err
}

const identityInsertRecoveryCode = `-- name: IdentityInsertRecoveryCode :exec
insert into identity.user_recovery_codes (user_id, code_hash) values ($1, $2)
`

type IdentityInsertRecoveryCodeParams struct {
	UserID   uuid.UUID `json:"userId"`
	CodeHash []byte    `json:"codeHash"`
}

func (q *Queries) IdentityInsertRecoveryCode(ctx context.Context, arg IdentityInsertRecoveryCodeParams) error {
	_, err := q.db.Exec(ctx, identityInsertRecoveryCode, arg.UserID, arg.CodeHash)
	return err
}

const identityLatestConsents = `-- name: IdentityLatestConsents :many
select distinct on (purpose) purpose, granted, policy_version, source, recorded_at
from identity.consents
where (user_id = $1 or anonymous_id = $2)
order by purpose, recorded_at desc
`

type IdentityLatestConsentsParams struct {
	UserID      *uuid.UUID `json:"userId"`
	AnonymousID *uuid.UUID `json:"anonymousId"`
}

type IdentityLatestConsentsRow struct {
	Purpose       string    `json:"purpose"`
	Granted       bool      `json:"granted"`
	PolicyVersion string    `json:"policyVersion"`
	Source        string    `json:"source"`
	RecordedAt    time.Time `json:"recordedAt"`
}

func (q *Queries) IdentityLatestConsents(ctx context.Context, arg IdentityLatestConsentsParams) ([]IdentityLatestConsentsRow, error) {
	rows, err := q.db.Query(ctx, identityLatestConsents, arg.UserID, arg.AnonymousID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []IdentityLatestConsentsRow{}
	for rows.Next() {
		var i IdentityLatestConsentsRow
		if err := rows.Scan(
			&i.Purpose,
			&i.Granted,
			&i.PolicyVersion,
			&i.Source,
			&i.RecordedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const identityListActiveSessions = `-- name: IdentityListActiveSessions :many
select distinct on (family_id) id, family_id, aud, platform, device_name, user_agent, ip, last_used_at, created_at
from identity.user_sessions
where user_id = $1 and revoked_at is null and replaced_by is null and expires_at > now()
order by family_id, created_at desc
`

type IdentityListActiveSessionsRow struct {
	ID         uuid.UUID   `json:"id"`
	FamilyID   uuid.UUID   `json:"familyId"`
	Aud        string      `json:"aud"`
	Platform   string      `json:"platform"`
	DeviceName *string     `json:"deviceName"`
	UserAgent  *string     `json:"userAgent"`
	Ip         *netip.Addr `json:"ip"`
	LastUsedAt time.Time   `json:"lastUsedAt"`
	CreatedAt  time.Time   `json:"createdAt"`
}

// One row per device (the newest token of each family).
func (q *Queries) IdentityListActiveSessions(ctx context.Context, userID uuid.UUID) ([]IdentityListActiveSessionsRow, error) {
	rows, err := q.db.Query(ctx, identityListActiveSessions, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []IdentityListActiveSessionsRow{}
	for rows.Next() {
		var i IdentityListActiveSessionsRow
		if err := rows.Scan(
			&i.ID,
			&i.FamilyID,
			&i.Aud,
			&i.Platform,
			&i.DeviceName,
			&i.UserAgent,
			&i.Ip,
			&i.LastUsedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const identityListAddresses = `-- name: IdentityListAddresses :many
select id, user_id, business_id, label, recipient_name, phone, line1, line2, landmark, city, lga, state_code, latitude, longitude, is_default, created_at, updated_at from identity.addresses where user_id = $1 order by is_default desc, created_at desc
`

func (q *Queries) IdentityListAddresses(ctx context.Context, userID *uuid.UUID) ([]IdentityAddress, error) {
	rows, err := q.db.Query(ctx, identityListAddresses, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []IdentityAddress{}
	for rows.Next() {
		var i IdentityAddress
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.BusinessID,
			&i.Label,
			&i.RecipientName,
			&i.Phone,
			&i.Line1,
			&i.Line2,
			&i.Landmark,
			&i.City,
			&i.Lga,
			&i.StateCode,
			&i.Latitude,
			&i.Longitude,
			&i.IsDefault,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const identityListAuthEvents = `-- name: IdentityListAuthEvents :many
select id, user_id, kind, ip, user_agent, device_id, state_code, meta, created_at from identity.auth_events
where ($2::uuid is null or user_id = $2)
  and ($3::text is null or kind = $3)
  and ($4::bigint is null or id < $4)
order by id desc
limit $1
`

type IdentityListAuthEventsParams struct {
	Limit    int32      `json:"limit"`
	UserID   *uuid.UUID `json:"userId"`
	Kind     *string    `json:"kind"`
	BeforeID *int64     `json:"beforeId"`
}

func (q *Queries) IdentityListAuthEvents(ctx context.Context, arg IdentityListAuthEventsParams) ([]IdentityAuthEvent, error) {
	rows, err := q.db.Query(ctx, identityListAuthEvents,
		arg.Limit,
		arg.UserID,
		arg.Kind,
		arg.BeforeID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []IdentityAuthEvent{}
	for rows.Next() {
		var i IdentityAuthEvent
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Kind,
			&i.Ip,
			&i.UserAgent,
			&i.DeviceID,
			&i.StateCode,
			&i.Meta,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const identityListPermissions = `-- name: IdentityListPermissions :many
select id, key, module, description, is_sensitive from identity.permissions order by module, key
`

func (q *Queries) IdentityListPermissions(ctx context.Context) ([]IdentityPermission, error) {
	rows, err := q.db.Query(ctx, identityListPermissions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []IdentityPermission{}
	for rows.Next() {
		var i IdentityPermission
		if err := rows.Scan(
			&i.ID,
			&i.Key,
			&i.Module,
			&i.Description,
			&i.IsSensitive,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const identityListPrivacyRequests = `-- name: IdentityListPrivacyRequests :many
select id, user_id, kind, status, cancel_until, file_id, completed_at, created_at, updated_at from identity.privacy_requests where user_id = $1 order by created_at desc
`

func (q *Queries) IdentityListPrivacyRequests(ctx context.Context, userID uuid.UUID) ([]IdentityPrivacyRequest, error) {
	rows, err := q.db.Query(ctx, identityListPrivacyRequests, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []IdentityPrivacyRequest{}
	for rows.Next() {
		var i IdentityPrivacyRequest
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Kind,
			&i.Status,
			&i.CancelUntil,
			&i.FileID,
			&i.CompletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const identityListRoles = `-- name: IdentityListRoles :many
select r.id, r.key, r.name, r.description, r.is_system, r.created_at, r.updated_at, coalesce(array_agg(p.key order by p.key) filter (where p.key is not null), '{}')::text[] as permission_keys
from identity.roles r
left join identity.role_permissions rp on rp.role_id = r.id
left join identity.permissions p on p.id = rp.permission_id
group by r.id
order by r.name
`

type IdentityListRolesRow struct {
	ID             uuid.UUID `json:"id"`
	Key            string    `json:"key"`
	Name           string    `json:"name"`
	Description    *string   `json:"description"`
	IsSystem       bool      `json:"isSystem"`
	CreatedAt      time.Time `json:"createdAt"`
	UpdatedAt      time.Time `json:"updatedAt"`
	PermissionKeys []string  `json:"permissionKeys"`
}

func (q *Queries) IdentityListRoles(ctx context.Context) ([]IdentityListRolesRow, error) {
	rows, err := q.db.Query(ctx, identityListRoles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []IdentityListRolesRow{}
	for rows.Next() {
		var i IdentityListRolesRow
		if err := rows.Scan(
			&i.ID,
			&i.Key,
			&i.Name,
			&i.Description,
			&i.IsSystem,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.PermissionKeys,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const identityListStaffMembers = `-- name: IdentityListStaffMembers :many
select sm.user_id, sm.employee_no, sm.department, sm.job_title, sm.status, sm.hired_on, sm.exited_on, sm.created_at, sm.updated_at, u.first_name, u.last_name, u.email,
       coalesce(array_agg(r.key order by r.key) filter (where r.key is not null), '{}')::text[] as role_keys,
       exists (select 1 from identity.user_mfa_factors f where f.user_id = sm.user_id and f.confirmed_at is not null) as mfa_enabled
from identity.staff_members sm
join identity.users u on u.id = sm.user_id
left join identity.staff_roles sr on sr.user_id = sm.user_id
left join identity.roles r on r.id = sr.role_id
group by sm.user_id, u.id
order by u.first_name, u.last_name
`

type IdentityListStaffMembersRow struct {
	UserID     uuid.UUID  `json:"userId"`
	EmployeeNo string     `json:"employeeNo"`
	Department string     `json:"department"`
	JobTitle   string     `json:"jobTitle"`
	Status     string     `json:"status"`
	HiredOn    *time.Time `json:"hiredOn"`
	ExitedOn   *time.Time `json:"exitedOn"`
	CreatedAt  time.Time  `json:"createdAt"`
	UpdatedAt  time.Time  `json:"updatedAt"`
	FirstName  string     `json:"firstName"`
	LastName   string     `json:"lastName"`
	Email      *string    `json:"email"`
	RoleKeys   []string   `json:"roleKeys"`
	MfaEnabled bool       `json:"mfaEnabled"`
}

func (q *Queries) IdentityListStaffMembers(ctx context.Context) ([]IdentityListStaffMembersRow, error) {
	rows, err := q.db.Query(ctx, identityListStaffMembers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []IdentityListStaffMembersRow{}
	for rows.Next() {
		var i IdentityListStaffMembersRow
		if err := rows.Scan(
			&i.UserID,
			&i.EmployeeNo,
			&i.Department,
			&i.JobTitle,
			&i.Status,
			&i.HiredOn,
			&i.ExitedOn,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.FirstName,
			&i.LastName,
			&i.Email,
			&i.RoleKeys,
			&i.MfaEnabled,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const identityListStates = `-- name: IdentityListStates :many
select code, name from identity.nigerian_states order by name
`

func (q *Queries) IdentityListStates(ctx context.Context) ([]IdentityNigerianState, error) {
	rows, err := q.db.Query(ctx, identityListStates)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []IdentityNigerianState{}
	for rows.Next() {
		var i IdentityNigerianState
		if err := rows.Scan(&i.Code, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const identityListUsers = `-- name: IdentityListUsers :many
select id, email, phone, password_hash, first_name, last_name, status, email_verified_at, phone_verified_at, marketing_opt_in, last_login_at, created_at, updated_at from identity.users
where ($2::text is null or email ilike '%' || $2 || '%' or phone like '%' || $2 || '%'
       or (first_name || ' ' || last_name) ilike '%' || $2 || '%')
  and ($3::timestamptz is null or (created_at, id) < ($3, $4::uuid))
order by created_at desc, id desc
limit $1
`

type IdentityListUsersParams struct {
	Limit        int32      `json:"limit"`
	Q            *string    `json:"q"`
	AfterCreated *time.Time `json:"afterCreated"`
	AfterID      *uuid.UUID `json:"afterId"`
}

func (q *Queries) IdentityListUsers(ctx context.Context, arg IdentityListUsersParams) ([]IdentityUser, error) {
	rows, err := q.db.Query(ctx, identityListUsers,
		arg.Limit,
		arg.Q,
		arg.AfterCreated,
		arg.AfterID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []IdentityUser{}
	for rows.Next() {
		var i IdentityUser
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Phone,
			&i.PasswordHash,
			&i.FirstName,
			&i.LastName,
			&i.Status,
			&i.EmailVerifiedAt,
			&i.PhoneVerifiedAt,
			&i.MarketingOptIn,
			&i.LastLoginAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const identityMarkPhoneVerified = `-- name: IdentityMarkPhoneVerified :exec
update identity.users set phone_verified_at = coalesce(phone_verified_at, now()) where id = $1
`

func (q *Queries) IdentityMarkPhoneVerified(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, identityMarkPhoneVerified, id)
	return err
}

const identityMarkSessionReplaced = `-- name: IdentityMarkSessionReplaced :exec
update identity.user_sessions set replaced_by = $2, last_used_at = now() where id = $1
`

type IdentityMarkSessionReplacedParams struct {
	ID         uuid.UUID  `json:"id"`
	ReplacedBy *uuid.UUID `json:"replacedBy"`
}

func (q *Queries) IdentityMarkSessionReplaced(ctx context.Context, arg IdentityMarkSessionReplacedParams) error {
	_, err := q.db.Exec(ctx, identityMarkSessionReplaced, arg.ID, arg.ReplacedBy)
	return err
}

const identityMemberships = `-- name: IdentityMemberships :one
select
  coalesce((select json_agg(json_build_object('sellerId', s.id, 'name', s.display_name, 'role', sm.role, 'status', s.status))
            from sellers.seller_members sm join sellers.sellers s on s.id = sm.seller_id where sm.user_id = $1), '[]')::jsonb as sellers,
  coalesce((select json_agg(json_build_object('businessId', b.id, 'name', b.legal_name, 'role', bm.role, 'status', b.status))
            from b2b.business_members bm join b2b.businesses b on b.id = bm.business_id where bm.user_id = $1), '[]')::jsonb as businesses,
  exists (select 1 from logistics.riders r where r.user_id = $1) as is_rider,
  exists (select 1 from identity.staff_members st where st.user_id = $1 and st.status = 'active') as is_staff,
  exists (select 1 from identity.user_mfa_factors f where f.user_id = $1 and f.confirmed_at is not null) as mfa_enabled
`

type IdentityMembershipsRow struct {
	Sellers    json.RawMessage `json:"sellers"`
	Businesses json.RawMessage `json:"businesses"`
	IsRider    bool            `json:"isRider"`
	IsStaff    bool            `json:"isStaff"`
	MfaEnabled bool            `json:"mfaEnabled"`
}

// Read-only summary of what an account may act as (documented cross-module read for /me).
func (q *Queries) IdentityMemberships(ctx context.Context, userID uuid.UUID) (IdentityMembershipsRow, error) {
	row := q.db.QueryRow(ctx, identityMemberships, userID)
	var i IdentityMembershipsRow
	err := row.Scan(
		&i.Sellers,
		&i.Businesses,
		&i.IsRider,
		&i.IsStaff,
		&i.MfaEnabled,
	)
	return i, err
}

const identityRevokeAllRoles = `-- name: IdentityRevokeAllRoles :execrows
delete from identity.staff_roles where user_id = $1
`

func (q *Queries) IdentityRevokeAllRoles(ctx context.Context, userID uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, identityRevokeAllRoles, userID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const identityRevokeAllSessions = `-- name: IdentityRevokeAllSessions :execrows
update identity.user_sessions set revoked_at = now(), revoked_reason = $2
where user_id = $1 and revoked_at is null
`

type IdentityRevokeAllSessionsParams struct {
	UserID        uuid.UUID `json:"userId"`
	RevokedReason *string   `json:"revokedReason"`
}

func (q *Queries) IdentityRevokeAllSessions(ctx context.Context, arg IdentityRevokeAllSessionsParams) (int64, error) {
	result, err := q.db.Exec(ctx, identityRevokeAllSessions, arg.UserID, arg.RevokedReason)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const identityRevokeFamily = `-- name: IdentityRevokeFamily :execrows
update identity.user_sessions set revoked_at = now(), revoked_reason = $2
where family_id = $1 and revoked_at is null
`

type IdentityRevokeFamilyParams struct {
	FamilyID      uuid.UUID `json:"familyId"`
	RevokedReason *string   `json:"revokedReason"`
}

func (q *Queries) IdentityRevokeFamily(ctx context.Context, arg IdentityRevokeFamilyParams) (int64, error) {
	result, err := q.db.Exec(ctx, identityRevokeFamily, arg.FamilyID, arg.RevokedReason)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const identityRevokeOtherSessions = `-- name: IdentityRevokeOtherSessions :execrows
update identity.user_sessions set revoked_at = now(), revoked_reason = 'logout_all'
where user_id = $1 and family_id <> $2 and revoked_at is null
`

type IdentityRevokeOtherSessionsParams struct {
	UserID   uuid.UUID `json:"userId"`
	FamilyID uuid.UUID `json:"familyId"`
}

func (q *Queries) IdentityRevokeOtherSessions(ctx context.Context, arg IdentityRevokeOtherSessionsParams) (int64, error) {
	result, err := q.db.Exec(ctx, identityRevokeOtherSessions, arg.UserID, arg.FamilyID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const identityRevokeRole = `-- name: IdentityRevokeRole :execrows
delete from identity.staff_roles where user_id = $1 and role_id = $2
`

type IdentityRevokeRoleParams struct {
	UserID uuid.UUID `json:"userId"`
	RoleID uuid.UUID `json:"roleId"`
}

func (q *Queries) IdentityRevokeRole(ctx context.Context, arg IdentityRevokeRoleParams) (int64, error) {
	result, err := q.db.Exec(ctx, identityRevokeRole, arg.UserID, arg.RoleID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const identityRevokeSession = `-- name: IdentityRevokeSession :execrows
update identity.user_sessions s set revoked_at = now(), revoked_reason = $3
where s.family_id = (select x.family_id from identity.user_sessions x where x.id = $1 and x.user_id = $2) and s.revoked_at is null
`

type IdentityRevokeSessionParams struct {
	ID            uuid.UUID `json:"id"`
	UserID        uuid.UUID `json:"userId"`
	RevokedReason *string   `json:"revokedReason"`
}

func (q *Queries) IdentityRevokeSession(ctx context.Context, arg IdentityRevokeSessionParams) (int64, error) {
	result, err := q.db.Exec(ctx, identityRevokeSession, arg.ID, arg.UserID, arg.RevokedReason)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const identitySeedTOTP = `-- name: IdentitySeedTOTP :exec
insert into identity.user_mfa_factors (user_id, kind, secret_encrypted, confirmed_at)
values ($1, 'totp', $2, now())
on conflict (user_id) where kind = 'totp' do update set secret_encrypted = excluded.secret_encrypted, confirmed_at = now(), last_used_step = null
`

type IdentitySeedTOTPParams struct {
	UserID          uuid.UUID `json:"userId"`
	SecretEncrypted []byte    `json:"secretEncrypted"`
}

// Dev seed only: a confirmed authenticator for a seeded staff account.
func (q *Queries) IdentitySeedTOTP(ctx context.Context, arg IdentitySeedTOTPParams) error {
	_, err := q.db.Exec(ctx, identitySeedTOTP, arg.UserID, arg.SecretEncrypted)
	return err
}

const identitySessionActive = `-- name: IdentitySessionActive :one
select exists (
  select 1 from identity.user_sessions s
  where s.id = $1 and s.revoked_at is null and s.expires_at > now()
) as active
`

func (q *Queries) IdentitySessionActive(ctx context.Context, id uuid.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, identitySessionActive, id)
	var active bool
	err := row.Scan(&active)
	return active, err
}

const identitySetDefaultAddress = `-- name: IdentitySetDefaultAddress :execrows
update identity.addresses set is_default = true where id = $1 and user_id = $2
`

type IdentitySetDefaultAddressParams struct {
	ID     uuid.UUID  `json:"id"`
	UserID *uuid.UUID `json:"userId"`
}

func (q *Queries) IdentitySetDefaultAddress(ctx context.Context, arg IdentitySetDefaultAddressParams) (int64, error) {
	result, err := q.db.Exec(ctx, identitySetDefaultAddress, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const identitySetPassword = `-- name: IdentitySetPassword :exec
update identity.users set password_hash = $2 where id = $1
`

type IdentitySetPasswordParams struct {
	ID           uuid.UUID `json:"id"`
	PasswordHash *string   `json:"passwordHash"`
}

func (q *Queries) IdentitySetPassword(ctx context.Context, arg IdentitySetPasswordParams) error {
	_, err := q.db.Exec(ctx, identitySetPassword, arg.ID, arg.PasswordHash)
	return err
}

const identitySetPhone = `-- name: IdentitySetPhone :exec
update identity.users set phone = $2, phone_verified_at = now() where id = $1
`

type IdentitySetPhoneParams struct {
	ID    uuid.UUID `json:"id"`
	Phone *string   `json:"phone"`
}

func (q *Queries) IdentitySetPhone(ctx context.Context, arg IdentitySetPhoneParams) error {
	_, err := q.db.Exec(ctx, identitySetPhone, arg.ID, arg.Phone)
	return err
}

const identitySetPrivacyRequestStatus = `-- name: IdentitySetPrivacyRequestStatus :exec
update identity.privacy_requests set status = $2, completed_at = case when $2 = 'completed' then now() else completed_at end where id = $1
`

type IdentitySetPrivacyRequestStatusParams struct {
	ID     uuid.UUID `json:"id"`
	Status string    `json:"status"`
}

func (q *Queries) IdentitySetPrivacyRequestStatus(ctx context.Context, arg IdentitySetPrivacyRequestStatusParams) error {
	_, err := q.db.Exec(ctx, identitySetPrivacyRequestStatus, arg.ID, arg.Status)
	return err
}

const identitySetSessionMFA = `-- name: IdentitySetSessionMFA :exec
update identity.user_sessions set mfa_at = now() where family_id = $1 and revoked_at is null
`

func (q *Queries) IdentitySetSessionMFA(ctx context.Context, familyID uuid.UUID) error {
	_, err := q.db.Exec(ctx, identitySetSessionMFA, familyID)
	return err
}

const identitySetStaffStatus = `-- name: IdentitySetStaffStatus :exec
update identity.staff_members set status = $2, exited_on = case when $2 = 'exited' then current_date else exited_on end where user_id = $1
`

type IdentitySetStaffStatusParams struct {
	UserID uuid.UUID `json:"userId"`
	Status string    `json:"status"`
}

func (q *Queries) IdentitySetStaffStatus(ctx context.Context, arg IdentitySetStaffStatusParams) error {
	_, err := q.db.Exec(ctx, identitySetStaffStatus, arg.UserID, arg.Status)
	return err
}

const identityTouchLogin = `-- name: IdentityTouchLogin :exec
update identity.users set last_login_at = now() where id = $1
`

func (q *Queries) IdentityTouchLogin(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, identityTouchLogin, id)
	return err
}

const identityUpdateAddress = `-- name: IdentityUpdateAddress :one
update identity.addresses
set label = $3, recipient_name = $4, phone = $5, line1 = $6, line2 = $7, landmark = $8, city = $9, lga = $10, state_code = $11
where id = $1 and user_id = $2
returning id, user_id, business_id, label, recipient_name, phone, line1, line2, landmark, city, lga, state_code, latitude, longitude, is_default, created_at, updated_at
`

type IdentityUpdateAddressParams struct {
	ID            uuid.UUID  `json:"id"`
	UserID        *uuid.UUID `json:"userId"`
	Label         *string    `json:"label"`
	RecipientName string     `json:"recipientName"`
	Phone         string     `json:"phone"`
	Line1         string     `json:"line1"`
	Line2         *string    `json:"line2"`
	Landmark      *string    `json:"landmark"`
	City          string     `json:"city"`
	Lga           *string    `json:"lga"`
	StateCode     string     `json:"stateCode"`
}

func (q *Queries) IdentityUpdateAddress(ctx context.Context, arg IdentityUpdateAddressParams) (IdentityAddress, error) {
	row := q.db.QueryRow(ctx, identityUpdateAddress,
		arg.ID,
		arg.UserID,
		arg.Label,
		arg.RecipientName,
		arg.Phone,
		arg.Line1,
		arg.Line2,
		arg.Landmark,
		arg.City,
		arg.Lga,
		arg.StateCode,
	)
	var i IdentityAddress
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.BusinessID,
		&i.Label,
		&i.RecipientName,
		&i.Phone,
		&i.Line1,
		&i.Line2,
		&i.Landmark,
		&i.City,
		&i.Lga,
		&i.StateCode,
		&i.Latitude,
		&i.Longitude,
		&i.IsDefault,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const identityUpdateProfile = `-- name: IdentityUpdateProfile :one
update identity.users
set first_name = coalesce($2, first_name),
    last_name = coalesce($3, last_name),
    marketing_opt_in = coalesce($4, marketing_opt_in)
where id = $1
returning id, email, phone, password_hash, first_name, last_name, status, email_verified_at, phone_verified_at, marketing_opt_in, last_login_at, created_at, updated_at
`

type IdentityUpdateProfileParams struct {
	ID             uuid.UUID `json:"id"`
	FirstName      *string   `json:"firstName"`
	LastName       *string   `json:"lastName"`
	MarketingOptIn *bool     `json:"marketingOptIn"`
}

func (q *Queries) IdentityUpdateProfile(ctx context.Context, arg IdentityUpdateProfileParams) (IdentityUser, error) {
	row := q.db.QueryRow(ctx, identityUpdateProfile,
		arg.ID,
		arg.FirstName,
		arg.LastName,
		arg.MarketingOptIn,
	)
	var i IdentityUser
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Phone,
		&i.PasswordHash,
		&i.FirstName,
		&i.LastName,
		&i.Status,
		&i.EmailVerifiedAt,
		&i.PhoneVerifiedAt,
		&i.MarketingOptIn,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const identityUpsertPendingTOTP = `-- name: IdentityUpsertPendingTOTP :one
insert into identity.user_mfa_factors (user_id, kind, secret_encrypted)
values ($1, 'totp', $2)
on conflict (user_id) where kind = 'totp' do update set secret_encrypted = excluded.secret_encrypted, confirmed_at = null, last_used_step = null
returning id, user_id, kind, secret_encrypted, encryption_key_id, last_used_step, confirmed_at, created_at
`

type IdentityUpsertPendingTOTPParams struct {
	UserID          uuid.UUID `json:"userId"`
	SecretEncrypted []byte    `json:"secretEncrypted"`
}

func (q *Queries) IdentityUpsertPendingTOTP(ctx context.Context, arg IdentityUpsertPendingTOTPParams) (IdentityUserMfaFactor, error) {
	row := q.db.QueryRow(ctx, identityUpsertPendingTOTP, arg.UserID, arg.SecretEncrypted)
	var i IdentityUserMfaFactor
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Kind,
		&i.SecretEncrypted,
		&i.EncryptionKeyID,
		&i.LastUsedStep,
		&i.ConfirmedAt,
		&i.CreatedAt,
	)
	return i, err
}

const identityUpsertPermission = `-- name: IdentityUpsertPermission :exec
insert into identity.permissions (key, module, description, is_sensitive) values ($1, $2, $3, $4)
on conflict (key) do update set module = excluded.module, description = excluded.description, is_sensitive = excluded.is_sensitive
`

type IdentityUpsertPermissionParams struct {
	Key         string  `json:"key"`
	Module      string  `json:"module"`
	Description *string `json:"description"`
	IsSensitive bool    `json:"isSensitive"`
}

func (q *Queries) IdentityUpsertPermission(ctx context.Context, arg IdentityUpsertPermissionParams) error {
	_, err := q.db.Exec(ctx, identityUpsertPermission,
		arg.Key,
		arg.Module,
		arg.Description,
		arg.IsSensitive,
	)
	return err
}

const identityUpsertRole = `-- name: IdentityUpsertRole :one
insert into identity.roles (key, name, description, is_system) values ($1, $2, $3, $4)
on conflict (key) do update set name = excluded.name, description = excluded.description
returning id, key, name, description, is_system, created_at, updated_at
`

type IdentityUpsertRoleParams struct {
	Key         string  `json:"key"`
	Name        string  `json:"name"`
	Description *string `json:"description"`
	IsSystem    bool    `json:"isSystem"`
}

func (q *Queries) IdentityUpsertRole(ctx context.Context, arg IdentityUpsertRoleParams) (IdentityRole, error) {
	row := q.db.QueryRow(ctx, identityUpsertRole,
		arg.Key,
		arg.Name,
		arg.Description,
		arg.IsSystem,
	)
	var i IdentityRole
	err := row.Scan(
		&i.ID,
		&i.Key,
		&i.Name,
		&i.Description,
		&i.IsSystem,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const identityUpsertServiceClient = `-- name: IdentityUpsertServiceClient :exec
insert into identity.service_clients (name, secret_hash, scopes) values ($1, $2, $3)
on conflict (name) do update set secret_hash = excluded.secret_hash, scopes = excluded.scopes, rotated_at = now()
`

type IdentityUpsertServiceClientParams struct {
	Name       string   `json:"name"`
	SecretHash []byte   `json:"secretHash"`
	Scopes     []string `json:"scopes"`
}

func (q *Queries) IdentityUpsertServiceClient(ctx context.Context, arg IdentityUpsertServiceClientParams) error {
	_, err := q.db.Exec(ctx, identityUpsertServiceClient, arg.Name, arg.SecretHash, arg.Scopes)
	return err
}

const identityUseInvite = `-- name: IdentityUseInvite :exec
update identity.staff_invites set used_at = now() where id = $1
`

func (q *Queries) IdentityUseInvite(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, identityUseInvite, id)
	return err
}

const identityUseRecoveryCode = `-- name: IdentityUseRecoveryCode :execrows
update identity.user_recovery_codes set used_at = now()
where user_id = $1 and code_hash = $2 and used_at is null
`

type IdentityUseRecoveryCodeParams struct {
	UserID   uuid.UUID `json:"userId"`
	CodeHash []byte    `json:"codeHash"`
}

func (q *Queries) IdentityUseRecoveryCode(ctx context.Context, arg IdentityUseRecoveryCodeParams) (int64, error) {
	result, err := q.db.Exec(ctx, identityUseRecoveryCode, arg.UserID, arg.CodeHash)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const identityUseTOTPStep = `-- name: IdentityUseTOTPStep :execrows
update identity.user_mfa_factors set last_used_step = $2
where id = $1 and (last_used_step is null or last_used_step < $2)
`

type IdentityUseTOTPStepParams struct {
	ID           uuid.UUID `json:"id"`
	LastUsedStep *int64    `json:"lastUsedStep"`
}

// Records the step; fails (0 rows) if this step or a later one was already used (no code reuse).
func (q *Queries) IdentityUseTOTPStep(ctx context.Context, arg IdentityUseTOTPStepParams) (int64, error) {
	result, err := q.db.Exec(ctx, identityUseTOTPStep, arg.ID, arg.LastUsedStep)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const identityUserPermissionKeys = `-- name: IdentityUserPermissionKeys :many

select distinct p.key
from identity.staff_members sm
join identity.staff_roles sr on sr.user_id = sm.user_id
join identity.role_permissions rp on rp.role_id = sr.role_id
join identity.permissions p on p.id = rp.permission_id
where sm.user_id = $1 and sm.status = 'active'
`

// RBAC
func (q *Queries) IdentityUserPermissionKeys(ctx context.Context, userID uuid.UUID) ([]string, error) {
	rows, err := q.db.Query(ctx, identityUserPermissionKeys, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var key string
		if err := rows.Scan(&key); err != nil {
			return nil, err
		}
		items = append(items, key)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const identityUsersWithRole = `-- name: IdentityUsersWithRole :many
select user_id from identity.staff_roles where role_id = $1
`

func (q *Queries) IdentityUsersWithRole(ctx context.Context, roleID uuid.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, identityUsersWithRole, roleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var user_id uuid.UUID
		if err := rows.Scan(&user_id); err != nil {
			return nil, err
		}
		items = append(items, user_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
