// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: logistics.sql

package store

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

const logisticsAddRiderZone = `-- name: LogisticsAddRiderZone :exec
insert into logistics.rider_zones (rider_id, zone_id) values ($1, $2) on conflict do nothing
`

type LogisticsAddRiderZoneParams struct {
	RiderID uuid.UUID `json:"riderId"`
	ZoneID  uuid.UUID `json:"zoneId"`
}

func (q *Queries) LogisticsAddRiderZone(ctx context.Context, arg LogisticsAddRiderZoneParams) error {
	_, err := q.db.Exec(ctx, logisticsAddRiderZone, arg.RiderID, arg.ZoneID)
	return err
}

const logisticsApproveDevice = `-- name: LogisticsApproveDevice :one
update logistics.rider_devices set approved_by = $2, approved_at = now(), revoked_at = null where id = $1 returning id, rider_id, device_id, platform, approved_by, approved_at, revoked_at, created_at
`

type LogisticsApproveDeviceParams struct {
	ID         uuid.UUID  `json:"id"`
	ApprovedBy *uuid.UUID `json:"approvedBy"`
}

func (q *Queries) LogisticsApproveDevice(ctx context.Context, arg LogisticsApproveDeviceParams) (LogisticsRiderDevice, error) {
	row := q.db.QueryRow(ctx, logisticsApproveDevice, arg.ID, arg.ApprovedBy)
	var i LogisticsRiderDevice
	err := row.Scan(
		&i.ID,
		&i.RiderID,
		&i.DeviceID,
		&i.Platform,
		&i.ApprovedBy,
		&i.ApprovedAt,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const logisticsAssignJob = `-- name: LogisticsAssignJob :one
update logistics.delivery_jobs set rider_id = $2, status = 'assigned', assigned_by = $3, assigned_at = now(), route_sequence = $4
where id = $1 and status in ('unassigned', 'assigned', 'failed') returning id, kind, fulfilment_id, return_request_id, rider_id, zone_id, status, pickup_warehouse_id, pickup_address, dropoff_latitude, dropoff_longitude, route_sequence, window_start, window_end, attempts, assigned_by, assigned_at, delivered_at, recipient_name, otp_hash, otp_expires_at, otp_attempts, otp_verified_at, proof_method, proof_file_id, created_at, updated_at
`

type LogisticsAssignJobParams struct {
	ID            uuid.UUID  `json:"id"`
	RiderID       *uuid.UUID `json:"riderId"`
	AssignedBy    *uuid.UUID `json:"assignedBy"`
	RouteSequence *int16     `json:"routeSequence"`
}

func (q *Queries) LogisticsAssignJob(ctx context.Context, arg LogisticsAssignJobParams) (LogisticsDeliveryJob, error) {
	row := q.db.QueryRow(ctx, logisticsAssignJob,
		arg.ID,
		arg.RiderID,
		arg.AssignedBy,
		arg.RouteSequence,
	)
	var i LogisticsDeliveryJob
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.FulfilmentID,
		&i.ReturnRequestID,
		&i.RiderID,
		&i.ZoneID,
		&i.Status,
		&i.PickupWarehouseID,
		&i.PickupAddress,
		&i.DropoffLatitude,
		&i.DropoffLongitude,
		&i.RouteSequence,
		&i.WindowStart,
		&i.WindowEnd,
		&i.Attempts,
		&i.AssignedBy,
		&i.AssignedAt,
		&i.DeliveredAt,
		&i.RecipientName,
		&i.OtpHash,
		&i.OtpExpiresAt,
		&i.OtpAttempts,
		&i.OtpVerifiedAt,
		&i.ProofMethod,
		&i.ProofFileID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const logisticsBoard = `-- name: LogisticsBoard :many
select j.id, j.kind, j.fulfilment_id, j.return_request_id, j.rider_id, j.zone_id, j.status, j.pickup_warehouse_id, j.pickup_address, j.dropoff_latitude, j.dropoff_longitude, j.route_sequence, j.window_start, j.window_end, j.attempts, j.assigned_by, j.assigned_at, j.delivered_at, j.recipient_name, j.otp_hash, j.otp_expires_at, j.otp_attempts, j.otp_verified_at, j.proof_method, j.proof_file_id, j.created_at, j.updated_at, z.name as zone_name, o.order_number, u.first_name as rider_first_name
from logistics.delivery_jobs j
join logistics.delivery_zones z on z.id = j.zone_id
left join sales.fulfilments f on f.id = j.fulfilment_id
left join sales.orders o on o.id = f.order_id
left join identity.users u on u.id = j.rider_id
where ($1::text is null or j.status = $1)
  and ($2::uuid is null or j.zone_id = $2)
  and (j.status not in ('delivered', 'returned', 'cancelled') or j.updated_at > now() - interval '24 hours')
order by j.window_start nulls last, j.created_at limit 500
`

type LogisticsBoardParams struct {
	Status *string    `json:"status"`
	ZoneID *uuid.UUID `json:"zoneId"`
}

type LogisticsBoardRow struct {
	ID                uuid.UUID       `json:"id"`
	Kind              string          `json:"kind"`
	FulfilmentID      *uuid.UUID      `json:"fulfilmentId"`
	ReturnRequestID   *uuid.UUID      `json:"returnRequestId"`
	RiderID           *uuid.UUID      `json:"riderId"`
	ZoneID            uuid.UUID       `json:"zoneId"`
	Status            string          `json:"status"`
	PickupWarehouseID *uuid.UUID      `json:"pickupWarehouseId"`
	PickupAddress     json.RawMessage `json:"pickupAddress"`
	DropoffLatitude   *float64        `json:"dropoffLatitude"`
	DropoffLongitude  *float64        `json:"dropoffLongitude"`
	RouteSequence     *int16          `json:"routeSequence"`
	WindowStart       *time.Time      `json:"windowStart"`
	WindowEnd         *time.Time      `json:"windowEnd"`
	Attempts          int16           `json:"attempts"`
	AssignedBy        *uuid.UUID      `json:"assignedBy"`
	AssignedAt        *time.Time      `json:"assignedAt"`
	DeliveredAt       *time.Time      `json:"deliveredAt"`
	RecipientName     *string         `json:"recipientName"`
	OtpHash           []byte          `json:"otpHash"`
	OtpExpiresAt      *time.Time      `json:"otpExpiresAt"`
	OtpAttempts       int16           `json:"otpAttempts"`
	OtpVerifiedAt     *time.Time      `json:"otpVerifiedAt"`
	ProofMethod       *string         `json:"proofMethod"`
	ProofFileID       *uuid.UUID      `json:"proofFileId"`
	CreatedAt         time.Time       `json:"createdAt"`
	UpdatedAt         time.Time       `json:"updatedAt"`
	ZoneName          string          `json:"zoneName"`
	OrderNumber       *string         `json:"orderNumber"`
	RiderFirstName    *string         `json:"riderFirstName"`
}

func (q *Queries) LogisticsBoard(ctx context.Context, arg LogisticsBoardParams) ([]LogisticsBoardRow, error) {
	rows, err := q.db.Query(ctx, logisticsBoard, arg.Status, arg.ZoneID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LogisticsBoardRow{}
	for rows.Next() {
		var i LogisticsBoardRow
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.FulfilmentID,
			&i.ReturnRequestID,
			&i.RiderID,
			&i.ZoneID,
			&i.Status,
			&i.PickupWarehouseID,
			&i.PickupAddress,
			&i.DropoffLatitude,
			&i.DropoffLongitude,
			&i.RouteSequence,
			&i.WindowStart,
			&i.WindowEnd,
			&i.Attempts,
			&i.AssignedBy,
			&i.AssignedAt,
			&i.DeliveredAt,
			&i.RecipientName,
			&i.OtpHash,
			&i.OtpExpiresAt,
			&i.OtpAttempts,
			&i.OtpVerifiedAt,
			&i.ProofMethod,
			&i.ProofFileID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ZoneName,
			&i.OrderNumber,
			&i.RiderFirstName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const logisticsBoardCounts = `-- name: LogisticsBoardCounts :one
select count(*) filter (where status = 'unassigned')::int as unassigned,
       count(*) filter (where status = 'assigned')::int as assigned,
       count(*) filter (where status in ('picked_up', 'en_route'))::int as in_transit,
       count(*) filter (where status = 'failed')::int as failed,
       count(*) filter (where status = 'delivered' and delivered_at > date_trunc('day', now()))::int as delivered_today
from logistics.delivery_jobs
`

type LogisticsBoardCountsRow struct {
	Unassigned     int32 `json:"unassigned"`
	Assigned       int32 `json:"assigned"`
	InTransit      int32 `json:"inTransit"`
	Failed         int32 `json:"failed"`
	DeliveredToday int32 `json:"deliveredToday"`
}

func (q *Queries) LogisticsBoardCounts(ctx context.Context) (LogisticsBoardCountsRow, error) {
	row := q.db.QueryRow(ctx, logisticsBoardCounts)
	var i LogisticsBoardCountsRow
	err := row.Scan(
		&i.Unassigned,
		&i.Assigned,
		&i.InTransit,
		&i.Failed,
		&i.DeliveredToday,
	)
	return i, err
}

const logisticsCreateJob = `-- name: LogisticsCreateJob :one
insert into logistics.delivery_jobs (kind, fulfilment_id, return_request_id, zone_id, pickup_warehouse_id, pickup_address,
  dropoff_latitude, dropoff_longitude, window_start, window_end, recipient_name)
values ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11) returning id, kind, fulfilment_id, return_request_id, rider_id, zone_id, status, pickup_warehouse_id, pickup_address, dropoff_latitude, dropoff_longitude, route_sequence, window_start, window_end, attempts, assigned_by, assigned_at, delivered_at, recipient_name, otp_hash, otp_expires_at, otp_attempts, otp_verified_at, proof_method, proof_file_id, created_at, updated_at
`

type LogisticsCreateJobParams struct {
	Kind              string          `json:"kind"`
	FulfilmentID      *uuid.UUID      `json:"fulfilmentId"`
	ReturnRequestID   *uuid.UUID      `json:"returnRequestId"`
	ZoneID            uuid.UUID       `json:"zoneId"`
	PickupWarehouseID *uuid.UUID      `json:"pickupWarehouseId"`
	PickupAddress     json.RawMessage `json:"pickupAddress"`
	DropoffLatitude   *float64        `json:"dropoffLatitude"`
	DropoffLongitude  *float64        `json:"dropoffLongitude"`
	WindowStart       *time.Time      `json:"windowStart"`
	WindowEnd         *time.Time      `json:"windowEnd"`
	RecipientName     *string         `json:"recipientName"`
}

func (q *Queries) LogisticsCreateJob(ctx context.Context, arg LogisticsCreateJobParams) (LogisticsDeliveryJob, error) {
	row := q.db.QueryRow(ctx, logisticsCreateJob,
		arg.Kind,
		arg.FulfilmentID,
		arg.ReturnRequestID,
		arg.ZoneID,
		arg.PickupWarehouseID,
		arg.PickupAddress,
		arg.DropoffLatitude,
		arg.DropoffLongitude,
		arg.WindowStart,
		arg.WindowEnd,
		arg.RecipientName,
	)
	var i LogisticsDeliveryJob
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.FulfilmentID,
		&i.ReturnRequestID,
		&i.RiderID,
		&i.ZoneID,
		&i.Status,
		&i.PickupWarehouseID,
		&i.PickupAddress,
		&i.DropoffLatitude,
		&i.DropoffLongitude,
		&i.RouteSequence,
		&i.WindowStart,
		&i.WindowEnd,
		&i.Attempts,
		&i.AssignedBy,
		&i.AssignedAt,
		&i.DeliveredAt,
		&i.RecipientName,
		&i.OtpHash,
		&i.OtpExpiresAt,
		&i.OtpAttempts,
		&i.OtpVerifiedAt,
		&i.ProofMethod,
		&i.ProofFileID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const logisticsCreateRate = `-- name: LogisticsCreateRate :one
insert into logistics.delivery_rates (zone_id, fulfilled_by, max_weight_grams, fee_kobo, eta_min_days, eta_max_days, valid_from)
values ($1, $2, $3, $4, $5, $6, $7) returning id, zone_id, fulfilled_by, max_weight_grams, fee_kobo, eta_min_days, eta_max_days, valid_from
`

type LogisticsCreateRateParams struct {
	ZoneID         uuid.UUID `json:"zoneId"`
	FulfilledBy    string    `json:"fulfilledBy"`
	MaxWeightGrams int32     `json:"maxWeightGrams"`
	FeeKobo        int64     `json:"feeKobo"`
	EtaMinDays     int16     `json:"etaMinDays"`
	EtaMaxDays     int16     `json:"etaMaxDays"`
	ValidFrom      time.Time `json:"validFrom"`
}

func (q *Queries) LogisticsCreateRate(ctx context.Context, arg LogisticsCreateRateParams) (LogisticsDeliveryRate, error) {
	row := q.db.QueryRow(ctx, logisticsCreateRate,
		arg.ZoneID,
		arg.FulfilledBy,
		arg.MaxWeightGrams,
		arg.FeeKobo,
		arg.EtaMinDays,
		arg.EtaMaxDays,
		arg.ValidFrom,
	)
	var i LogisticsDeliveryRate
	err := row.Scan(
		&i.ID,
		&i.ZoneID,
		&i.FulfilledBy,
		&i.MaxWeightGrams,
		&i.FeeKobo,
		&i.EtaMinDays,
		&i.EtaMaxDays,
		&i.ValidFrom,
	)
	return i, err
}

const logisticsCreateRider = `-- name: LogisticsCreateRider :one
insert into logistics.riders (user_id, vehicle_type, plate_number, home_warehouse_id) values ($1, $2, $3, $4) returning user_id, vehicle_type, plate_number, home_warehouse_id, status, created_at, updated_at
`

type LogisticsCreateRiderParams struct {
	UserID          uuid.UUID `json:"userId"`
	VehicleType     string    `json:"vehicleType"`
	PlateNumber     *string   `json:"plateNumber"`
	HomeWarehouseID uuid.UUID `json:"homeWarehouseId"`
}

func (q *Queries) LogisticsCreateRider(ctx context.Context, arg LogisticsCreateRiderParams) (LogisticsRider, error) {
	row := q.db.QueryRow(ctx, logisticsCreateRider,
		arg.UserID,
		arg.VehicleType,
		arg.PlateNumber,
		arg.HomeWarehouseID,
	)
	var i LogisticsRider
	err := row.Scan(
		&i.UserID,
		&i.VehicleType,
		&i.PlateNumber,
		&i.HomeWarehouseID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const logisticsCreateZone = `-- name: LogisticsCreateZone :one
insert into logistics.delivery_zones (name, state_code, lgas, is_active) values ($1, $2, $3, $4) returning id, name, state_code, lgas, is_active, created_at
`

type LogisticsCreateZoneParams struct {
	Name      string   `json:"name"`
	StateCode string   `json:"stateCode"`
	Lgas      []string `json:"lgas"`
	IsActive  bool     `json:"isActive"`
}

func (q *Queries) LogisticsCreateZone(ctx context.Context, arg LogisticsCreateZoneParams) (LogisticsDeliveryZone, error) {
	row := q.db.QueryRow(ctx, logisticsCreateZone,
		arg.Name,
		arg.StateCode,
		arg.Lgas,
		arg.IsActive,
	)
	var i LogisticsDeliveryZone
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.StateCode,
		&i.Lgas,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const logisticsDeviceApproved = `-- name: LogisticsDeviceApproved :one
select exists (select 1 from logistics.rider_devices where rider_id = $1 and device_id = $2 and approved_at is not null and revoked_at is null)::bool
`

type LogisticsDeviceApprovedParams struct {
	RiderID  uuid.UUID `json:"riderId"`
	DeviceID string    `json:"deviceId"`
}

func (q *Queries) LogisticsDeviceApproved(ctx context.Context, arg LogisticsDeviceApprovedParams) (bool, error) {
	row := q.db.QueryRow(ctx, logisticsDeviceApproved, arg.RiderID, arg.DeviceID)
	var column_1 bool
	err := row.Scan(&column_1)
	return column_1, err
}

const logisticsEnRouteJobs = `-- name: LogisticsEnRouteJobs :many
select j.id, f.order_id from logistics.delivery_jobs j join sales.fulfilments f on f.id = j.fulfilment_id
where j.rider_id = $1 and j.status = 'en_route'
`

type LogisticsEnRouteJobsRow struct {
	ID      uuid.UUID `json:"id"`
	OrderID uuid.UUID `json:"orderId"`
}

func (q *Queries) LogisticsEnRouteJobs(ctx context.Context, riderID *uuid.UUID) ([]LogisticsEnRouteJobsRow, error) {
	rows, err := q.db.Query(ctx, logisticsEnRouteJobs, riderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LogisticsEnRouteJobsRow{}
	for rows.Next() {
		var i LogisticsEnRouteJobsRow
		if err := rows.Scan(&i.ID, &i.OrderID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const logisticsEndShift = `-- name: LogisticsEndShift :one
update logistics.rider_shifts set ended_at = now() where rider_id = $1 and ended_at is null returning id, rider_id, device_session_id, started_at, ended_at, start_latitude, start_longitude, location_consent_at
`

func (q *Queries) LogisticsEndShift(ctx context.Context, riderID uuid.UUID) (LogisticsRiderShift, error) {
	row := q.db.QueryRow(ctx, logisticsEndShift, riderID)
	var i LogisticsRiderShift
	err := row.Scan(
		&i.ID,
		&i.RiderID,
		&i.DeviceSessionID,
		&i.StartedAt,
		&i.EndedAt,
		&i.StartLatitude,
		&i.StartLongitude,
		&i.LocationConsentAt,
	)
	return i, err
}

const logisticsFulfilmentDeliveryInfo = `-- name: LogisticsFulfilmentDeliveryInfo :one
select f.id, f.order_id, f.seller_id, f.fulfilled_by, f.method, f.warehouse_id, o.ship_to, o.order_number,
  (select r.warehouse_id from inventory.stock_reservations r where r.order_id = f.order_id and r.owner_seller_id = f.seller_id
     and r.warehouse_id is not null limit 1) as reserved_warehouse_id
from sales.fulfilments f join sales.orders o on o.id = f.order_id where f.id = $1
`

type LogisticsFulfilmentDeliveryInfoRow struct {
	ID                  uuid.UUID       `json:"id"`
	OrderID             uuid.UUID       `json:"orderId"`
	SellerID            uuid.UUID       `json:"sellerId"`
	FulfilledBy         string          `json:"fulfilledBy"`
	Method              string          `json:"method"`
	WarehouseID         *uuid.UUID      `json:"warehouseId"`
	ShipTo              json.RawMessage `json:"shipTo"`
	OrderNumber         string          `json:"orderNumber"`
	ReservedWarehouseID *uuid.UUID      `json:"reservedWarehouseId"`
}

// Everything needed to create a delivery job for a packed fulfilment.
func (q *Queries) LogisticsFulfilmentDeliveryInfo(ctx context.Context, id uuid.UUID) (LogisticsFulfilmentDeliveryInfoRow, error) {
	row := q.db.QueryRow(ctx, logisticsFulfilmentDeliveryInfo, id)
	var i LogisticsFulfilmentDeliveryInfoRow
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.SellerID,
		&i.FulfilledBy,
		&i.Method,
		&i.WarehouseID,
		&i.ShipTo,
		&i.OrderNumber,
		&i.ReservedWarehouseID,
	)
	return i, err
}

const logisticsGetJob = `-- name: LogisticsGetJob :one
select id, kind, fulfilment_id, return_request_id, rider_id, zone_id, status, pickup_warehouse_id, pickup_address, dropoff_latitude, dropoff_longitude, route_sequence, window_start, window_end, attempts, assigned_by, assigned_at, delivered_at, recipient_name, otp_hash, otp_expires_at, otp_attempts, otp_verified_at, proof_method, proof_file_id, created_at, updated_at from logistics.delivery_jobs where id = $1
`

func (q *Queries) LogisticsGetJob(ctx context.Context, id uuid.UUID) (LogisticsDeliveryJob, error) {
	row := q.db.QueryRow(ctx, logisticsGetJob, id)
	var i LogisticsDeliveryJob
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.FulfilmentID,
		&i.ReturnRequestID,
		&i.RiderID,
		&i.ZoneID,
		&i.Status,
		&i.PickupWarehouseID,
		&i.PickupAddress,
		&i.DropoffLatitude,
		&i.DropoffLongitude,
		&i.RouteSequence,
		&i.WindowStart,
		&i.WindowEnd,
		&i.Attempts,
		&i.AssignedBy,
		&i.AssignedAt,
		&i.DeliveredAt,
		&i.RecipientName,
		&i.OtpHash,
		&i.OtpExpiresAt,
		&i.OtpAttempts,
		&i.OtpVerifiedAt,
		&i.ProofMethod,
		&i.ProofFileID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const logisticsGetJobForUpdate = `-- name: LogisticsGetJobForUpdate :one
select id, kind, fulfilment_id, return_request_id, rider_id, zone_id, status, pickup_warehouse_id, pickup_address, dropoff_latitude, dropoff_longitude, route_sequence, window_start, window_end, attempts, assigned_by, assigned_at, delivered_at, recipient_name, otp_hash, otp_expires_at, otp_attempts, otp_verified_at, proof_method, proof_file_id, created_at, updated_at from logistics.delivery_jobs where id = $1 for update
`

func (q *Queries) LogisticsGetJobForUpdate(ctx context.Context, id uuid.UUID) (LogisticsDeliveryJob, error) {
	row := q.db.QueryRow(ctx, logisticsGetJobForUpdate, id)
	var i LogisticsDeliveryJob
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.FulfilmentID,
		&i.ReturnRequestID,
		&i.RiderID,
		&i.ZoneID,
		&i.Status,
		&i.PickupWarehouseID,
		&i.PickupAddress,
		&i.DropoffLatitude,
		&i.DropoffLongitude,
		&i.RouteSequence,
		&i.WindowStart,
		&i.WindowEnd,
		&i.Attempts,
		&i.AssignedBy,
		&i.AssignedAt,
		&i.DeliveredAt,
		&i.RecipientName,
		&i.OtpHash,
		&i.OtpExpiresAt,
		&i.OtpAttempts,
		&i.OtpVerifiedAt,
		&i.ProofMethod,
		&i.ProofFileID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const logisticsGetRider = `-- name: LogisticsGetRider :one
select user_id, vehicle_type, plate_number, home_warehouse_id, status, created_at, updated_at from logistics.riders where user_id = $1
`

func (q *Queries) LogisticsGetRider(ctx context.Context, userID uuid.UUID) (LogisticsRider, error) {
	row := q.db.QueryRow(ctx, logisticsGetRider, userID)
	var i LogisticsRider
	err := row.Scan(
		&i.UserID,
		&i.VehicleType,
		&i.PlateNumber,
		&i.HomeWarehouseID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const logisticsInsertEvent = `-- name: LogisticsInsertEvent :one
insert into logistics.delivery_events (delivery_job_id, client_event_id, kind, reason, latitude, longitude, accuracy_m, note, file_id, created_by, occurred_at)
values ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
on conflict (client_event_id) do nothing
returning id, delivery_job_id, client_event_id, kind, reason, latitude, longitude, accuracy_m, note, file_id, created_by, occurred_at, created_at
`

type LogisticsInsertEventParams struct {
	DeliveryJobID uuid.UUID  `json:"deliveryJobId"`
	ClientEventID *uuid.UUID `json:"clientEventId"`
	Kind          string     `json:"kind"`
	Reason        *string    `json:"reason"`
	Latitude      *float64   `json:"latitude"`
	Longitude     *float64   `json:"longitude"`
	AccuracyM     *float32   `json:"accuracyM"`
	Note          *string    `json:"note"`
	FileID        *uuid.UUID `json:"fileId"`
	CreatedBy     *uuid.UUID `json:"createdBy"`
	OccurredAt    time.Time  `json:"occurredAt"`
}

// Idempotent per client_event_id (offline sync): a replay returns no row.
func (q *Queries) LogisticsInsertEvent(ctx context.Context, arg LogisticsInsertEventParams) (LogisticsDeliveryEvent, error) {
	row := q.db.QueryRow(ctx, logisticsInsertEvent,
		arg.DeliveryJobID,
		arg.ClientEventID,
		arg.Kind,
		arg.Reason,
		arg.Latitude,
		arg.Longitude,
		arg.AccuracyM,
		arg.Note,
		arg.FileID,
		arg.CreatedBy,
		arg.OccurredAt,
	)
	var i LogisticsDeliveryEvent
	err := row.Scan(
		&i.ID,
		&i.DeliveryJobID,
		&i.ClientEventID,
		&i.Kind,
		&i.Reason,
		&i.Latitude,
		&i.Longitude,
		&i.AccuracyM,
		&i.Note,
		&i.FileID,
		&i.CreatedBy,
		&i.OccurredAt,
		&i.CreatedAt,
	)
	return i, err
}

const logisticsInsertPing = `-- name: LogisticsInsertPing :exec
insert into logistics.rider_location_pings (rider_id, latitude, longitude, accuracy_m, speed, heading, recorded_at) values ($1, $2, $3, $4, $5, $6, $7)
on conflict do nothing
`

type LogisticsInsertPingParams struct {
	RiderID    uuid.UUID `json:"riderId"`
	Latitude   float64   `json:"latitude"`
	Longitude  float64   `json:"longitude"`
	AccuracyM  *float32  `json:"accuracyM"`
	Speed      *float32  `json:"speed"`
	Heading    *float32  `json:"heading"`
	RecordedAt time.Time `json:"recordedAt"`
}

func (q *Queries) LogisticsInsertPing(ctx context.Context, arg LogisticsInsertPingParams) error {
	_, err := q.db.Exec(ctx, logisticsInsertPing,
		arg.RiderID,
		arg.Latitude,
		arg.Longitude,
		arg.AccuracyM,
		arg.Speed,
		arg.Heading,
		arg.RecordedAt,
	)
	return err
}

const logisticsJobEvents = `-- name: LogisticsJobEvents :many
select id, delivery_job_id, client_event_id, kind, reason, latitude, longitude, accuracy_m, note, file_id, created_by, occurred_at, created_at from logistics.delivery_events where delivery_job_id = $1 order by occurred_at, created_at
`

func (q *Queries) LogisticsJobEvents(ctx context.Context, deliveryJobID uuid.UUID) ([]LogisticsDeliveryEvent, error) {
	rows, err := q.db.Query(ctx, logisticsJobEvents, deliveryJobID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LogisticsDeliveryEvent{}
	for rows.Next() {
		var i LogisticsDeliveryEvent
		if err := rows.Scan(
			&i.ID,
			&i.DeliveryJobID,
			&i.ClientEventID,
			&i.Kind,
			&i.Reason,
			&i.Latitude,
			&i.Longitude,
			&i.AccuracyM,
			&i.Note,
			&i.FileID,
			&i.CreatedBy,
			&i.OccurredAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const logisticsJobForFulfilment = `-- name: LogisticsJobForFulfilment :one
select id, kind, fulfilment_id, return_request_id, rider_id, zone_id, status, pickup_warehouse_id, pickup_address, dropoff_latitude, dropoff_longitude, route_sequence, window_start, window_end, attempts, assigned_by, assigned_at, delivered_at, recipient_name, otp_hash, otp_expires_at, otp_attempts, otp_verified_at, proof_method, proof_file_id, created_at, updated_at from logistics.delivery_jobs where fulfilment_id = $1 and kind = 'delivery' and status <> 'cancelled' order by created_at desc limit 1
`

func (q *Queries) LogisticsJobForFulfilment(ctx context.Context, fulfilmentID *uuid.UUID) (LogisticsDeliveryJob, error) {
	row := q.db.QueryRow(ctx, logisticsJobForFulfilment, fulfilmentID)
	var i LogisticsDeliveryJob
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.FulfilmentID,
		&i.ReturnRequestID,
		&i.RiderID,
		&i.ZoneID,
		&i.Status,
		&i.PickupWarehouseID,
		&i.PickupAddress,
		&i.DropoffLatitude,
		&i.DropoffLongitude,
		&i.RouteSequence,
		&i.WindowStart,
		&i.WindowEnd,
		&i.Attempts,
		&i.AssignedBy,
		&i.AssignedAt,
		&i.DeliveredAt,
		&i.RecipientName,
		&i.OtpHash,
		&i.OtpExpiresAt,
		&i.OtpAttempts,
		&i.OtpVerifiedAt,
		&i.ProofMethod,
		&i.ProofFileID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const logisticsJobView = `-- name: LogisticsJobView :one
select j.id, j.kind, j.fulfilment_id, j.return_request_id, j.rider_id, j.zone_id, j.status, j.pickup_warehouse_id, j.pickup_address, j.dropoff_latitude, j.dropoff_longitude, j.route_sequence, j.window_start, j.window_end, j.attempts, j.assigned_by, j.assigned_at, j.delivered_at, j.recipient_name, j.otp_hash, j.otp_expires_at, j.otp_attempts, j.otp_verified_at, j.proof_method, j.proof_file_id, j.created_at, j.updated_at, f.order_id, o.order_number, o.ship_to, o.contact_phone, o.customer_user_id, w.name as pickup_warehouse_name, w.address as pickup_warehouse_address
from logistics.delivery_jobs j
left join sales.fulfilments f on f.id = j.fulfilment_id
left join sales.orders o on o.id = f.order_id
left join inventory.warehouses w on w.id = j.pickup_warehouse_id
where j.id = $1
`

type LogisticsJobViewRow struct {
	ID                     uuid.UUID       `json:"id"`
	Kind                   string          `json:"kind"`
	FulfilmentID           *uuid.UUID      `json:"fulfilmentId"`
	ReturnRequestID        *uuid.UUID      `json:"returnRequestId"`
	RiderID                *uuid.UUID      `json:"riderId"`
	ZoneID                 uuid.UUID       `json:"zoneId"`
	Status                 string          `json:"status"`
	PickupWarehouseID      *uuid.UUID      `json:"pickupWarehouseId"`
	PickupAddress          json.RawMessage `json:"pickupAddress"`
	DropoffLatitude        *float64        `json:"dropoffLatitude"`
	DropoffLongitude       *float64        `json:"dropoffLongitude"`
	RouteSequence          *int16          `json:"routeSequence"`
	WindowStart            *time.Time      `json:"windowStart"`
	WindowEnd              *time.Time      `json:"windowEnd"`
	Attempts               int16           `json:"attempts"`
	AssignedBy             *uuid.UUID      `json:"assignedBy"`
	AssignedAt             *time.Time      `json:"assignedAt"`
	DeliveredAt            *time.Time      `json:"deliveredAt"`
	RecipientName          *string         `json:"recipientName"`
	OtpHash                []byte          `json:"otpHash"`
	OtpExpiresAt           *time.Time      `json:"otpExpiresAt"`
	OtpAttempts            int16           `json:"otpAttempts"`
	OtpVerifiedAt          *time.Time      `json:"otpVerifiedAt"`
	ProofMethod            *string         `json:"proofMethod"`
	ProofFileID            *uuid.UUID      `json:"proofFileId"`
	CreatedAt              time.Time       `json:"createdAt"`
	UpdatedAt              time.Time       `json:"updatedAt"`
	OrderID                *uuid.UUID      `json:"orderId"`
	OrderNumber            *string         `json:"orderNumber"`
	ShipTo                 json.RawMessage `json:"shipTo"`
	ContactPhone           *string         `json:"contactPhone"`
	CustomerUserID         *uuid.UUID      `json:"customerUserId"`
	PickupWarehouseName    *string         `json:"pickupWarehouseName"`
	PickupWarehouseAddress *string         `json:"pickupWarehouseAddress"`
}

func (q *Queries) LogisticsJobView(ctx context.Context, id uuid.UUID) (LogisticsJobViewRow, error) {
	row := q.db.QueryRow(ctx, logisticsJobView, id)
	var i LogisticsJobViewRow
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.FulfilmentID,
		&i.ReturnRequestID,
		&i.RiderID,
		&i.ZoneID,
		&i.Status,
		&i.PickupWarehouseID,
		&i.PickupAddress,
		&i.DropoffLatitude,
		&i.DropoffLongitude,
		&i.RouteSequence,
		&i.WindowStart,
		&i.WindowEnd,
		&i.Attempts,
		&i.AssignedBy,
		&i.AssignedAt,
		&i.DeliveredAt,
		&i.RecipientName,
		&i.OtpHash,
		&i.OtpExpiresAt,
		&i.OtpAttempts,
		&i.OtpVerifiedAt,
		&i.ProofMethod,
		&i.ProofFileID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OrderID,
		&i.OrderNumber,
		&i.ShipTo,
		&i.ContactPhone,
		&i.CustomerUserID,
		&i.PickupWarehouseName,
		&i.PickupWarehouseAddress,
	)
	return i, err
}

const logisticsListDevices = `-- name: LogisticsListDevices :many
select d.id, d.rider_id, d.device_id, d.platform, d.approved_by, d.approved_at, d.revoked_at, d.created_at, u.first_name, u.last_name from logistics.rider_devices d join identity.users u on u.id = d.rider_id
where ($1::bool is not true or (d.approved_at is null and d.revoked_at is null))
order by d.created_at desc limit 200
`

type LogisticsListDevicesRow struct {
	ID         uuid.UUID  `json:"id"`
	RiderID    uuid.UUID  `json:"riderId"`
	DeviceID   string     `json:"deviceId"`
	Platform   string     `json:"platform"`
	ApprovedBy *uuid.UUID `json:"approvedBy"`
	ApprovedAt *time.Time `json:"approvedAt"`
	RevokedAt  *time.Time `json:"revokedAt"`
	CreatedAt  time.Time  `json:"createdAt"`
	FirstName  string     `json:"firstName"`
	LastName   string     `json:"lastName"`
}

func (q *Queries) LogisticsListDevices(ctx context.Context, pending *bool) ([]LogisticsListDevicesRow, error) {
	rows, err := q.db.Query(ctx, logisticsListDevices, pending)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LogisticsListDevicesRow{}
	for rows.Next() {
		var i LogisticsListDevicesRow
		if err := rows.Scan(
			&i.ID,
			&i.RiderID,
			&i.DeviceID,
			&i.Platform,
			&i.ApprovedBy,
			&i.ApprovedAt,
			&i.RevokedAt,
			&i.CreatedAt,
			&i.FirstName,
			&i.LastName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const logisticsListRiders = `-- name: LogisticsListRiders :many
select r.user_id, r.vehicle_type, r.plate_number, r.home_warehouse_id, r.status, u.first_name, u.last_name, u.phone,
       l.latitude, l.longitude, l.recorded_at as last_seen_at,
       (select s.id from logistics.rider_shifts s where s.rider_id = r.user_id and s.ended_at is null) as open_shift_id,
       (select count(*) from logistics.delivery_jobs j where j.rider_id = r.user_id and j.status in ('assigned', 'picked_up', 'en_route'))::int as active_jobs,
       coalesce((select array_agg(z.zone_id) from logistics.rider_zones z where z.rider_id = r.user_id), '{}')::uuid[] as zone_ids
from logistics.riders r join identity.users u on u.id = r.user_id
left join logistics.rider_locations l on l.rider_id = r.user_id
order by r.status, u.first_name
`

type LogisticsListRidersRow struct {
	UserID          uuid.UUID   `json:"userId"`
	VehicleType     string      `json:"vehicleType"`
	PlateNumber     *string     `json:"plateNumber"`
	HomeWarehouseID uuid.UUID   `json:"homeWarehouseId"`
	Status          string      `json:"status"`
	FirstName       string      `json:"firstName"`
	LastName        string      `json:"lastName"`
	Phone           *string     `json:"phone"`
	Latitude        *float64    `json:"latitude"`
	Longitude       *float64    `json:"longitude"`
	LastSeenAt      *time.Time  `json:"lastSeenAt"`
	OpenShiftID     uuid.UUID   `json:"openShiftId"`
	ActiveJobs      int32       `json:"activeJobs"`
	ZoneIds         []uuid.UUID `json:"zoneIds"`
}

// Riders with their latest position, open shift and active job count (for the assign sheet and map).
func (q *Queries) LogisticsListRiders(ctx context.Context) ([]LogisticsListRidersRow, error) {
	rows, err := q.db.Query(ctx, logisticsListRiders)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LogisticsListRidersRow{}
	for rows.Next() {
		var i LogisticsListRidersRow
		if err := rows.Scan(
			&i.UserID,
			&i.VehicleType,
			&i.PlateNumber,
			&i.HomeWarehouseID,
			&i.Status,
			&i.FirstName,
			&i.LastName,
			&i.Phone,
			&i.Latitude,
			&i.Longitude,
			&i.LastSeenAt,
			&i.OpenShiftID,
			&i.ActiveJobs,
			&i.ZoneIds,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const logisticsListZones = `-- name: LogisticsListZones :many

select id, name, state_code, lgas, is_active, created_at from logistics.delivery_zones order by state_code, name
`

// Logistics: zones, rates, riders, devices, shifts, delivery jobs, events, locations (docs/mobile.md §4).
func (q *Queries) LogisticsListZones(ctx context.Context) ([]LogisticsDeliveryZone, error) {
	rows, err := q.db.Query(ctx, logisticsListZones)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LogisticsDeliveryZone{}
	for rows.Next() {
		var i LogisticsDeliveryZone
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.StateCode,
			&i.Lgas,
			&i.IsActive,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const logisticsOTPFailed = `-- name: LogisticsOTPFailed :one
update logistics.delivery_jobs set otp_attempts = otp_attempts + 1 where id = $1 returning otp_attempts
`

func (q *Queries) LogisticsOTPFailed(ctx context.Context, id uuid.UUID) (int16, error) {
	row := q.db.QueryRow(ctx, logisticsOTPFailed, id)
	var otp_attempts int16
	err := row.Scan(&otp_attempts)
	return otp_attempts, err
}

const logisticsOTPVerified = `-- name: LogisticsOTPVerified :exec
update logistics.delivery_jobs set otp_verified_at = now() where id = $1
`

func (q *Queries) LogisticsOTPVerified(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, logisticsOTPVerified, id)
	return err
}

const logisticsOpenShift = `-- name: LogisticsOpenShift :one
select id, rider_id, device_session_id, started_at, ended_at, start_latitude, start_longitude, location_consent_at from logistics.rider_shifts where rider_id = $1 and ended_at is null
`

func (q *Queries) LogisticsOpenShift(ctx context.Context, riderID uuid.UUID) (LogisticsRiderShift, error) {
	row := q.db.QueryRow(ctx, logisticsOpenShift, riderID)
	var i LogisticsRiderShift
	err := row.Scan(
		&i.ID,
		&i.RiderID,
		&i.DeviceSessionID,
		&i.StartedAt,
		&i.EndedAt,
		&i.StartLatitude,
		&i.StartLongitude,
		&i.LocationConsentAt,
	)
	return i, err
}

const logisticsPurgePings = `-- name: LogisticsPurgePings :execrows
delete from logistics.rider_location_pings where recorded_at < now() - interval '90 days'
`

// Raw location points are kept about 90 days (docs/mobile.md §4.4).
func (q *Queries) LogisticsPurgePings(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, logisticsPurgePings)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const logisticsRate = `-- name: LogisticsRate :one
select id, zone_id, fulfilled_by, max_weight_grams, fee_kobo, eta_min_days, eta_max_days, valid_from from logistics.delivery_rates
where zone_id = $1 and fulfilled_by = $2 and max_weight_grams >= $3::int and valid_from <= current_date
order by max_weight_grams, valid_from desc limit 1
`

type LogisticsRateParams struct {
	ZoneID      uuid.UUID `json:"zoneId"`
	FulfilledBy string    `json:"fulfilledBy"`
	Weight      int32     `json:"weight"`
}

// The current rate band for a parcel: the smallest weight band that fits, newest valid version.
func (q *Queries) LogisticsRate(ctx context.Context, arg LogisticsRateParams) (LogisticsDeliveryRate, error) {
	row := q.db.QueryRow(ctx, logisticsRate, arg.ZoneID, arg.FulfilledBy, arg.Weight)
	var i LogisticsDeliveryRate
	err := row.Scan(
		&i.ID,
		&i.ZoneID,
		&i.FulfilledBy,
		&i.MaxWeightGrams,
		&i.FeeKobo,
		&i.EtaMinDays,
		&i.EtaMaxDays,
		&i.ValidFrom,
	)
	return i, err
}

const logisticsRegisterDevice = `-- name: LogisticsRegisterDevice :one
insert into logistics.rider_devices (rider_id, device_id, platform) values ($1, $2, $3)
on conflict (rider_id, device_id) do update set platform = excluded.platform
returning id, rider_id, device_id, platform, approved_by, approved_at, revoked_at, created_at
`

type LogisticsRegisterDeviceParams struct {
	RiderID  uuid.UUID `json:"riderId"`
	DeviceID string    `json:"deviceId"`
	Platform string    `json:"platform"`
}

func (q *Queries) LogisticsRegisterDevice(ctx context.Context, arg LogisticsRegisterDeviceParams) (LogisticsRiderDevice, error) {
	row := q.db.QueryRow(ctx, logisticsRegisterDevice, arg.RiderID, arg.DeviceID, arg.Platform)
	var i LogisticsRiderDevice
	err := row.Scan(
		&i.ID,
		&i.RiderID,
		&i.DeviceID,
		&i.Platform,
		&i.ApprovedBy,
		&i.ApprovedAt,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const logisticsResolveZone = `-- name: LogisticsResolveZone :one
select id, name, state_code, lgas, is_active, created_at from logistics.delivery_zones
where is_active and state_code = $1 and (cardinality(lgas) = 0 or $2::text = any(lgas))
order by cardinality(lgas) > 0 desc, name limit 1
`

type LogisticsResolveZoneParams struct {
	StateCode string `json:"stateCode"`
	Lga       string `json:"lga"`
}

// The zone for a state and LGA: an LGA-specific zone first, then the state-wide zone (no LGAs listed).
func (q *Queries) LogisticsResolveZone(ctx context.Context, arg LogisticsResolveZoneParams) (LogisticsDeliveryZone, error) {
	row := q.db.QueryRow(ctx, logisticsResolveZone, arg.StateCode, arg.Lga)
	var i LogisticsDeliveryZone
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.StateCode,
		&i.Lgas,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const logisticsRevokeDevice = `-- name: LogisticsRevokeDevice :one
update logistics.rider_devices set revoked_at = now() where id = $1 returning id, rider_id, device_id, platform, approved_by, approved_at, revoked_at, created_at
`

func (q *Queries) LogisticsRevokeDevice(ctx context.Context, id uuid.UUID) (LogisticsRiderDevice, error) {
	row := q.db.QueryRow(ctx, logisticsRevokeDevice, id)
	var i LogisticsRiderDevice
	err := row.Scan(
		&i.ID,
		&i.RiderID,
		&i.DeviceID,
		&i.Platform,
		&i.ApprovedBy,
		&i.ApprovedAt,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const logisticsRiderJobs = `-- name: LogisticsRiderJobs :many
select j.id, j.kind, j.fulfilment_id, j.return_request_id, j.rider_id, j.zone_id, j.status, j.pickup_warehouse_id, j.pickup_address, j.dropoff_latitude, j.dropoff_longitude, j.route_sequence, j.window_start, j.window_end, j.attempts, j.assigned_by, j.assigned_at, j.delivered_at, j.recipient_name, j.otp_hash, j.otp_expires_at, j.otp_attempts, j.otp_verified_at, j.proof_method, j.proof_file_id, j.created_at, j.updated_at, f.order_id, o.order_number, o.ship_to, o.contact_phone, w.name as pickup_warehouse_name, w.address as pickup_warehouse_address
from logistics.delivery_jobs j
left join sales.fulfilments f on f.id = j.fulfilment_id
left join sales.orders o on o.id = f.order_id
left join inventory.warehouses w on w.id = j.pickup_warehouse_id
where j.rider_id = $1 and (j.status in ('assigned', 'picked_up', 'en_route', 'failed') or j.updated_at > now() - interval '24 hours')
order by j.route_sequence nulls last, j.window_start nulls last, j.created_at
`

type LogisticsRiderJobsRow struct {
	ID                     uuid.UUID       `json:"id"`
	Kind                   string          `json:"kind"`
	FulfilmentID           *uuid.UUID      `json:"fulfilmentId"`
	ReturnRequestID        *uuid.UUID      `json:"returnRequestId"`
	RiderID                *uuid.UUID      `json:"riderId"`
	ZoneID                 uuid.UUID       `json:"zoneId"`
	Status                 string          `json:"status"`
	PickupWarehouseID      *uuid.UUID      `json:"pickupWarehouseId"`
	PickupAddress          json.RawMessage `json:"pickupAddress"`
	DropoffLatitude        *float64        `json:"dropoffLatitude"`
	DropoffLongitude       *float64        `json:"dropoffLongitude"`
	RouteSequence          *int16          `json:"routeSequence"`
	WindowStart            *time.Time      `json:"windowStart"`
	WindowEnd              *time.Time      `json:"windowEnd"`
	Attempts               int16           `json:"attempts"`
	AssignedBy             *uuid.UUID      `json:"assignedBy"`
	AssignedAt             *time.Time      `json:"assignedAt"`
	DeliveredAt            *time.Time      `json:"deliveredAt"`
	RecipientName          *string         `json:"recipientName"`
	OtpHash                []byte          `json:"otpHash"`
	OtpExpiresAt           *time.Time      `json:"otpExpiresAt"`
	OtpAttempts            int16           `json:"otpAttempts"`
	OtpVerifiedAt          *time.Time      `json:"otpVerifiedAt"`
	ProofMethod            *string         `json:"proofMethod"`
	ProofFileID            *uuid.UUID      `json:"proofFileId"`
	CreatedAt              time.Time       `json:"createdAt"`
	UpdatedAt              time.Time       `json:"updatedAt"`
	OrderID                *uuid.UUID      `json:"orderId"`
	OrderNumber            *string         `json:"orderNumber"`
	ShipTo                 json.RawMessage `json:"shipTo"`
	ContactPhone           *string         `json:"contactPhone"`
	PickupWarehouseName    *string         `json:"pickupWarehouseName"`
	PickupWarehouseAddress *string         `json:"pickupWarehouseAddress"`
}

// A rider's work: active jobs plus today's finished ones, with what the job screen needs.
func (q *Queries) LogisticsRiderJobs(ctx context.Context, riderID *uuid.UUID) ([]LogisticsRiderJobsRow, error) {
	rows, err := q.db.Query(ctx, logisticsRiderJobs, riderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LogisticsRiderJobsRow{}
	for rows.Next() {
		var i LogisticsRiderJobsRow
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.FulfilmentID,
			&i.ReturnRequestID,
			&i.RiderID,
			&i.ZoneID,
			&i.Status,
			&i.PickupWarehouseID,
			&i.PickupAddress,
			&i.DropoffLatitude,
			&i.DropoffLongitude,
			&i.RouteSequence,
			&i.WindowStart,
			&i.WindowEnd,
			&i.Attempts,
			&i.AssignedBy,
			&i.AssignedAt,
			&i.DeliveredAt,
			&i.RecipientName,
			&i.OtpHash,
			&i.OtpExpiresAt,
			&i.OtpAttempts,
			&i.OtpVerifiedAt,
			&i.ProofMethod,
			&i.ProofFileID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.OrderID,
			&i.OrderNumber,
			&i.ShipTo,
			&i.ContactPhone,
			&i.PickupWarehouseName,
			&i.PickupWarehouseAddress,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const logisticsSetJobOTP = `-- name: LogisticsSetJobOTP :exec
update logistics.delivery_jobs set otp_hash = $2, otp_expires_at = $3, otp_attempts = 0, otp_verified_at = null where id = $1
`

type LogisticsSetJobOTPParams struct {
	ID           uuid.UUID  `json:"id"`
	OtpHash      []byte     `json:"otpHash"`
	OtpExpiresAt *time.Time `json:"otpExpiresAt"`
}

func (q *Queries) LogisticsSetJobOTP(ctx context.Context, arg LogisticsSetJobOTPParams) error {
	_, err := q.db.Exec(ctx, logisticsSetJobOTP, arg.ID, arg.OtpHash, arg.OtpExpiresAt)
	return err
}

const logisticsSetJobStatus = `-- name: LogisticsSetJobStatus :one
update logistics.delivery_jobs
set status = $2,
    attempts = case when $2 = 'failed' then attempts + 1 else attempts end,
    delivered_at = case when $2 = 'delivered' then now() else delivered_at end,
    proof_method = coalesce($3, proof_method),
    proof_file_id = coalesce($4, proof_file_id),
    recipient_name = coalesce($5, recipient_name)
where id = $1 returning id, kind, fulfilment_id, return_request_id, rider_id, zone_id, status, pickup_warehouse_id, pickup_address, dropoff_latitude, dropoff_longitude, route_sequence, window_start, window_end, attempts, assigned_by, assigned_at, delivered_at, recipient_name, otp_hash, otp_expires_at, otp_attempts, otp_verified_at, proof_method, proof_file_id, created_at, updated_at
`

type LogisticsSetJobStatusParams struct {
	ID            uuid.UUID  `json:"id"`
	Status        string     `json:"status"`
	ProofMethod   *string    `json:"proofMethod"`
	ProofFileID   *uuid.UUID `json:"proofFileId"`
	RecipientName *string    `json:"recipientName"`
}

func (q *Queries) LogisticsSetJobStatus(ctx context.Context, arg LogisticsSetJobStatusParams) (LogisticsDeliveryJob, error) {
	row := q.db.QueryRow(ctx, logisticsSetJobStatus,
		arg.ID,
		arg.Status,
		arg.ProofMethod,
		arg.ProofFileID,
		arg.RecipientName,
	)
	var i LogisticsDeliveryJob
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.FulfilmentID,
		&i.ReturnRequestID,
		&i.RiderID,
		&i.ZoneID,
		&i.Status,
		&i.PickupWarehouseID,
		&i.PickupAddress,
		&i.DropoffLatitude,
		&i.DropoffLongitude,
		&i.RouteSequence,
		&i.WindowStart,
		&i.WindowEnd,
		&i.Attempts,
		&i.AssignedBy,
		&i.AssignedAt,
		&i.DeliveredAt,
		&i.RecipientName,
		&i.OtpHash,
		&i.OtpExpiresAt,
		&i.OtpAttempts,
		&i.OtpVerifiedAt,
		&i.ProofMethod,
		&i.ProofFileID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const logisticsSetRiderStatus = `-- name: LogisticsSetRiderStatus :exec
update logistics.riders set status = $2 where user_id = $1
`

type LogisticsSetRiderStatusParams struct {
	UserID uuid.UUID `json:"userId"`
	Status string    `json:"status"`
}

func (q *Queries) LogisticsSetRiderStatus(ctx context.Context, arg LogisticsSetRiderStatusParams) error {
	_, err := q.db.Exec(ctx, logisticsSetRiderStatus, arg.UserID, arg.Status)
	return err
}

const logisticsSetRiderZones = `-- name: LogisticsSetRiderZones :exec
delete from logistics.rider_zones where rider_id = $1
`

func (q *Queries) LogisticsSetRiderZones(ctx context.Context, riderID uuid.UUID) error {
	_, err := q.db.Exec(ctx, logisticsSetRiderZones, riderID)
	return err
}

const logisticsStaleShifts = `-- name: LogisticsStaleShifts :many
select id, rider_id, device_session_id, started_at, ended_at, start_latitude, start_longitude, location_consent_at from logistics.rider_shifts where ended_at is null and started_at < now() - interval '12 hours'
`

// Shifts open for more than 12 hours are closed automatically (location tracking stops).
func (q *Queries) LogisticsStaleShifts(ctx context.Context) ([]LogisticsRiderShift, error) {
	rows, err := q.db.Query(ctx, logisticsStaleShifts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LogisticsRiderShift{}
	for rows.Next() {
		var i LogisticsRiderShift
		if err := rows.Scan(
			&i.ID,
			&i.RiderID,
			&i.DeviceSessionID,
			&i.StartedAt,
			&i.EndedAt,
			&i.StartLatitude,
			&i.StartLongitude,
			&i.LocationConsentAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const logisticsStartShift = `-- name: LogisticsStartShift :one
insert into logistics.rider_shifts (rider_id, device_session_id, start_latitude, start_longitude, location_consent_at)
values ($1, $2, $3, $4, now()) returning id, rider_id, device_session_id, started_at, ended_at, start_latitude, start_longitude, location_consent_at
`

type LogisticsStartShiftParams struct {
	RiderID         uuid.UUID  `json:"riderId"`
	DeviceSessionID *uuid.UUID `json:"deviceSessionId"`
	StartLatitude   *float64   `json:"startLatitude"`
	StartLongitude  *float64   `json:"startLongitude"`
}

func (q *Queries) LogisticsStartShift(ctx context.Context, arg LogisticsStartShiftParams) (LogisticsRiderShift, error) {
	row := q.db.QueryRow(ctx, logisticsStartShift,
		arg.RiderID,
		arg.DeviceSessionID,
		arg.StartLatitude,
		arg.StartLongitude,
	)
	var i LogisticsRiderShift
	err := row.Scan(
		&i.ID,
		&i.RiderID,
		&i.DeviceSessionID,
		&i.StartedAt,
		&i.EndedAt,
		&i.StartLatitude,
		&i.StartLongitude,
		&i.LocationConsentAt,
	)
	return i, err
}

const logisticsUnassignJob = `-- name: LogisticsUnassignJob :one
update logistics.delivery_jobs set rider_id = null, status = 'unassigned', assigned_by = null, assigned_at = null
where id = $1 and status = 'assigned' returning id, kind, fulfilment_id, return_request_id, rider_id, zone_id, status, pickup_warehouse_id, pickup_address, dropoff_latitude, dropoff_longitude, route_sequence, window_start, window_end, attempts, assigned_by, assigned_at, delivered_at, recipient_name, otp_hash, otp_expires_at, otp_attempts, otp_verified_at, proof_method, proof_file_id, created_at, updated_at
`

func (q *Queries) LogisticsUnassignJob(ctx context.Context, id uuid.UUID) (LogisticsDeliveryJob, error) {
	row := q.db.QueryRow(ctx, logisticsUnassignJob, id)
	var i LogisticsDeliveryJob
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.FulfilmentID,
		&i.ReturnRequestID,
		&i.RiderID,
		&i.ZoneID,
		&i.Status,
		&i.PickupWarehouseID,
		&i.PickupAddress,
		&i.DropoffLatitude,
		&i.DropoffLongitude,
		&i.RouteSequence,
		&i.WindowStart,
		&i.WindowEnd,
		&i.Attempts,
		&i.AssignedBy,
		&i.AssignedAt,
		&i.DeliveredAt,
		&i.RecipientName,
		&i.OtpHash,
		&i.OtpExpiresAt,
		&i.OtpAttempts,
		&i.OtpVerifiedAt,
		&i.ProofMethod,
		&i.ProofFileID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const logisticsUpdateZone = `-- name: LogisticsUpdateZone :one
update logistics.delivery_zones set name = $2, lgas = $3, is_active = $4 where id = $1 returning id, name, state_code, lgas, is_active, created_at
`

type LogisticsUpdateZoneParams struct {
	ID       uuid.UUID `json:"id"`
	Name     string    `json:"name"`
	Lgas     []string  `json:"lgas"`
	IsActive bool      `json:"isActive"`
}

func (q *Queries) LogisticsUpdateZone(ctx context.Context, arg LogisticsUpdateZoneParams) (LogisticsDeliveryZone, error) {
	row := q.db.QueryRow(ctx, logisticsUpdateZone,
		arg.ID,
		arg.Name,
		arg.Lgas,
		arg.IsActive,
	)
	var i LogisticsDeliveryZone
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.StateCode,
		&i.Lgas,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const logisticsUpsertLocation = `-- name: LogisticsUpsertLocation :exec
insert into logistics.rider_locations (rider_id, latitude, longitude, accuracy_m, job_id, recorded_at) values ($1, $2, $3, $4, $5, $6)
on conflict (rider_id) do update set latitude = excluded.latitude, longitude = excluded.longitude, accuracy_m = excluded.accuracy_m,
  job_id = excluded.job_id, recorded_at = excluded.recorded_at
where logistics.rider_locations.recorded_at < excluded.recorded_at
`

type LogisticsUpsertLocationParams struct {
	RiderID    uuid.UUID  `json:"riderId"`
	Latitude   float64    `json:"latitude"`
	Longitude  float64    `json:"longitude"`
	AccuracyM  *float32   `json:"accuracyM"`
	JobID      *uuid.UUID `json:"jobId"`
	RecordedAt time.Time  `json:"recordedAt"`
}

func (q *Queries) LogisticsUpsertLocation(ctx context.Context, arg LogisticsUpsertLocationParams) error {
	_, err := q.db.Exec(ctx, logisticsUpsertLocation,
		arg.RiderID,
		arg.Latitude,
		arg.Longitude,
		arg.AccuracyM,
		arg.JobID,
		arg.RecordedAt,
	)
	return err
}

const logisticsZoneRates = `-- name: LogisticsZoneRates :many
select id, zone_id, fulfilled_by, max_weight_grams, fee_kobo, eta_min_days, eta_max_days, valid_from from logistics.delivery_rates where zone_id = $1 order by fulfilled_by, max_weight_grams, valid_from desc
`

func (q *Queries) LogisticsZoneRates(ctx context.Context, zoneID uuid.UUID) ([]LogisticsDeliveryRate, error) {
	rows, err := q.db.Query(ctx, logisticsZoneRates, zoneID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LogisticsDeliveryRate{}
	for rows.Next() {
		var i LogisticsDeliveryRate
		if err := rows.Scan(
			&i.ID,
			&i.ZoneID,
			&i.FulfilledBy,
			&i.MaxWeightGrams,
			&i.FeeKobo,
			&i.EtaMinDays,
			&i.EtaMaxDays,
			&i.ValidFrom,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
