// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: marketing.sql

package store

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

const marketingAbandonedCarts = `-- name: MarketingAbandonedCarts :many
select c.id as cart_id, c.user_id, count(ci.id)::int as items, sum(ci.quantity * l.price_kobo)::bigint as value_kobo
from sales.carts c
join sales.cart_items ci on ci.cart_id = c.id
join catalog.listings l on l.id = ci.listing_id
where c.status = 'active' and c.user_id is not null and c.updated_at < now() - interval '1 hour' and c.updated_at > now() - interval '3 days'
group by c.id limit 500
`

type MarketingAbandonedCartsRow struct {
	CartID    uuid.UUID  `json:"cartId"`
	UserID    *uuid.UUID `json:"userId"`
	Items     int32      `json:"items"`
	ValueKobo int64      `json:"valueKobo"`
}

// Signed-in carts idle for an hour with items, not yet enrolled in the abandoned-cart journey.
func (q *Queries) MarketingAbandonedCarts(ctx context.Context) ([]MarketingAbandonedCartsRow, error) {
	rows, err := q.db.Query(ctx, marketingAbandonedCarts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MarketingAbandonedCartsRow{}
	for rows.Next() {
		var i MarketingAbandonedCartsRow
		if err := rows.Scan(
			&i.CartID,
			&i.UserID,
			&i.Items,
			&i.ValueKobo,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const marketingActiveJourneysByTrigger = `-- name: MarketingActiveJourneysByTrigger :many
select id, name, trigger, entry_rules, reentry_days, goal_event, status, created_by, created_at, updated_at from marketing.journeys where trigger = $1 and status = 'active'
`

func (q *Queries) MarketingActiveJourneysByTrigger(ctx context.Context, trigger string) ([]MarketingJourney, error) {
	rows, err := q.db.Query(ctx, marketingActiveJourneysByTrigger, trigger)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MarketingJourney{}
	for rows.Next() {
		var i MarketingJourney
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Trigger,
			&i.EntryRules,
			&i.ReentryDays,
			&i.GoalEvent,
			&i.Status,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const marketingAddJourneyStep = `-- name: MarketingAddJourneyStep :one
insert into marketing.journey_steps (journey_id, position, kind, config) values ($1, $2, $3, $4) returning id, journey_id, position, kind, config
`

type MarketingAddJourneyStepParams struct {
	JourneyID uuid.UUID       `json:"journeyId"`
	Position  int32           `json:"position"`
	Kind      string          `json:"kind"`
	Config    json.RawMessage `json:"config"`
}

func (q *Queries) MarketingAddJourneyStep(ctx context.Context, arg MarketingAddJourneyStepParams) (MarketingJourneyStep, error) {
	row := q.db.QueryRow(ctx, marketingAddJourneyStep,
		arg.JourneyID,
		arg.Position,
		arg.Kind,
		arg.Config,
	)
	var i MarketingJourneyStep
	err := row.Scan(
		&i.ID,
		&i.JourneyID,
		&i.Position,
		&i.Kind,
		&i.Config,
	)
	return i, err
}

const marketingAddTarget = `-- name: MarketingAddTarget :one
insert into marketing.promotion_targets (promotion_id, category_id, listing_id) values ($1, $2, $3) returning id, promotion_id, category_id, listing_id
`

type MarketingAddTargetParams struct {
	PromotionID uuid.UUID  `json:"promotionId"`
	CategoryID  *uuid.UUID `json:"categoryId"`
	ListingID   *uuid.UUID `json:"listingId"`
}

func (q *Queries) MarketingAddTarget(ctx context.Context, arg MarketingAddTargetParams) (MarketingPromotionTarget, error) {
	row := q.db.QueryRow(ctx, marketingAddTarget, arg.PromotionID, arg.CategoryID, arg.ListingID)
	var i MarketingPromotionTarget
	err := row.Scan(
		&i.ID,
		&i.PromotionID,
		&i.CategoryID,
		&i.ListingID,
	)
	return i, err
}

const marketingAddVariant = `-- name: MarketingAddVariant :one
insert into marketing.campaign_variants (campaign_id, label, channel, template_version_id, share_pct) values ($1, $2, $3, $4, $5) returning id, campaign_id, label, channel, template_version_id, share_pct, is_winner
`

type MarketingAddVariantParams struct {
	CampaignID        uuid.UUID  `json:"campaignId"`
	Label             string     `json:"label"`
	Channel           string     `json:"channel"`
	TemplateVersionID *uuid.UUID `json:"templateVersionId"`
	SharePct          float64    `json:"sharePct"`
}

func (q *Queries) MarketingAddVariant(ctx context.Context, arg MarketingAddVariantParams) (MarketingCampaignVariant, error) {
	row := q.db.QueryRow(ctx, marketingAddVariant,
		arg.CampaignID,
		arg.Label,
		arg.Channel,
		arg.TemplateVersionID,
		arg.SharePct,
	)
	var i MarketingCampaignVariant
	err := row.Scan(
		&i.ID,
		&i.CampaignID,
		&i.Label,
		&i.Channel,
		&i.TemplateVersionID,
		&i.SharePct,
		&i.IsWinner,
	)
	return i, err
}

const marketingAdvanceEnrollment = `-- name: MarketingAdvanceEnrollment :exec
update marketing.journey_enrollments set current_step = $2, next_run_at = $3, updated_at = now() where id = $1
`

type MarketingAdvanceEnrollmentParams struct {
	ID          uuid.UUID  `json:"id"`
	CurrentStep int32      `json:"currentStep"`
	NextRunAt   *time.Time `json:"nextRunAt"`
}

func (q *Queries) MarketingAdvanceEnrollment(ctx context.Context, arg MarketingAdvanceEnrollmentParams) error {
	_, err := q.db.Exec(ctx, marketingAdvanceEnrollment, arg.ID, arg.CurrentStep, arg.NextRunAt)
	return err
}

const marketingAdvancePromotions = `-- name: MarketingAdvancePromotions :many
update marketing.promotions set status = case when now() >= ends_at then 'ended' else 'live' end, updated_at = now()
where (status = 'scheduled' and now() >= starts_at) or (status = 'live' and now() >= ends_at)
returning id, status
`

type MarketingAdvancePromotionsRow struct {
	ID     uuid.UUID `json:"id"`
	Status string    `json:"status"`
}

// Scheduled promotions go live at starts_at; live ones end at ends_at (runs every minute).
func (q *Queries) MarketingAdvancePromotions(ctx context.Context) ([]MarketingAdvancePromotionsRow, error) {
	rows, err := q.db.Query(ctx, marketingAdvancePromotions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MarketingAdvancePromotionsRow{}
	for rows.Next() {
		var i MarketingAdvancePromotionsRow
		if err := rows.Scan(&i.ID, &i.Status); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const marketingCampaignLink = `-- name: MarketingCampaignLink :one
select id, url, notification_id, campaign_id, created_at from marketing.tracked_links where campaign_id = $1 order by created_at limit 1
`

func (q *Queries) MarketingCampaignLink(ctx context.Context, campaignID *uuid.UUID) (MarketingTrackedLink, error) {
	row := q.db.QueryRow(ctx, marketingCampaignLink, campaignID)
	var i MarketingTrackedLink
	err := row.Scan(
		&i.ID,
		&i.Url,
		&i.NotificationID,
		&i.CampaignID,
		&i.CreatedAt,
	)
	return i, err
}

const marketingCampaignNotification = `-- name: MarketingCampaignNotification :one
select id from messaging.notifications where campaign_id = $1 and user_id = $2 order by created_at limit 1
`

type MarketingCampaignNotificationParams struct {
	CampaignID *uuid.UUID `json:"campaignId"`
	UserID     *uuid.UUID `json:"userId"`
}

func (q *Queries) MarketingCampaignNotification(ctx context.Context, arg MarketingCampaignNotificationParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, marketingCampaignNotification, arg.CampaignID, arg.UserID)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const marketingCampaignStats = `-- name: MarketingCampaignStats :one
select count(*)::int as recipients,
       count(*) filter (where holdout)::int as holdout,
       count(*) filter (where status = 'sent')::int as sent,
       count(*) filter (where status = 'skipped')::int as skipped,
       (select count(*) from messaging.notifications n where n.campaign_id = $1 and n.clicked_at is not null)::int as clicked,
       (select count(*) from sales.orders o join messaging.notifications n on n.id = o.attributed_notification_id where n.campaign_id = $1)::int as orders
from marketing.campaign_recipients where campaign_id = $1
`

type MarketingCampaignStatsRow struct {
	Recipients int32 `json:"recipients"`
	Holdout    int32 `json:"holdout"`
	Sent       int32 `json:"sent"`
	Skipped    int32 `json:"skipped"`
	Clicked    int32 `json:"clicked"`
	Orders     int32 `json:"orders"`
}

func (q *Queries) MarketingCampaignStats(ctx context.Context, campaignID *uuid.UUID) (MarketingCampaignStatsRow, error) {
	row := q.db.QueryRow(ctx, marketingCampaignStats, campaignID)
	var i MarketingCampaignStatsRow
	err := row.Scan(
		&i.Recipients,
		&i.Holdout,
		&i.Sent,
		&i.Skipped,
		&i.Clicked,
		&i.Orders,
	)
	return i, err
}

const marketingCampaignVariants = `-- name: MarketingCampaignVariants :many
select id, campaign_id, label, channel, template_version_id, share_pct, is_winner from marketing.campaign_variants where campaign_id = $1 order by label, channel
`

func (q *Queries) MarketingCampaignVariants(ctx context.Context, campaignID uuid.UUID) ([]MarketingCampaignVariant, error) {
	rows, err := q.db.Query(ctx, marketingCampaignVariants, campaignID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MarketingCampaignVariant{}
	for rows.Next() {
		var i MarketingCampaignVariant
		if err := rows.Scan(
			&i.ID,
			&i.CampaignID,
			&i.Label,
			&i.Channel,
			&i.TemplateVersionID,
			&i.SharePct,
			&i.IsWinner,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const marketingCartStillActive = `-- name: MarketingCartStillActive :one
select exists (select 1 from sales.carts c join sales.cart_items ci on ci.cart_id = c.id where c.user_id = $1 and c.status = 'active')::bool
`

func (q *Queries) MarketingCartStillActive(ctx context.Context, userID *uuid.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, marketingCartStillActive, userID)
	var column_1 bool
	err := row.Scan(&column_1)
	return column_1, err
}

const marketingCategoryAncestors = `-- name: MarketingCategoryAncestors :many
with recursive up as (
  select c.id, c.parent_id from catalog.categories c where c.id = $1
  union all
  select p.id, p.parent_id from catalog.categories p join up on up.parent_id = p.id
)
select id from up
`

// A category and its parents (a promotion on "Phones" covers "Phones › Android").
func (q *Queries) MarketingCategoryAncestors(ctx context.Context, id uuid.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, marketingCategoryAncestors, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const marketingClaimFlash = `-- name: MarketingClaimFlash :one
update marketing.promotion_listing_prices set claimed = claimed + $1::int
where promotion_id = $2 and listing_id = $3 and (stock_limit is null or claimed + $1::int <= stock_limit)
returning claimed, stock_limit
`

type MarketingClaimFlashParams struct {
	Qty         int32     `json:"qty"`
	PromotionID uuid.UUID `json:"promotionId"`
	ListingID   uuid.UUID `json:"listingId"`
}

type MarketingClaimFlashRow struct {
	Claimed    int32  `json:"claimed"`
	StockLimit *int32 `json:"stockLimit"`
}

// Concurrency-safe: claimed never exceeds stock_limit (a 0-row result means sold out).
func (q *Queries) MarketingClaimFlash(ctx context.Context, arg MarketingClaimFlashParams) (MarketingClaimFlashRow, error) {
	row := q.db.QueryRow(ctx, marketingClaimFlash, arg.Qty, arg.PromotionID, arg.ListingID)
	var i MarketingClaimFlashRow
	err := row.Scan(&i.Claimed, &i.StockLimit)
	return i, err
}

const marketingCreateCampaign = `-- name: MarketingCreateCampaign :one
insert into marketing.campaigns (name, segment_id, exclusions, channels, holdout_pct, ab_test, cost_estimate_kobo, created_by)
values ($1, $2, $3, $4, $5, $6, $7, $8) returning id, name, status, segment_id, exclusions, channels, scheduled_at, holdout_pct, ab_test, cost_estimate_kobo, created_by, approved_by, approved_at, created_at, updated_at
`

type MarketingCreateCampaignParams struct {
	Name             string          `json:"name"`
	SegmentID        uuid.UUID       `json:"segmentId"`
	Exclusions       json.RawMessage `json:"exclusions"`
	Channels         []string        `json:"channels"`
	HoldoutPct       float64         `json:"holdoutPct"`
	AbTest           json.RawMessage `json:"abTest"`
	CostEstimateKobo *int64          `json:"costEstimateKobo"`
	CreatedBy        uuid.UUID       `json:"createdBy"`
}

func (q *Queries) MarketingCreateCampaign(ctx context.Context, arg MarketingCreateCampaignParams) (MarketingCampaign, error) {
	row := q.db.QueryRow(ctx, marketingCreateCampaign,
		arg.Name,
		arg.SegmentID,
		arg.Exclusions,
		arg.Channels,
		arg.HoldoutPct,
		arg.AbTest,
		arg.CostEstimateKobo,
		arg.CreatedBy,
	)
	var i MarketingCampaign
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Status,
		&i.SegmentID,
		&i.Exclusions,
		&i.Channels,
		&i.ScheduledAt,
		&i.HoldoutPct,
		&i.AbTest,
		&i.CostEstimateKobo,
		&i.CreatedBy,
		&i.ApprovedBy,
		&i.ApprovedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const marketingCreateCoupon = `-- name: MarketingCreateCoupon :one
insert into marketing.coupons (code, promotion_id, is_unique_codes, max_redemptions, per_user_limit, min_order_kobo)
values ($1, $2, $3, $4, $5, $6) returning id, code, promotion_id, is_unique_codes, max_redemptions, redeemed_count, per_user_limit, min_order_kobo, created_at
`

type MarketingCreateCouponParams struct {
	Code           *string   `json:"code"`
	PromotionID    uuid.UUID `json:"promotionId"`
	IsUniqueCodes  bool      `json:"isUniqueCodes"`
	MaxRedemptions *int32    `json:"maxRedemptions"`
	PerUserLimit   int32     `json:"perUserLimit"`
	MinOrderKobo   *int64    `json:"minOrderKobo"`
}

func (q *Queries) MarketingCreateCoupon(ctx context.Context, arg MarketingCreateCouponParams) (MarketingCoupon, error) {
	row := q.db.QueryRow(ctx, marketingCreateCoupon,
		arg.Code,
		arg.PromotionID,
		arg.IsUniqueCodes,
		arg.MaxRedemptions,
		arg.PerUserLimit,
		arg.MinOrderKobo,
	)
	var i MarketingCoupon
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.PromotionID,
		&i.IsUniqueCodes,
		&i.MaxRedemptions,
		&i.RedeemedCount,
		&i.PerUserLimit,
		&i.MinOrderKobo,
		&i.CreatedAt,
	)
	return i, err
}

const marketingCreateCouponCode = `-- name: MarketingCreateCouponCode :one
insert into marketing.coupon_codes (coupon_id, code, issued_to_user_id, notification_id, expires_at) values ($1, $2, $3, $4, $5) returning id, coupon_id, code, issued_to_user_id, notification_id, expires_at, redeemed_at, created_at
`

type MarketingCreateCouponCodeParams struct {
	CouponID       uuid.UUID  `json:"couponId"`
	Code           string     `json:"code"`
	IssuedToUserID *uuid.UUID `json:"issuedToUserId"`
	NotificationID *uuid.UUID `json:"notificationId"`
	ExpiresAt      *time.Time `json:"expiresAt"`
}

func (q *Queries) MarketingCreateCouponCode(ctx context.Context, arg MarketingCreateCouponCodeParams) (MarketingCouponCode, error) {
	row := q.db.QueryRow(ctx, marketingCreateCouponCode,
		arg.CouponID,
		arg.Code,
		arg.IssuedToUserID,
		arg.NotificationID,
		arg.ExpiresAt,
	)
	var i MarketingCouponCode
	err := row.Scan(
		&i.ID,
		&i.CouponID,
		&i.Code,
		&i.IssuedToUserID,
		&i.NotificationID,
		&i.ExpiresAt,
		&i.RedeemedAt,
		&i.CreatedAt,
	)
	return i, err
}

const marketingCreateJourney = `-- name: MarketingCreateJourney :one
insert into marketing.journeys (name, trigger, entry_rules, reentry_days, goal_event, created_by) values ($1, $2, $3, $4, $5, $6) returning id, name, trigger, entry_rules, reentry_days, goal_event, status, created_by, created_at, updated_at
`

type MarketingCreateJourneyParams struct {
	Name        string          `json:"name"`
	Trigger     string          `json:"trigger"`
	EntryRules  json.RawMessage `json:"entryRules"`
	ReentryDays *int32          `json:"reentryDays"`
	GoalEvent   *string         `json:"goalEvent"`
	CreatedBy   uuid.UUID       `json:"createdBy"`
}

func (q *Queries) MarketingCreateJourney(ctx context.Context, arg MarketingCreateJourneyParams) (MarketingJourney, error) {
	row := q.db.QueryRow(ctx, marketingCreateJourney,
		arg.Name,
		arg.Trigger,
		arg.EntryRules,
		arg.ReentryDays,
		arg.GoalEvent,
		arg.CreatedBy,
	)
	var i MarketingJourney
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Trigger,
		&i.EntryRules,
		&i.ReentryDays,
		&i.GoalEvent,
		&i.Status,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const marketingCreateLink = `-- name: MarketingCreateLink :one
insert into marketing.tracked_links (url, notification_id, campaign_id) values ($1, $2, $3) returning id, url, notification_id, campaign_id, created_at
`

type MarketingCreateLinkParams struct {
	Url            string     `json:"url"`
	NotificationID *uuid.UUID `json:"notificationId"`
	CampaignID     *uuid.UUID `json:"campaignId"`
}

func (q *Queries) MarketingCreateLink(ctx context.Context, arg MarketingCreateLinkParams) (MarketingTrackedLink, error) {
	row := q.db.QueryRow(ctx, marketingCreateLink, arg.Url, arg.NotificationID, arg.CampaignID)
	var i MarketingTrackedLink
	err := row.Scan(
		&i.ID,
		&i.Url,
		&i.NotificationID,
		&i.CampaignID,
		&i.CreatedAt,
	)
	return i, err
}

const marketingCreatePromotion = `-- name: MarketingCreatePromotion :one

insert into marketing.promotions (name, kind, value, funded_by, starts_at, ends_at, status, created_by)
values ($1, $2, $3, $4, $5, $6, $7, $8) returning id, name, kind, value, funded_by, starts_at, ends_at, status, created_by, created_at, updated_at
`

type MarketingCreatePromotionParams struct {
	Name      string    `json:"name"`
	Kind      string    `json:"kind"`
	Value     *int32    `json:"value"`
	FundedBy  string    `json:"fundedBy"`
	StartsAt  time.Time `json:"startsAt"`
	EndsAt    time.Time `json:"endsAt"`
	Status    string    `json:"status"`
	CreatedBy uuid.UUID `json:"createdBy"`
}

// Marketing: promotions, flash deals, coupons, segments, campaigns, journeys, tracked links
// (docs/messaging-marketing.md §4, docs/backend.md §4.4).
func (q *Queries) MarketingCreatePromotion(ctx context.Context, arg MarketingCreatePromotionParams) (MarketingPromotion, error) {
	row := q.db.QueryRow(ctx, marketingCreatePromotion,
		arg.Name,
		arg.Kind,
		arg.Value,
		arg.FundedBy,
		arg.StartsAt,
		arg.EndsAt,
		arg.Status,
		arg.CreatedBy,
	)
	var i MarketingPromotion
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Kind,
		&i.Value,
		&i.FundedBy,
		&i.StartsAt,
		&i.EndsAt,
		&i.Status,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const marketingCreateSegment = `-- name: MarketingCreateSegment :one
insert into marketing.segments (name, rules, created_by) values ($1, $2, $3) returning id, name, rules, created_by, last_count, last_counted_at, created_at, updated_at
`

type MarketingCreateSegmentParams struct {
	Name      string          `json:"name"`
	Rules     json.RawMessage `json:"rules"`
	CreatedBy uuid.UUID       `json:"createdBy"`
}

func (q *Queries) MarketingCreateSegment(ctx context.Context, arg MarketingCreateSegmentParams) (MarketingSegment, error) {
	row := q.db.QueryRow(ctx, marketingCreateSegment, arg.Name, arg.Rules, arg.CreatedBy)
	var i MarketingSegment
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Rules,
		&i.CreatedBy,
		&i.LastCount,
		&i.LastCountedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const marketingDecrementCoupon = `-- name: MarketingDecrementCoupon :exec
update marketing.coupons set redeemed_count = greatest(redeemed_count - 1, 0) where id = $1
`

func (q *Queries) MarketingDecrementCoupon(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, marketingDecrementCoupon, id)
	return err
}

const marketingDueCampaigns = `-- name: MarketingDueCampaigns :many
select id, name, status, segment_id, exclusions, channels, scheduled_at, holdout_pct, ab_test, cost_estimate_kobo, created_by, approved_by, approved_at, created_at, updated_at from marketing.campaigns where status = 'scheduled' and scheduled_at <= now() limit 10
`

func (q *Queries) MarketingDueCampaigns(ctx context.Context) ([]MarketingCampaign, error) {
	rows, err := q.db.Query(ctx, marketingDueCampaigns)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MarketingCampaign{}
	for rows.Next() {
		var i MarketingCampaign
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Status,
			&i.SegmentID,
			&i.Exclusions,
			&i.Channels,
			&i.ScheduledAt,
			&i.HoldoutPct,
			&i.AbTest,
			&i.CostEstimateKobo,
			&i.CreatedBy,
			&i.ApprovedBy,
			&i.ApprovedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const marketingDueEnrollments = `-- name: MarketingDueEnrollments :many
select e.id, e.journey_id, e.user_id, e.current_step, e.next_run_at, e.status, e.exit_reason, e.context, e.created_at, e.updated_at, j.goal_event from marketing.journey_enrollments e join marketing.journeys j on j.id = e.journey_id
where e.status = 'active' and e.next_run_at <= now() and j.status = 'active'
order by e.next_run_at limit 100
for update of e skip locked
`

type MarketingDueEnrollmentsRow struct {
	ID          uuid.UUID       `json:"id"`
	JourneyID   uuid.UUID       `json:"journeyId"`
	UserID      uuid.UUID       `json:"userId"`
	CurrentStep int32           `json:"currentStep"`
	NextRunAt   *time.Time      `json:"nextRunAt"`
	Status      string          `json:"status"`
	ExitReason  *string         `json:"exitReason"`
	Context     json.RawMessage `json:"context"`
	CreatedAt   time.Time       `json:"createdAt"`
	UpdatedAt   time.Time       `json:"updatedAt"`
	GoalEvent   *string         `json:"goalEvent"`
}

func (q *Queries) MarketingDueEnrollments(ctx context.Context) ([]MarketingDueEnrollmentsRow, error) {
	rows, err := q.db.Query(ctx, marketingDueEnrollments)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MarketingDueEnrollmentsRow{}
	for rows.Next() {
		var i MarketingDueEnrollmentsRow
		if err := rows.Scan(
			&i.ID,
			&i.JourneyID,
			&i.UserID,
			&i.CurrentStep,
			&i.NextRunAt,
			&i.Status,
			&i.ExitReason,
			&i.Context,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.GoalEvent,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const marketingEnroll = `-- name: MarketingEnroll :one
insert into marketing.journey_enrollments (journey_id, user_id, next_run_at, context) values ($1, $2, now(), $3)
on conflict (journey_id, user_id) where status = 'active' do nothing returning id, journey_id, user_id, current_step, next_run_at, status, exit_reason, context, created_at, updated_at
`

type MarketingEnrollParams struct {
	JourneyID uuid.UUID       `json:"journeyId"`
	UserID    uuid.UUID       `json:"userId"`
	Context   json.RawMessage `json:"context"`
}

func (q *Queries) MarketingEnroll(ctx context.Context, arg MarketingEnrollParams) (MarketingJourneyEnrollment, error) {
	row := q.db.QueryRow(ctx, marketingEnroll, arg.JourneyID, arg.UserID, arg.Context)
	var i MarketingJourneyEnrollment
	err := row.Scan(
		&i.ID,
		&i.JourneyID,
		&i.UserID,
		&i.CurrentStep,
		&i.NextRunAt,
		&i.Status,
		&i.ExitReason,
		&i.Context,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const marketingFindCoupon = `-- name: MarketingFindCoupon :one
select c.id as coupon_id, c.promotion_id, c.max_redemptions, c.redeemed_count, c.per_user_limit, c.min_order_kobo,
       cc.id as code_id, cc.issued_to_user_id, cc.expires_at as code_expires_at, cc.redeemed_at as code_redeemed_at,
       p.kind, p.value, p.funded_by, p.status as promotion_status, p.starts_at, p.ends_at
from marketing.coupons c
join marketing.promotions p on p.id = c.promotion_id
left join marketing.coupon_codes cc on cc.coupon_id = c.id and cc.code = $1::citext
where (c.code = $1::citext and not c.is_unique_codes) or cc.id is not null
limit 1
`

type MarketingFindCouponRow struct {
	CouponID        uuid.UUID  `json:"couponId"`
	PromotionID     uuid.UUID  `json:"promotionId"`
	MaxRedemptions  *int32     `json:"maxRedemptions"`
	RedeemedCount   int32      `json:"redeemedCount"`
	PerUserLimit    int32      `json:"perUserLimit"`
	MinOrderKobo    *int64     `json:"minOrderKobo"`
	CodeID          *uuid.UUID `json:"codeId"`
	IssuedToUserID  *uuid.UUID `json:"issuedToUserId"`
	CodeExpiresAt   *time.Time `json:"codeExpiresAt"`
	CodeRedeemedAt  *time.Time `json:"codeRedeemedAt"`
	Kind            string     `json:"kind"`
	Value           *int32     `json:"value"`
	FundedBy        string     `json:"fundedBy"`
	PromotionStatus string     `json:"promotionStatus"`
	StartsAt        time.Time  `json:"startsAt"`
	EndsAt          time.Time  `json:"endsAt"`
}

// Resolve a typed code: a shared coupon code, or a unique single-use code.
func (q *Queries) MarketingFindCoupon(ctx context.Context, code string) (MarketingFindCouponRow, error) {
	row := q.db.QueryRow(ctx, marketingFindCoupon, code)
	var i MarketingFindCouponRow
	err := row.Scan(
		&i.CouponID,
		&i.PromotionID,
		&i.MaxRedemptions,
		&i.RedeemedCount,
		&i.PerUserLimit,
		&i.MinOrderKobo,
		&i.CodeID,
		&i.IssuedToUserID,
		&i.CodeExpiresAt,
		&i.CodeRedeemedAt,
		&i.Kind,
		&i.Value,
		&i.FundedBy,
		&i.PromotionStatus,
		&i.StartsAt,
		&i.EndsAt,
	)
	return i, err
}

const marketingFinishEnrollment = `-- name: MarketingFinishEnrollment :exec
update marketing.journey_enrollments set status = $2, exit_reason = $3, next_run_at = null, updated_at = now() where id = $1 and status = 'active'
`

type MarketingFinishEnrollmentParams struct {
	ID         uuid.UUID `json:"id"`
	Status     string    `json:"status"`
	ExitReason *string   `json:"exitReason"`
}

func (q *Queries) MarketingFinishEnrollment(ctx context.Context, arg MarketingFinishEnrollmentParams) error {
	_, err := q.db.Exec(ctx, marketingFinishEnrollment, arg.ID, arg.Status, arg.ExitReason)
	return err
}

const marketingGetCampaign = `-- name: MarketingGetCampaign :one
select id, name, status, segment_id, exclusions, channels, scheduled_at, holdout_pct, ab_test, cost_estimate_kobo, created_by, approved_by, approved_at, created_at, updated_at from marketing.campaigns where id = $1
`

func (q *Queries) MarketingGetCampaign(ctx context.Context, id uuid.UUID) (MarketingCampaign, error) {
	row := q.db.QueryRow(ctx, marketingGetCampaign, id)
	var i MarketingCampaign
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Status,
		&i.SegmentID,
		&i.Exclusions,
		&i.Channels,
		&i.ScheduledAt,
		&i.HoldoutPct,
		&i.AbTest,
		&i.CostEstimateKobo,
		&i.CreatedBy,
		&i.ApprovedBy,
		&i.ApprovedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const marketingGetCampaignForUpdate = `-- name: MarketingGetCampaignForUpdate :one
select id, name, status, segment_id, exclusions, channels, scheduled_at, holdout_pct, ab_test, cost_estimate_kobo, created_by, approved_by, approved_at, created_at, updated_at from marketing.campaigns where id = $1 for update
`

func (q *Queries) MarketingGetCampaignForUpdate(ctx context.Context, id uuid.UUID) (MarketingCampaign, error) {
	row := q.db.QueryRow(ctx, marketingGetCampaignForUpdate, id)
	var i MarketingCampaign
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Status,
		&i.SegmentID,
		&i.Exclusions,
		&i.Channels,
		&i.ScheduledAt,
		&i.HoldoutPct,
		&i.AbTest,
		&i.CostEstimateKobo,
		&i.CreatedBy,
		&i.ApprovedBy,
		&i.ApprovedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const marketingGetJourney = `-- name: MarketingGetJourney :one
select id, name, trigger, entry_rules, reentry_days, goal_event, status, created_by, created_at, updated_at from marketing.journeys where id = $1
`

func (q *Queries) MarketingGetJourney(ctx context.Context, id uuid.UUID) (MarketingJourney, error) {
	row := q.db.QueryRow(ctx, marketingGetJourney, id)
	var i MarketingJourney
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Trigger,
		&i.EntryRules,
		&i.ReentryDays,
		&i.GoalEvent,
		&i.Status,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const marketingGetLink = `-- name: MarketingGetLink :one
select id, url, notification_id, campaign_id, created_at from marketing.tracked_links where id = $1
`

func (q *Queries) MarketingGetLink(ctx context.Context, id uuid.UUID) (MarketingTrackedLink, error) {
	row := q.db.QueryRow(ctx, marketingGetLink, id)
	var i MarketingTrackedLink
	err := row.Scan(
		&i.ID,
		&i.Url,
		&i.NotificationID,
		&i.CampaignID,
		&i.CreatedAt,
	)
	return i, err
}

const marketingGetPromotion = `-- name: MarketingGetPromotion :one
select id, name, kind, value, funded_by, starts_at, ends_at, status, created_by, created_at, updated_at from marketing.promotions where id = $1
`

func (q *Queries) MarketingGetPromotion(ctx context.Context, id uuid.UUID) (MarketingPromotion, error) {
	row := q.db.QueryRow(ctx, marketingGetPromotion, id)
	var i MarketingPromotion
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Kind,
		&i.Value,
		&i.FundedBy,
		&i.StartsAt,
		&i.EndsAt,
		&i.Status,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const marketingGetSegment = `-- name: MarketingGetSegment :one
select id, name, rules, created_by, last_count, last_counted_at, created_at, updated_at from marketing.segments where id = $1
`

func (q *Queries) MarketingGetSegment(ctx context.Context, id uuid.UUID) (MarketingSegment, error) {
	row := q.db.QueryRow(ctx, marketingGetSegment, id)
	var i MarketingSegment
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Rules,
		&i.CreatedBy,
		&i.LastCount,
		&i.LastCountedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const marketingGoalReached = `-- name: MarketingGoalReached :exec
update marketing.journey_enrollments e set status = 'goal_reached', next_run_at = null, updated_at = now()
from marketing.journeys j
where j.id = e.journey_id and e.user_id = $1 and e.status = 'active' and j.goal_event = $2
`

type MarketingGoalReachedParams struct {
	UserID    uuid.UUID `json:"userId"`
	GoalEvent *string   `json:"goalEvent"`
}

// A goal event (e.g. order placed) exits that person from journeys waiting for it.
func (q *Queries) MarketingGoalReached(ctx context.Context, arg MarketingGoalReachedParams) error {
	_, err := q.db.Exec(ctx, marketingGoalReached, arg.UserID, arg.GoalEvent)
	return err
}

const marketingIncrementCoupon = `-- name: MarketingIncrementCoupon :one
update marketing.coupons set redeemed_count = redeemed_count + 1
where id = $1 and (max_redemptions is null or redeemed_count < max_redemptions) returning redeemed_count
`

// Concurrency-safe counter: never passes max_redemptions.
func (q *Queries) MarketingIncrementCoupon(ctx context.Context, id uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, marketingIncrementCoupon, id)
	var redeemed_count int32
	err := row.Scan(&redeemed_count)
	return redeemed_count, err
}

const marketingInsertFlashClaim = `-- name: MarketingInsertFlashClaim :exec
insert into marketing.flash_claims (promotion_id, listing_id, user_id, order_id, quantity) values ($1, $2, $3, $4, $5)
`

type MarketingInsertFlashClaimParams struct {
	PromotionID uuid.UUID `json:"promotionId"`
	ListingID   uuid.UUID `json:"listingId"`
	UserID      uuid.UUID `json:"userId"`
	OrderID     uuid.UUID `json:"orderId"`
	Quantity    int32     `json:"quantity"`
}

func (q *Queries) MarketingInsertFlashClaim(ctx context.Context, arg MarketingInsertFlashClaimParams) error {
	_, err := q.db.Exec(ctx, marketingInsertFlashClaim,
		arg.PromotionID,
		arg.ListingID,
		arg.UserID,
		arg.OrderID,
		arg.Quantity,
	)
	return err
}

const marketingInsertRecipient = `-- name: MarketingInsertRecipient :exec
insert into marketing.campaign_recipients (campaign_id, user_id, variant_id, holdout) values ($1, $2, $3, $4) on conflict do nothing
`

type MarketingInsertRecipientParams struct {
	CampaignID uuid.UUID  `json:"campaignId"`
	UserID     uuid.UUID  `json:"userId"`
	VariantID  *uuid.UUID `json:"variantId"`
	Holdout    bool       `json:"holdout"`
}

func (q *Queries) MarketingInsertRecipient(ctx context.Context, arg MarketingInsertRecipientParams) error {
	_, err := q.db.Exec(ctx, marketingInsertRecipient,
		arg.CampaignID,
		arg.UserID,
		arg.VariantID,
		arg.Holdout,
	)
	return err
}

const marketingInsertRedemption = `-- name: MarketingInsertRedemption :exec
insert into marketing.coupon_redemptions (coupon_id, coupon_code_id, order_id, user_id, discount_kobo) values ($1, $2, $3, $4, $5)
`

type MarketingInsertRedemptionParams struct {
	CouponID     uuid.UUID  `json:"couponId"`
	CouponCodeID *uuid.UUID `json:"couponCodeId"`
	OrderID      uuid.UUID  `json:"orderId"`
	UserID       *uuid.UUID `json:"userId"`
	DiscountKobo int64      `json:"discountKobo"`
}

func (q *Queries) MarketingInsertRedemption(ctx context.Context, arg MarketingInsertRedemptionParams) error {
	_, err := q.db.Exec(ctx, marketingInsertRedemption,
		arg.CouponID,
		arg.CouponCodeID,
		arg.OrderID,
		arg.UserID,
		arg.DiscountKobo,
	)
	return err
}

const marketingJourneyStats = `-- name: MarketingJourneyStats :many
select status, count(*)::int as n from marketing.journey_enrollments where journey_id = $1 group by status
`

type MarketingJourneyStatsRow struct {
	Status string `json:"status"`
	N      int32  `json:"n"`
}

func (q *Queries) MarketingJourneyStats(ctx context.Context, journeyID uuid.UUID) ([]MarketingJourneyStatsRow, error) {
	rows, err := q.db.Query(ctx, marketingJourneyStats, journeyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MarketingJourneyStatsRow{}
	for rows.Next() {
		var i MarketingJourneyStatsRow
		if err := rows.Scan(&i.Status, &i.N); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const marketingJourneySteps = `-- name: MarketingJourneySteps :many
select id, journey_id, position, kind, config from marketing.journey_steps where journey_id = $1 order by position
`

func (q *Queries) MarketingJourneySteps(ctx context.Context, journeyID uuid.UUID) ([]MarketingJourneyStep, error) {
	rows, err := q.db.Query(ctx, marketingJourneySteps, journeyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MarketingJourneyStep{}
	for rows.Next() {
		var i MarketingJourneyStep
		if err := rows.Scan(
			&i.ID,
			&i.JourneyID,
			&i.Position,
			&i.Kind,
			&i.Config,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const marketingLastClick = `-- name: MarketingLastClick :one
select id from messaging.notifications
where user_id = $1 and clicked_at > $2 and (campaign_id is not null or journey_enrollment_id is not null)
order by clicked_at desc limit 1
`

type MarketingLastClickParams struct {
	UserID    *uuid.UUID `json:"userId"`
	ClickedAt *time.Time `json:"clickedAt"`
}

// Attribution: the latest marketing message this person clicked within the window.
func (q *Queries) MarketingLastClick(ctx context.Context, arg MarketingLastClickParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, marketingLastClick, arg.UserID, arg.ClickedAt)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const marketingListCampaigns = `-- name: MarketingListCampaigns :many
select id, name, status, segment_id, exclusions, channels, scheduled_at, holdout_pct, ab_test, cost_estimate_kobo, created_by, approved_by, approved_at, created_at, updated_at from marketing.campaigns order by created_at desc limit $1
`

func (q *Queries) MarketingListCampaigns(ctx context.Context, limit int32) ([]MarketingCampaign, error) {
	rows, err := q.db.Query(ctx, marketingListCampaigns, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MarketingCampaign{}
	for rows.Next() {
		var i MarketingCampaign
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Status,
			&i.SegmentID,
			&i.Exclusions,
			&i.Channels,
			&i.ScheduledAt,
			&i.HoldoutPct,
			&i.AbTest,
			&i.CostEstimateKobo,
			&i.CreatedBy,
			&i.ApprovedBy,
			&i.ApprovedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const marketingListCoupons = `-- name: MarketingListCoupons :many
select c.id, c.code, c.promotion_id, c.is_unique_codes, c.max_redemptions, c.redeemed_count, c.per_user_limit, c.min_order_kobo, c.created_at, p.name as promotion_name, p.kind, p.value, p.status as promotion_status, p.ends_at
from marketing.coupons c join marketing.promotions p on p.id = c.promotion_id order by c.created_at desc limit $1
`

type MarketingListCouponsRow struct {
	ID              uuid.UUID `json:"id"`
	Code            *string   `json:"code"`
	PromotionID     uuid.UUID `json:"promotionId"`
	IsUniqueCodes   bool      `json:"isUniqueCodes"`
	MaxRedemptions  *int32    `json:"maxRedemptions"`
	RedeemedCount   int32     `json:"redeemedCount"`
	PerUserLimit    int32     `json:"perUserLimit"`
	MinOrderKobo    *int64    `json:"minOrderKobo"`
	CreatedAt       time.Time `json:"createdAt"`
	PromotionName   string    `json:"promotionName"`
	Kind            string    `json:"kind"`
	Value           *int32    `json:"value"`
	PromotionStatus string    `json:"promotionStatus"`
	EndsAt          time.Time `json:"endsAt"`
}

func (q *Queries) MarketingListCoupons(ctx context.Context, limit int32) ([]MarketingListCouponsRow, error) {
	rows, err := q.db.Query(ctx, marketingListCoupons, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MarketingListCouponsRow{}
	for rows.Next() {
		var i MarketingListCouponsRow
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.PromotionID,
			&i.IsUniqueCodes,
			&i.MaxRedemptions,
			&i.RedeemedCount,
			&i.PerUserLimit,
			&i.MinOrderKobo,
			&i.CreatedAt,
			&i.PromotionName,
			&i.Kind,
			&i.Value,
			&i.PromotionStatus,
			&i.EndsAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const marketingListJourneys = `-- name: MarketingListJourneys :many
select id, name, trigger, entry_rules, reentry_days, goal_event, status, created_by, created_at, updated_at from marketing.journeys order by created_at desc limit 100
`

func (q *Queries) MarketingListJourneys(ctx context.Context) ([]MarketingJourney, error) {
	rows, err := q.db.Query(ctx, marketingListJourneys)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MarketingJourney{}
	for rows.Next() {
		var i MarketingJourney
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Trigger,
			&i.EntryRules,
			&i.ReentryDays,
			&i.GoalEvent,
			&i.Status,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const marketingListPromotions = `-- name: MarketingListPromotions :many
select id, name, kind, value, funded_by, starts_at, ends_at, status, created_by, created_at, updated_at from marketing.promotions where ($2::text is null or status = $2) order by starts_at desc limit $1
`

type MarketingListPromotionsParams struct {
	Limit  int32   `json:"limit"`
	Status *string `json:"status"`
}

func (q *Queries) MarketingListPromotions(ctx context.Context, arg MarketingListPromotionsParams) ([]MarketingPromotion, error) {
	rows, err := q.db.Query(ctx, marketingListPromotions, arg.Limit, arg.Status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MarketingPromotion{}
	for rows.Next() {
		var i MarketingPromotion
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Kind,
			&i.Value,
			&i.FundedBy,
			&i.StartsAt,
			&i.EndsAt,
			&i.Status,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const marketingListSegments = `-- name: MarketingListSegments :many
select id, name, rules, created_by, last_count, last_counted_at, created_at, updated_at from marketing.segments order by created_at desc limit 200
`

func (q *Queries) MarketingListSegments(ctx context.Context) ([]MarketingSegment, error) {
	rows, err := q.db.Query(ctx, marketingListSegments)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MarketingSegment{}
	for rows.Next() {
		var i MarketingSegment
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Rules,
			&i.CreatedBy,
			&i.LastCount,
			&i.LastCountedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const marketingLiveAutoPromotions = `-- name: MarketingLiveAutoPromotions :many
select pr.id, pr.name, pr.kind, pr.value, pr.funded_by,
       coalesce(array_agg(t.category_id) filter (where t.category_id is not null), '{}')::uuid[] as category_ids,
       coalesce(array_agg(t.listing_id) filter (where t.listing_id is not null), '{}')::uuid[] as listing_ids
from marketing.promotions pr
left join marketing.promotion_targets t on t.promotion_id = pr.id
where pr.status = 'live' and now() between pr.starts_at and pr.ends_at and pr.kind in ('percentage', 'fixed_amount', 'free_delivery')
  and not exists (select 1 from marketing.coupons c where c.promotion_id = pr.id)
group by pr.id
`

type MarketingLiveAutoPromotionsRow struct {
	ID          uuid.UUID   `json:"id"`
	Name        string      `json:"name"`
	Kind        string      `json:"kind"`
	Value       *int32      `json:"value"`
	FundedBy    string      `json:"fundedBy"`
	CategoryIds []uuid.UUID `json:"categoryIds"`
	ListingIds  []uuid.UUID `json:"listingIds"`
}

// Live automatic promotions (not coupon-only, not flash) with their targets; empty targets = sitewide.
func (q *Queries) MarketingLiveAutoPromotions(ctx context.Context) ([]MarketingLiveAutoPromotionsRow, error) {
	rows, err := q.db.Query(ctx, marketingLiveAutoPromotions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MarketingLiveAutoPromotionsRow{}
	for rows.Next() {
		var i MarketingLiveAutoPromotionsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Kind,
			&i.Value,
			&i.FundedBy,
			&i.CategoryIds,
			&i.ListingIds,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const marketingOrderedSince = `-- name: MarketingOrderedSince :one
select exists (select 1 from sales.orders where customer_user_id = $1 and placed_at > $2 and status <> 'cancelled')::bool
`

type MarketingOrderedSinceParams struct {
	CustomerUserID *uuid.UUID `json:"customerUserId"`
	PlacedAt       time.Time  `json:"placedAt"`
}

func (q *Queries) MarketingOrderedSince(ctx context.Context, arg MarketingOrderedSinceParams) (bool, error) {
	row := q.db.QueryRow(ctx, marketingOrderedSince, arg.CustomerUserID, arg.PlacedAt)
	var column_1 bool
	err := row.Scan(&column_1)
	return column_1, err
}

const marketingPendingRecipients = `-- name: MarketingPendingRecipients :many
select r.campaign_id, r.user_id, r.variant_id, r.holdout, r.status, u.phone, u.email from marketing.campaign_recipients r join identity.users u on u.id = r.user_id
where r.campaign_id = $1 and r.status = 'pending' and not r.holdout limit $2
`

type MarketingPendingRecipientsParams struct {
	CampaignID uuid.UUID `json:"campaignId"`
	Limit      int32     `json:"limit"`
}

type MarketingPendingRecipientsRow struct {
	CampaignID uuid.UUID  `json:"campaignId"`
	UserID     uuid.UUID  `json:"userId"`
	VariantID  *uuid.UUID `json:"variantId"`
	Holdout    bool       `json:"holdout"`
	Status     string     `json:"status"`
	Phone      *string    `json:"phone"`
	Email      *string    `json:"email"`
}

func (q *Queries) MarketingPendingRecipients(ctx context.Context, arg MarketingPendingRecipientsParams) ([]MarketingPendingRecipientsRow, error) {
	rows, err := q.db.Query(ctx, marketingPendingRecipients, arg.CampaignID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MarketingPendingRecipientsRow{}
	for rows.Next() {
		var i MarketingPendingRecipientsRow
		if err := rows.Scan(
			&i.CampaignID,
			&i.UserID,
			&i.VariantID,
			&i.Holdout,
			&i.Status,
			&i.Phone,
			&i.Email,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const marketingPromotionListingPrices = `-- name: MarketingPromotionListingPrices :many
select promotion_id, listing_id, price_kobo, stock_limit, claimed, per_user_limit from marketing.promotion_listing_prices where promotion_id = $1
`

func (q *Queries) MarketingPromotionListingPrices(ctx context.Context, promotionID uuid.UUID) ([]MarketingPromotionListingPrice, error) {
	rows, err := q.db.Query(ctx, marketingPromotionListingPrices, promotionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MarketingPromotionListingPrice{}
	for rows.Next() {
		var i MarketingPromotionListingPrice
		if err := rows.Scan(
			&i.PromotionID,
			&i.ListingID,
			&i.PriceKobo,
			&i.StockLimit,
			&i.Claimed,
			&i.PerUserLimit,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const marketingPromotionTargets = `-- name: MarketingPromotionTargets :many
select id, promotion_id, category_id, listing_id from marketing.promotion_targets where promotion_id = $1
`

func (q *Queries) MarketingPromotionTargets(ctx context.Context, promotionID uuid.UUID) ([]MarketingPromotionTarget, error) {
	rows, err := q.db.Query(ctx, marketingPromotionTargets, promotionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MarketingPromotionTarget{}
	for rows.Next() {
		var i MarketingPromotionTarget
		if err := rows.Scan(
			&i.ID,
			&i.PromotionID,
			&i.CategoryID,
			&i.ListingID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const marketingPromotionTargetsFor = `-- name: MarketingPromotionTargetsFor :one
select coalesce(array_agg(category_id) filter (where category_id is not null), '{}')::uuid[] as category_ids,
       coalesce(array_agg(listing_id) filter (where listing_id is not null), '{}')::uuid[] as listing_ids
from marketing.promotion_targets where promotion_id = $1
`

type MarketingPromotionTargetsForRow struct {
	CategoryIds []uuid.UUID `json:"categoryIds"`
	ListingIds  []uuid.UUID `json:"listingIds"`
}

func (q *Queries) MarketingPromotionTargetsFor(ctx context.Context, promotionID uuid.UUID) (MarketingPromotionTargetsForRow, error) {
	row := q.db.QueryRow(ctx, marketingPromotionTargetsFor, promotionID)
	var i MarketingPromotionTargetsForRow
	err := row.Scan(&i.CategoryIds, &i.ListingIds)
	return i, err
}

const marketingRecentlyEnrolled = `-- name: MarketingRecentlyEnrolled :one
select exists (select 1 from marketing.journey_enrollments where journey_id = $1 and user_id = $2 and created_at > $3)::bool
`

type MarketingRecentlyEnrolledParams struct {
	JourneyID uuid.UUID `json:"journeyId"`
	UserID    uuid.UUID `json:"userId"`
	CreatedAt time.Time `json:"createdAt"`
}

// Re-entry guard: was this person in the journey within reentry_days?
func (q *Queries) MarketingRecentlyEnrolled(ctx context.Context, arg MarketingRecentlyEnrolledParams) (bool, error) {
	row := q.db.QueryRow(ctx, marketingRecentlyEnrolled, arg.JourneyID, arg.UserID, arg.CreatedAt)
	var column_1 bool
	err := row.Scan(&column_1)
	return column_1, err
}

const marketingRedeemCode = `-- name: MarketingRedeemCode :execrows
update marketing.coupon_codes set redeemed_at = now() where id = $1 and redeemed_at is null
`

func (q *Queries) MarketingRedeemCode(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, marketingRedeemCode, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const marketingReleaseFlashClaims = `-- name: MarketingReleaseFlashClaims :many
with gone as (delete from marketing.flash_claims where order_id = $1 returning promotion_id, listing_id, quantity)
update marketing.promotion_listing_prices p set claimed = greatest(p.claimed - g.quantity, 0)
from gone g where p.promotion_id = g.promotion_id and p.listing_id = g.listing_id
returning p.promotion_id, p.listing_id, p.claimed
`

type MarketingReleaseFlashClaimsRow struct {
	PromotionID uuid.UUID `json:"promotionId"`
	ListingID   uuid.UUID `json:"listingId"`
	Claimed     int32     `json:"claimed"`
}

// Cancellation gives flash units back to the pool.
func (q *Queries) MarketingReleaseFlashClaims(ctx context.Context, orderID uuid.UUID) ([]MarketingReleaseFlashClaimsRow, error) {
	rows, err := q.db.Query(ctx, marketingReleaseFlashClaims, orderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MarketingReleaseFlashClaimsRow{}
	for rows.Next() {
		var i MarketingReleaseFlashClaimsRow
		if err := rows.Scan(&i.PromotionID, &i.ListingID, &i.Claimed); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const marketingReleaseRedemption = `-- name: MarketingReleaseRedemption :one
update marketing.coupon_redemptions set status = 'released' where order_id = $1 and status = 'applied' returning id, coupon_id, coupon_code_id, order_id, user_id, discount_kobo, status, redeemed_at
`

func (q *Queries) MarketingReleaseRedemption(ctx context.Context, orderID uuid.UUID) (MarketingCouponRedemption, error) {
	row := q.db.QueryRow(ctx, marketingReleaseRedemption, orderID)
	var i MarketingCouponRedemption
	err := row.Scan(
		&i.ID,
		&i.CouponID,
		&i.CouponCodeID,
		&i.OrderID,
		&i.UserID,
		&i.DiscountKobo,
		&i.Status,
		&i.RedeemedAt,
	)
	return i, err
}

const marketingSetCampaignStatus = `-- name: MarketingSetCampaignStatus :one
update marketing.campaigns set status = $2, scheduled_at = coalesce($3, scheduled_at),
  approved_by = coalesce($4, approved_by), approved_at = case when $4::uuid is not null then now() else approved_at end,
  updated_at = now()
where id = $1 returning id, name, status, segment_id, exclusions, channels, scheduled_at, holdout_pct, ab_test, cost_estimate_kobo, created_by, approved_by, approved_at, created_at, updated_at
`

type MarketingSetCampaignStatusParams struct {
	ID          uuid.UUID  `json:"id"`
	Status      string     `json:"status"`
	ScheduledAt *time.Time `json:"scheduledAt"`
	ApprovedBy  *uuid.UUID `json:"approvedBy"`
}

func (q *Queries) MarketingSetCampaignStatus(ctx context.Context, arg MarketingSetCampaignStatusParams) (MarketingCampaign, error) {
	row := q.db.QueryRow(ctx, marketingSetCampaignStatus,
		arg.ID,
		arg.Status,
		arg.ScheduledAt,
		arg.ApprovedBy,
	)
	var i MarketingCampaign
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Status,
		&i.SegmentID,
		&i.Exclusions,
		&i.Channels,
		&i.ScheduledAt,
		&i.HoldoutPct,
		&i.AbTest,
		&i.CostEstimateKobo,
		&i.CreatedBy,
		&i.ApprovedBy,
		&i.ApprovedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const marketingSetEnrollmentContext = `-- name: MarketingSetEnrollmentContext :exec
update marketing.journey_enrollments set context = $2, updated_at = now() where id = $1
`

type MarketingSetEnrollmentContextParams struct {
	ID      uuid.UUID       `json:"id"`
	Context json.RawMessage `json:"context"`
}

func (q *Queries) MarketingSetEnrollmentContext(ctx context.Context, arg MarketingSetEnrollmentContextParams) error {
	_, err := q.db.Exec(ctx, marketingSetEnrollmentContext, arg.ID, arg.Context)
	return err
}

const marketingSetJourneyStatus = `-- name: MarketingSetJourneyStatus :one
update marketing.journeys set status = $2, updated_at = now() where id = $1 returning id, name, trigger, entry_rules, reentry_days, goal_event, status, created_by, created_at, updated_at
`

type MarketingSetJourneyStatusParams struct {
	ID     uuid.UUID `json:"id"`
	Status string    `json:"status"`
}

func (q *Queries) MarketingSetJourneyStatus(ctx context.Context, arg MarketingSetJourneyStatusParams) (MarketingJourney, error) {
	row := q.db.QueryRow(ctx, marketingSetJourneyStatus, arg.ID, arg.Status)
	var i MarketingJourney
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Trigger,
		&i.EntryRules,
		&i.ReentryDays,
		&i.GoalEvent,
		&i.Status,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const marketingSetListingPrice = `-- name: MarketingSetListingPrice :one
insert into marketing.promotion_listing_prices (promotion_id, listing_id, price_kobo, stock_limit, per_user_limit) values ($1, $2, $3, $4, $5)
on conflict (promotion_id, listing_id) do update set price_kobo = excluded.price_kobo, stock_limit = excluded.stock_limit, per_user_limit = excluded.per_user_limit
returning promotion_id, listing_id, price_kobo, stock_limit, claimed, per_user_limit
`

type MarketingSetListingPriceParams struct {
	PromotionID  uuid.UUID `json:"promotionId"`
	ListingID    uuid.UUID `json:"listingId"`
	PriceKobo    int64     `json:"priceKobo"`
	StockLimit   *int32    `json:"stockLimit"`
	PerUserLimit *int32    `json:"perUserLimit"`
}

func (q *Queries) MarketingSetListingPrice(ctx context.Context, arg MarketingSetListingPriceParams) (MarketingPromotionListingPrice, error) {
	row := q.db.QueryRow(ctx, marketingSetListingPrice,
		arg.PromotionID,
		arg.ListingID,
		arg.PriceKobo,
		arg.StockLimit,
		arg.PerUserLimit,
	)
	var i MarketingPromotionListingPrice
	err := row.Scan(
		&i.PromotionID,
		&i.ListingID,
		&i.PriceKobo,
		&i.StockLimit,
		&i.Claimed,
		&i.PerUserLimit,
	)
	return i, err
}

const marketingSetPromotionStatus = `-- name: MarketingSetPromotionStatus :one
update marketing.promotions set status = $2, updated_at = now() where id = $1 returning id, name, kind, value, funded_by, starts_at, ends_at, status, created_by, created_at, updated_at
`

type MarketingSetPromotionStatusParams struct {
	ID     uuid.UUID `json:"id"`
	Status string    `json:"status"`
}

func (q *Queries) MarketingSetPromotionStatus(ctx context.Context, arg MarketingSetPromotionStatusParams) (MarketingPromotion, error) {
	row := q.db.QueryRow(ctx, marketingSetPromotionStatus, arg.ID, arg.Status)
	var i MarketingPromotion
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Kind,
		&i.Value,
		&i.FundedBy,
		&i.StartsAt,
		&i.EndsAt,
		&i.Status,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const marketingSetRecipientStatus = `-- name: MarketingSetRecipientStatus :exec
update marketing.campaign_recipients set status = $3 where campaign_id = $1 and user_id = $2
`

type MarketingSetRecipientStatusParams struct {
	CampaignID uuid.UUID `json:"campaignId"`
	UserID     uuid.UUID `json:"userId"`
	Status     string    `json:"status"`
}

func (q *Queries) MarketingSetRecipientStatus(ctx context.Context, arg MarketingSetRecipientStatusParams) error {
	_, err := q.db.Exec(ctx, marketingSetRecipientStatus, arg.CampaignID, arg.UserID, arg.Status)
	return err
}

const marketingSetSegmentCount = `-- name: MarketingSetSegmentCount :exec
update marketing.segments set last_count = $2, last_counted_at = now(), updated_at = now() where id = $1
`

type MarketingSetSegmentCountParams struct {
	ID        uuid.UUID `json:"id"`
	LastCount *int32    `json:"lastCount"`
}

func (q *Queries) MarketingSetSegmentCount(ctx context.Context, arg MarketingSetSegmentCountParams) error {
	_, err := q.db.Exec(ctx, marketingSetSegmentCount, arg.ID, arg.LastCount)
	return err
}

const marketingUnredeemCode = `-- name: MarketingUnredeemCode :exec
update marketing.coupon_codes set redeemed_at = null where id = $1
`

func (q *Queries) MarketingUnredeemCode(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, marketingUnredeemCode, id)
	return err
}

const marketingUpdatePromotion = `-- name: MarketingUpdatePromotion :one
update marketing.promotions set name = $2, value = $3, starts_at = $4, ends_at = $5, updated_at = now()
where id = $1 and status in ('draft', 'scheduled') returning id, name, kind, value, funded_by, starts_at, ends_at, status, created_by, created_at, updated_at
`

type MarketingUpdatePromotionParams struct {
	ID       uuid.UUID `json:"id"`
	Name     string    `json:"name"`
	Value    *int32    `json:"value"`
	StartsAt time.Time `json:"startsAt"`
	EndsAt   time.Time `json:"endsAt"`
}

func (q *Queries) MarketingUpdatePromotion(ctx context.Context, arg MarketingUpdatePromotionParams) (MarketingPromotion, error) {
	row := q.db.QueryRow(ctx, marketingUpdatePromotion,
		arg.ID,
		arg.Name,
		arg.Value,
		arg.StartsAt,
		arg.EndsAt,
	)
	var i MarketingPromotion
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Kind,
		&i.Value,
		&i.FundedBy,
		&i.StartsAt,
		&i.EndsAt,
		&i.Status,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const marketingUserContact = `-- name: MarketingUserContact :one
select id, phone, email, first_name from identity.users where id = $1 and status = 'active'
`

type MarketingUserContactRow struct {
	ID        uuid.UUID `json:"id"`
	Phone     *string   `json:"phone"`
	Email     *string   `json:"email"`
	FirstName string    `json:"firstName"`
}

func (q *Queries) MarketingUserContact(ctx context.Context, id uuid.UUID) (MarketingUserContactRow, error) {
	row := q.db.QueryRow(ctx, marketingUserContact, id)
	var i MarketingUserContactRow
	err := row.Scan(
		&i.ID,
		&i.Phone,
		&i.Email,
		&i.FirstName,
	)
	return i, err
}

const marketingUserFlashClaimed = `-- name: MarketingUserFlashClaimed :one
select coalesce(sum(quantity), 0)::int from marketing.flash_claims where promotion_id = $1 and listing_id = $2 and user_id = $3
`

type MarketingUserFlashClaimedParams struct {
	PromotionID uuid.UUID `json:"promotionId"`
	ListingID   uuid.UUID `json:"listingId"`
	UserID      uuid.UUID `json:"userId"`
}

func (q *Queries) MarketingUserFlashClaimed(ctx context.Context, arg MarketingUserFlashClaimedParams) (int32, error) {
	row := q.db.QueryRow(ctx, marketingUserFlashClaimed, arg.PromotionID, arg.ListingID, arg.UserID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const marketingUserRedemptions = `-- name: MarketingUserRedemptions :one
select count(*)::int from marketing.coupon_redemptions where coupon_id = $1 and user_id = $2 and status = 'applied'
`

type MarketingUserRedemptionsParams struct {
	CouponID uuid.UUID  `json:"couponId"`
	UserID   *uuid.UUID `json:"userId"`
}

func (q *Queries) MarketingUserRedemptions(ctx context.Context, arg MarketingUserRedemptionsParams) (int32, error) {
	row := q.db.QueryRow(ctx, marketingUserRedemptions, arg.CouponID, arg.UserID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}
