// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: messaging.sql

package store

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const messagingActivePushTokens = `-- name: MessagingActivePushTokens :many
select id, user_id, app, platform, token, provider, app_version, locale, last_seen_at, revoked_at, created_at from messaging.push_tokens where user_id = $1 and revoked_at is null and ($2::text is null or app = $2)
`

type MessagingActivePushTokensParams struct {
	UserID uuid.UUID `json:"userId"`
	App    *string   `json:"app"`
}

func (q *Queries) MessagingActivePushTokens(ctx context.Context, arg MessagingActivePushTokensParams) ([]MessagingPushToken, error) {
	rows, err := q.db.Query(ctx, messagingActivePushTokens, arg.UserID, arg.App)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MessagingPushToken{}
	for rows.Next() {
		var i MessagingPushToken
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.App,
			&i.Platform,
			&i.Token,
			&i.Provider,
			&i.AppVersion,
			&i.Locale,
			&i.LastSeenAt,
			&i.RevokedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const messagingAddTemplateVersion = `-- name: MessagingAddTemplateVersion :one
insert into messaging.template_versions (template_id, version, subject, blocks, created_by, published_at)
values ($1, coalesce((select max(version) from messaging.template_versions where template_id = $1), 0) + 1, $2, $3, $4, now())
returning id, template_id, version, subject, blocks, created_by, published_at, created_at
`

type MessagingAddTemplateVersionParams struct {
	TemplateID uuid.UUID       `json:"templateId"`
	Subject    *string         `json:"subject"`
	Blocks     json.RawMessage `json:"blocks"`
	CreatedBy  uuid.UUID       `json:"createdBy"`
}

func (q *Queries) MessagingAddTemplateVersion(ctx context.Context, arg MessagingAddTemplateVersionParams) (MessagingTemplateVersion, error) {
	row := q.db.QueryRow(ctx, messagingAddTemplateVersion,
		arg.TemplateID,
		arg.Subject,
		arg.Blocks,
		arg.CreatedBy,
	)
	var i MessagingTemplateVersion
	err := row.Scan(
		&i.ID,
		&i.TemplateID,
		&i.Version,
		&i.Subject,
		&i.Blocks,
		&i.CreatedBy,
		&i.PublishedAt,
		&i.CreatedAt,
	)
	return i, err
}

const messagingCountMarketingToday = `-- name: MessagingCountMarketingToday :one
select count(*)::int from messaging.notifications
where user_id = $1 and channel = $2 and priority = 'marketing' and status in ('sent', 'delivered', 'read') and sent_at >= $3
`

type MessagingCountMarketingTodayParams struct {
	UserID  *uuid.UUID `json:"userId"`
	Channel string     `json:"channel"`
	SentAt  *time.Time `json:"sentAt"`
}

func (q *Queries) MessagingCountMarketingToday(ctx context.Context, arg MessagingCountMarketingTodayParams) (int32, error) {
	row := q.db.QueryRow(ctx, messagingCountMarketingToday, arg.UserID, arg.Channel, arg.SentAt)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const messagingCreateTemplate = `-- name: MessagingCreateTemplate :one
insert into messaging.message_templates (key, channel, category, locale, status) values ($1, $2, $3, $4, 'draft') returning id, key, channel, category, locale, status, created_at, updated_at
`

type MessagingCreateTemplateParams struct {
	Key      string `json:"key"`
	Channel  string `json:"channel"`
	Category string `json:"category"`
	Locale   string `json:"locale"`
}

func (q *Queries) MessagingCreateTemplate(ctx context.Context, arg MessagingCreateTemplateParams) (MessagingMessageTemplate, error) {
	row := q.db.QueryRow(ctx, messagingCreateTemplate,
		arg.Key,
		arg.Channel,
		arg.Category,
		arg.Locale,
	)
	var i MessagingMessageTemplate
	err := row.Scan(
		&i.ID,
		&i.Key,
		&i.Channel,
		&i.Category,
		&i.Locale,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const messagingDevRecent = `-- name: MessagingDevRecent :many
select id, channel, template, payload, status, created_at from messaging.notifications
where payload->>'to' = $1 order by created_at desc limit 10
`

type MessagingDevRecentRow struct {
	ID        uuid.UUID       `json:"id"`
	Channel   string          `json:"channel"`
	Template  string          `json:"template"`
	Payload   json.RawMessage `json:"payload"`
	Status    string          `json:"status"`
	CreatedAt time.Time       `json:"createdAt"`
}

// Development only: recent messages to an address, so tests and local dev can read codes.
func (q *Queries) MessagingDevRecent(ctx context.Context, payload json.RawMessage) ([]MessagingDevRecentRow, error) {
	rows, err := q.db.Query(ctx, messagingDevRecent, payload)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MessagingDevRecentRow{}
	for rows.Next() {
		var i MessagingDevRecentRow
		if err := rows.Scan(
			&i.ID,
			&i.Channel,
			&i.Template,
			&i.Payload,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const messagingGetNotification = `-- name: MessagingGetNotification :one
select id, user_id, channel, category, priority, template, template_version_id, locale, payload, idempotency_key, campaign_id, journey_enrollment_id, to_hash, provider, provider_message_id, cost_kobo, status, skip_reason, error, scheduled_for, sent_at, delivered_at, clicked_at, read_at, created_at from messaging.notifications where id = $1
`

func (q *Queries) MessagingGetNotification(ctx context.Context, id uuid.UUID) (MessagingNotification, error) {
	row := q.db.QueryRow(ctx, messagingGetNotification, id)
	var i MessagingNotification
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Channel,
		&i.Category,
		&i.Priority,
		&i.Template,
		&i.TemplateVersionID,
		&i.Locale,
		&i.Payload,
		&i.IdempotencyKey,
		&i.CampaignID,
		&i.JourneyEnrollmentID,
		&i.ToHash,
		&i.Provider,
		&i.ProviderMessageID,
		&i.CostKobo,
		&i.Status,
		&i.SkipReason,
		&i.Error,
		&i.ScheduledFor,
		&i.SentAt,
		&i.DeliveredAt,
		&i.ClickedAt,
		&i.ReadAt,
		&i.CreatedAt,
	)
	return i, err
}

const messagingGetPreferences = `-- name: MessagingGetPreferences :many
select user_id, category, channel, enabled, updated_at from messaging.notification_preferences where user_id = $1
`

func (q *Queries) MessagingGetPreferences(ctx context.Context, userID uuid.UUID) ([]MessagingNotificationPreference, error) {
	rows, err := q.db.Query(ctx, messagingGetPreferences, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MessagingNotificationPreference{}
	for rows.Next() {
		var i MessagingNotificationPreference
		if err := rows.Scan(
			&i.UserID,
			&i.Category,
			&i.Channel,
			&i.Enabled,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const messagingGetSettings = `-- name: MessagingGetSettings :one
select user_id, quiet_start, quiet_end, quiet_hours, timezone, updated_at from messaging.notification_settings where user_id = $1
`

func (q *Queries) MessagingGetSettings(ctx context.Context, userID uuid.UUID) (MessagingNotificationSetting, error) {
	row := q.db.QueryRow(ctx, messagingGetSettings, userID)
	var i MessagingNotificationSetting
	err := row.Scan(
		&i.UserID,
		&i.QuietStart,
		&i.QuietEnd,
		&i.QuietHours,
		&i.Timezone,
		&i.UpdatedAt,
	)
	return i, err
}

const messagingGetTemplateVersion = `-- name: MessagingGetTemplateVersion :one
select id, template_id, version, subject, blocks, created_by, published_at, created_at from messaging.template_versions where id = $1
`

func (q *Queries) MessagingGetTemplateVersion(ctx context.Context, id uuid.UUID) (MessagingTemplateVersion, error) {
	row := q.db.QueryRow(ctx, messagingGetTemplateVersion, id)
	var i MessagingTemplateVersion
	err := row.Scan(
		&i.ID,
		&i.TemplateID,
		&i.Version,
		&i.Subject,
		&i.Blocks,
		&i.CreatedBy,
		&i.PublishedAt,
		&i.CreatedAt,
	)
	return i, err
}

const messagingInsertEvent = `-- name: MessagingInsertEvent :exec
insert into messaging.message_events (notification_id, kind, meta) values ($1, $2, $3)
`

type MessagingInsertEventParams struct {
	NotificationID uuid.UUID       `json:"notificationId"`
	Kind           string          `json:"kind"`
	Meta           json.RawMessage `json:"meta"`
}

func (q *Queries) MessagingInsertEvent(ctx context.Context, arg MessagingInsertEventParams) error {
	_, err := q.db.Exec(ctx, messagingInsertEvent, arg.NotificationID, arg.Kind, arg.Meta)
	return err
}

const messagingInsertNotification = `-- name: MessagingInsertNotification :one

insert into messaging.notifications (user_id, channel, category, priority, template, template_version_id, locale, payload,
  idempotency_key, campaign_id, journey_enrollment_id, to_hash, scheduled_for)
values ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13)
on conflict (idempotency_key) do nothing
returning id, user_id, channel, category, priority, template, template_version_id, locale, payload, idempotency_key, campaign_id, journey_enrollment_id, to_hash, provider, provider_message_id, cost_kobo, status, skip_reason, error, scheduled_for, sent_at, delivered_at, clicked_at, read_at, created_at
`

type MessagingInsertNotificationParams struct {
	UserID              *uuid.UUID      `json:"userId"`
	Channel             string          `json:"channel"`
	Category            string          `json:"category"`
	Priority            string          `json:"priority"`
	Template            string          `json:"template"`
	TemplateVersionID   *uuid.UUID      `json:"templateVersionId"`
	Locale              string          `json:"locale"`
	Payload             json.RawMessage `json:"payload"`
	IdempotencyKey      string          `json:"idempotencyKey"`
	CampaignID          *uuid.UUID      `json:"campaignId"`
	JourneyEnrollmentID *uuid.UUID      `json:"journeyEnrollmentId"`
	ToHash              []byte          `json:"toHash"`
	ScheduledFor        *time.Time      `json:"scheduledFor"`
}

// Messaging queries (docs/messaging-marketing.md §3, §5–§6).
func (q *Queries) MessagingInsertNotification(ctx context.Context, arg MessagingInsertNotificationParams) (MessagingNotification, error) {
	row := q.db.QueryRow(ctx, messagingInsertNotification,
		arg.UserID,
		arg.Channel,
		arg.Category,
		arg.Priority,
		arg.Template,
		arg.TemplateVersionID,
		arg.Locale,
		arg.Payload,
		arg.IdempotencyKey,
		arg.CampaignID,
		arg.JourneyEnrollmentID,
		arg.ToHash,
		arg.ScheduledFor,
	)
	var i MessagingNotification
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Channel,
		&i.Category,
		&i.Priority,
		&i.Template,
		&i.TemplateVersionID,
		&i.Locale,
		&i.Payload,
		&i.IdempotencyKey,
		&i.CampaignID,
		&i.JourneyEnrollmentID,
		&i.ToHash,
		&i.Provider,
		&i.ProviderMessageID,
		&i.CostKobo,
		&i.Status,
		&i.SkipReason,
		&i.Error,
		&i.ScheduledFor,
		&i.SentAt,
		&i.DeliveredAt,
		&i.ClickedAt,
		&i.ReadAt,
		&i.CreatedAt,
	)
	return i, err
}

const messagingIsSuppressed = `-- name: MessagingIsSuppressed :one
select exists (select 1 from messaging.message_suppressions where channel = $1 and address_hash = $2) as suppressed
`

type MessagingIsSuppressedParams struct {
	Channel     string `json:"channel"`
	AddressHash []byte `json:"addressHash"`
}

func (q *Queries) MessagingIsSuppressed(ctx context.Context, arg MessagingIsSuppressedParams) (bool, error) {
	row := q.db.QueryRow(ctx, messagingIsSuppressed, arg.Channel, arg.AddressHash)
	var suppressed bool
	err := row.Scan(&suppressed)
	return suppressed, err
}

const messagingListInbox = `-- name: MessagingListInbox :many
select id, user_id, channel, category, priority, template, template_version_id, locale, payload, idempotency_key, campaign_id, journey_enrollment_id, to_hash, provider, provider_message_id, cost_kobo, status, skip_reason, error, scheduled_for, sent_at, delivered_at, clicked_at, read_at, created_at from messaging.notifications
where user_id = $1 and channel = 'in_app'
  and ($3::timestamptz is null or created_at < $3)
order by created_at desc
limit $2
`

type MessagingListInboxParams struct {
	UserID *uuid.UUID `json:"userId"`
	Limit  int32      `json:"limit"`
	Before *time.Time `json:"before"`
}

func (q *Queries) MessagingListInbox(ctx context.Context, arg MessagingListInboxParams) ([]MessagingNotification, error) {
	rows, err := q.db.Query(ctx, messagingListInbox, arg.UserID, arg.Limit, arg.Before)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MessagingNotification{}
	for rows.Next() {
		var i MessagingNotification
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Channel,
			&i.Category,
			&i.Priority,
			&i.Template,
			&i.TemplateVersionID,
			&i.Locale,
			&i.Payload,
			&i.IdempotencyKey,
			&i.CampaignID,
			&i.JourneyEnrollmentID,
			&i.ToHash,
			&i.Provider,
			&i.ProviderMessageID,
			&i.CostKobo,
			&i.Status,
			&i.SkipReason,
			&i.Error,
			&i.ScheduledFor,
			&i.SentAt,
			&i.DeliveredAt,
			&i.ClickedAt,
			&i.ReadAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const messagingListSuppressions = `-- name: MessagingListSuppressions :many
select id, channel, address_hash, reason, created_at from messaging.message_suppressions order by created_at desc limit $1
`

func (q *Queries) MessagingListSuppressions(ctx context.Context, limit int32) ([]MessagingMessageSuppression, error) {
	rows, err := q.db.Query(ctx, messagingListSuppressions, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MessagingMessageSuppression{}
	for rows.Next() {
		var i MessagingMessageSuppression
		if err := rows.Scan(
			&i.ID,
			&i.Channel,
			&i.AddressHash,
			&i.Reason,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const messagingListTemplates = `-- name: MessagingListTemplates :many
select t.id, t.key, t.channel, t.category, t.locale, t.status, t.created_at, t.updated_at, (select max(version) from messaging.template_versions v where v.template_id = t.id)::int as latest_version
from messaging.message_templates t order by key, channel
`

type MessagingListTemplatesRow struct {
	ID            uuid.UUID `json:"id"`
	Key           string    `json:"key"`
	Channel       string    `json:"channel"`
	Category      string    `json:"category"`
	Locale        string    `json:"locale"`
	Status        string    `json:"status"`
	CreatedAt     time.Time `json:"createdAt"`
	UpdatedAt     time.Time `json:"updatedAt"`
	LatestVersion int32     `json:"latestVersion"`
}

func (q *Queries) MessagingListTemplates(ctx context.Context) ([]MessagingListTemplatesRow, error) {
	rows, err := q.db.Query(ctx, messagingListTemplates)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MessagingListTemplatesRow{}
	for rows.Next() {
		var i MessagingListTemplatesRow
		if err := rows.Scan(
			&i.ID,
			&i.Key,
			&i.Channel,
			&i.Category,
			&i.Locale,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LatestVersion,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const messagingMarkAllRead = `-- name: MessagingMarkAllRead :execrows
update messaging.notifications set read_at = now(), status = 'read' where user_id = $1 and channel = 'in_app' and read_at is null
`

func (q *Queries) MessagingMarkAllRead(ctx context.Context, userID *uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, messagingMarkAllRead, userID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const messagingMarkClicked = `-- name: MessagingMarkClicked :exec
update messaging.notifications set clicked_at = coalesce(clicked_at, now()) where id = $1
`

func (q *Queries) MessagingMarkClicked(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, messagingMarkClicked, id)
	return err
}

const messagingMarkDeliveredByProvider = `-- name: MessagingMarkDeliveredByProvider :one
update messaging.notifications set status = 'delivered', delivered_at = now()
where provider = $1 and provider_message_id = $2 and status in ('sent', 'queued')
returning id
`

type MessagingMarkDeliveredByProviderParams struct {
	Provider          *string `json:"provider"`
	ProviderMessageID *string `json:"providerMessageId"`
}

func (q *Queries) MessagingMarkDeliveredByProvider(ctx context.Context, arg MessagingMarkDeliveredByProviderParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, messagingMarkDeliveredByProvider, arg.Provider, arg.ProviderMessageID)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const messagingMarkFailed = `-- name: MessagingMarkFailed :exec
update messaging.notifications set status = 'failed', error = $2 where id = $1
`

type MessagingMarkFailedParams struct {
	ID    uuid.UUID `json:"id"`
	Error *string   `json:"error"`
}

func (q *Queries) MessagingMarkFailed(ctx context.Context, arg MessagingMarkFailedParams) error {
	_, err := q.db.Exec(ctx, messagingMarkFailed, arg.ID, arg.Error)
	return err
}

const messagingMarkRead = `-- name: MessagingMarkRead :execrows
update messaging.notifications set read_at = now(), status = 'read' where id = $1 and user_id = $2 and channel = 'in_app'
`

type MessagingMarkReadParams struct {
	ID     uuid.UUID  `json:"id"`
	UserID *uuid.UUID `json:"userId"`
}

func (q *Queries) MessagingMarkRead(ctx context.Context, arg MessagingMarkReadParams) (int64, error) {
	result, err := q.db.Exec(ctx, messagingMarkRead, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const messagingMarkSent = `-- name: MessagingMarkSent :exec
update messaging.notifications
set status = 'sent', provider = $2, provider_message_id = $3, cost_kobo = $4, sent_at = now(), payload = payload || $5::jsonb
where id = $1
`

type MessagingMarkSentParams struct {
	ID                uuid.UUID       `json:"id"`
	Provider          *string         `json:"provider"`
	ProviderMessageID *string         `json:"providerMessageId"`
	CostKobo          *int64          `json:"costKobo"`
	Extra             json.RawMessage `json:"extra"`
}

func (q *Queries) MessagingMarkSent(ctx context.Context, arg MessagingMarkSentParams) error {
	_, err := q.db.Exec(ctx, messagingMarkSent,
		arg.ID,
		arg.Provider,
		arg.ProviderMessageID,
		arg.CostKobo,
		arg.Extra,
	)
	return err
}

const messagingMarkSkipped = `-- name: MessagingMarkSkipped :exec
update messaging.notifications set status = 'skipped', skip_reason = $2 where id = $1
`

type MessagingMarkSkippedParams struct {
	ID         uuid.UUID `json:"id"`
	SkipReason *string   `json:"skipReason"`
}

func (q *Queries) MessagingMarkSkipped(ctx context.Context, arg MessagingMarkSkippedParams) error {
	_, err := q.db.Exec(ctx, messagingMarkSkipped, arg.ID, arg.SkipReason)
	return err
}

const messagingReschedule = `-- name: MessagingReschedule :exec
update messaging.notifications set scheduled_for = $2 where id = $1
`

type MessagingRescheduleParams struct {
	ID           uuid.UUID  `json:"id"`
	ScheduledFor *time.Time `json:"scheduledFor"`
}

func (q *Queries) MessagingReschedule(ctx context.Context, arg MessagingRescheduleParams) error {
	_, err := q.db.Exec(ctx, messagingReschedule, arg.ID, arg.ScheduledFor)
	return err
}

const messagingRevokePushToken = `-- name: MessagingRevokePushToken :exec
update messaging.push_tokens set revoked_at = now() where token = $1
`

func (q *Queries) MessagingRevokePushToken(ctx context.Context, token string) error {
	_, err := q.db.Exec(ctx, messagingRevokePushToken, token)
	return err
}

const messagingRevokeUserPushTokens = `-- name: MessagingRevokeUserPushTokens :exec
update messaging.push_tokens set revoked_at = now() where user_id = $1 and revoked_at is null
`

func (q *Queries) MessagingRevokeUserPushTokens(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, messagingRevokeUserPushTokens, userID)
	return err
}

const messagingSetPreference = `-- name: MessagingSetPreference :exec
insert into messaging.notification_preferences (user_id, category, channel, enabled) values ($1, $2, $3, $4)
on conflict (user_id, category, channel) do update set enabled = excluded.enabled, updated_at = now()
`

type MessagingSetPreferenceParams struct {
	UserID   uuid.UUID `json:"userId"`
	Category string    `json:"category"`
	Channel  string    `json:"channel"`
	Enabled  bool      `json:"enabled"`
}

func (q *Queries) MessagingSetPreference(ctx context.Context, arg MessagingSetPreferenceParams) error {
	_, err := q.db.Exec(ctx, messagingSetPreference,
		arg.UserID,
		arg.Category,
		arg.Channel,
		arg.Enabled,
	)
	return err
}

const messagingSuppress = `-- name: MessagingSuppress :exec
insert into messaging.message_suppressions (channel, address_hash, reason) values ($1, $2, $3)
on conflict (channel, address_hash) do nothing
`

type MessagingSuppressParams struct {
	Channel     string `json:"channel"`
	AddressHash []byte `json:"addressHash"`
	Reason      string `json:"reason"`
}

func (q *Queries) MessagingSuppress(ctx context.Context, arg MessagingSuppressParams) error {
	_, err := q.db.Exec(ctx, messagingSuppress, arg.Channel, arg.AddressHash, arg.Reason)
	return err
}

const messagingTrimBodies = `-- name: MessagingTrimBodies :execrows
update messaging.notifications set payload = payload - 'body' - 'data'
where created_at < now() - interval '90 days' and payload ? 'body'
`

func (q *Queries) MessagingTrimBodies(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, messagingTrimBodies)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const messagingUnreadCount = `-- name: MessagingUnreadCount :one
select count(*)::int from messaging.notifications where user_id = $1 and channel = 'in_app' and read_at is null
`

func (q *Queries) MessagingUnreadCount(ctx context.Context, userID *uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, messagingUnreadCount, userID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const messagingUpsertPushToken = `-- name: MessagingUpsertPushToken :one
insert into messaging.push_tokens (user_id, app, platform, token, app_version, locale)
values ($1, $2, $3, $4, $5, $6)
on conflict (token) do update set user_id = excluded.user_id, app = excluded.app, platform = excluded.platform,
  app_version = excluded.app_version, locale = excluded.locale, last_seen_at = now(), revoked_at = null
returning id, user_id, app, platform, token, provider, app_version, locale, last_seen_at, revoked_at, created_at
`

type MessagingUpsertPushTokenParams struct {
	UserID     uuid.UUID `json:"userId"`
	App        string    `json:"app"`
	Platform   string    `json:"platform"`
	Token      string    `json:"token"`
	AppVersion *string   `json:"appVersion"`
	Locale     *string   `json:"locale"`
}

func (q *Queries) MessagingUpsertPushToken(ctx context.Context, arg MessagingUpsertPushTokenParams) (MessagingPushToken, error) {
	row := q.db.QueryRow(ctx, messagingUpsertPushToken,
		arg.UserID,
		arg.App,
		arg.Platform,
		arg.Token,
		arg.AppVersion,
		arg.Locale,
	)
	var i MessagingPushToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.App,
		&i.Platform,
		&i.Token,
		&i.Provider,
		&i.AppVersion,
		&i.Locale,
		&i.LastSeenAt,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const messagingUpsertSettings = `-- name: MessagingUpsertSettings :one
insert into messaging.notification_settings (user_id, quiet_start, quiet_end, quiet_hours) values ($1, $2, $3, $4)
on conflict (user_id) do update set quiet_start = excluded.quiet_start, quiet_end = excluded.quiet_end, quiet_hours = excluded.quiet_hours, updated_at = now()
returning user_id, quiet_start, quiet_end, quiet_hours, timezone, updated_at
`

type MessagingUpsertSettingsParams struct {
	UserID     uuid.UUID   `json:"userId"`
	QuietStart pgtype.Time `json:"quietStart"`
	QuietEnd   pgtype.Time `json:"quietEnd"`
	QuietHours bool        `json:"quietHours"`
}

func (q *Queries) MessagingUpsertSettings(ctx context.Context, arg MessagingUpsertSettingsParams) (MessagingNotificationSetting, error) {
	row := q.db.QueryRow(ctx, messagingUpsertSettings,
		arg.UserID,
		arg.QuietStart,
		arg.QuietEnd,
		arg.QuietHours,
	)
	var i MessagingNotificationSetting
	err := row.Scan(
		&i.UserID,
		&i.QuietStart,
		&i.QuietEnd,
		&i.QuietHours,
		&i.Timezone,
		&i.UpdatedAt,
	)
	return i, err
}
