// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: payments.sql

package store

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

const paymentsCountForOrder = `-- name: PaymentsCountForOrder :one
select count(*)::int from payments.payments where order_id = $1
`

func (q *Queries) PaymentsCountForOrder(ctx context.Context, orderID *uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, paymentsCountForOrder, orderID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const paymentsCreate = `-- name: PaymentsCreate :one

insert into payments.payments (order_id, invoice_id, provider, channel, idempotency_key, amount_kobo, expires_at)
values ($1, $2, $3, $4, $5, $6, $7)
returning id, order_id, invoice_id, provider, channel, provider_reference, provider_status, checkout_url, idempotency_key, amount_kobo, fees_kobo, currency, status, expires_at, paid_at, failure_reason, created_at, updated_at
`

type PaymentsCreateParams struct {
	OrderID        *uuid.UUID `json:"orderId"`
	InvoiceID      *uuid.UUID `json:"invoiceId"`
	Provider       string     `json:"provider"`
	Channel        *string    `json:"channel"`
	IdempotencyKey string     `json:"idempotencyKey"`
	AmountKobo     int64      `json:"amountKobo"`
	ExpiresAt      *time.Time `json:"expiresAt"`
}

// Payments: charges, provider events, refunds, provider health, reconciliation (docs/payments-finance.md).
func (q *Queries) PaymentsCreate(ctx context.Context, arg PaymentsCreateParams) (PaymentsPayment, error) {
	row := q.db.QueryRow(ctx, paymentsCreate,
		arg.OrderID,
		arg.InvoiceID,
		arg.Provider,
		arg.Channel,
		arg.IdempotencyKey,
		arg.AmountKobo,
		arg.ExpiresAt,
	)
	var i PaymentsPayment
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.InvoiceID,
		&i.Provider,
		&i.Channel,
		&i.ProviderReference,
		&i.ProviderStatus,
		&i.CheckoutUrl,
		&i.IdempotencyKey,
		&i.AmountKobo,
		&i.FeesKobo,
		&i.Currency,
		&i.Status,
		&i.ExpiresAt,
		&i.PaidAt,
		&i.FailureReason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const paymentsCreateException = `-- name: PaymentsCreateException :one
insert into payments.reconciliation_exceptions (kind, provider, reference, amount_kobo, detail) values ($1, $2, $3, $4, $5) returning id, kind, provider, reference, amount_kobo, detail, status, owner_id, resolution, resolved_by, resolved_at, created_at, updated_at
`

type PaymentsCreateExceptionParams struct {
	Kind       string  `json:"kind"`
	Provider   *string `json:"provider"`
	Reference  *string `json:"reference"`
	AmountKobo *int64  `json:"amountKobo"`
	Detail     string  `json:"detail"`
}

func (q *Queries) PaymentsCreateException(ctx context.Context, arg PaymentsCreateExceptionParams) (PaymentsReconciliationException, error) {
	row := q.db.QueryRow(ctx, paymentsCreateException,
		arg.Kind,
		arg.Provider,
		arg.Reference,
		arg.AmountKobo,
		arg.Detail,
	)
	var i PaymentsReconciliationException
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Provider,
		&i.Reference,
		&i.AmountKobo,
		&i.Detail,
		&i.Status,
		&i.OwnerID,
		&i.Resolution,
		&i.ResolvedBy,
		&i.ResolvedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const paymentsCreateRefund = `-- name: PaymentsCreateRefund :one
insert into payments.refunds (payment_id, order_id, return_request_id, amount_kobo, method, reason, requested_by)
values ($1, $2, $3, $4, $5, $6, $7)
returning id, payment_id, order_id, return_request_id, amount_kobo, currency, method, reason, status, requested_by, approved_by, provider_reference, failure_reason, created_at, updated_at
`

type PaymentsCreateRefundParams struct {
	PaymentID       uuid.UUID  `json:"paymentId"`
	OrderID         uuid.UUID  `json:"orderId"`
	ReturnRequestID *uuid.UUID `json:"returnRequestId"`
	AmountKobo      int64      `json:"amountKobo"`
	Method          string     `json:"method"`
	Reason          string     `json:"reason"`
	RequestedBy     *uuid.UUID `json:"requestedBy"`
}

func (q *Queries) PaymentsCreateRefund(ctx context.Context, arg PaymentsCreateRefundParams) (PaymentsRefund, error) {
	row := q.db.QueryRow(ctx, paymentsCreateRefund,
		arg.PaymentID,
		arg.OrderID,
		arg.ReturnRequestID,
		arg.AmountKobo,
		arg.Method,
		arg.Reason,
		arg.RequestedBy,
	)
	var i PaymentsRefund
	err := row.Scan(
		&i.ID,
		&i.PaymentID,
		&i.OrderID,
		&i.ReturnRequestID,
		&i.AmountKobo,
		&i.Currency,
		&i.Method,
		&i.Reason,
		&i.Status,
		&i.RequestedBy,
		&i.ApprovedBy,
		&i.ProviderReference,
		&i.FailureReason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const paymentsCreateVirtualAccount = `-- name: PaymentsCreateVirtualAccount :one
insert into payments.virtual_accounts (provider, account_number, bank_name, owner_type, order_id, business_id, expected_kobo, expires_at)
values ($1, $2, $3, $4, $5, $6, $7, $8) returning id, provider, account_number, bank_name, owner_type, order_id, business_id, expected_kobo, received_kobo, expires_at, status, created_at, updated_at
`

type PaymentsCreateVirtualAccountParams struct {
	Provider      string     `json:"provider"`
	AccountNumber string     `json:"accountNumber"`
	BankName      string     `json:"bankName"`
	OwnerType     string     `json:"ownerType"`
	OrderID       *uuid.UUID `json:"orderId"`
	BusinessID    *uuid.UUID `json:"businessId"`
	ExpectedKobo  *int64     `json:"expectedKobo"`
	ExpiresAt     *time.Time `json:"expiresAt"`
}

func (q *Queries) PaymentsCreateVirtualAccount(ctx context.Context, arg PaymentsCreateVirtualAccountParams) (PaymentsVirtualAccount, error) {
	row := q.db.QueryRow(ctx, paymentsCreateVirtualAccount,
		arg.Provider,
		arg.AccountNumber,
		arg.BankName,
		arg.OwnerType,
		arg.OrderID,
		arg.BusinessID,
		arg.ExpectedKobo,
		arg.ExpiresAt,
	)
	var i PaymentsVirtualAccount
	err := row.Scan(
		&i.ID,
		&i.Provider,
		&i.AccountNumber,
		&i.BankName,
		&i.OwnerType,
		&i.OrderID,
		&i.BusinessID,
		&i.ExpectedKobo,
		&i.ReceivedKobo,
		&i.ExpiresAt,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const paymentsCustomerRefunds = `-- name: PaymentsCustomerRefunds :many
select r.id, r.amount_kobo, r.method, r.reason, r.status, r.created_at, r.updated_at, o.order_number
from payments.refunds r join sales.orders o on o.id = r.order_id
where o.customer_user_id = $1 order by r.created_at desc limit 100
`

type PaymentsCustomerRefundsRow struct {
	ID          uuid.UUID `json:"id"`
	AmountKobo  int64     `json:"amountKobo"`
	Method      string    `json:"method"`
	Reason      string    `json:"reason"`
	Status      string    `json:"status"`
	CreatedAt   time.Time `json:"createdAt"`
	UpdatedAt   time.Time `json:"updatedAt"`
	OrderNumber string    `json:"orderNumber"`
}

func (q *Queries) PaymentsCustomerRefunds(ctx context.Context, customerUserID *uuid.UUID) ([]PaymentsCustomerRefundsRow, error) {
	rows, err := q.db.Query(ctx, paymentsCustomerRefunds, customerUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PaymentsCustomerRefundsRow{}
	for rows.Next() {
		var i PaymentsCustomerRefundsRow
		if err := rows.Scan(
			&i.ID,
			&i.AmountKobo,
			&i.Method,
			&i.Reason,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.OrderNumber,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const paymentsFakeLatestCharge = `-- name: PaymentsFakeLatestCharge :one
select payload from payments.payment_events
where provider = $1 and payload -> 'data' ->> 'reference' = $2::text and signature_valid and event_type like 'charge.%'
order by received_at desc limit 1
`

type PaymentsFakeLatestChargeParams struct {
	Provider  string `json:"provider"`
	Reference string `json:"reference"`
}

// Development fake provider: its "server state" is the last signed charge event it sent.
func (q *Queries) PaymentsFakeLatestCharge(ctx context.Context, arg PaymentsFakeLatestChargeParams) (json.RawMessage, error) {
	row := q.db.QueryRow(ctx, paymentsFakeLatestCharge, arg.Provider, arg.Reference)
	var payload json.RawMessage
	err := row.Scan(&payload)
	return payload, err
}

const paymentsForOrder = `-- name: PaymentsForOrder :many
select id, order_id, invoice_id, provider, channel, provider_reference, provider_status, checkout_url, idempotency_key, amount_kobo, fees_kobo, currency, status, expires_at, paid_at, failure_reason, created_at, updated_at from payments.payments where order_id = $1 order by created_at
`

func (q *Queries) PaymentsForOrder(ctx context.Context, orderID *uuid.UUID) ([]PaymentsPayment, error) {
	rows, err := q.db.Query(ctx, paymentsForOrder, orderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PaymentsPayment{}
	for rows.Next() {
		var i PaymentsPayment
		if err := rows.Scan(
			&i.ID,
			&i.OrderID,
			&i.InvoiceID,
			&i.Provider,
			&i.Channel,
			&i.ProviderReference,
			&i.ProviderStatus,
			&i.CheckoutUrl,
			&i.IdempotencyKey,
			&i.AmountKobo,
			&i.FeesKobo,
			&i.Currency,
			&i.Status,
			&i.ExpiresAt,
			&i.PaidAt,
			&i.FailureReason,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const paymentsGet = `-- name: PaymentsGet :one
select id, order_id, invoice_id, provider, channel, provider_reference, provider_status, checkout_url, idempotency_key, amount_kobo, fees_kobo, currency, status, expires_at, paid_at, failure_reason, created_at, updated_at from payments.payments where id = $1
`

func (q *Queries) PaymentsGet(ctx context.Context, id uuid.UUID) (PaymentsPayment, error) {
	row := q.db.QueryRow(ctx, paymentsGet, id)
	var i PaymentsPayment
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.InvoiceID,
		&i.Provider,
		&i.Channel,
		&i.ProviderReference,
		&i.ProviderStatus,
		&i.CheckoutUrl,
		&i.IdempotencyKey,
		&i.AmountKobo,
		&i.FeesKobo,
		&i.Currency,
		&i.Status,
		&i.ExpiresAt,
		&i.PaidAt,
		&i.FailureReason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const paymentsGetByAnyReference = `-- name: PaymentsGetByAnyReference :one
select id, order_id, invoice_id, provider, channel, provider_reference, provider_status, checkout_url, idempotency_key, amount_kobo, fees_kobo, currency, status, expires_at, paid_at, failure_reason, created_at, updated_at from payments.payments where provider_reference = $1
`

func (q *Queries) PaymentsGetByAnyReference(ctx context.Context, providerReference *string) (PaymentsPayment, error) {
	row := q.db.QueryRow(ctx, paymentsGetByAnyReference, providerReference)
	var i PaymentsPayment
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.InvoiceID,
		&i.Provider,
		&i.Channel,
		&i.ProviderReference,
		&i.ProviderStatus,
		&i.CheckoutUrl,
		&i.IdempotencyKey,
		&i.AmountKobo,
		&i.FeesKobo,
		&i.Currency,
		&i.Status,
		&i.ExpiresAt,
		&i.PaidAt,
		&i.FailureReason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const paymentsGetByReference = `-- name: PaymentsGetByReference :one
select id, order_id, invoice_id, provider, channel, provider_reference, provider_status, checkout_url, idempotency_key, amount_kobo, fees_kobo, currency, status, expires_at, paid_at, failure_reason, created_at, updated_at from payments.payments where provider = $1 and provider_reference = $2
`

type PaymentsGetByReferenceParams struct {
	Provider          string  `json:"provider"`
	ProviderReference *string `json:"providerReference"`
}

func (q *Queries) PaymentsGetByReference(ctx context.Context, arg PaymentsGetByReferenceParams) (PaymentsPayment, error) {
	row := q.db.QueryRow(ctx, paymentsGetByReference, arg.Provider, arg.ProviderReference)
	var i PaymentsPayment
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.InvoiceID,
		&i.Provider,
		&i.Channel,
		&i.ProviderReference,
		&i.ProviderStatus,
		&i.CheckoutUrl,
		&i.IdempotencyKey,
		&i.AmountKobo,
		&i.FeesKobo,
		&i.Currency,
		&i.Status,
		&i.ExpiresAt,
		&i.PaidAt,
		&i.FailureReason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const paymentsGetEvent = `-- name: PaymentsGetEvent :one
select id, provider, provider_event_id, event_type, payment_id, refund_id, payout_id, payload, signature_valid, received_at, processed_at from payments.payment_events where id = $1
`

func (q *Queries) PaymentsGetEvent(ctx context.Context, id uuid.UUID) (PaymentsPaymentEvent, error) {
	row := q.db.QueryRow(ctx, paymentsGetEvent, id)
	var i PaymentsPaymentEvent
	err := row.Scan(
		&i.ID,
		&i.Provider,
		&i.ProviderEventID,
		&i.EventType,
		&i.PaymentID,
		&i.RefundID,
		&i.PayoutID,
		&i.Payload,
		&i.SignatureValid,
		&i.ReceivedAt,
		&i.ProcessedAt,
	)
	return i, err
}

const paymentsGetForUpdate = `-- name: PaymentsGetForUpdate :one
select id, order_id, invoice_id, provider, channel, provider_reference, provider_status, checkout_url, idempotency_key, amount_kobo, fees_kobo, currency, status, expires_at, paid_at, failure_reason, created_at, updated_at from payments.payments where id = $1 for update
`

func (q *Queries) PaymentsGetForUpdate(ctx context.Context, id uuid.UUID) (PaymentsPayment, error) {
	row := q.db.QueryRow(ctx, paymentsGetForUpdate, id)
	var i PaymentsPayment
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.InvoiceID,
		&i.Provider,
		&i.Channel,
		&i.ProviderReference,
		&i.ProviderStatus,
		&i.CheckoutUrl,
		&i.IdempotencyKey,
		&i.AmountKobo,
		&i.FeesKobo,
		&i.Currency,
		&i.Status,
		&i.ExpiresAt,
		&i.PaidAt,
		&i.FailureReason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const paymentsGetHealth = `-- name: PaymentsGetHealth :many
select provider, breaker_state, failures, last_failure_at, updated_at from payments.provider_health
`

func (q *Queries) PaymentsGetHealth(ctx context.Context) ([]PaymentsProviderHealth, error) {
	rows, err := q.db.Query(ctx, paymentsGetHealth)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PaymentsProviderHealth{}
	for rows.Next() {
		var i PaymentsProviderHealth
		if err := rows.Scan(
			&i.Provider,
			&i.BreakerState,
			&i.Failures,
			&i.LastFailureAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const paymentsGetRefund = `-- name: PaymentsGetRefund :one
select id, payment_id, order_id, return_request_id, amount_kobo, currency, method, reason, status, requested_by, approved_by, provider_reference, failure_reason, created_at, updated_at from payments.refunds where id = $1
`

func (q *Queries) PaymentsGetRefund(ctx context.Context, id uuid.UUID) (PaymentsRefund, error) {
	row := q.db.QueryRow(ctx, paymentsGetRefund, id)
	var i PaymentsRefund
	err := row.Scan(
		&i.ID,
		&i.PaymentID,
		&i.OrderID,
		&i.ReturnRequestID,
		&i.AmountKobo,
		&i.Currency,
		&i.Method,
		&i.Reason,
		&i.Status,
		&i.RequestedBy,
		&i.ApprovedBy,
		&i.ProviderReference,
		&i.FailureReason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const paymentsGetRefundForUpdate = `-- name: PaymentsGetRefundForUpdate :one
select id, payment_id, order_id, return_request_id, amount_kobo, currency, method, reason, status, requested_by, approved_by, provider_reference, failure_reason, created_at, updated_at from payments.refunds where id = $1 for update
`

func (q *Queries) PaymentsGetRefundForUpdate(ctx context.Context, id uuid.UUID) (PaymentsRefund, error) {
	row := q.db.QueryRow(ctx, paymentsGetRefundForUpdate, id)
	var i PaymentsRefund
	err := row.Scan(
		&i.ID,
		&i.PaymentID,
		&i.OrderID,
		&i.ReturnRequestID,
		&i.AmountKobo,
		&i.Currency,
		&i.Method,
		&i.Reason,
		&i.Status,
		&i.RequestedBy,
		&i.ApprovedBy,
		&i.ProviderReference,
		&i.FailureReason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const paymentsInsertEvent = `-- name: PaymentsInsertEvent :one
insert into payments.payment_events (provider, provider_event_id, event_type, payment_id, payload, signature_valid)
values ($1, $2, $3, $4, $5, $6)
on conflict (provider, provider_event_id) do nothing
returning id
`

type PaymentsInsertEventParams struct {
	Provider        string          `json:"provider"`
	ProviderEventID string          `json:"providerEventId"`
	EventType       string          `json:"eventType"`
	PaymentID       *uuid.UUID      `json:"paymentId"`
	Payload         json.RawMessage `json:"payload"`
	SignatureValid  bool            `json:"signatureValid"`
}

func (q *Queries) PaymentsInsertEvent(ctx context.Context, arg PaymentsInsertEventParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, paymentsInsertEvent,
		arg.Provider,
		arg.ProviderEventID,
		arg.EventType,
		arg.PaymentID,
		arg.Payload,
		arg.SignatureValid,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const paymentsLatestForOrder = `-- name: PaymentsLatestForOrder :one
select id, order_id, invoice_id, provider, channel, provider_reference, provider_status, checkout_url, idempotency_key, amount_kobo, fees_kobo, currency, status, expires_at, paid_at, failure_reason, created_at, updated_at from payments.payments where order_id = $1 order by created_at desc limit 1
`

func (q *Queries) PaymentsLatestForOrder(ctx context.Context, orderID *uuid.UUID) (PaymentsPayment, error) {
	row := q.db.QueryRow(ctx, paymentsLatestForOrder, orderID)
	var i PaymentsPayment
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.InvoiceID,
		&i.Provider,
		&i.Channel,
		&i.ProviderReference,
		&i.ProviderStatus,
		&i.CheckoutUrl,
		&i.IdempotencyKey,
		&i.AmountKobo,
		&i.FeesKobo,
		&i.Currency,
		&i.Status,
		&i.ExpiresAt,
		&i.PaidAt,
		&i.FailureReason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const paymentsListExceptions = `-- name: PaymentsListExceptions :many
select id, kind, provider, reference, amount_kobo, detail, status, owner_id, resolution, resolved_by, resolved_at, created_at, updated_at from payments.reconciliation_exceptions where ($2::text is null or status = $2) order by created_at desc limit $1
`

type PaymentsListExceptionsParams struct {
	Limit  int32   `json:"limit"`
	Status *string `json:"status"`
}

func (q *Queries) PaymentsListExceptions(ctx context.Context, arg PaymentsListExceptionsParams) ([]PaymentsReconciliationException, error) {
	rows, err := q.db.Query(ctx, paymentsListExceptions, arg.Limit, arg.Status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PaymentsReconciliationException{}
	for rows.Next() {
		var i PaymentsReconciliationException
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.Provider,
			&i.Reference,
			&i.AmountKobo,
			&i.Detail,
			&i.Status,
			&i.OwnerID,
			&i.Resolution,
			&i.ResolvedBy,
			&i.ResolvedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const paymentsListRefunds = `-- name: PaymentsListRefunds :many
select r.id, r.payment_id, r.order_id, r.return_request_id, r.amount_kobo, r.currency, r.method, r.reason, r.status, r.requested_by, r.approved_by, r.provider_reference, r.failure_reason, r.created_at, r.updated_at, o.order_number from payments.refunds r join sales.orders o on o.id = r.order_id
where ($2::text is null or r.status = $2)
order by r.created_at desc limit $1
`

type PaymentsListRefundsParams struct {
	Limit  int32   `json:"limit"`
	Status *string `json:"status"`
}

type PaymentsListRefundsRow struct {
	ID                uuid.UUID  `json:"id"`
	PaymentID         uuid.UUID  `json:"paymentId"`
	OrderID           uuid.UUID  `json:"orderId"`
	ReturnRequestID   *uuid.UUID `json:"returnRequestId"`
	AmountKobo        int64      `json:"amountKobo"`
	Currency          string     `json:"currency"`
	Method            string     `json:"method"`
	Reason            string     `json:"reason"`
	Status            string     `json:"status"`
	RequestedBy       *uuid.UUID `json:"requestedBy"`
	ApprovedBy        *uuid.UUID `json:"approvedBy"`
	ProviderReference *string    `json:"providerReference"`
	FailureReason     *string    `json:"failureReason"`
	CreatedAt         time.Time  `json:"createdAt"`
	UpdatedAt         time.Time  `json:"updatedAt"`
	OrderNumber       string     `json:"orderNumber"`
}

func (q *Queries) PaymentsListRefunds(ctx context.Context, arg PaymentsListRefundsParams) ([]PaymentsListRefundsRow, error) {
	rows, err := q.db.Query(ctx, paymentsListRefunds, arg.Limit, arg.Status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PaymentsListRefundsRow{}
	for rows.Next() {
		var i PaymentsListRefundsRow
		if err := rows.Scan(
			&i.ID,
			&i.PaymentID,
			&i.OrderID,
			&i.ReturnRequestID,
			&i.AmountKobo,
			&i.Currency,
			&i.Method,
			&i.Reason,
			&i.Status,
			&i.RequestedBy,
			&i.ApprovedBy,
			&i.ProviderReference,
			&i.FailureReason,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.OrderNumber,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const paymentsMarkEventProcessed = `-- name: PaymentsMarkEventProcessed :exec
update payments.payment_events set processed_at = now(), payment_id = coalesce(payment_id, $2) where id = $1
`

type PaymentsMarkEventProcessedParams struct {
	ID        uuid.UUID  `json:"id"`
	PaymentID *uuid.UUID `json:"paymentId"`
}

func (q *Queries) PaymentsMarkEventProcessed(ctx context.Context, arg PaymentsMarkEventProcessedParams) error {
	_, err := q.db.Exec(ctx, paymentsMarkEventProcessed, arg.ID, arg.PaymentID)
	return err
}

const paymentsOrderRefunds = `-- name: PaymentsOrderRefunds :many
select id, payment_id, order_id, return_request_id, amount_kobo, currency, method, reason, status, requested_by, approved_by, provider_reference, failure_reason, created_at, updated_at from payments.refunds where order_id = $1 order by created_at
`

func (q *Queries) PaymentsOrderRefunds(ctx context.Context, orderID uuid.UUID) ([]PaymentsRefund, error) {
	rows, err := q.db.Query(ctx, paymentsOrderRefunds, orderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PaymentsRefund{}
	for rows.Next() {
		var i PaymentsRefund
		if err := rows.Scan(
			&i.ID,
			&i.PaymentID,
			&i.OrderID,
			&i.ReturnRequestID,
			&i.AmountKobo,
			&i.Currency,
			&i.Method,
			&i.Reason,
			&i.Status,
			&i.RequestedBy,
			&i.ApprovedBy,
			&i.ProviderReference,
			&i.FailureReason,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const paymentsOrderWithCustomer = `-- name: PaymentsOrderWithCustomer :one
select o.id, o.order_number, o.channel, o.customer_user_id, o.business_id, o.quote_id, o.pos_shift_id, o.status, o.subtotal_kobo, o.delivery_fee_kobo, o.discount_kobo, o.vat_kobo, o.total_kobo, o.currency, o.ship_to, o.contact_phone, o.price_hash, o.payment_due_at, o.attributed_notification_id, o.placed_at, o.cancelled_at, o.created_at, o.updated_at, u.email as customer_email, u.phone as customer_phone, u.first_name as customer_first_name
from sales.orders o left join identity.users u on u.id = o.customer_user_id where o.id = $1
`

type PaymentsOrderWithCustomerRow struct {
	ID                       uuid.UUID       `json:"id"`
	OrderNumber              string          `json:"orderNumber"`
	Channel                  string          `json:"channel"`
	CustomerUserID           *uuid.UUID      `json:"customerUserId"`
	BusinessID               *uuid.UUID      `json:"businessId"`
	QuoteID                  *uuid.UUID      `json:"quoteId"`
	PosShiftID               *uuid.UUID      `json:"posShiftId"`
	Status                   string          `json:"status"`
	SubtotalKobo             int64           `json:"subtotalKobo"`
	DeliveryFeeKobo          int64           `json:"deliveryFeeKobo"`
	DiscountKobo             int64           `json:"discountKobo"`
	VatKobo                  int64           `json:"vatKobo"`
	TotalKobo                int64           `json:"totalKobo"`
	Currency                 string          `json:"currency"`
	ShipTo                   json.RawMessage `json:"shipTo"`
	ContactPhone             *string         `json:"contactPhone"`
	PriceHash                *string         `json:"priceHash"`
	PaymentDueAt             *time.Time      `json:"paymentDueAt"`
	AttributedNotificationID *uuid.UUID      `json:"attributedNotificationId"`
	PlacedAt                 time.Time       `json:"placedAt"`
	CancelledAt              *time.Time      `json:"cancelledAt"`
	CreatedAt                time.Time       `json:"createdAt"`
	UpdatedAt                time.Time       `json:"updatedAt"`
	CustomerEmail            *string         `json:"customerEmail"`
	CustomerPhone            *string         `json:"customerPhone"`
	CustomerFirstName        *string         `json:"customerFirstName"`
}

func (q *Queries) PaymentsOrderWithCustomer(ctx context.Context, id uuid.UUID) (PaymentsOrderWithCustomerRow, error) {
	row := q.db.QueryRow(ctx, paymentsOrderWithCustomer, id)
	var i PaymentsOrderWithCustomerRow
	err := row.Scan(
		&i.ID,
		&i.OrderNumber,
		&i.Channel,
		&i.CustomerUserID,
		&i.BusinessID,
		&i.QuoteID,
		&i.PosShiftID,
		&i.Status,
		&i.SubtotalKobo,
		&i.DeliveryFeeKobo,
		&i.DiscountKobo,
		&i.VatKobo,
		&i.TotalKobo,
		&i.Currency,
		&i.ShipTo,
		&i.ContactPhone,
		&i.PriceHash,
		&i.PaymentDueAt,
		&i.AttributedNotificationID,
		&i.PlacedAt,
		&i.CancelledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CustomerEmail,
		&i.CustomerPhone,
		&i.CustomerFirstName,
	)
	return i, err
}

const paymentsRecordFailure = `-- name: PaymentsRecordFailure :one
insert into payments.provider_health (provider, failures, last_failure_at, breaker_state) values ($1, 1, now(), 'closed')
on conflict (provider) do update set failures = payments.provider_health.failures + 1, last_failure_at = now(),
  breaker_state = case when payments.provider_health.failures + 1 >= 5 then 'open' else payments.provider_health.breaker_state end, updated_at = now()
returning provider, breaker_state, failures, last_failure_at, updated_at
`

// Circuit breaker: 5 failures in a row open the breaker for this provider.
func (q *Queries) PaymentsRecordFailure(ctx context.Context, provider string) (PaymentsProviderHealth, error) {
	row := q.db.QueryRow(ctx, paymentsRecordFailure, provider)
	var i PaymentsProviderHealth
	err := row.Scan(
		&i.Provider,
		&i.BreakerState,
		&i.Failures,
		&i.LastFailureAt,
		&i.UpdatedAt,
	)
	return i, err
}

const paymentsRecordSuccess = `-- name: PaymentsRecordSuccess :exec
insert into payments.provider_health (provider) values ($1)
on conflict (provider) do update set failures = 0, breaker_state = 'closed', updated_at = now()
`

func (q *Queries) PaymentsRecordSuccess(ctx context.Context, provider string) error {
	_, err := q.db.Exec(ctx, paymentsRecordSuccess, provider)
	return err
}

const paymentsRefundedTotal = `-- name: PaymentsRefundedTotal :one
select coalesce(sum(amount_kobo), 0)::bigint from payments.refunds
where payment_id = $1 and status not in ('rejected', 'failed') and reason not like 'Excess payment: %'
`

// Money already committed to refunds of a payment's order total (anything not rejected or
// failed). Excess-payment refunds are money on top of the total, so they don't count.
func (q *Queries) PaymentsRefundedTotal(ctx context.Context, paymentID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, paymentsRefundedTotal, paymentID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const paymentsResolveException = `-- name: PaymentsResolveException :one
update payments.reconciliation_exceptions set status = $2, resolution = $3, resolved_by = $4, resolved_at = now(), updated_at = now()
where id = $1 and status = 'open' returning id, kind, provider, reference, amount_kobo, detail, status, owner_id, resolution, resolved_by, resolved_at, created_at, updated_at
`

type PaymentsResolveExceptionParams struct {
	ID         uuid.UUID  `json:"id"`
	Status     string     `json:"status"`
	Resolution *string    `json:"resolution"`
	ResolvedBy *uuid.UUID `json:"resolvedBy"`
}

func (q *Queries) PaymentsResolveException(ctx context.Context, arg PaymentsResolveExceptionParams) (PaymentsReconciliationException, error) {
	row := q.db.QueryRow(ctx, paymentsResolveException,
		arg.ID,
		arg.Status,
		arg.Resolution,
		arg.ResolvedBy,
	)
	var i PaymentsReconciliationException
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Provider,
		&i.Reference,
		&i.AmountKobo,
		&i.Detail,
		&i.Status,
		&i.OwnerID,
		&i.Resolution,
		&i.ResolvedBy,
		&i.ResolvedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const paymentsSetOpened = `-- name: PaymentsSetOpened :one
update payments.payments set status = 'pending', provider_reference = $2, checkout_url = $3, channel = coalesce($4, channel), updated_at = now()
where id = $1 and status = 'initiated' returning id, order_id, invoice_id, provider, channel, provider_reference, provider_status, checkout_url, idempotency_key, amount_kobo, fees_kobo, currency, status, expires_at, paid_at, failure_reason, created_at, updated_at
`

type PaymentsSetOpenedParams struct {
	ID                uuid.UUID `json:"id"`
	ProviderReference *string   `json:"providerReference"`
	CheckoutUrl       *string   `json:"checkoutUrl"`
	Channel           *string   `json:"channel"`
}

func (q *Queries) PaymentsSetOpened(ctx context.Context, arg PaymentsSetOpenedParams) (PaymentsPayment, error) {
	row := q.db.QueryRow(ctx, paymentsSetOpened,
		arg.ID,
		arg.ProviderReference,
		arg.CheckoutUrl,
		arg.Channel,
	)
	var i PaymentsPayment
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.InvoiceID,
		&i.Provider,
		&i.Channel,
		&i.ProviderReference,
		&i.ProviderStatus,
		&i.CheckoutUrl,
		&i.IdempotencyKey,
		&i.AmountKobo,
		&i.FeesKobo,
		&i.Currency,
		&i.Status,
		&i.ExpiresAt,
		&i.PaidAt,
		&i.FailureReason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const paymentsSetRefundStatus = `-- name: PaymentsSetRefundStatus :one
update payments.refunds
set status = $2, approved_by = coalesce($3, approved_by),
    provider_reference = coalesce($4, provider_reference),
    failure_reason = coalesce($5, failure_reason), updated_at = now()
where id = $1 returning id, payment_id, order_id, return_request_id, amount_kobo, currency, method, reason, status, requested_by, approved_by, provider_reference, failure_reason, created_at, updated_at
`

type PaymentsSetRefundStatusParams struct {
	ID                uuid.UUID  `json:"id"`
	Status            string     `json:"status"`
	ApprovedBy        *uuid.UUID `json:"approvedBy"`
	ProviderReference *string    `json:"providerReference"`
	FailureReason     *string    `json:"failureReason"`
}

func (q *Queries) PaymentsSetRefundStatus(ctx context.Context, arg PaymentsSetRefundStatusParams) (PaymentsRefund, error) {
	row := q.db.QueryRow(ctx, paymentsSetRefundStatus,
		arg.ID,
		arg.Status,
		arg.ApprovedBy,
		arg.ProviderReference,
		arg.FailureReason,
	)
	var i PaymentsRefund
	err := row.Scan(
		&i.ID,
		&i.PaymentID,
		&i.OrderID,
		&i.ReturnRequestID,
		&i.AmountKobo,
		&i.Currency,
		&i.Method,
		&i.Reason,
		&i.Status,
		&i.RequestedBy,
		&i.ApprovedBy,
		&i.ProviderReference,
		&i.FailureReason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const paymentsSetStatus = `-- name: PaymentsSetStatus :one
update payments.payments
set status = $2, provider_status = coalesce($3, provider_status),
    paid_at = case when $2 = 'succeeded' then coalesce(paid_at, now()) else paid_at end,
    fees_kobo = coalesce($4, fees_kobo),
    failure_reason = coalesce($5, failure_reason), updated_at = now()
where id = $1 returning id, order_id, invoice_id, provider, channel, provider_reference, provider_status, checkout_url, idempotency_key, amount_kobo, fees_kobo, currency, status, expires_at, paid_at, failure_reason, created_at, updated_at
`

type PaymentsSetStatusParams struct {
	ID             uuid.UUID `json:"id"`
	Status         string    `json:"status"`
	ProviderStatus *string   `json:"providerStatus"`
	FeesKobo       *int64    `json:"feesKobo"`
	FailureReason  *string   `json:"failureReason"`
}

func (q *Queries) PaymentsSetStatus(ctx context.Context, arg PaymentsSetStatusParams) (PaymentsPayment, error) {
	row := q.db.QueryRow(ctx, paymentsSetStatus,
		arg.ID,
		arg.Status,
		arg.ProviderStatus,
		arg.FeesKobo,
		arg.FailureReason,
	)
	var i PaymentsPayment
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.InvoiceID,
		&i.Provider,
		&i.Channel,
		&i.ProviderReference,
		&i.ProviderStatus,
		&i.CheckoutUrl,
		&i.IdempotencyKey,
		&i.AmountKobo,
		&i.FeesKobo,
		&i.Currency,
		&i.Status,
		&i.ExpiresAt,
		&i.PaidAt,
		&i.FailureReason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const paymentsSetVirtualAccountStatus = `-- name: PaymentsSetVirtualAccountStatus :exec
update payments.virtual_accounts set status = $2, received_kobo = $3, updated_at = now() where id = $1
`

type PaymentsSetVirtualAccountStatusParams struct {
	ID           uuid.UUID `json:"id"`
	Status       string    `json:"status"`
	ReceivedKobo int64     `json:"receivedKobo"`
}

func (q *Queries) PaymentsSetVirtualAccountStatus(ctx context.Context, arg PaymentsSetVirtualAccountStatusParams) error {
	_, err := q.db.Exec(ctx, paymentsSetVirtualAccountStatus, arg.ID, arg.Status, arg.ReceivedKobo)
	return err
}

const paymentsStalePending = `-- name: PaymentsStalePending :many
select id, order_id, invoice_id, provider, channel, provider_reference, provider_status, checkout_url, idempotency_key, amount_kobo, fees_kobo, currency, status, expires_at, paid_at, failure_reason, created_at, updated_at from payments.payments where status in ('initiated', 'pending') and created_at < $1 order by created_at limit 100
`

// The sweep re-verifies pending payments older than the threshold, so a missed webhook never strands an order.
func (q *Queries) PaymentsStalePending(ctx context.Context, createdAt time.Time) ([]PaymentsPayment, error) {
	rows, err := q.db.Query(ctx, paymentsStalePending, createdAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PaymentsPayment{}
	for rows.Next() {
		var i PaymentsPayment
		if err := rows.Scan(
			&i.ID,
			&i.OrderID,
			&i.InvoiceID,
			&i.Provider,
			&i.Channel,
			&i.ProviderReference,
			&i.ProviderStatus,
			&i.CheckoutUrl,
			&i.IdempotencyKey,
			&i.AmountKobo,
			&i.FeesKobo,
			&i.Currency,
			&i.Status,
			&i.ExpiresAt,
			&i.PaidAt,
			&i.FailureReason,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const paymentsSucceededForOrder = `-- name: PaymentsSucceededForOrder :one
select id, order_id, invoice_id, provider, channel, provider_reference, provider_status, checkout_url, idempotency_key, amount_kobo, fees_kobo, currency, status, expires_at, paid_at, failure_reason, created_at, updated_at from payments.payments where order_id = $1 and status in ('succeeded', 'reversed') order by paid_at limit 1
`

func (q *Queries) PaymentsSucceededForOrder(ctx context.Context, orderID *uuid.UUID) (PaymentsPayment, error) {
	row := q.db.QueryRow(ctx, paymentsSucceededForOrder, orderID)
	var i PaymentsPayment
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.InvoiceID,
		&i.Provider,
		&i.Channel,
		&i.ProviderReference,
		&i.ProviderStatus,
		&i.CheckoutUrl,
		&i.IdempotencyKey,
		&i.AmountKobo,
		&i.FeesKobo,
		&i.Currency,
		&i.Status,
		&i.ExpiresAt,
		&i.PaidAt,
		&i.FailureReason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const paymentsVirtualAccountForOrder = `-- name: PaymentsVirtualAccountForOrder :one
select id, provider, account_number, bank_name, owner_type, order_id, business_id, expected_kobo, received_kobo, expires_at, status, created_at, updated_at from payments.virtual_accounts where order_id = $1 and status = 'active' order by created_at desc limit 1
`

func (q *Queries) PaymentsVirtualAccountForOrder(ctx context.Context, orderID *uuid.UUID) (PaymentsVirtualAccount, error) {
	row := q.db.QueryRow(ctx, paymentsVirtualAccountForOrder, orderID)
	var i PaymentsVirtualAccount
	err := row.Scan(
		&i.ID,
		&i.Provider,
		&i.AccountNumber,
		&i.BankName,
		&i.OwnerType,
		&i.OrderID,
		&i.BusinessID,
		&i.ExpectedKobo,
		&i.ReceivedKobo,
		&i.ExpiresAt,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
