// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: personalisation.sql

package store

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

type PersonalisationInsertEventParams struct {
	OccurredAt   time.Time       `json:"occurredAt"`
	AnonymousID  uuid.UUID       `json:"anonymousId"`
	UserID       *uuid.UUID      `json:"userId"`
	SessionID    *string         `json:"sessionId"`
	EventType    string          `json:"eventType"`
	App          string          `json:"app"`
	Surface      *string         `json:"surface"`
	ProductID    *uuid.UUID      `json:"productId"`
	ListingID    *uuid.UUID      `json:"listingId"`
	CategoryID   *uuid.UUID      `json:"categoryId"`
	QueryNorm    *string         `json:"queryNorm"`
	ResultsCount *int32          `json:"resultsCount"`
	Position     *int16          `json:"position"`
	RecRequestID *string         `json:"recRequestId"`
	Strategy     *string         `json:"strategy"`
	StateCode    *string         `json:"stateCode"`
	DeviceClass  *string         `json:"deviceClass"`
	Properties   json.RawMessage `json:"properties"`
}

const personalisationLinkIdentity = `-- name: PersonalisationLinkIdentity :exec
insert into personalisation.identity_links (anonymous_id, user_id) values ($1, $2) on conflict (anonymous_id) do nothing
`

type PersonalisationLinkIdentityParams struct {
	AnonymousID uuid.UUID `json:"anonymousId"`
	UserID      uuid.UUID `json:"userId"`
}

func (q *Queries) PersonalisationLinkIdentity(ctx context.Context, arg PersonalisationLinkIdentityParams) error {
	_, err := q.db.Exec(ctx, personalisationLinkIdentity, arg.AnonymousID, arg.UserID)
	return err
}
