// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: platform.sql

package store

import (
	"context"
	"encoding/json"
	"net/netip"
	"time"

	"github.com/google/uuid"
)

const platformCompleteIdempotencyKey = `-- name: PlatformCompleteIdempotencyKey :exec
update platform.idempotency_keys
set response_code = $3, response_body = $4, completed_at = now(), locked_at = null
where scope = $1 and key = $2
`

type PlatformCompleteIdempotencyKeyParams struct {
	Scope        string          `json:"scope"`
	Key          string          `json:"key"`
	ResponseCode *int16          `json:"responseCode"`
	ResponseBody json.RawMessage `json:"responseBody"`
}

func (q *Queries) PlatformCompleteIdempotencyKey(ctx context.Context, arg PlatformCompleteIdempotencyKeyParams) error {
	_, err := q.db.Exec(ctx, platformCompleteIdempotencyKey,
		arg.Scope,
		arg.Key,
		arg.ResponseCode,
		arg.ResponseBody,
	)
	return err
}

const platformCountRateLimit = `-- name: PlatformCountRateLimit :one
select coalesce(sum(count), 0)::int from identity.auth_rate_limits where key = $1 and window_start >= $2
`

type PlatformCountRateLimitParams struct {
	Key         string    `json:"key"`
	WindowStart time.Time `json:"windowStart"`
}

func (q *Queries) PlatformCountRateLimit(ctx context.Context, arg PlatformCountRateLimitParams) (int32, error) {
	row := q.db.QueryRow(ctx, platformCountRateLimit, arg.Key, arg.WindowStart)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const platformCreateFile = `-- name: PlatformCreateFile :one
insert into platform.files (storage_key, purpose, status, original_name, content_type, size_bytes, visibility, uploaded_by)
values ($1, $2, 'pending', $3, $4, $5, $6, $7)
returning id, storage_key, purpose, status, original_name, content_type, size_bytes, checksum, width, height, blurhash, visibility, uploaded_by, deleted_at, created_at
`

type PlatformCreateFileParams struct {
	StorageKey   string     `json:"storageKey"`
	Purpose      string     `json:"purpose"`
	OriginalName *string    `json:"originalName"`
	ContentType  string     `json:"contentType"`
	SizeBytes    int64      `json:"sizeBytes"`
	Visibility   string     `json:"visibility"`
	UploadedBy   *uuid.UUID `json:"uploadedBy"`
}

func (q *Queries) PlatformCreateFile(ctx context.Context, arg PlatformCreateFileParams) (PlatformFile, error) {
	row := q.db.QueryRow(ctx, platformCreateFile,
		arg.StorageKey,
		arg.Purpose,
		arg.OriginalName,
		arg.ContentType,
		arg.SizeBytes,
		arg.Visibility,
		arg.UploadedBy,
	)
	var i PlatformFile
	err := row.Scan(
		&i.ID,
		&i.StorageKey,
		&i.Purpose,
		&i.Status,
		&i.OriginalName,
		&i.ContentType,
		&i.SizeBytes,
		&i.Checksum,
		&i.Width,
		&i.Height,
		&i.Blurhash,
		&i.Visibility,
		&i.UploadedBy,
		&i.DeletedAt,
		&i.CreatedAt,
	)
	return i, err
}

const platformDeleteExpiredIdempotencyKeys = `-- name: PlatformDeleteExpiredIdempotencyKeys :execrows
delete from platform.idempotency_keys where expires_at < now()
`

func (q *Queries) PlatformDeleteExpiredIdempotencyKeys(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, platformDeleteExpiredIdempotencyKeys)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const platformDeleteOldRateLimits = `-- name: PlatformDeleteOldRateLimits :execrows
delete from identity.auth_rate_limits where window_start < now() - interval '2 days'
`

func (q *Queries) PlatformDeleteOldRateLimits(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, platformDeleteOldRateLimits)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const platformGetFeatureFlag = `-- name: PlatformGetFeatureFlag :one
select key, description, enabled, rules, updated_by, updated_at from platform.feature_flags where key = $1
`

func (q *Queries) PlatformGetFeatureFlag(ctx context.Context, key string) (PlatformFeatureFlag, error) {
	row := q.db.QueryRow(ctx, platformGetFeatureFlag, key)
	var i PlatformFeatureFlag
	err := row.Scan(
		&i.Key,
		&i.Description,
		&i.Enabled,
		&i.Rules,
		&i.UpdatedBy,
		&i.UpdatedAt,
	)
	return i, err
}

const platformGetFile = `-- name: PlatformGetFile :one
select id, storage_key, purpose, status, original_name, content_type, size_bytes, checksum, width, height, blurhash, visibility, uploaded_by, deleted_at, created_at from platform.files where id = $1 and deleted_at is null
`

func (q *Queries) PlatformGetFile(ctx context.Context, id uuid.UUID) (PlatformFile, error) {
	row := q.db.QueryRow(ctx, platformGetFile, id)
	var i PlatformFile
	err := row.Scan(
		&i.ID,
		&i.StorageKey,
		&i.Purpose,
		&i.Status,
		&i.OriginalName,
		&i.ContentType,
		&i.SizeBytes,
		&i.Checksum,
		&i.Width,
		&i.Height,
		&i.Blurhash,
		&i.Visibility,
		&i.UploadedBy,
		&i.DeletedAt,
		&i.CreatedAt,
	)
	return i, err
}

const platformGetIdempotencyKey = `-- name: PlatformGetIdempotencyKey :one
select scope, key, user_id, method, path, request_hash, response_code, response_body, locked_at, completed_at, expires_at, created_at from platform.idempotency_keys where scope = $1 and key = $2
`

type PlatformGetIdempotencyKeyParams struct {
	Scope string `json:"scope"`
	Key   string `json:"key"`
}

func (q *Queries) PlatformGetIdempotencyKey(ctx context.Context, arg PlatformGetIdempotencyKeyParams) (PlatformIdempotencyKey, error) {
	row := q.db.QueryRow(ctx, platformGetIdempotencyKey, arg.Scope, arg.Key)
	var i PlatformIdempotencyKey
	err := row.Scan(
		&i.Scope,
		&i.Key,
		&i.UserID,
		&i.Method,
		&i.Path,
		&i.RequestHash,
		&i.ResponseCode,
		&i.ResponseBody,
		&i.LockedAt,
		&i.CompletedAt,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const platformHitRateLimit = `-- name: PlatformHitRateLimit :one
insert into identity.auth_rate_limits (key, window_start, count)
values ($1, $2, 1)
on conflict (key, window_start) do update set count = identity.auth_rate_limits.count + 1
returning count
`

type PlatformHitRateLimitParams struct {
	Key         string    `json:"key"`
	WindowStart time.Time `json:"windowStart"`
}

// Atomically counts one hit in the window and returns the new count.
func (q *Queries) PlatformHitRateLimit(ctx context.Context, arg PlatformHitRateLimitParams) (int32, error) {
	row := q.db.QueryRow(ctx, platformHitRateLimit, arg.Key, arg.WindowStart)
	var count int32
	err := row.Scan(&count)
	return count, err
}

const platformInsertAudit = `-- name: PlatformInsertAudit :exec
insert into platform.audit_log (actor_user_id, actor_kind, action, entity_type, entity_id, changes, request_id, ip, user_agent)
values ($1, $2, $3, $4, $5, $6, $7, $8, $9)
`

type PlatformInsertAuditParams struct {
	ActorUserID *uuid.UUID      `json:"actorUserId"`
	ActorKind   string          `json:"actorKind"`
	Action      string          `json:"action"`
	EntityType  string          `json:"entityType"`
	EntityID    string          `json:"entityId"`
	Changes     json.RawMessage `json:"changes"`
	RequestID   *string         `json:"requestId"`
	Ip          *netip.Addr     `json:"ip"`
	UserAgent   *string         `json:"userAgent"`
}

func (q *Queries) PlatformInsertAudit(ctx context.Context, arg PlatformInsertAuditParams) error {
	_, err := q.db.Exec(ctx, platformInsertAudit,
		arg.ActorUserID,
		arg.ActorKind,
		arg.Action,
		arg.EntityType,
		arg.EntityID,
		arg.Changes,
		arg.RequestID,
		arg.Ip,
		arg.UserAgent,
	)
	return err
}

const platformInsertIdempotencyKey = `-- name: PlatformInsertIdempotencyKey :one
insert into platform.idempotency_keys (scope, key, user_id, method, path, request_hash, locked_at, expires_at)
values ($1, $2, $3, $4, $5, $6, now(), $7)
on conflict (scope, key) do nothing
returning scope, key, user_id, method, path, request_hash, response_code, response_body, locked_at, completed_at, expires_at, created_at
`

type PlatformInsertIdempotencyKeyParams struct {
	Scope       string     `json:"scope"`
	Key         string     `json:"key"`
	UserID      *uuid.UUID `json:"userId"`
	Method      string     `json:"method"`
	Path        string     `json:"path"`
	RequestHash []byte     `json:"requestHash"`
	ExpiresAt   time.Time  `json:"expiresAt"`
}

func (q *Queries) PlatformInsertIdempotencyKey(ctx context.Context, arg PlatformInsertIdempotencyKeyParams) (PlatformIdempotencyKey, error) {
	row := q.db.QueryRow(ctx, platformInsertIdempotencyKey,
		arg.Scope,
		arg.Key,
		arg.UserID,
		arg.Method,
		arg.Path,
		arg.RequestHash,
		arg.ExpiresAt,
	)
	var i PlatformIdempotencyKey
	err := row.Scan(
		&i.Scope,
		&i.Key,
		&i.UserID,
		&i.Method,
		&i.Path,
		&i.RequestHash,
		&i.ResponseCode,
		&i.ResponseBody,
		&i.LockedAt,
		&i.CompletedAt,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const platformInsertOutboxEvent = `-- name: PlatformInsertOutboxEvent :exec
insert into platform.outbox_events (aggregate_type, aggregate_id, event_type, payload, trace_context)
values ($1, $2, $3, $4, $5)
`

type PlatformInsertOutboxEventParams struct {
	AggregateType string          `json:"aggregateType"`
	AggregateID   uuid.UUID       `json:"aggregateId"`
	EventType     string          `json:"eventType"`
	Payload       json.RawMessage `json:"payload"`
	TraceContext  json.RawMessage `json:"traceContext"`
}

func (q *Queries) PlatformInsertOutboxEvent(ctx context.Context, arg PlatformInsertOutboxEventParams) error {
	_, err := q.db.Exec(ctx, platformInsertOutboxEvent,
		arg.AggregateType,
		arg.AggregateID,
		arg.EventType,
		arg.Payload,
		arg.TraceContext,
	)
	return err
}

const platformListAudit = `-- name: PlatformListAudit :many
select id, actor_user_id, actor_kind, action, entity_type, entity_id, changes, request_id, ip, user_agent, created_at from platform.audit_log
where ($2::text is null or entity_type = $2)
  and ($3::uuid is null or actor_user_id = $3)
  and ($4::bigint is null or id < $4)
order by id desc
limit $1
`

type PlatformListAuditParams struct {
	Limit       int32      `json:"limit"`
	EntityType  *string    `json:"entityType"`
	ActorUserID *uuid.UUID `json:"actorUserId"`
	BeforeID    *int64     `json:"beforeId"`
}

func (q *Queries) PlatformListAudit(ctx context.Context, arg PlatformListAuditParams) ([]PlatformAuditLog, error) {
	rows, err := q.db.Query(ctx, platformListAudit,
		arg.Limit,
		arg.EntityType,
		arg.ActorUserID,
		arg.BeforeID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PlatformAuditLog{}
	for rows.Next() {
		var i PlatformAuditLog
		if err := rows.Scan(
			&i.ID,
			&i.ActorUserID,
			&i.ActorKind,
			&i.Action,
			&i.EntityType,
			&i.EntityID,
			&i.Changes,
			&i.RequestID,
			&i.Ip,
			&i.UserAgent,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const platformListFeatureFlags = `-- name: PlatformListFeatureFlags :many
select key, description, enabled, rules, updated_by, updated_at from platform.feature_flags order by key
`

func (q *Queries) PlatformListFeatureFlags(ctx context.Context) ([]PlatformFeatureFlag, error) {
	rows, err := q.db.Query(ctx, platformListFeatureFlags)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PlatformFeatureFlag{}
	for rows.Next() {
		var i PlatformFeatureFlag
		if err := rows.Scan(
			&i.Key,
			&i.Description,
			&i.Enabled,
			&i.Rules,
			&i.UpdatedBy,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const platformListJobsSummary = `-- name: PlatformListJobsSummary :many
select state::text as state, count(*)::int as count from river.river_job group by state order by state
`

type PlatformListJobsSummaryRow struct {
	State string `json:"state"`
	Count int32  `json:"count"`
}

func (q *Queries) PlatformListJobsSummary(ctx context.Context) ([]PlatformListJobsSummaryRow, error) {
	rows, err := q.db.Query(ctx, platformListJobsSummary)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PlatformListJobsSummaryRow{}
	for rows.Next() {
		var i PlatformListJobsSummaryRow
		if err := rows.Scan(&i.State, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const platformListPublicHolidays = `-- name: PlatformListPublicHolidays :many
select date, name from platform.public_holidays where date between $1 and $2 order by date
`

type PlatformListPublicHolidaysParams struct {
	Date   time.Time `json:"date"`
	Date_2 time.Time `json:"date2"`
}

func (q *Queries) PlatformListPublicHolidays(ctx context.Context, arg PlatformListPublicHolidaysParams) ([]PlatformPublicHoliday, error) {
	rows, err := q.db.Query(ctx, platformListPublicHolidays, arg.Date, arg.Date_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PlatformPublicHoliday{}
	for rows.Next() {
		var i PlatformPublicHoliday
		if err := rows.Scan(&i.Date, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const platformLockUnpublishedEvents = `-- name: PlatformLockUnpublishedEvents :many
select id, aggregate_type, aggregate_id, event_type, payload, created_at
from platform.outbox_events
where published_at is null
order by id
limit $1
for update skip locked
`

type PlatformLockUnpublishedEventsRow struct {
	ID            int64           `json:"id"`
	AggregateType string          `json:"aggregateType"`
	AggregateID   uuid.UUID       `json:"aggregateId"`
	EventType     string          `json:"eventType"`
	Payload       json.RawMessage `json:"payload"`
	CreatedAt     time.Time       `json:"createdAt"`
}

func (q *Queries) PlatformLockUnpublishedEvents(ctx context.Context, limit int32) ([]PlatformLockUnpublishedEventsRow, error) {
	rows, err := q.db.Query(ctx, platformLockUnpublishedEvents, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PlatformLockUnpublishedEventsRow{}
	for rows.Next() {
		var i PlatformLockUnpublishedEventsRow
		if err := rows.Scan(
			&i.ID,
			&i.AggregateType,
			&i.AggregateID,
			&i.EventType,
			&i.Payload,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const platformMarkEventsPublished = `-- name: PlatformMarkEventsPublished :exec
update platform.outbox_events set published_at = now() where id = any($1::bigint[])
`

func (q *Queries) PlatformMarkEventsPublished(ctx context.Context, ids []int64) error {
	_, err := q.db.Exec(ctx, platformMarkEventsPublished, ids)
	return err
}

const platformMarkFileReady = `-- name: PlatformMarkFileReady :one
update platform.files set status = 'ready', checksum = $2, width = $3, height = $4
where id = $1 and status = 'pending' returning id, storage_key, purpose, status, original_name, content_type, size_bytes, checksum, width, height, blurhash, visibility, uploaded_by, deleted_at, created_at
`

type PlatformMarkFileReadyParams struct {
	ID       uuid.UUID `json:"id"`
	Checksum *string   `json:"checksum"`
	Width    *int32    `json:"width"`
	Height   *int32    `json:"height"`
}

func (q *Queries) PlatformMarkFileReady(ctx context.Context, arg PlatformMarkFileReadyParams) (PlatformFile, error) {
	row := q.db.QueryRow(ctx, platformMarkFileReady,
		arg.ID,
		arg.Checksum,
		arg.Width,
		arg.Height,
	)
	var i PlatformFile
	err := row.Scan(
		&i.ID,
		&i.StorageKey,
		&i.Purpose,
		&i.Status,
		&i.OriginalName,
		&i.ContentType,
		&i.SizeBytes,
		&i.Checksum,
		&i.Width,
		&i.Height,
		&i.Blurhash,
		&i.Visibility,
		&i.UploadedBy,
		&i.DeletedAt,
		&i.CreatedAt,
	)
	return i, err
}

const platformOutboxLag = `-- name: PlatformOutboxLag :one
select count(*)::int as pending, coalesce(extract(epoch from now() - min(created_at)), 0)::float8 as oldest_seconds
from platform.outbox_events where published_at is null
`

type PlatformOutboxLagRow struct {
	Pending       int32   `json:"pending"`
	OldestSeconds float64 `json:"oldestSeconds"`
}

func (q *Queries) PlatformOutboxLag(ctx context.Context) (PlatformOutboxLagRow, error) {
	row := q.db.QueryRow(ctx, platformOutboxLag)
	var i PlatformOutboxLagRow
	err := row.Scan(&i.Pending, &i.OldestSeconds)
	return i, err
}

const platformPing = `-- name: PlatformPing :one

select 1::int as ok
`

// Platform queries: outbox, audit log, idempotency keys, rate limits, feature flags, files.
func (q *Queries) PlatformPing(ctx context.Context) (int32, error) {
	row := q.db.QueryRow(ctx, platformPing)
	var ok int32
	err := row.Scan(&ok)
	return ok, err
}

const platformReleaseIdempotencyKey = `-- name: PlatformReleaseIdempotencyKey :exec
delete from platform.idempotency_keys where scope = $1 and key = $2 and completed_at is null
`

type PlatformReleaseIdempotencyKeyParams struct {
	Scope string `json:"scope"`
	Key   string `json:"key"`
}

func (q *Queries) PlatformReleaseIdempotencyKey(ctx context.Context, arg PlatformReleaseIdempotencyKeyParams) error {
	_, err := q.db.Exec(ctx, platformReleaseIdempotencyKey, arg.Scope, arg.Key)
	return err
}

const platformSetFeatureFlag = `-- name: PlatformSetFeatureFlag :one
update platform.feature_flags set enabled = $2, rules = $3, updated_by = $4 where key = $1 returning key, description, enabled, rules, updated_by, updated_at
`

type PlatformSetFeatureFlagParams struct {
	Key       string          `json:"key"`
	Enabled   bool            `json:"enabled"`
	Rules     json.RawMessage `json:"rules"`
	UpdatedBy *uuid.UUID      `json:"updatedBy"`
}

func (q *Queries) PlatformSetFeatureFlag(ctx context.Context, arg PlatformSetFeatureFlagParams) (PlatformFeatureFlag, error) {
	row := q.db.QueryRow(ctx, platformSetFeatureFlag,
		arg.Key,
		arg.Enabled,
		arg.Rules,
		arg.UpdatedBy,
	)
	var i PlatformFeatureFlag
	err := row.Scan(
		&i.Key,
		&i.Description,
		&i.Enabled,
		&i.Rules,
		&i.UpdatedBy,
		&i.UpdatedAt,
	)
	return i, err
}
