// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

type Querier interface {
	CatalogAddCompatibility(ctx context.Context, arg CatalogAddCompatibilityParams) error
	CatalogAddImage(ctx context.Context, arg CatalogAddImageParams) (CatalogProductImage, error)
	CatalogAddStockAlert(ctx context.Context, arg CatalogAddStockAlertParams) error
	CatalogAllProductIDs(ctx context.Context) ([]uuid.UUID, error)
	CatalogCreateCategory(ctx context.Context, arg CatalogCreateCategoryParams) (CatalogCategory, error)
	CatalogCreateListing(ctx context.Context, arg CatalogCreateListingParams) (CatalogListing, error)
	CatalogCreateProduct(ctx context.Context, arg CatalogCreateProductParams) (CatalogProduct, error)
	CatalogCreateSuggestion(ctx context.Context, arg CatalogCreateSuggestionParams) (CatalogProductSuggestion, error)
	CatalogCreateVariant(ctx context.Context, arg CatalogCreateVariantParams) (CatalogProductVariant, error)
	CatalogDecideSuggestion(ctx context.Context, arg CatalogDecideSuggestionParams) (CatalogProductSuggestion, error)
	CatalogDeleteOfferSummary(ctx context.Context, productID uuid.UUID) error
	CatalogDeleteSaved(ctx context.Context, arg CatalogDeleteSavedParams) (int64, error)
	CatalogDueStockAlerts(ctx context.Context) ([]CatalogDueStockAlertsRow, error)
	CatalogGetCategoryBySlug(ctx context.Context, slug string) (CatalogCategory, error)
	CatalogGetListing(ctx context.Context, id uuid.UUID) (CatalogGetListingRow, error)
	CatalogGetProduct(ctx context.Context, id uuid.UUID) (CatalogProduct, error)
	CatalogGetProductBySlug(ctx context.Context, slug string) (CatalogGetProductBySlugRow, error)
	CatalogGetProductBySlugForUpdate(ctx context.Context, slug string) (CatalogProduct, error)
	CatalogGetVariant(ctx context.Context, id uuid.UUID) (CatalogGetVariantRow, error)
	CatalogInsertListingReview(ctx context.Context, arg CatalogInsertListingReviewParams) error
	CatalogInsertPriceHistory(ctx context.Context, arg CatalogInsertPriceHistoryParams) error
	CatalogInsertSaved(ctx context.Context, arg CatalogInsertSavedParams) error
	CatalogInsertTier(ctx context.Context, arg CatalogInsertTierParams) error
	CatalogListAttributeDefinitions(ctx context.Context, categoryID uuid.UUID) ([]CatalogAttributeDefinition, error)
	CatalogListAttributeValues(ctx context.Context, productID uuid.UUID) ([]CatalogListAttributeValuesRow, error)
	CatalogListBrands(ctx context.Context) ([]CatalogBrand, error)
	// Catalogue queries (docs/search-catalogue.md). Search itself is the documented dynamic
	// query in internal/catalog/search_query.go.
	CatalogListCategories(ctx context.Context) ([]CatalogCategory, error)
	CatalogListCompatible(ctx context.Context, deviceProductID *uuid.UUID) ([]CatalogListCompatibleRow, error)
	CatalogListImages(ctx context.Context, productID uuid.UUID) ([]CatalogListImagesRow, error)
	CatalogListListingReviews(ctx context.Context, listingID uuid.UUID) ([]CatalogListingReview, error)
	// Every sellable offer for a product (buy box candidates).
	CatalogListOffers(ctx context.Context, productID uuid.UUID) ([]CatalogListOffersRow, error)
	CatalogListSaved(ctx context.Context, userID uuid.UUID) ([]CatalogListSavedRow, error)
	CatalogListSellerListings(ctx context.Context, arg CatalogListSellerListingsParams) ([]CatalogListSellerListingsRow, error)
	CatalogListSuggestions(ctx context.Context, limit int32) ([]CatalogProductSuggestion, error)
	CatalogListTiers(ctx context.Context, listingID uuid.UUID) ([]CatalogPriceTier, error)
	CatalogListVariants(ctx context.Context, productID uuid.UUID) ([]CatalogProductVariant, error)
	CatalogMarkStockAlertNotified(ctx context.Context, arg CatalogMarkStockAlertNotifiedParams) error
	// The highest price this listing sold at in the last 30 days (FCCPA guard for "was" prices).
	CatalogMaxPrice30d(ctx context.Context, listingID uuid.UUID) (int64, error)
	// Median active price for a variant and condition (price-outlier check).
	CatalogMedianPrice(ctx context.Context, arg CatalogMedianPriceParams) (int64, error)
	CatalogModerationQueue(ctx context.Context, limit int32) ([]CatalogModerationQueueRow, error)
	CatalogProductIDForListing(ctx context.Context, id uuid.UUID) (uuid.UUID, error)
	CatalogProductIDForVariant(ctx context.Context, id uuid.UUID) (uuid.UUID, error)
	// Read model ------------------------------------------------------------------
	// Rebuilds the search/browse row for one product and channel from listings, stock, ratings and
	// promotions. Called by the outbox subscriber within seconds of a change (and nightly).
	CatalogRefreshOfferSummary(ctx context.Context, arg CatalogRefreshOfferSummaryParams) error
	CatalogSellerListingCount(ctx context.Context, sellerID uuid.UUID) (int32, error)
	CatalogSetAttributeValue(ctx context.Context, arg CatalogSetAttributeValueParams) error
	CatalogSetListingStatus(ctx context.Context, arg CatalogSetListingStatusParams) (CatalogListing, error)
	CatalogSetListingStock(ctx context.Context, arg CatalogSetListingStockParams) (CatalogListing, error)
	CatalogSuggestCategories(ctx context.Context, dollar_1 *string) ([]CatalogSuggestCategoriesRow, error)
	CatalogSuggestProducts(ctx context.Context, prefix *string) ([]CatalogSuggestProductsRow, error)
	CatalogSuggestQueries(ctx context.Context, prefix string) ([]string, error)
	CatalogSummaryByProduct(ctx context.Context, arg CatalogSummaryByProductParams) (CatalogProductOfferSummary, error)
	CatalogUpdateListingPrice(ctx context.Context, arg CatalogUpdateListingPriceParams) (CatalogListing, error)
	CatalogUpdateProduct(ctx context.Context, arg CatalogUpdateProductParams) (CatalogProduct, error)
	CatalogUpsertAttributeDefinition(ctx context.Context, arg CatalogUpsertAttributeDefinitionParams) (CatalogAttributeDefinition, error)
	CatalogUpsertBrand(ctx context.Context, arg CatalogUpsertBrandParams) (CatalogBrand, error)
	ContentGetHelp(ctx context.Context, arg ContentGetHelpParams) (ContentHelpArticle, error)
	ContentGetPage(ctx context.Context, id uuid.UUID) (ContentCmsPage, error)
	// Content: CMS pages, banners, help articles.
	ContentGetPublishedPage(ctx context.Context, arg ContentGetPublishedPageParams) (ContentCmsPage, error)
	ContentListBanners(ctx context.Context) ([]ContentBanner, error)
	ContentListHelp(ctx context.Context, site string) ([]ContentListHelpRow, error)
	ContentListPages(ctx context.Context, site *string) ([]ContentCmsPage, error)
	ContentLiveBanners(ctx context.Context, arg ContentLiveBannersParams) ([]ContentBanner, error)
	ContentSetBannerStatus(ctx context.Context, arg ContentSetBannerStatusParams) (ContentBanner, error)
	ContentSetPageStatus(ctx context.Context, arg ContentSetPageStatusParams) (ContentCmsPage, error)
	ContentUpsertBanner(ctx context.Context, arg ContentUpsertBannerParams) (ContentBanner, error)
	ContentUpsertHelp(ctx context.Context, arg ContentUpsertHelpParams) (ContentHelpArticle, error)
	ContentUpsertPage(ctx context.Context, arg ContentUpsertPageParams) (ContentCmsPage, error)
	FinanceAccountBalance(ctx context.Context, code string) (int64, error)
	FinanceAccountBalances(ctx context.Context) ([]FinanceAccountBalancesRow, error)
	FinanceAccountLedger(ctx context.Context, arg FinanceAccountLedgerParams) ([]FinanceAccountLedgerRow, error)
	FinanceClosePeriod(ctx context.Context, arg FinanceClosePeriodParams) (FinanceAccountingPeriod, error)
	FinanceDashboard(ctx context.Context) (FinanceDashboardRow, error)
	// Finance: chart of accounts, double-entry journals, periods (docs/payments-finance.md §4).
	// Get-or-create an account by code (seller payables and store credit accounts are created on first use).
	FinanceEnsureAccount(ctx context.Context, arg FinanceEnsureAccountParams) (FinanceLedgerAccount, error)
	FinanceGetAccountByCode(ctx context.Context, code string) (FinanceLedgerAccount, error)
	FinanceGetJournal(ctx context.Context, id uuid.UUID) (FinanceLedgerJournal, error)
	FinanceGetJournalByKey(ctx context.Context, postingKey string) (FinanceLedgerJournal, error)
	FinanceGetPeriod(ctx context.Context, month time.Time) (FinanceAccountingPeriod, error)
	FinanceInsertEntry(ctx context.Context, arg FinanceInsertEntryParams) error
	// Idempotent by posting_key: returns no row when the key was already posted.
	FinanceInsertJournal(ctx context.Context, arg FinanceInsertJournalParams) (FinanceLedgerJournal, error)
	FinanceJournalEntries(ctx context.Context, journalID uuid.UUID) ([]FinanceJournalEntriesRow, error)
	FinanceJournalsForReference(ctx context.Context, arg FinanceJournalsForReferenceParams) ([]FinanceLedgerJournal, error)
	FinanceListJournals(ctx context.Context, arg FinanceListJournalsParams) ([]FinanceLedgerJournal, error)
	FinanceListPeriods(ctx context.Context) ([]FinanceAccountingPeriod, error)
	// Nightly check: every succeeded order payment has exactly one sale journal.
	FinanceSucceededPaymentsWithoutSale(ctx context.Context) ([]FinanceSucceededPaymentsWithoutSaleRow, error)
	// Must always be zero: every journal balances.
	FinanceTrialBalance(ctx context.Context) (FinanceTrialBalanceRow, error)
	FulfilmentAddManifestParcel(ctx context.Context, arg FulfilmentAddManifestParcelParams) error
	FulfilmentAddPickItem(ctx context.Context, arg FulfilmentAddPickItemParams) (FulfilmentPickListItem, error)
	FulfilmentCreateManifest(ctx context.Context, arg FulfilmentCreateManifestParams) (FulfilmentManifest, error)
	FulfilmentCreatePackRecord(ctx context.Context, arg FulfilmentCreatePackRecordParams) (FulfilmentPackRecord, error)
	FulfilmentCreateParcel(ctx context.Context, arg FulfilmentCreateParcelParams) (FulfilmentParcel, error)
	FulfilmentCreatePickList(ctx context.Context, arg FulfilmentCreatePickListParams) (FulfilmentPickList, error)
	FulfilmentCreateShipment(ctx context.Context, arg FulfilmentCreateShipmentParams) (FulfilmentShipment, error)
	FulfilmentExpectedWeight(ctx context.Context, fulfilmentID uuid.UUID) (int32, error)
	FulfilmentGetCarrierByCode(ctx context.Context, code string) (FulfilmentCarrier, error)
	FulfilmentGetManifest(ctx context.Context, id uuid.UUID) (FulfilmentManifest, error)
	FulfilmentGetManifestForUpdate(ctx context.Context, id uuid.UUID) (FulfilmentManifest, error)
	FulfilmentGetParcel(ctx context.Context, id uuid.UUID) (FulfilmentParcel, error)
	FulfilmentGetPickList(ctx context.Context, id uuid.UUID) (FulfilmentPickList, error)
	FulfilmentGetPickListForUpdate(ctx context.Context, id uuid.UUID) (FulfilmentPickList, error)
	FulfilmentInsertSLAEvent(ctx context.Context, arg FulfilmentInsertSLAEventParams) error
	FulfilmentInsertShipmentEvent(ctx context.Context, arg FulfilmentInsertShipmentEventParams) (FulfilmentShipmentEvent, error)
	FulfilmentListCarriers(ctx context.Context) ([]FulfilmentCarrier, error)
	FulfilmentListManifests(ctx context.Context, warehouseID uuid.UUID) ([]FulfilmentManifest, error)
	FulfilmentListPickLists(ctx context.Context, arg FulfilmentListPickListsParams) ([]FulfilmentListPickListsRow, error)
	FulfilmentManifestParcels(ctx context.Context, manifestID uuid.UUID) ([]FulfilmentManifestParcelsRow, error)
	FulfilmentMarkParcelScanned(ctx context.Context, id uuid.UUID) error
	FulfilmentParcelByLabel(ctx context.Context, labelCode string) (FulfilmentParcel, error)
	FulfilmentParcelsForFulfilment(ctx context.Context, fulfilmentID uuid.UUID) ([]FulfilmentParcel, error)
	FulfilmentPickItems(ctx context.Context, pickListID uuid.UUID) ([]FulfilmentPickItemsRow, error)
	FulfilmentPickListOpenItems(ctx context.Context, pickListID uuid.UUID) (int32, error)
	// Conditional: never picks more than ordered.
	FulfilmentScanItem(ctx context.Context, arg FulfilmentScanItemParams) (FulfilmentPickListItem, error)
	FulfilmentSellerSLAStats(ctx context.Context, sellerID uuid.UUID) (FulfilmentSellerSLAStatsRow, error)
	FulfilmentSetPickListStatus(ctx context.Context, arg FulfilmentSetPickListStatusParams) (FulfilmentPickList, error)
	FulfilmentSetShipmentStatus(ctx context.Context, arg FulfilmentSetShipmentStatusParams) (FulfilmentShipment, error)
	FulfilmentShipmentByTracking(ctx context.Context, arg FulfilmentShipmentByTrackingParams) (FulfilmentShipment, error)
	FulfilmentShipmentEvents(ctx context.Context, shipmentID uuid.UUID) ([]FulfilmentShipmentEvent, error)
	FulfilmentShipmentsForFulfilment(ctx context.Context, fulfilmentID uuid.UUID) ([]FulfilmentShipment, error)
	FulfilmentSignManifest(ctx context.Context, arg FulfilmentSignManifestParams) (FulfilmentManifest, error)
	// Lines of a TechShop fulfilment not fully picked yet (packing waits for all of them).
	FulfilmentUnpickedForFulfilment(ctx context.Context, fulfilmentID uuid.UUID) (int32, error)
	FulfilmentUpsertCarrier(ctx context.Context, arg FulfilmentUpsertCarrierParams) (FulfilmentCarrier, error)
	// Fulfilment: waves and pick lists, packing, parcels, manifests, carriers, shipments, seller SLAs
	// (docs/orders-fulfilment.md §4–§5).
	// Paid TechShop-fulfilled lines whose stock was committed in this warehouse and not yet on a pick list.
	FulfilmentWaveCandidates(ctx context.Context, arg FulfilmentWaveCandidatesParams) ([]FulfilmentWaveCandidatesRow, error)
	IdentityAddRolePermissions(ctx context.Context, arg IdentityAddRolePermissionsParams) error
	IdentityAnonymiseUser(ctx context.Context, id uuid.UUID) error
	IdentityBumpCodeAttempts(ctx context.Context, id uuid.UUID) (int16, error)
	IdentityCancelPrivacyRequest(ctx context.Context, arg IdentityCancelPrivacyRequestParams) (int64, error)
	IdentityClearDefaultAddress(ctx context.Context, userID *uuid.UUID) error
	IdentityClearRolePermissions(ctx context.Context, roleID uuid.UUID) error
	IdentityConfirmTOTP(ctx context.Context, arg IdentityConfirmTOTPParams) error
	IdentityConsumeCode(ctx context.Context, id uuid.UUID) error
	IdentityCreateAddress(ctx context.Context, arg IdentityCreateAddressParams) (IdentityAddress, error)
	IdentityCreateCode(ctx context.Context, arg IdentityCreateCodeParams) (IdentityVerificationCode, error)
	IdentityCreateInvite(ctx context.Context, arg IdentityCreateInviteParams) (IdentityStaffInvite, error)
	IdentityCreatePrivacyRequest(ctx context.Context, arg IdentityCreatePrivacyRequestParams) (IdentityPrivacyRequest, error)
	IdentityCreateSession(ctx context.Context, arg IdentityCreateSessionParams) (IdentityUserSession, error)
	IdentityCreateStaffMember(ctx context.Context, arg IdentityCreateStaffMemberParams) (IdentityStaffMember, error)
	IdentityCreateUser(ctx context.Context, arg IdentityCreateUserParams) (IdentityUser, error)
	IdentityDeleteAddress(ctx context.Context, arg IdentityDeleteAddressParams) (int64, error)
	IdentityDeleteRecoveryCodes(ctx context.Context, userID uuid.UUID) error
	IdentityDeleteTOTP(ctx context.Context, userID uuid.UUID) error
	IdentityDuePrivacyDeletions(ctx context.Context) ([]IdentityPrivacyRequest, error)
	IdentityGetAddress(ctx context.Context, arg IdentityGetAddressParams) (IdentityAddress, error)
	IdentityGetCode(ctx context.Context, id uuid.UUID) (IdentityVerificationCode, error)
	IdentityGetInvite(ctx context.Context, tokenHash []byte) (IdentityStaffInvite, error)
	IdentityGetRoleByKey(ctx context.Context, key string) (IdentityRole, error)
	IdentityGetServiceClient(ctx context.Context, name string) (IdentityServiceClient, error)
	IdentityGetSession(ctx context.Context, id uuid.UUID) (IdentityUserSession, error)
	IdentityGetSessionByToken(ctx context.Context, refreshTokenHash []byte) (IdentityUserSession, error)
	IdentityGetStaffMember(ctx context.Context, userID uuid.UUID) (IdentityStaffMember, error)
	IdentityGetTOTPFactor(ctx context.Context, userID uuid.UUID) (IdentityUserMfaFactor, error)
	// Identity & access queries (docs/identity-access.md).
	IdentityGetUser(ctx context.Context, id uuid.UUID) (IdentityUser, error)
	IdentityGetUserByEmail(ctx context.Context, email *string) (IdentityUser, error)
	IdentityGetUserByPhone(ctx context.Context, phone *string) (IdentityUser, error)
	IdentityGrantRole(ctx context.Context, arg IdentityGrantRoleParams) error
	IdentityHasConsent(ctx context.Context, arg IdentityHasConsentParams) (bool, error)
	IdentityHasDeviceSession(ctx context.Context, arg IdentityHasDeviceSessionParams) (bool, error)
	IdentityInsertAuthEvent(ctx context.Context, arg IdentityInsertAuthEventParams) error
	IdentityInsertConsent(ctx context.Context, arg IdentityInsertConsentParams) error
	IdentityInsertRecoveryCode(ctx context.Context, arg IdentityInsertRecoveryCodeParams) error
	IdentityLatestConsents(ctx context.Context, arg IdentityLatestConsentsParams) ([]IdentityLatestConsentsRow, error)
	// One row per device (the newest token of each family).
	IdentityListActiveSessions(ctx context.Context, userID uuid.UUID) ([]IdentityListActiveSessionsRow, error)
	IdentityListAddresses(ctx context.Context, userID *uuid.UUID) ([]IdentityAddress, error)
	IdentityListAuthEvents(ctx context.Context, arg IdentityListAuthEventsParams) ([]IdentityAuthEvent, error)
	IdentityListPermissions(ctx context.Context) ([]IdentityPermission, error)
	IdentityListPrivacyRequests(ctx context.Context, userID uuid.UUID) ([]IdentityPrivacyRequest, error)
	IdentityListRoles(ctx context.Context) ([]IdentityListRolesRow, error)
	IdentityListStaffMembers(ctx context.Context) ([]IdentityListStaffMembersRow, error)
	IdentityListStates(ctx context.Context) ([]IdentityNigerianState, error)
	IdentityListUsers(ctx context.Context, arg IdentityListUsersParams) ([]IdentityUser, error)
	IdentityMarkPhoneVerified(ctx context.Context, id uuid.UUID) error
	IdentityMarkSessionReplaced(ctx context.Context, arg IdentityMarkSessionReplacedParams) error
	// Read-only summary of what an account may act as (documented cross-module read for /me).
	IdentityMemberships(ctx context.Context, userID uuid.UUID) (IdentityMembershipsRow, error)
	IdentityRevokeAllRoles(ctx context.Context, userID uuid.UUID) (int64, error)
	IdentityRevokeAllSessions(ctx context.Context, arg IdentityRevokeAllSessionsParams) (int64, error)
	IdentityRevokeFamily(ctx context.Context, arg IdentityRevokeFamilyParams) (int64, error)
	IdentityRevokeOtherSessions(ctx context.Context, arg IdentityRevokeOtherSessionsParams) (int64, error)
	IdentityRevokeRole(ctx context.Context, arg IdentityRevokeRoleParams) (int64, error)
	IdentityRevokeSession(ctx context.Context, arg IdentityRevokeSessionParams) (int64, error)
	// Dev seed only: a confirmed authenticator for a seeded staff account.
	IdentitySeedTOTP(ctx context.Context, arg IdentitySeedTOTPParams) error
	IdentitySessionActive(ctx context.Context, id uuid.UUID) (bool, error)
	IdentitySetDefaultAddress(ctx context.Context, arg IdentitySetDefaultAddressParams) (int64, error)
	IdentitySetPassword(ctx context.Context, arg IdentitySetPasswordParams) error
	IdentitySetPhone(ctx context.Context, arg IdentitySetPhoneParams) error
	IdentitySetPrivacyRequestStatus(ctx context.Context, arg IdentitySetPrivacyRequestStatusParams) error
	IdentitySetSessionMFA(ctx context.Context, familyID uuid.UUID) error
	IdentitySetStaffStatus(ctx context.Context, arg IdentitySetStaffStatusParams) error
	IdentityTouchLogin(ctx context.Context, id uuid.UUID) error
	IdentityUpdateAddress(ctx context.Context, arg IdentityUpdateAddressParams) (IdentityAddress, error)
	IdentityUpdateProfile(ctx context.Context, arg IdentityUpdateProfileParams) (IdentityUser, error)
	IdentityUpsertPendingTOTP(ctx context.Context, arg IdentityUpsertPendingTOTPParams) (IdentityUserMfaFactor, error)
	IdentityUpsertPermission(ctx context.Context, arg IdentityUpsertPermissionParams) error
	IdentityUpsertRole(ctx context.Context, arg IdentityUpsertRoleParams) (IdentityRole, error)
	IdentityUpsertServiceClient(ctx context.Context, arg IdentityUpsertServiceClientParams) error
	IdentityUseInvite(ctx context.Context, id uuid.UUID) error
	IdentityUseRecoveryCode(ctx context.Context, arg IdentityUseRecoveryCodeParams) (int64, error)
	// Records the step; fails (0 rows) if this step or a later one was already used (no code reuse).
	IdentityUseTOTPStep(ctx context.Context, arg IdentityUseTOTPStepParams) (int64, error)
	// RBAC
	IdentityUserPermissionKeys(ctx context.Context, userID uuid.UUID) ([]string, error)
	IdentityUsersWithRole(ctx context.Context, roleID uuid.UUID) ([]uuid.UUID, error)
	InventoryAddCountLine(ctx context.Context, arg InventoryAddCountLineParams) (InventoryInventoryCountLine, error)
	InventoryAddTransferLine(ctx context.Context, arg InventoryAddTransferLineParams) (InventoryStockTransferLine, error)
	// Changes on_hand (never below zero, never below reserved) and returns the new level.
	InventoryApplyMovement(ctx context.Context, arg InventoryApplyMovementParams) (InventoryInventoryLevel, error)
	// On payment: the reserved units leave stock (on_hand and reserved both drop).
	InventoryCommitWarehouseReservation(ctx context.Context, arg InventoryCommitWarehouseReservationParams) error
	InventoryCountLines(ctx context.Context, countID uuid.UUID) ([]InventoryInventoryCountLine, error)
	InventoryCreateCount(ctx context.Context, arg InventoryCreateCountParams) (InventoryInventoryCount, error)
	InventoryCreateDeviceUnit(ctx context.Context, arg InventoryCreateDeviceUnitParams) (InventoryDeviceUnit, error)
	InventoryCreateTransfer(ctx context.Context, arg InventoryCreateTransferParams) (InventoryStockTransfer, error)
	InventoryCreateWarehouse(ctx context.Context, arg InventoryCreateWarehouseParams) (InventoryWarehouse, error)
	InventoryExpiredReservationOrders(ctx context.Context) ([]uuid.UUID, error)
	InventoryGetCount(ctx context.Context, id uuid.UUID) (InventoryInventoryCount, error)
	InventoryGetDeviceUnit(ctx context.Context, id uuid.UUID) (InventoryDeviceUnit, error)
	InventoryGetDeviceUnitBySerial(ctx context.Context, imei *string) (InventoryDeviceUnit, error)
	InventoryGetTransfer(ctx context.Context, id uuid.UUID) (InventoryStockTransfer, error)
	InventoryGetWarehouse(ctx context.Context, id uuid.UUID) (InventoryWarehouse, error)
	InventoryGetWarehouseByCode(ctx context.Context, code string) (InventoryWarehouse, error)
	InventoryInsertMovement(ctx context.Context, arg InventoryInsertMovementParams) (InventoryStockMovement, error)
	InventoryInsertReservation(ctx context.Context, arg InventoryInsertReservationParams) (InventoryStockReservation, error)
	// Nightly check: levels whose on_hand differs from the sum of their movements.
	InventoryIntegrityDrift(ctx context.Context) ([]InventoryIntegrityDriftRow, error)
	InventoryIsBlocklisted(ctx context.Context, imei string) (bool, error)
	InventoryListDeviceUnits(ctx context.Context, arg InventoryListDeviceUnitsParams) ([]InventoryDeviceUnit, error)
	InventoryListLevels(ctx context.Context, arg InventoryListLevelsParams) ([]InventoryListLevelsRow, error)
	InventoryListMovements(ctx context.Context, arg InventoryListMovementsParams) ([]InventoryStockMovement, error)
	// Inventory: the single stock code path, reservations, device units, transfers, counts, costs.
	// Plan: docs/orders-fulfilment.md §3, §5, §9.
	InventoryListWarehouses(ctx context.Context) ([]InventoryWarehouse, error)
	InventoryOrderReservations(ctx context.Context, orderID uuid.UUID) ([]InventoryStockReservation, error)
	InventoryReleaseSellerStock(ctx context.Context, arg InventoryReleaseSellerStockParams) error
	InventoryReleaseWarehouseReservation(ctx context.Context, arg InventoryReleaseWarehouseReservationParams) error
	// Seller-held stock: conditional decrement of the listing's stock counter.
	InventoryReserveSellerStock(ctx context.Context, arg InventoryReserveSellerStockParams) (*int32, error)
	// Race-free reservation: only succeeds if enough unreserved stock exists in one row.
	InventoryReserveWarehouse(ctx context.Context, arg InventoryReserveWarehouseParams) (uuid.UUID, error)
	InventorySetCountStatus(ctx context.Context, arg InventorySetCountStatusParams) (InventoryInventoryCount, error)
	InventorySetDeviceUnitStatus(ctx context.Context, arg InventorySetDeviceUnitStatusParams) (InventoryDeviceUnit, error)
	InventorySetReservationStatus(ctx context.Context, arg InventorySetReservationStatusParams) error
	InventorySetTransferStatus(ctx context.Context, arg InventorySetTransferStatusParams) (InventoryStockTransfer, error)
	InventoryTransferLines(ctx context.Context, transferID uuid.UUID) ([]InventoryStockTransferLine, error)
	InventoryUpsertCost(ctx context.Context, arg InventoryUpsertCostParams) error
	LogisticsAddRiderZone(ctx context.Context, arg LogisticsAddRiderZoneParams) error
	LogisticsApproveDevice(ctx context.Context, arg LogisticsApproveDeviceParams) (LogisticsRiderDevice, error)
	LogisticsAssignJob(ctx context.Context, arg LogisticsAssignJobParams) (LogisticsDeliveryJob, error)
	LogisticsBoard(ctx context.Context, arg LogisticsBoardParams) ([]LogisticsBoardRow, error)
	LogisticsBoardCounts(ctx context.Context) (LogisticsBoardCountsRow, error)
	LogisticsCreateJob(ctx context.Context, arg LogisticsCreateJobParams) (LogisticsDeliveryJob, error)
	LogisticsCreateRate(ctx context.Context, arg LogisticsCreateRateParams) (LogisticsDeliveryRate, error)
	LogisticsCreateRider(ctx context.Context, arg LogisticsCreateRiderParams) (LogisticsRider, error)
	LogisticsCreateZone(ctx context.Context, arg LogisticsCreateZoneParams) (LogisticsDeliveryZone, error)
	LogisticsDeviceApproved(ctx context.Context, arg LogisticsDeviceApprovedParams) (bool, error)
	LogisticsEnRouteJobs(ctx context.Context, riderID *uuid.UUID) ([]LogisticsEnRouteJobsRow, error)
	LogisticsEndShift(ctx context.Context, riderID uuid.UUID) (LogisticsRiderShift, error)
	// Everything needed to create a delivery job for a packed fulfilment.
	LogisticsFulfilmentDeliveryInfo(ctx context.Context, id uuid.UUID) (LogisticsFulfilmentDeliveryInfoRow, error)
	LogisticsGetJob(ctx context.Context, id uuid.UUID) (LogisticsDeliveryJob, error)
	LogisticsGetJobForUpdate(ctx context.Context, id uuid.UUID) (LogisticsDeliveryJob, error)
	LogisticsGetRider(ctx context.Context, userID uuid.UUID) (LogisticsRider, error)
	// Idempotent per client_event_id (offline sync): a replay returns no row.
	LogisticsInsertEvent(ctx context.Context, arg LogisticsInsertEventParams) (LogisticsDeliveryEvent, error)
	LogisticsInsertPing(ctx context.Context, arg LogisticsInsertPingParams) error
	LogisticsJobEvents(ctx context.Context, deliveryJobID uuid.UUID) ([]LogisticsDeliveryEvent, error)
	LogisticsJobForFulfilment(ctx context.Context, fulfilmentID *uuid.UUID) (LogisticsDeliveryJob, error)
	LogisticsJobView(ctx context.Context, id uuid.UUID) (LogisticsJobViewRow, error)
	LogisticsListDevices(ctx context.Context, pending *bool) ([]LogisticsListDevicesRow, error)
	// Riders with their latest position, open shift and active job count (for the assign sheet and map).
	LogisticsListRiders(ctx context.Context) ([]LogisticsListRidersRow, error)
	// Logistics: zones, rates, riders, devices, shifts, delivery jobs, events, locations (docs/mobile.md §4).
	LogisticsListZones(ctx context.Context) ([]LogisticsDeliveryZone, error)
	LogisticsOTPFailed(ctx context.Context, id uuid.UUID) (int16, error)
	LogisticsOTPVerified(ctx context.Context, id uuid.UUID) error
	LogisticsOpenShift(ctx context.Context, riderID uuid.UUID) (LogisticsRiderShift, error)
	// Raw location points are kept about 90 days (docs/mobile.md §4.4).
	LogisticsPurgePings(ctx context.Context) (int64, error)
	// The current rate band for a parcel: the smallest weight band that fits, newest valid version.
	LogisticsRate(ctx context.Context, arg LogisticsRateParams) (LogisticsDeliveryRate, error)
	LogisticsRegisterDevice(ctx context.Context, arg LogisticsRegisterDeviceParams) (LogisticsRiderDevice, error)
	// The zone for a state and LGA: an LGA-specific zone first, then the state-wide zone (no LGAs listed).
	LogisticsResolveZone(ctx context.Context, arg LogisticsResolveZoneParams) (LogisticsDeliveryZone, error)
	LogisticsRevokeDevice(ctx context.Context, id uuid.UUID) (LogisticsRiderDevice, error)
	// A rider's work: active jobs plus today's finished ones, with what the job screen needs.
	LogisticsRiderJobs(ctx context.Context, riderID *uuid.UUID) ([]LogisticsRiderJobsRow, error)
	LogisticsSetJobOTP(ctx context.Context, arg LogisticsSetJobOTPParams) error
	LogisticsSetJobStatus(ctx context.Context, arg LogisticsSetJobStatusParams) (LogisticsDeliveryJob, error)
	LogisticsSetRiderStatus(ctx context.Context, arg LogisticsSetRiderStatusParams) error
	LogisticsSetRiderZones(ctx context.Context, riderID uuid.UUID) error
	// Shifts open for more than 12 hours are closed automatically (location tracking stops).
	LogisticsStaleShifts(ctx context.Context) ([]LogisticsRiderShift, error)
	LogisticsStartShift(ctx context.Context, arg LogisticsStartShiftParams) (LogisticsRiderShift, error)
	LogisticsUnassignJob(ctx context.Context, id uuid.UUID) (LogisticsDeliveryJob, error)
	LogisticsUpdateZone(ctx context.Context, arg LogisticsUpdateZoneParams) (LogisticsDeliveryZone, error)
	LogisticsUpsertLocation(ctx context.Context, arg LogisticsUpsertLocationParams) error
	LogisticsZoneRates(ctx context.Context, zoneID uuid.UUID) ([]LogisticsDeliveryRate, error)
	// Signed-in carts idle for an hour with items, not yet enrolled in the abandoned-cart journey.
	MarketingAbandonedCarts(ctx context.Context) ([]MarketingAbandonedCartsRow, error)
	MarketingActiveJourneysByTrigger(ctx context.Context, trigger string) ([]MarketingJourney, error)
	MarketingAddJourneyStep(ctx context.Context, arg MarketingAddJourneyStepParams) (MarketingJourneyStep, error)
	MarketingAddTarget(ctx context.Context, arg MarketingAddTargetParams) (MarketingPromotionTarget, error)
	MarketingAddVariant(ctx context.Context, arg MarketingAddVariantParams) (MarketingCampaignVariant, error)
	MarketingAdvanceEnrollment(ctx context.Context, arg MarketingAdvanceEnrollmentParams) error
	// Scheduled promotions go live at starts_at; live ones end at ends_at (runs every minute).
	MarketingAdvancePromotions(ctx context.Context) ([]MarketingAdvancePromotionsRow, error)
	MarketingCampaignLink(ctx context.Context, campaignID *uuid.UUID) (MarketingTrackedLink, error)
	MarketingCampaignNotification(ctx context.Context, arg MarketingCampaignNotificationParams) (uuid.UUID, error)
	MarketingCampaignStats(ctx context.Context, campaignID *uuid.UUID) (MarketingCampaignStatsRow, error)
	MarketingCampaignVariants(ctx context.Context, campaignID uuid.UUID) ([]MarketingCampaignVariant, error)
	MarketingCartStillActive(ctx context.Context, userID *uuid.UUID) (bool, error)
	// A category and its parents (a promotion on "Phones" covers "Phones › Android").
	MarketingCategoryAncestors(ctx context.Context, id uuid.UUID) ([]uuid.UUID, error)
	// Concurrency-safe: claimed never exceeds stock_limit (a 0-row result means sold out).
	MarketingClaimFlash(ctx context.Context, arg MarketingClaimFlashParams) (MarketingClaimFlashRow, error)
	MarketingCreateCampaign(ctx context.Context, arg MarketingCreateCampaignParams) (MarketingCampaign, error)
	MarketingCreateCoupon(ctx context.Context, arg MarketingCreateCouponParams) (MarketingCoupon, error)
	MarketingCreateCouponCode(ctx context.Context, arg MarketingCreateCouponCodeParams) (MarketingCouponCode, error)
	MarketingCreateJourney(ctx context.Context, arg MarketingCreateJourneyParams) (MarketingJourney, error)
	MarketingCreateLink(ctx context.Context, arg MarketingCreateLinkParams) (MarketingTrackedLink, error)
	// Marketing: promotions, flash deals, coupons, segments, campaigns, journeys, tracked links
	// (docs/messaging-marketing.md §4, docs/backend.md §4.4).
	MarketingCreatePromotion(ctx context.Context, arg MarketingCreatePromotionParams) (MarketingPromotion, error)
	MarketingCreateSegment(ctx context.Context, arg MarketingCreateSegmentParams) (MarketingSegment, error)
	MarketingDecrementCoupon(ctx context.Context, id uuid.UUID) error
	MarketingDueCampaigns(ctx context.Context) ([]MarketingCampaign, error)
	MarketingDueEnrollments(ctx context.Context) ([]MarketingDueEnrollmentsRow, error)
	MarketingEnroll(ctx context.Context, arg MarketingEnrollParams) (MarketingJourneyEnrollment, error)
	// Resolve a typed code: a shared coupon code, or a unique single-use code.
	MarketingFindCoupon(ctx context.Context, code string) (MarketingFindCouponRow, error)
	MarketingFinishEnrollment(ctx context.Context, arg MarketingFinishEnrollmentParams) error
	MarketingGetCampaign(ctx context.Context, id uuid.UUID) (MarketingCampaign, error)
	MarketingGetCampaignForUpdate(ctx context.Context, id uuid.UUID) (MarketingCampaign, error)
	MarketingGetJourney(ctx context.Context, id uuid.UUID) (MarketingJourney, error)
	MarketingGetLink(ctx context.Context, id uuid.UUID) (MarketingTrackedLink, error)
	MarketingGetPromotion(ctx context.Context, id uuid.UUID) (MarketingPromotion, error)
	MarketingGetSegment(ctx context.Context, id uuid.UUID) (MarketingSegment, error)
	// A goal event (e.g. order placed) exits that person from journeys waiting for it.
	MarketingGoalReached(ctx context.Context, arg MarketingGoalReachedParams) error
	// Concurrency-safe counter: never passes max_redemptions.
	MarketingIncrementCoupon(ctx context.Context, id uuid.UUID) (int32, error)
	MarketingInsertFlashClaim(ctx context.Context, arg MarketingInsertFlashClaimParams) error
	MarketingInsertRecipient(ctx context.Context, arg MarketingInsertRecipientParams) error
	MarketingInsertRedemption(ctx context.Context, arg MarketingInsertRedemptionParams) error
	MarketingJourneyStats(ctx context.Context, journeyID uuid.UUID) ([]MarketingJourneyStatsRow, error)
	MarketingJourneySteps(ctx context.Context, journeyID uuid.UUID) ([]MarketingJourneyStep, error)
	// Attribution: the latest marketing message this person clicked within the window.
	MarketingLastClick(ctx context.Context, arg MarketingLastClickParams) (uuid.UUID, error)
	MarketingListCampaigns(ctx context.Context, limit int32) ([]MarketingCampaign, error)
	MarketingListCoupons(ctx context.Context, limit int32) ([]MarketingListCouponsRow, error)
	MarketingListJourneys(ctx context.Context) ([]MarketingJourney, error)
	MarketingListPromotions(ctx context.Context, arg MarketingListPromotionsParams) ([]MarketingPromotion, error)
	MarketingListSegments(ctx context.Context) ([]MarketingSegment, error)
	// Live automatic promotions (not coupon-only, not flash) with their targets; empty targets = sitewide.
	MarketingLiveAutoPromotions(ctx context.Context) ([]MarketingLiveAutoPromotionsRow, error)
	MarketingOrderedSince(ctx context.Context, arg MarketingOrderedSinceParams) (bool, error)
	MarketingPendingRecipients(ctx context.Context, arg MarketingPendingRecipientsParams) ([]MarketingPendingRecipientsRow, error)
	MarketingPromotionListingPrices(ctx context.Context, promotionID uuid.UUID) ([]MarketingPromotionListingPrice, error)
	MarketingPromotionTargets(ctx context.Context, promotionID uuid.UUID) ([]MarketingPromotionTarget, error)
	MarketingPromotionTargetsFor(ctx context.Context, promotionID uuid.UUID) (MarketingPromotionTargetsForRow, error)
	// Re-entry guard: was this person in the journey within reentry_days?
	MarketingRecentlyEnrolled(ctx context.Context, arg MarketingRecentlyEnrolledParams) (bool, error)
	MarketingRedeemCode(ctx context.Context, id uuid.UUID) (int64, error)
	// Cancellation gives flash units back to the pool.
	MarketingReleaseFlashClaims(ctx context.Context, orderID uuid.UUID) ([]MarketingReleaseFlashClaimsRow, error)
	MarketingReleaseRedemption(ctx context.Context, orderID uuid.UUID) (MarketingCouponRedemption, error)
	MarketingSetCampaignStatus(ctx context.Context, arg MarketingSetCampaignStatusParams) (MarketingCampaign, error)
	MarketingSetEnrollmentContext(ctx context.Context, arg MarketingSetEnrollmentContextParams) error
	MarketingSetJourneyStatus(ctx context.Context, arg MarketingSetJourneyStatusParams) (MarketingJourney, error)
	MarketingSetListingPrice(ctx context.Context, arg MarketingSetListingPriceParams) (MarketingPromotionListingPrice, error)
	MarketingSetPromotionStatus(ctx context.Context, arg MarketingSetPromotionStatusParams) (MarketingPromotion, error)
	MarketingSetRecipientStatus(ctx context.Context, arg MarketingSetRecipientStatusParams) error
	MarketingSetSegmentCount(ctx context.Context, arg MarketingSetSegmentCountParams) error
	MarketingUnredeemCode(ctx context.Context, id uuid.UUID) error
	MarketingUpdatePromotion(ctx context.Context, arg MarketingUpdatePromotionParams) (MarketingPromotion, error)
	MarketingUserContact(ctx context.Context, id uuid.UUID) (MarketingUserContactRow, error)
	MarketingUserFlashClaimed(ctx context.Context, arg MarketingUserFlashClaimedParams) (int32, error)
	MarketingUserRedemptions(ctx context.Context, arg MarketingUserRedemptionsParams) (int32, error)
	MessagingActivePushTokens(ctx context.Context, arg MessagingActivePushTokensParams) ([]MessagingPushToken, error)
	MessagingAddTemplateVersion(ctx context.Context, arg MessagingAddTemplateVersionParams) (MessagingTemplateVersion, error)
	MessagingCountMarketingToday(ctx context.Context, arg MessagingCountMarketingTodayParams) (int32, error)
	MessagingCreateTemplate(ctx context.Context, arg MessagingCreateTemplateParams) (MessagingMessageTemplate, error)
	// Development only: recent messages to an address, so tests and local dev can read codes.
	MessagingDevRecent(ctx context.Context, payload json.RawMessage) ([]MessagingDevRecentRow, error)
	MessagingGetNotification(ctx context.Context, id uuid.UUID) (MessagingNotification, error)
	MessagingGetPreferences(ctx context.Context, userID uuid.UUID) ([]MessagingNotificationPreference, error)
	MessagingGetSettings(ctx context.Context, userID uuid.UUID) (MessagingNotificationSetting, error)
	MessagingGetTemplateVersion(ctx context.Context, id uuid.UUID) (MessagingTemplateVersion, error)
	MessagingInsertEvent(ctx context.Context, arg MessagingInsertEventParams) error
	// Messaging queries (docs/messaging-marketing.md §3, §5–§6).
	MessagingInsertNotification(ctx context.Context, arg MessagingInsertNotificationParams) (MessagingNotification, error)
	MessagingIsSuppressed(ctx context.Context, arg MessagingIsSuppressedParams) (bool, error)
	MessagingListInbox(ctx context.Context, arg MessagingListInboxParams) ([]MessagingNotification, error)
	MessagingListSuppressions(ctx context.Context, limit int32) ([]MessagingMessageSuppression, error)
	MessagingListTemplates(ctx context.Context) ([]MessagingListTemplatesRow, error)
	MessagingMarkAllRead(ctx context.Context, userID *uuid.UUID) (int64, error)
	MessagingMarkClicked(ctx context.Context, id uuid.UUID) error
	MessagingMarkDeliveredByProvider(ctx context.Context, arg MessagingMarkDeliveredByProviderParams) (uuid.UUID, error)
	MessagingMarkFailed(ctx context.Context, arg MessagingMarkFailedParams) error
	MessagingMarkRead(ctx context.Context, arg MessagingMarkReadParams) (int64, error)
	MessagingMarkSent(ctx context.Context, arg MessagingMarkSentParams) error
	MessagingMarkSkipped(ctx context.Context, arg MessagingMarkSkippedParams) error
	MessagingReschedule(ctx context.Context, arg MessagingRescheduleParams) error
	MessagingRevokePushToken(ctx context.Context, token string) error
	MessagingRevokeUserPushTokens(ctx context.Context, userID uuid.UUID) error
	MessagingSetPreference(ctx context.Context, arg MessagingSetPreferenceParams) error
	MessagingSuppress(ctx context.Context, arg MessagingSuppressParams) error
	MessagingTrimBodies(ctx context.Context) (int64, error)
	MessagingUnreadCount(ctx context.Context, userID *uuid.UUID) (int32, error)
	MessagingUpsertPushToken(ctx context.Context, arg MessagingUpsertPushTokenParams) (MessagingPushToken, error)
	MessagingUpsertSettings(ctx context.Context, arg MessagingUpsertSettingsParams) (MessagingNotificationSetting, error)
	PaymentsCountForOrder(ctx context.Context, orderID *uuid.UUID) (int32, error)
	// Payments: charges, provider events, refunds, provider health, reconciliation (docs/payments-finance.md).
	PaymentsCreate(ctx context.Context, arg PaymentsCreateParams) (PaymentsPayment, error)
	PaymentsCreateException(ctx context.Context, arg PaymentsCreateExceptionParams) (PaymentsReconciliationException, error)
	PaymentsCreateRefund(ctx context.Context, arg PaymentsCreateRefundParams) (PaymentsRefund, error)
	PaymentsCreateVirtualAccount(ctx context.Context, arg PaymentsCreateVirtualAccountParams) (PaymentsVirtualAccount, error)
	PaymentsCustomerRefunds(ctx context.Context, customerUserID *uuid.UUID) ([]PaymentsCustomerRefundsRow, error)
	// Development fake provider: its "server state" is the last signed charge event it sent.
	PaymentsFakeLatestCharge(ctx context.Context, arg PaymentsFakeLatestChargeParams) (json.RawMessage, error)
	PaymentsForOrder(ctx context.Context, orderID *uuid.UUID) ([]PaymentsPayment, error)
	PaymentsGet(ctx context.Context, id uuid.UUID) (PaymentsPayment, error)
	PaymentsGetByAnyReference(ctx context.Context, providerReference *string) (PaymentsPayment, error)
	PaymentsGetByReference(ctx context.Context, arg PaymentsGetByReferenceParams) (PaymentsPayment, error)
	PaymentsGetEvent(ctx context.Context, id uuid.UUID) (PaymentsPaymentEvent, error)
	PaymentsGetForUpdate(ctx context.Context, id uuid.UUID) (PaymentsPayment, error)
	PaymentsGetHealth(ctx context.Context) ([]PaymentsProviderHealth, error)
	PaymentsGetRefund(ctx context.Context, id uuid.UUID) (PaymentsRefund, error)
	PaymentsGetRefundForUpdate(ctx context.Context, id uuid.UUID) (PaymentsRefund, error)
	PaymentsInsertEvent(ctx context.Context, arg PaymentsInsertEventParams) (uuid.UUID, error)
	PaymentsLatestForOrder(ctx context.Context, orderID *uuid.UUID) (PaymentsPayment, error)
	PaymentsListExceptions(ctx context.Context, arg PaymentsListExceptionsParams) ([]PaymentsReconciliationException, error)
	PaymentsListRefunds(ctx context.Context, arg PaymentsListRefundsParams) ([]PaymentsListRefundsRow, error)
	PaymentsMarkEventProcessed(ctx context.Context, arg PaymentsMarkEventProcessedParams) error
	PaymentsOrderRefunds(ctx context.Context, orderID uuid.UUID) ([]PaymentsRefund, error)
	PaymentsOrderWithCustomer(ctx context.Context, id uuid.UUID) (PaymentsOrderWithCustomerRow, error)
	// Circuit breaker: 5 failures in a row open the breaker for this provider.
	PaymentsRecordFailure(ctx context.Context, provider string) (PaymentsProviderHealth, error)
	PaymentsRecordSuccess(ctx context.Context, provider string) error
	// Money already committed to refunds of a payment's order total (anything not rejected or
	// failed). Excess-payment refunds are money on top of the total, so they don't count.
	PaymentsRefundedTotal(ctx context.Context, paymentID uuid.UUID) (int64, error)
	PaymentsResolveException(ctx context.Context, arg PaymentsResolveExceptionParams) (PaymentsReconciliationException, error)
	PaymentsSetOpened(ctx context.Context, arg PaymentsSetOpenedParams) (PaymentsPayment, error)
	PaymentsSetRefundStatus(ctx context.Context, arg PaymentsSetRefundStatusParams) (PaymentsRefund, error)
	PaymentsSetStatus(ctx context.Context, arg PaymentsSetStatusParams) (PaymentsPayment, error)
	PaymentsSetVirtualAccountStatus(ctx context.Context, arg PaymentsSetVirtualAccountStatusParams) error
	// The sweep re-verifies pending payments older than the threshold, so a missed webhook never strands an order.
	PaymentsStalePending(ctx context.Context, createdAt time.Time) ([]PaymentsPayment, error)
	PaymentsSucceededForOrder(ctx context.Context, orderID *uuid.UUID) (PaymentsPayment, error)
	PaymentsVirtualAccountForOrder(ctx context.Context, orderID *uuid.UUID) (PaymentsVirtualAccount, error)
	// Behaviour events and identity links (docs/recommendations.md; consent-gated).
	PersonalisationInsertEvent(ctx context.Context, arg []PersonalisationInsertEventParams) (int64, error)
	PersonalisationLinkIdentity(ctx context.Context, arg PersonalisationLinkIdentityParams) error
	PlatformCompleteIdempotencyKey(ctx context.Context, arg PlatformCompleteIdempotencyKeyParams) error
	PlatformCountRateLimit(ctx context.Context, arg PlatformCountRateLimitParams) (int32, error)
	PlatformCreateFile(ctx context.Context, arg PlatformCreateFileParams) (PlatformFile, error)
	PlatformDeleteExpiredIdempotencyKeys(ctx context.Context) (int64, error)
	PlatformDeleteOldRateLimits(ctx context.Context) (int64, error)
	PlatformGetFeatureFlag(ctx context.Context, key string) (PlatformFeatureFlag, error)
	PlatformGetFile(ctx context.Context, id uuid.UUID) (PlatformFile, error)
	PlatformGetIdempotencyKey(ctx context.Context, arg PlatformGetIdempotencyKeyParams) (PlatformIdempotencyKey, error)
	// Atomically counts one hit in the window and returns the new count.
	PlatformHitRateLimit(ctx context.Context, arg PlatformHitRateLimitParams) (int32, error)
	PlatformInsertAudit(ctx context.Context, arg PlatformInsertAuditParams) error
	PlatformInsertIdempotencyKey(ctx context.Context, arg PlatformInsertIdempotencyKeyParams) (PlatformIdempotencyKey, error)
	PlatformInsertOutboxEvent(ctx context.Context, arg PlatformInsertOutboxEventParams) error
	PlatformListAudit(ctx context.Context, arg PlatformListAuditParams) ([]PlatformAuditLog, error)
	PlatformListFeatureFlags(ctx context.Context) ([]PlatformFeatureFlag, error)
	PlatformListJobsSummary(ctx context.Context) ([]PlatformListJobsSummaryRow, error)
	PlatformListPublicHolidays(ctx context.Context, arg PlatformListPublicHolidaysParams) ([]PlatformPublicHoliday, error)
	PlatformLockUnpublishedEvents(ctx context.Context, limit int32) ([]PlatformLockUnpublishedEventsRow, error)
	PlatformMarkEventsPublished(ctx context.Context, ids []int64) error
	PlatformMarkFileReady(ctx context.Context, arg PlatformMarkFileReadyParams) (PlatformFile, error)
	PlatformOutboxLag(ctx context.Context) (PlatformOutboxLagRow, error)
	// Platform queries: outbox, audit log, idempotency keys, rate limits, feature flags, files.
	PlatformPing(ctx context.Context) (int32, error)
	PlatformReleaseIdempotencyKey(ctx context.Context, arg PlatformReleaseIdempotencyKeyParams) error
	PlatformSetFeatureFlag(ctx context.Context, arg PlatformSetFeatureFlagParams) (PlatformFeatureFlag, error)
	// The exact device sold (IMEI/serial), bound when the unit is picked.
	SalesBindDeviceUnit(ctx context.Context, arg SalesBindDeviceUnitParams) (SalesOrderLine, error)
	SalesCancelLine(ctx context.Context, arg SalesCancelLineParams) (SalesOrderLine, error)
	// Cart lines with live prices and everything pricing and checkout need.
	SalesCartLines(ctx context.Context, cartID uuid.UUID) ([]SalesCartLinesRow, error)
	SalesClearCart(ctx context.Context, cartID uuid.UUID) error
	// Seller-specific rule, then category rule, then the seller override, then the configured default.
	SalesCommissionBps(ctx context.Context, arg SalesCommissionBpsParams) (int32, error)
	// Commission owed on a delivered fulfilment: Σ line total × the line's snapshot rate.
	SalesCommissionForFulfilment(ctx context.Context, fulfilmentID uuid.UUID) (int64, error)
	SalesCreateCart(ctx context.Context, arg SalesCreateCartParams) (SalesCart, error)
	SalesCreateFulfilment(ctx context.Context, arg SalesCreateFulfilmentParams) (SalesFulfilment, error)
	SalesCreateLine(ctx context.Context, arg SalesCreateLineParams) (SalesOrderLine, error)
	SalesCreateOrder(ctx context.Context, arg SalesCreateOrderParams) (SalesOrder, error)
	SalesCustomerOrderByNumber(ctx context.Context, arg SalesCustomerOrderByNumberParams) (SalesOrder, error)
	SalesDeleteCartItem(ctx context.Context, arg SalesDeleteCartItemParams) (int64, error)
	SalesFulfilmentLines(ctx context.Context, fulfilmentID uuid.UUID) ([]SalesOrderLine, error)
	SalesGetFulfilment(ctx context.Context, id uuid.UUID) (SalesFulfilment, error)
	SalesGetFulfilmentForUpdate(ctx context.Context, id uuid.UUID) (SalesFulfilment, error)
	SalesGetGuestCart(ctx context.Context, sessionTokenHash []byte) (SalesCart, error)
	SalesGetLine(ctx context.Context, id uuid.UUID) (SalesOrderLine, error)
	SalesGetOrder(ctx context.Context, id uuid.UUID) (SalesOrder, error)
	SalesGetOrderByNumber(ctx context.Context, orderNumber string) (SalesOrder, error)
	SalesGetOrderForUpdate(ctx context.Context, id uuid.UUID) (SalesOrder, error)
	// Sales: carts, orders, fulfilments, lines, status history (docs/orders-fulfilment.md §2).
	SalesGetUserCart(ctx context.Context, userID *uuid.UUID) (SalesCart, error)
	SalesInsertHistory(ctx context.Context, arg SalesInsertHistoryParams) error
	SalesLineReservations(ctx context.Context, orderLineID uuid.UUID) ([]InventoryStockReservation, error)
	SalesListCustomerOrders(ctx context.Context, arg SalesListCustomerOrdersParams) ([]SalesOrder, error)
	// Units that can still be sold for a listing: seller-held stock, or unreserved warehouse stock.
	SalesListingAvailable(ctx context.Context, id uuid.UUID) (int32, error)
	SalesLiveFlashPrice(ctx context.Context, listingID uuid.UUID) (SalesLiveFlashPriceRow, error)
	SalesMergeCartItems(ctx context.Context, arg SalesMergeCartItemsParams) error
	SalesOrderFulfilments(ctx context.Context, orderID uuid.UUID) ([]SalesOrderFulfilmentsRow, error)
	SalesOrderHistory(ctx context.Context, orderID uuid.UUID) ([]SalesOrderStatusHistory, error)
	SalesOrderLines(ctx context.Context, orderID uuid.UUID) ([]SalesOrderLine, error)
	SalesPaidOrdersCount(ctx context.Context, customerUserID *uuid.UUID) (int32, error)
	SalesPendingAcceptBreaches(ctx context.Context) ([]SalesPendingAcceptBreachesRow, error)
	SalesSellerFulfilments(ctx context.Context, arg SalesSellerFulfilmentsParams) ([]SalesSellerFulfilmentsRow, error)
	// Was this listing's discount seller-funded when the order was placed? (Seller-funded
	// promotions always target the seller's own listings and never carry coupons.)
	SalesSellerFundedAt(ctx context.Context, arg SalesSellerFundedAtParams) (bool, error)
	SalesSetAttribution(ctx context.Context, arg SalesSetAttributionParams) error
	SalesSetCartItemQuantity(ctx context.Context, arg SalesSetCartItemQuantityParams) (int64, error)
	SalesSetCartStatus(ctx context.Context, arg SalesSetCartStatusParams) error
	SalesSetFulfilmentMethod(ctx context.Context, arg SalesSetFulfilmentMethodParams) error
	SalesSetFulfilmentStatus(ctx context.Context, arg SalesSetFulfilmentStatusParams) (SalesFulfilment, error)
	SalesSetFulfilmentWarehouse(ctx context.Context, arg SalesSetFulfilmentWarehouseParams) error
	SalesSetOrderStatus(ctx context.Context, arg SalesSetOrderStatusParams) (SalesOrder, error)
	SalesStaffListOrders(ctx context.Context, arg SalesStaffListOrdersParams) ([]SalesStaffListOrdersRow, error)
	// Best wholesale tier unit price for a quantity (null when no tier applies).
	SalesTierPrice(ctx context.Context, arg SalesTierPriceParams) (int64, error)
	SalesTouchCart(ctx context.Context, id uuid.UUID) error
	SalesUnpaidExpiredOrders(ctx context.Context) ([]SalesOrder, error)
	SalesUpsertCartItem(ctx context.Context, arg SalesUpsertCartItemParams) (SalesCartItem, error)
	SearchActivePins(ctx context.Context, queryNorm string) ([]SearchSearchPin, error)
	SearchCreatePin(ctx context.Context, arg SearchCreatePinParams) (SearchSearchPin, error)
	SearchCreateSynonym(ctx context.Context, arg SearchCreateSynonymParams) (SearchSearchSynonym, error)
	SearchDeactivateSynonym(ctx context.Context, id uuid.UUID) (int64, error)
	SearchGetRedirect(ctx context.Context, queryNorm string) (SearchSearchRedirect, error)
	SearchListGaps(ctx context.Context) ([]SearchCatalogueGap, error)
	SearchListRedirects(ctx context.Context) ([]SearchSearchRedirect, error)
	// Search merchandising and analytics (docs/search-catalogue.md §4–§5).
	SearchListSynonyms(ctx context.Context) ([]SearchSearchSynonym, error)
	SearchLogQuery(ctx context.Context, arg SearchLogQueryParams) error
	// Nightly: popular queries with results become autocomplete entries keyed by 1–4 letter prefixes.
	SearchRebuildSuggestions(ctx context.Context) error
	SearchStats(ctx context.Context) (SearchStatsRow, error)
	SearchTopQueries(ctx context.Context, limit int32) ([]SearchTopQueriesRow, error)
	SearchUpsertGap(ctx context.Context, arg SearchUpsertGapParams) (SearchCatalogueGap, error)
	SearchUpsertRedirect(ctx context.Context, arg SearchUpsertRedirectParams) (SearchSearchRedirect, error)
	SearchZeroResults(ctx context.Context, limit int32) ([]SearchZeroResultsRow, error)
	SellersAddMember(ctx context.Context, arg SellersAddMemberParams) error
	SellersCreate(ctx context.Context, arg SellersCreateParams) (SellersSeller, error)
	SellersGet(ctx context.Context, id uuid.UUID) (SellersSeller, error)
	SellersGetBySlug(ctx context.Context, slug string) (SellersSeller, error)
	// Sellers (marketplace shops, members, KYC, bank accounts). Plan: trust-safety.md §2.
	SellersGetFirstParty(ctx context.Context) (SellersSeller, error)
}

var _ Querier = (*Queries)(nil)
