// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sales.sql

package store

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

const salesBindDeviceUnit = `-- name: SalesBindDeviceUnit :one
update sales.order_lines set device_unit_id = $2 where id = $1 and device_unit_id is null and quantity = 1 returning id, order_id, fulfilment_id, listing_id, seller_id, variant_id, product_name, variant_name, sku, condition, quantity, unit_price_kobo, discount_kobo, line_total_kobo, vat_kobo, commission_bps, device_unit_id, cancelled_at, created_at
`

type SalesBindDeviceUnitParams struct {
	ID           uuid.UUID  `json:"id"`
	DeviceUnitID *uuid.UUID `json:"deviceUnitId"`
}

// The exact device sold (IMEI/serial), bound when the unit is picked.
func (q *Queries) SalesBindDeviceUnit(ctx context.Context, arg SalesBindDeviceUnitParams) (SalesOrderLine, error) {
	row := q.db.QueryRow(ctx, salesBindDeviceUnit, arg.ID, arg.DeviceUnitID)
	var i SalesOrderLine
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.FulfilmentID,
		&i.ListingID,
		&i.SellerID,
		&i.VariantID,
		&i.ProductName,
		&i.VariantName,
		&i.Sku,
		&i.Condition,
		&i.Quantity,
		&i.UnitPriceKobo,
		&i.DiscountKobo,
		&i.LineTotalKobo,
		&i.VatKobo,
		&i.CommissionBps,
		&i.DeviceUnitID,
		&i.CancelledAt,
		&i.CreatedAt,
	)
	return i, err
}

const salesCancelLine = `-- name: SalesCancelLine :one
update sales.order_lines set cancelled_at = now() where id = $1 and order_id = $2 and cancelled_at is null returning id, order_id, fulfilment_id, listing_id, seller_id, variant_id, product_name, variant_name, sku, condition, quantity, unit_price_kobo, discount_kobo, line_total_kobo, vat_kobo, commission_bps, device_unit_id, cancelled_at, created_at
`

type SalesCancelLineParams struct {
	ID      uuid.UUID `json:"id"`
	OrderID uuid.UUID `json:"orderId"`
}

func (q *Queries) SalesCancelLine(ctx context.Context, arg SalesCancelLineParams) (SalesOrderLine, error) {
	row := q.db.QueryRow(ctx, salesCancelLine, arg.ID, arg.OrderID)
	var i SalesOrderLine
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.FulfilmentID,
		&i.ListingID,
		&i.SellerID,
		&i.VariantID,
		&i.ProductName,
		&i.VariantName,
		&i.Sku,
		&i.Condition,
		&i.Quantity,
		&i.UnitPriceKobo,
		&i.DiscountKobo,
		&i.LineTotalKobo,
		&i.VatKobo,
		&i.CommissionBps,
		&i.DeviceUnitID,
		&i.CancelledAt,
		&i.CreatedAt,
	)
	return i, err
}

const salesCartLines = `-- name: SalesCartLines :many
select ci.id, ci.cart_id, ci.listing_id, ci.quantity, ci.added_at,
       l.price_kobo, l.compare_at_kobo, l.condition, l.status as listing_status, l.fulfilled_by, l.seller_stock, l.min_order_quantity,
       l.seller_id, l.variant_id, v.name as variant_name, v.sku, v.weight_grams, p.id as product_id, p.name as product_name, p.slug as product_slug,
       p.category_id, s.display_name as seller_name, s.type as seller_type, s.state_code as seller_state, s.status as seller_status
from sales.cart_items ci
join catalog.listings l on l.id = ci.listing_id
join catalog.product_variants v on v.id = l.variant_id
join catalog.products p on p.id = v.product_id
join sellers.sellers s on s.id = l.seller_id
where ci.cart_id = $1
order by ci.listing_id
`

type SalesCartLinesRow struct {
	ID               uuid.UUID `json:"id"`
	CartID           uuid.UUID `json:"cartId"`
	ListingID        uuid.UUID `json:"listingId"`
	Quantity         int32     `json:"quantity"`
	AddedAt          time.Time `json:"addedAt"`
	PriceKobo        int64     `json:"priceKobo"`
	CompareAtKobo    *int64    `json:"compareAtKobo"`
	Condition        string    `json:"condition"`
	ListingStatus    string    `json:"listingStatus"`
	FulfilledBy      string    `json:"fulfilledBy"`
	SellerStock      *int32    `json:"sellerStock"`
	MinOrderQuantity *int32    `json:"minOrderQuantity"`
	SellerID         uuid.UUID `json:"sellerId"`
	VariantID        uuid.UUID `json:"variantId"`
	VariantName      string    `json:"variantName"`
	Sku              string    `json:"sku"`
	WeightGrams      *int32    `json:"weightGrams"`
	ProductID        uuid.UUID `json:"productId"`
	ProductName      string    `json:"productName"`
	ProductSlug      string    `json:"productSlug"`
	CategoryID       uuid.UUID `json:"categoryId"`
	SellerName       string    `json:"sellerName"`
	SellerType       string    `json:"sellerType"`
	SellerState      *string   `json:"sellerState"`
	SellerStatus     string    `json:"sellerStatus"`
}

// Cart lines with live prices and everything pricing and checkout need.
func (q *Queries) SalesCartLines(ctx context.Context, cartID uuid.UUID) ([]SalesCartLinesRow, error) {
	rows, err := q.db.Query(ctx, salesCartLines, cartID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SalesCartLinesRow{}
	for rows.Next() {
		var i SalesCartLinesRow
		if err := rows.Scan(
			&i.ID,
			&i.CartID,
			&i.ListingID,
			&i.Quantity,
			&i.AddedAt,
			&i.PriceKobo,
			&i.CompareAtKobo,
			&i.Condition,
			&i.ListingStatus,
			&i.FulfilledBy,
			&i.SellerStock,
			&i.MinOrderQuantity,
			&i.SellerID,
			&i.VariantID,
			&i.VariantName,
			&i.Sku,
			&i.WeightGrams,
			&i.ProductID,
			&i.ProductName,
			&i.ProductSlug,
			&i.CategoryID,
			&i.SellerName,
			&i.SellerType,
			&i.SellerState,
			&i.SellerStatus,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const salesClearCart = `-- name: SalesClearCart :exec
delete from sales.cart_items where cart_id = $1
`

func (q *Queries) SalesClearCart(ctx context.Context, cartID uuid.UUID) error {
	_, err := q.db.Exec(ctx, salesClearCart, cartID)
	return err
}

const salesCommissionBps = `-- name: SalesCommissionBps :one
select coalesce(
  (select cs.rate_bps from finance.commission_rules cs where cs.seller_id = $1::uuid and cs.category_id is null
     and current_date >= cs.valid_from and (cs.valid_to is null or current_date < cs.valid_to) order by cs.valid_from desc limit 1),
  (select cc.rate_bps from finance.commission_rules cc where cc.category_id = $2::uuid and cc.seller_id is null
     and current_date >= cc.valid_from and (cc.valid_to is null or current_date < cc.valid_to) order by cc.valid_from desc limit 1),
  (select so.commission_override_bps from sellers.sellers so where so.id = $1::uuid),
  $3::int
)::int as bps
`

type SalesCommissionBpsParams struct {
	SellerID   uuid.UUID `json:"sellerId"`
	CategoryID uuid.UUID `json:"categoryId"`
	DefaultBps int32     `json:"defaultBps"`
}

// Seller-specific rule, then category rule, then the seller override, then the configured default.
func (q *Queries) SalesCommissionBps(ctx context.Context, arg SalesCommissionBpsParams) (int32, error) {
	row := q.db.QueryRow(ctx, salesCommissionBps, arg.SellerID, arg.CategoryID, arg.DefaultBps)
	var bps int32
	err := row.Scan(&bps)
	return bps, err
}

const salesCommissionForFulfilment = `-- name: SalesCommissionForFulfilment :one
select coalesce(sum((ol.line_total_kobo * ol.commission_bps + 5000) / 10000), 0)::bigint
from sales.order_lines ol where ol.fulfilment_id = $1 and ol.cancelled_at is null
`

// Commission owed on a delivered fulfilment: Σ line total × the line's snapshot rate.
func (q *Queries) SalesCommissionForFulfilment(ctx context.Context, fulfilmentID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, salesCommissionForFulfilment, fulfilmentID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const salesCreateCart = `-- name: SalesCreateCart :one
insert into sales.carts (user_id, session_token_hash) values ($1, $2) returning id, user_id, session_token_hash, business_id, status, created_at, updated_at
`

type SalesCreateCartParams struct {
	UserID           *uuid.UUID `json:"userId"`
	SessionTokenHash []byte     `json:"sessionTokenHash"`
}

func (q *Queries) SalesCreateCart(ctx context.Context, arg SalesCreateCartParams) (SalesCart, error) {
	row := q.db.QueryRow(ctx, salesCreateCart, arg.UserID, arg.SessionTokenHash)
	var i SalesCart
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.SessionTokenHash,
		&i.BusinessID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const salesCreateFulfilment = `-- name: SalesCreateFulfilment :one
insert into sales.fulfilments (order_id, seller_id, fulfilled_by, method, warehouse_id, collection_store_id, delivery_fee_kobo)
values ($1, $2, $3, $4, $5, $6, $7)
returning id, order_id, seller_id, fulfilled_by, method, warehouse_id, collection_store_id, status, delivery_fee_kobo, accept_by, pack_by, delivered_at, cancelled_reason, created_at, updated_at
`

type SalesCreateFulfilmentParams struct {
	OrderID           uuid.UUID  `json:"orderId"`
	SellerID          uuid.UUID  `json:"sellerId"`
	FulfilledBy       string     `json:"fulfilledBy"`
	Method            string     `json:"method"`
	WarehouseID       *uuid.UUID `json:"warehouseId"`
	CollectionStoreID *uuid.UUID `json:"collectionStoreId"`
	DeliveryFeeKobo   int64      `json:"deliveryFeeKobo"`
}

func (q *Queries) SalesCreateFulfilment(ctx context.Context, arg SalesCreateFulfilmentParams) (SalesFulfilment, error) {
	row := q.db.QueryRow(ctx, salesCreateFulfilment,
		arg.OrderID,
		arg.SellerID,
		arg.FulfilledBy,
		arg.Method,
		arg.WarehouseID,
		arg.CollectionStoreID,
		arg.DeliveryFeeKobo,
	)
	var i SalesFulfilment
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.SellerID,
		&i.FulfilledBy,
		&i.Method,
		&i.WarehouseID,
		&i.CollectionStoreID,
		&i.Status,
		&i.DeliveryFeeKobo,
		&i.AcceptBy,
		&i.PackBy,
		&i.DeliveredAt,
		&i.CancelledReason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const salesCreateLine = `-- name: SalesCreateLine :one
insert into sales.order_lines (order_id, fulfilment_id, listing_id, seller_id, variant_id, product_name, variant_name, sku, condition, quantity,
  unit_price_kobo, discount_kobo, line_total_kobo, vat_kobo, commission_bps)
values ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15)
returning id, order_id, fulfilment_id, listing_id, seller_id, variant_id, product_name, variant_name, sku, condition, quantity, unit_price_kobo, discount_kobo, line_total_kobo, vat_kobo, commission_bps, device_unit_id, cancelled_at, created_at
`

type SalesCreateLineParams struct {
	OrderID       uuid.UUID `json:"orderId"`
	FulfilmentID  uuid.UUID `json:"fulfilmentId"`
	ListingID     uuid.UUID `json:"listingId"`
	SellerID      uuid.UUID `json:"sellerId"`
	VariantID     uuid.UUID `json:"variantId"`
	ProductName   string    `json:"productName"`
	VariantName   string    `json:"variantName"`
	Sku           string    `json:"sku"`
	Condition     string    `json:"condition"`
	Quantity      int32     `json:"quantity"`
	UnitPriceKobo int64     `json:"unitPriceKobo"`
	DiscountKobo  int64     `json:"discountKobo"`
	LineTotalKobo int64     `json:"lineTotalKobo"`
	VatKobo       int64     `json:"vatKobo"`
	CommissionBps int32     `json:"commissionBps"`
}

func (q *Queries) SalesCreateLine(ctx context.Context, arg SalesCreateLineParams) (SalesOrderLine, error) {
	row := q.db.QueryRow(ctx, salesCreateLine,
		arg.OrderID,
		arg.FulfilmentID,
		arg.ListingID,
		arg.SellerID,
		arg.VariantID,
		arg.ProductName,
		arg.VariantName,
		arg.Sku,
		arg.Condition,
		arg.Quantity,
		arg.UnitPriceKobo,
		arg.DiscountKobo,
		arg.LineTotalKobo,
		arg.VatKobo,
		arg.CommissionBps,
	)
	var i SalesOrderLine
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.FulfilmentID,
		&i.ListingID,
		&i.SellerID,
		&i.VariantID,
		&i.ProductName,
		&i.VariantName,
		&i.Sku,
		&i.Condition,
		&i.Quantity,
		&i.UnitPriceKobo,
		&i.DiscountKobo,
		&i.LineTotalKobo,
		&i.VatKobo,
		&i.CommissionBps,
		&i.DeviceUnitID,
		&i.CancelledAt,
		&i.CreatedAt,
	)
	return i, err
}

const salesCreateOrder = `-- name: SalesCreateOrder :one
insert into sales.orders (channel, customer_user_id, business_id, quote_id, pos_shift_id, status, subtotal_kobo, delivery_fee_kobo, discount_kobo,
  vat_kobo, total_kobo, ship_to, contact_phone, price_hash, payment_due_at)
values ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15)
returning id, order_number, channel, customer_user_id, business_id, quote_id, pos_shift_id, status, subtotal_kobo, delivery_fee_kobo, discount_kobo, vat_kobo, total_kobo, currency, ship_to, contact_phone, price_hash, payment_due_at, attributed_notification_id, placed_at, cancelled_at, created_at, updated_at
`

type SalesCreateOrderParams struct {
	Channel         string          `json:"channel"`
	CustomerUserID  *uuid.UUID      `json:"customerUserId"`
	BusinessID      *uuid.UUID      `json:"businessId"`
	QuoteID         *uuid.UUID      `json:"quoteId"`
	PosShiftID      *uuid.UUID      `json:"posShiftId"`
	Status          string          `json:"status"`
	SubtotalKobo    int64           `json:"subtotalKobo"`
	DeliveryFeeKobo int64           `json:"deliveryFeeKobo"`
	DiscountKobo    int64           `json:"discountKobo"`
	VatKobo         int64           `json:"vatKobo"`
	TotalKobo       int64           `json:"totalKobo"`
	ShipTo          json.RawMessage `json:"shipTo"`
	ContactPhone    *string         `json:"contactPhone"`
	PriceHash       *string         `json:"priceHash"`
	PaymentDueAt    *time.Time      `json:"paymentDueAt"`
}

func (q *Queries) SalesCreateOrder(ctx context.Context, arg SalesCreateOrderParams) (SalesOrder, error) {
	row := q.db.QueryRow(ctx, salesCreateOrder,
		arg.Channel,
		arg.CustomerUserID,
		arg.BusinessID,
		arg.QuoteID,
		arg.PosShiftID,
		arg.Status,
		arg.SubtotalKobo,
		arg.DeliveryFeeKobo,
		arg.DiscountKobo,
		arg.VatKobo,
		arg.TotalKobo,
		arg.ShipTo,
		arg.ContactPhone,
		arg.PriceHash,
		arg.PaymentDueAt,
	)
	var i SalesOrder
	err := row.Scan(
		&i.ID,
		&i.OrderNumber,
		&i.Channel,
		&i.CustomerUserID,
		&i.BusinessID,
		&i.QuoteID,
		&i.PosShiftID,
		&i.Status,
		&i.SubtotalKobo,
		&i.DeliveryFeeKobo,
		&i.DiscountKobo,
		&i.VatKobo,
		&i.TotalKobo,
		&i.Currency,
		&i.ShipTo,
		&i.ContactPhone,
		&i.PriceHash,
		&i.PaymentDueAt,
		&i.AttributedNotificationID,
		&i.PlacedAt,
		&i.CancelledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const salesCustomerOrderByNumber = `-- name: SalesCustomerOrderByNumber :one
select id, order_number, channel, customer_user_id, business_id, quote_id, pos_shift_id, status, subtotal_kobo, delivery_fee_kobo, discount_kobo, vat_kobo, total_kobo, currency, ship_to, contact_phone, price_hash, payment_due_at, attributed_notification_id, placed_at, cancelled_at, created_at, updated_at from sales.orders where order_number = $1 and customer_user_id = $2
`

type SalesCustomerOrderByNumberParams struct {
	OrderNumber    string     `json:"orderNumber"`
	CustomerUserID *uuid.UUID `json:"customerUserId"`
}

func (q *Queries) SalesCustomerOrderByNumber(ctx context.Context, arg SalesCustomerOrderByNumberParams) (SalesOrder, error) {
	row := q.db.QueryRow(ctx, salesCustomerOrderByNumber, arg.OrderNumber, arg.CustomerUserID)
	var i SalesOrder
	err := row.Scan(
		&i.ID,
		&i.OrderNumber,
		&i.Channel,
		&i.CustomerUserID,
		&i.BusinessID,
		&i.QuoteID,
		&i.PosShiftID,
		&i.Status,
		&i.SubtotalKobo,
		&i.DeliveryFeeKobo,
		&i.DiscountKobo,
		&i.VatKobo,
		&i.TotalKobo,
		&i.Currency,
		&i.ShipTo,
		&i.ContactPhone,
		&i.PriceHash,
		&i.PaymentDueAt,
		&i.AttributedNotificationID,
		&i.PlacedAt,
		&i.CancelledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const salesDeleteCartItem = `-- name: SalesDeleteCartItem :execrows
delete from sales.cart_items where id = $1 and cart_id = $2
`

type SalesDeleteCartItemParams struct {
	ID     uuid.UUID `json:"id"`
	CartID uuid.UUID `json:"cartId"`
}

func (q *Queries) SalesDeleteCartItem(ctx context.Context, arg SalesDeleteCartItemParams) (int64, error) {
	result, err := q.db.Exec(ctx, salesDeleteCartItem, arg.ID, arg.CartID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const salesFulfilmentLines = `-- name: SalesFulfilmentLines :many
select id, order_id, fulfilment_id, listing_id, seller_id, variant_id, product_name, variant_name, sku, condition, quantity, unit_price_kobo, discount_kobo, line_total_kobo, vat_kobo, commission_bps, device_unit_id, cancelled_at, created_at from sales.order_lines where fulfilment_id = $1 order by created_at
`

func (q *Queries) SalesFulfilmentLines(ctx context.Context, fulfilmentID uuid.UUID) ([]SalesOrderLine, error) {
	rows, err := q.db.Query(ctx, salesFulfilmentLines, fulfilmentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SalesOrderLine{}
	for rows.Next() {
		var i SalesOrderLine
		if err := rows.Scan(
			&i.ID,
			&i.OrderID,
			&i.FulfilmentID,
			&i.ListingID,
			&i.SellerID,
			&i.VariantID,
			&i.ProductName,
			&i.VariantName,
			&i.Sku,
			&i.Condition,
			&i.Quantity,
			&i.UnitPriceKobo,
			&i.DiscountKobo,
			&i.LineTotalKobo,
			&i.VatKobo,
			&i.CommissionBps,
			&i.DeviceUnitID,
			&i.CancelledAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const salesGetFulfilment = `-- name: SalesGetFulfilment :one
select id, order_id, seller_id, fulfilled_by, method, warehouse_id, collection_store_id, status, delivery_fee_kobo, accept_by, pack_by, delivered_at, cancelled_reason, created_at, updated_at from sales.fulfilments where id = $1
`

func (q *Queries) SalesGetFulfilment(ctx context.Context, id uuid.UUID) (SalesFulfilment, error) {
	row := q.db.QueryRow(ctx, salesGetFulfilment, id)
	var i SalesFulfilment
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.SellerID,
		&i.FulfilledBy,
		&i.Method,
		&i.WarehouseID,
		&i.CollectionStoreID,
		&i.Status,
		&i.DeliveryFeeKobo,
		&i.AcceptBy,
		&i.PackBy,
		&i.DeliveredAt,
		&i.CancelledReason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const salesGetFulfilmentForUpdate = `-- name: SalesGetFulfilmentForUpdate :one
select id, order_id, seller_id, fulfilled_by, method, warehouse_id, collection_store_id, status, delivery_fee_kobo, accept_by, pack_by, delivered_at, cancelled_reason, created_at, updated_at from sales.fulfilments where id = $1 for update
`

func (q *Queries) SalesGetFulfilmentForUpdate(ctx context.Context, id uuid.UUID) (SalesFulfilment, error) {
	row := q.db.QueryRow(ctx, salesGetFulfilmentForUpdate, id)
	var i SalesFulfilment
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.SellerID,
		&i.FulfilledBy,
		&i.Method,
		&i.WarehouseID,
		&i.CollectionStoreID,
		&i.Status,
		&i.DeliveryFeeKobo,
		&i.AcceptBy,
		&i.PackBy,
		&i.DeliveredAt,
		&i.CancelledReason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const salesGetGuestCart = `-- name: SalesGetGuestCart :one
select id, user_id, session_token_hash, business_id, status, created_at, updated_at from sales.carts where session_token_hash = $1 and status = 'active'
`

func (q *Queries) SalesGetGuestCart(ctx context.Context, sessionTokenHash []byte) (SalesCart, error) {
	row := q.db.QueryRow(ctx, salesGetGuestCart, sessionTokenHash)
	var i SalesCart
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.SessionTokenHash,
		&i.BusinessID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const salesGetLine = `-- name: SalesGetLine :one
select id, order_id, fulfilment_id, listing_id, seller_id, variant_id, product_name, variant_name, sku, condition, quantity, unit_price_kobo, discount_kobo, line_total_kobo, vat_kobo, commission_bps, device_unit_id, cancelled_at, created_at from sales.order_lines where id = $1
`

func (q *Queries) SalesGetLine(ctx context.Context, id uuid.UUID) (SalesOrderLine, error) {
	row := q.db.QueryRow(ctx, salesGetLine, id)
	var i SalesOrderLine
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.FulfilmentID,
		&i.ListingID,
		&i.SellerID,
		&i.VariantID,
		&i.ProductName,
		&i.VariantName,
		&i.Sku,
		&i.Condition,
		&i.Quantity,
		&i.UnitPriceKobo,
		&i.DiscountKobo,
		&i.LineTotalKobo,
		&i.VatKobo,
		&i.CommissionBps,
		&i.DeviceUnitID,
		&i.CancelledAt,
		&i.CreatedAt,
	)
	return i, err
}

const salesGetOrder = `-- name: SalesGetOrder :one
select id, order_number, channel, customer_user_id, business_id, quote_id, pos_shift_id, status, subtotal_kobo, delivery_fee_kobo, discount_kobo, vat_kobo, total_kobo, currency, ship_to, contact_phone, price_hash, payment_due_at, attributed_notification_id, placed_at, cancelled_at, created_at, updated_at from sales.orders where id = $1
`

func (q *Queries) SalesGetOrder(ctx context.Context, id uuid.UUID) (SalesOrder, error) {
	row := q.db.QueryRow(ctx, salesGetOrder, id)
	var i SalesOrder
	err := row.Scan(
		&i.ID,
		&i.OrderNumber,
		&i.Channel,
		&i.CustomerUserID,
		&i.BusinessID,
		&i.QuoteID,
		&i.PosShiftID,
		&i.Status,
		&i.SubtotalKobo,
		&i.DeliveryFeeKobo,
		&i.DiscountKobo,
		&i.VatKobo,
		&i.TotalKobo,
		&i.Currency,
		&i.ShipTo,
		&i.ContactPhone,
		&i.PriceHash,
		&i.PaymentDueAt,
		&i.AttributedNotificationID,
		&i.PlacedAt,
		&i.CancelledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const salesGetOrderByNumber = `-- name: SalesGetOrderByNumber :one
select id, order_number, channel, customer_user_id, business_id, quote_id, pos_shift_id, status, subtotal_kobo, delivery_fee_kobo, discount_kobo, vat_kobo, total_kobo, currency, ship_to, contact_phone, price_hash, payment_due_at, attributed_notification_id, placed_at, cancelled_at, created_at, updated_at from sales.orders where order_number = $1
`

func (q *Queries) SalesGetOrderByNumber(ctx context.Context, orderNumber string) (SalesOrder, error) {
	row := q.db.QueryRow(ctx, salesGetOrderByNumber, orderNumber)
	var i SalesOrder
	err := row.Scan(
		&i.ID,
		&i.OrderNumber,
		&i.Channel,
		&i.CustomerUserID,
		&i.BusinessID,
		&i.QuoteID,
		&i.PosShiftID,
		&i.Status,
		&i.SubtotalKobo,
		&i.DeliveryFeeKobo,
		&i.DiscountKobo,
		&i.VatKobo,
		&i.TotalKobo,
		&i.Currency,
		&i.ShipTo,
		&i.ContactPhone,
		&i.PriceHash,
		&i.PaymentDueAt,
		&i.AttributedNotificationID,
		&i.PlacedAt,
		&i.CancelledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const salesGetOrderForUpdate = `-- name: SalesGetOrderForUpdate :one
select id, order_number, channel, customer_user_id, business_id, quote_id, pos_shift_id, status, subtotal_kobo, delivery_fee_kobo, discount_kobo, vat_kobo, total_kobo, currency, ship_to, contact_phone, price_hash, payment_due_at, attributed_notification_id, placed_at, cancelled_at, created_at, updated_at from sales.orders where id = $1 for update
`

func (q *Queries) SalesGetOrderForUpdate(ctx context.Context, id uuid.UUID) (SalesOrder, error) {
	row := q.db.QueryRow(ctx, salesGetOrderForUpdate, id)
	var i SalesOrder
	err := row.Scan(
		&i.ID,
		&i.OrderNumber,
		&i.Channel,
		&i.CustomerUserID,
		&i.BusinessID,
		&i.QuoteID,
		&i.PosShiftID,
		&i.Status,
		&i.SubtotalKobo,
		&i.DeliveryFeeKobo,
		&i.DiscountKobo,
		&i.VatKobo,
		&i.TotalKobo,
		&i.Currency,
		&i.ShipTo,
		&i.ContactPhone,
		&i.PriceHash,
		&i.PaymentDueAt,
		&i.AttributedNotificationID,
		&i.PlacedAt,
		&i.CancelledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const salesGetUserCart = `-- name: SalesGetUserCart :one

select id, user_id, session_token_hash, business_id, status, created_at, updated_at from sales.carts where user_id = $1 and status = 'active' and business_id is null
`

// Sales: carts, orders, fulfilments, lines, status history (docs/orders-fulfilment.md §2).
func (q *Queries) SalesGetUserCart(ctx context.Context, userID *uuid.UUID) (SalesCart, error) {
	row := q.db.QueryRow(ctx, salesGetUserCart, userID)
	var i SalesCart
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.SessionTokenHash,
		&i.BusinessID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const salesInsertHistory = `-- name: SalesInsertHistory :exec
insert into sales.order_status_history (order_id, fulfilment_id, from_status, to_status, actor_user_id, note) values ($1, $2, $3, $4, $5, $6)
`

type SalesInsertHistoryParams struct {
	OrderID      uuid.UUID  `json:"orderId"`
	FulfilmentID *uuid.UUID `json:"fulfilmentId"`
	FromStatus   *string    `json:"fromStatus"`
	ToStatus     string     `json:"toStatus"`
	ActorUserID  *uuid.UUID `json:"actorUserId"`
	Note         *string    `json:"note"`
}

func (q *Queries) SalesInsertHistory(ctx context.Context, arg SalesInsertHistoryParams) error {
	_, err := q.db.Exec(ctx, salesInsertHistory,
		arg.OrderID,
		arg.FulfilmentID,
		arg.FromStatus,
		arg.ToStatus,
		arg.ActorUserID,
		arg.Note,
	)
	return err
}

const salesLineReservations = `-- name: SalesLineReservations :many
select id, order_id, order_line_id, warehouse_id, listing_id, variant_id, condition, owner_seller_id, quantity, status, expires_at, created_at, updated_at from inventory.stock_reservations where order_line_id = $1
`

func (q *Queries) SalesLineReservations(ctx context.Context, orderLineID uuid.UUID) ([]InventoryStockReservation, error) {
	rows, err := q.db.Query(ctx, salesLineReservations, orderLineID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []InventoryStockReservation{}
	for rows.Next() {
		var i InventoryStockReservation
		if err := rows.Scan(
			&i.ID,
			&i.OrderID,
			&i.OrderLineID,
			&i.WarehouseID,
			&i.ListingID,
			&i.VariantID,
			&i.Condition,
			&i.OwnerSellerID,
			&i.Quantity,
			&i.Status,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const salesListCustomerOrders = `-- name: SalesListCustomerOrders :many
select id, order_number, channel, customer_user_id, business_id, quote_id, pos_shift_id, status, subtotal_kobo, delivery_fee_kobo, discount_kobo, vat_kobo, total_kobo, currency, ship_to, contact_phone, price_hash, payment_due_at, attributed_notification_id, placed_at, cancelled_at, created_at, updated_at from sales.orders where customer_user_id = $1
  and ($3::timestamptz is null or placed_at < $3)
order by placed_at desc limit $2
`

type SalesListCustomerOrdersParams struct {
	CustomerUserID *uuid.UUID `json:"customerUserId"`
	Limit          int32      `json:"limit"`
	Before         *time.Time `json:"before"`
}

func (q *Queries) SalesListCustomerOrders(ctx context.Context, arg SalesListCustomerOrdersParams) ([]SalesOrder, error) {
	rows, err := q.db.Query(ctx, salesListCustomerOrders, arg.CustomerUserID, arg.Limit, arg.Before)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SalesOrder{}
	for rows.Next() {
		var i SalesOrder
		if err := rows.Scan(
			&i.ID,
			&i.OrderNumber,
			&i.Channel,
			&i.CustomerUserID,
			&i.BusinessID,
			&i.QuoteID,
			&i.PosShiftID,
			&i.Status,
			&i.SubtotalKobo,
			&i.DeliveryFeeKobo,
			&i.DiscountKobo,
			&i.VatKobo,
			&i.TotalKobo,
			&i.Currency,
			&i.ShipTo,
			&i.ContactPhone,
			&i.PriceHash,
			&i.PaymentDueAt,
			&i.AttributedNotificationID,
			&i.PlacedAt,
			&i.CancelledAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const salesListingAvailable = `-- name: SalesListingAvailable :one
select case when l.fulfilled_by = 'seller' then coalesce(l.seller_stock, 0)
  else coalesce((select sum(il.on_hand - il.reserved) from inventory.inventory_levels il
                 where il.variant_id = l.variant_id and il.condition = l.condition and il.owner_seller_id = l.seller_id), 0) end::int as available
from catalog.listings l where l.id = $1
`

// Units that can still be sold for a listing: seller-held stock, or unreserved warehouse stock.
func (q *Queries) SalesListingAvailable(ctx context.Context, id uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, salesListingAvailable, id)
	var available int32
	err := row.Scan(&available)
	return available, err
}

const salesLiveFlashPrice = `-- name: SalesLiveFlashPrice :one
select plp.promotion_id, plp.price_kobo, plp.stock_limit, plp.claimed, plp.per_user_limit
from marketing.promotion_listing_prices plp
join marketing.promotions pr on pr.id = plp.promotion_id
where plp.listing_id = $1 and pr.status = 'live' and now() between pr.starts_at and pr.ends_at
order by plp.price_kobo limit 1
`

type SalesLiveFlashPriceRow struct {
	PromotionID  uuid.UUID `json:"promotionId"`
	PriceKobo    int64     `json:"priceKobo"`
	StockLimit   *int32    `json:"stockLimit"`
	Claimed      int32     `json:"claimed"`
	PerUserLimit *int32    `json:"perUserLimit"`
}

func (q *Queries) SalesLiveFlashPrice(ctx context.Context, listingID uuid.UUID) (SalesLiveFlashPriceRow, error) {
	row := q.db.QueryRow(ctx, salesLiveFlashPrice, listingID)
	var i SalesLiveFlashPriceRow
	err := row.Scan(
		&i.PromotionID,
		&i.PriceKobo,
		&i.StockLimit,
		&i.Claimed,
		&i.PerUserLimit,
	)
	return i, err
}

const salesMergeCartItems = `-- name: SalesMergeCartItems :exec
insert into sales.cart_items (cart_id, listing_id, quantity)
select $1::uuid, listing_id, quantity from sales.cart_items where cart_id = $2::uuid
on conflict (cart_id, listing_id) do update set quantity = greatest(sales.cart_items.quantity, excluded.quantity)
`

type SalesMergeCartItemsParams struct {
	Target uuid.UUID `json:"target"`
	Source uuid.UUID `json:"source"`
}

func (q *Queries) SalesMergeCartItems(ctx context.Context, arg SalesMergeCartItemsParams) error {
	_, err := q.db.Exec(ctx, salesMergeCartItems, arg.Target, arg.Source)
	return err
}

const salesOrderFulfilments = `-- name: SalesOrderFulfilments :many
select f.id, f.order_id, f.seller_id, f.fulfilled_by, f.method, f.warehouse_id, f.collection_store_id, f.status, f.delivery_fee_kobo, f.accept_by, f.pack_by, f.delivered_at, f.cancelled_reason, f.created_at, f.updated_at, s.display_name as seller_name, s.type as seller_type from sales.fulfilments f join sellers.sellers s on s.id = f.seller_id
where f.order_id = $1 order by f.created_at
`

type SalesOrderFulfilmentsRow struct {
	ID                uuid.UUID  `json:"id"`
	OrderID           uuid.UUID  `json:"orderId"`
	SellerID          uuid.UUID  `json:"sellerId"`
	FulfilledBy       string     `json:"fulfilledBy"`
	Method            string     `json:"method"`
	WarehouseID       *uuid.UUID `json:"warehouseId"`
	CollectionStoreID *uuid.UUID `json:"collectionStoreId"`
	Status            string     `json:"status"`
	DeliveryFeeKobo   int64      `json:"deliveryFeeKobo"`
	AcceptBy          *time.Time `json:"acceptBy"`
	PackBy            *time.Time `json:"packBy"`
	DeliveredAt       *time.Time `json:"deliveredAt"`
	CancelledReason   *string    `json:"cancelledReason"`
	CreatedAt         time.Time  `json:"createdAt"`
	UpdatedAt         time.Time  `json:"updatedAt"`
	SellerName        string     `json:"sellerName"`
	SellerType        string     `json:"sellerType"`
}

func (q *Queries) SalesOrderFulfilments(ctx context.Context, orderID uuid.UUID) ([]SalesOrderFulfilmentsRow, error) {
	rows, err := q.db.Query(ctx, salesOrderFulfilments, orderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SalesOrderFulfilmentsRow{}
	for rows.Next() {
		var i SalesOrderFulfilmentsRow
		if err := rows.Scan(
			&i.ID,
			&i.OrderID,
			&i.SellerID,
			&i.FulfilledBy,
			&i.Method,
			&i.WarehouseID,
			&i.CollectionStoreID,
			&i.Status,
			&i.DeliveryFeeKobo,
			&i.AcceptBy,
			&i.PackBy,
			&i.DeliveredAt,
			&i.CancelledReason,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SellerName,
			&i.SellerType,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const salesOrderHistory = `-- name: SalesOrderHistory :many
select id, order_id, fulfilment_id, from_status, to_status, actor_user_id, note, created_at from sales.order_status_history where order_id = $1 order by created_at
`

func (q *Queries) SalesOrderHistory(ctx context.Context, orderID uuid.UUID) ([]SalesOrderStatusHistory, error) {
	rows, err := q.db.Query(ctx, salesOrderHistory, orderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SalesOrderStatusHistory{}
	for rows.Next() {
		var i SalesOrderStatusHistory
		if err := rows.Scan(
			&i.ID,
			&i.OrderID,
			&i.FulfilmentID,
			&i.FromStatus,
			&i.ToStatus,
			&i.ActorUserID,
			&i.Note,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const salesOrderLines = `-- name: SalesOrderLines :many
select id, order_id, fulfilment_id, listing_id, seller_id, variant_id, product_name, variant_name, sku, condition, quantity, unit_price_kobo, discount_kobo, line_total_kobo, vat_kobo, commission_bps, device_unit_id, cancelled_at, created_at from sales.order_lines where order_id = $1 order by created_at
`

func (q *Queries) SalesOrderLines(ctx context.Context, orderID uuid.UUID) ([]SalesOrderLine, error) {
	rows, err := q.db.Query(ctx, salesOrderLines, orderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SalesOrderLine{}
	for rows.Next() {
		var i SalesOrderLine
		if err := rows.Scan(
			&i.ID,
			&i.OrderID,
			&i.FulfilmentID,
			&i.ListingID,
			&i.SellerID,
			&i.VariantID,
			&i.ProductName,
			&i.VariantName,
			&i.Sku,
			&i.Condition,
			&i.Quantity,
			&i.UnitPriceKobo,
			&i.DiscountKobo,
			&i.LineTotalKobo,
			&i.VatKobo,
			&i.CommissionBps,
			&i.DeviceUnitID,
			&i.CancelledAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const salesPaidOrdersCount = `-- name: SalesPaidOrdersCount :one
select count(*)::int from sales.orders where customer_user_id = $1 and status not in ('pending_payment', 'cancelled')
`

func (q *Queries) SalesPaidOrdersCount(ctx context.Context, customerUserID *uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, salesPaidOrdersCount, customerUserID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const salesPendingAcceptBreaches = `-- name: SalesPendingAcceptBreaches :many
select f.id, f.order_id, f.seller_id, f.fulfilled_by, f.method, f.warehouse_id, f.collection_store_id, f.status, f.delivery_fee_kobo, f.accept_by, f.pack_by, f.delivered_at, f.cancelled_reason, f.created_at, f.updated_at, o.order_number from sales.fulfilments f join sales.orders o on o.id = f.order_id
where f.status = 'pending' and f.fulfilled_by = 'seller' and f.accept_by < now() limit 50
`

type SalesPendingAcceptBreachesRow struct {
	ID                uuid.UUID  `json:"id"`
	OrderID           uuid.UUID  `json:"orderId"`
	SellerID          uuid.UUID  `json:"sellerId"`
	FulfilledBy       string     `json:"fulfilledBy"`
	Method            string     `json:"method"`
	WarehouseID       *uuid.UUID `json:"warehouseId"`
	CollectionStoreID *uuid.UUID `json:"collectionStoreId"`
	Status            string     `json:"status"`
	DeliveryFeeKobo   int64      `json:"deliveryFeeKobo"`
	AcceptBy          *time.Time `json:"acceptBy"`
	PackBy            *time.Time `json:"packBy"`
	DeliveredAt       *time.Time `json:"deliveredAt"`
	CancelledReason   *string    `json:"cancelledReason"`
	CreatedAt         time.Time  `json:"createdAt"`
	UpdatedAt         time.Time  `json:"updatedAt"`
	OrderNumber       string     `json:"orderNumber"`
}

func (q *Queries) SalesPendingAcceptBreaches(ctx context.Context) ([]SalesPendingAcceptBreachesRow, error) {
	rows, err := q.db.Query(ctx, salesPendingAcceptBreaches)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SalesPendingAcceptBreachesRow{}
	for rows.Next() {
		var i SalesPendingAcceptBreachesRow
		if err := rows.Scan(
			&i.ID,
			&i.OrderID,
			&i.SellerID,
			&i.FulfilledBy,
			&i.Method,
			&i.WarehouseID,
			&i.CollectionStoreID,
			&i.Status,
			&i.DeliveryFeeKobo,
			&i.AcceptBy,
			&i.PackBy,
			&i.DeliveredAt,
			&i.CancelledReason,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.OrderNumber,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const salesSellerFulfilments = `-- name: SalesSellerFulfilments :many
select f.id, f.order_id, f.seller_id, f.fulfilled_by, f.method, f.warehouse_id, f.collection_store_id, f.status, f.delivery_fee_kobo, f.accept_by, f.pack_by, f.delivered_at, f.cancelled_reason, f.created_at, f.updated_at, o.order_number, o.ship_to, o.placed_at from sales.fulfilments f join sales.orders o on o.id = f.order_id
where f.seller_id = $1 and ($3::text is null or f.status = $3)
order by f.created_at desc limit $2
`

type SalesSellerFulfilmentsParams struct {
	SellerID uuid.UUID `json:"sellerId"`
	Limit    int32     `json:"limit"`
	Status   *string   `json:"status"`
}

type SalesSellerFulfilmentsRow struct {
	ID                uuid.UUID       `json:"id"`
	OrderID           uuid.UUID       `json:"orderId"`
	SellerID          uuid.UUID       `json:"sellerId"`
	FulfilledBy       string          `json:"fulfilledBy"`
	Method            string          `json:"method"`
	WarehouseID       *uuid.UUID      `json:"warehouseId"`
	CollectionStoreID *uuid.UUID      `json:"collectionStoreId"`
	Status            string          `json:"status"`
	DeliveryFeeKobo   int64           `json:"deliveryFeeKobo"`
	AcceptBy          *time.Time      `json:"acceptBy"`
	PackBy            *time.Time      `json:"packBy"`
	DeliveredAt       *time.Time      `json:"deliveredAt"`
	CancelledReason   *string         `json:"cancelledReason"`
	CreatedAt         time.Time       `json:"createdAt"`
	UpdatedAt         time.Time       `json:"updatedAt"`
	OrderNumber       string          `json:"orderNumber"`
	ShipTo            json.RawMessage `json:"shipTo"`
	PlacedAt          time.Time       `json:"placedAt"`
}

func (q *Queries) SalesSellerFulfilments(ctx context.Context, arg SalesSellerFulfilmentsParams) ([]SalesSellerFulfilmentsRow, error) {
	rows, err := q.db.Query(ctx, salesSellerFulfilments, arg.SellerID, arg.Limit, arg.Status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SalesSellerFulfilmentsRow{}
	for rows.Next() {
		var i SalesSellerFulfilmentsRow
		if err := rows.Scan(
			&i.ID,
			&i.OrderID,
			&i.SellerID,
			&i.FulfilledBy,
			&i.Method,
			&i.WarehouseID,
			&i.CollectionStoreID,
			&i.Status,
			&i.DeliveryFeeKobo,
			&i.AcceptBy,
			&i.PackBy,
			&i.DeliveredAt,
			&i.CancelledReason,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.OrderNumber,
			&i.ShipTo,
			&i.PlacedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const salesSellerFundedAt = `-- name: SalesSellerFundedAt :one
select exists (
  select 1 from marketing.promotions p join marketing.promotion_targets t on t.promotion_id = p.id
  where p.funded_by = 'seller' and t.listing_id = $1 and p.starts_at <= $2 and p.ends_at > $2 and p.status in ('live', 'ended')
)::bool
`

type SalesSellerFundedAtParams struct {
	ListingID *uuid.UUID `json:"listingId"`
	StartsAt  time.Time  `json:"startsAt"`
}

// Was this listing's discount seller-funded when the order was placed? (Seller-funded
// promotions always target the seller's own listings and never carry coupons.)
func (q *Queries) SalesSellerFundedAt(ctx context.Context, arg SalesSellerFundedAtParams) (bool, error) {
	row := q.db.QueryRow(ctx, salesSellerFundedAt, arg.ListingID, arg.StartsAt)
	var column_1 bool
	err := row.Scan(&column_1)
	return column_1, err
}

const salesSetAttribution = `-- name: SalesSetAttribution :exec
update sales.orders set attributed_notification_id = $2 where id = $1 and attributed_notification_id is null
`

type SalesSetAttributionParams struct {
	ID                       uuid.UUID  `json:"id"`
	AttributedNotificationID *uuid.UUID `json:"attributedNotificationId"`
}

func (q *Queries) SalesSetAttribution(ctx context.Context, arg SalesSetAttributionParams) error {
	_, err := q.db.Exec(ctx, salesSetAttribution, arg.ID, arg.AttributedNotificationID)
	return err
}

const salesSetCartItemQuantity = `-- name: SalesSetCartItemQuantity :execrows
update sales.cart_items set quantity = $3 where id = $1 and cart_id = $2
`

type SalesSetCartItemQuantityParams struct {
	ID       uuid.UUID `json:"id"`
	CartID   uuid.UUID `json:"cartId"`
	Quantity int32     `json:"quantity"`
}

func (q *Queries) SalesSetCartItemQuantity(ctx context.Context, arg SalesSetCartItemQuantityParams) (int64, error) {
	result, err := q.db.Exec(ctx, salesSetCartItemQuantity, arg.ID, arg.CartID, arg.Quantity)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const salesSetCartStatus = `-- name: SalesSetCartStatus :exec
update sales.carts set status = $2 where id = $1
`

type SalesSetCartStatusParams struct {
	ID     uuid.UUID `json:"id"`
	Status string    `json:"status"`
}

func (q *Queries) SalesSetCartStatus(ctx context.Context, arg SalesSetCartStatusParams) error {
	_, err := q.db.Exec(ctx, salesSetCartStatus, arg.ID, arg.Status)
	return err
}

const salesSetFulfilmentMethod = `-- name: SalesSetFulfilmentMethod :exec
update sales.fulfilments set method = $2, collection_store_id = $3 where id = $1
`

type SalesSetFulfilmentMethodParams struct {
	ID                uuid.UUID  `json:"id"`
	Method            string     `json:"method"`
	CollectionStoreID *uuid.UUID `json:"collectionStoreId"`
}

func (q *Queries) SalesSetFulfilmentMethod(ctx context.Context, arg SalesSetFulfilmentMethodParams) error {
	_, err := q.db.Exec(ctx, salesSetFulfilmentMethod, arg.ID, arg.Method, arg.CollectionStoreID)
	return err
}

const salesSetFulfilmentStatus = `-- name: SalesSetFulfilmentStatus :one
update sales.fulfilments
set status = $2, delivered_at = case when $2 = 'delivered' then now() else delivered_at end,
    cancelled_reason = coalesce($3, cancelled_reason),
    accept_by = coalesce($4, accept_by), pack_by = coalesce($5, pack_by)
where id = $1 returning id, order_id, seller_id, fulfilled_by, method, warehouse_id, collection_store_id, status, delivery_fee_kobo, accept_by, pack_by, delivered_at, cancelled_reason, created_at, updated_at
`

type SalesSetFulfilmentStatusParams struct {
	ID       uuid.UUID  `json:"id"`
	Status   string     `json:"status"`
	Reason   *string    `json:"reason"`
	AcceptBy *time.Time `json:"acceptBy"`
	PackBy   *time.Time `json:"packBy"`
}

func (q *Queries) SalesSetFulfilmentStatus(ctx context.Context, arg SalesSetFulfilmentStatusParams) (SalesFulfilment, error) {
	row := q.db.QueryRow(ctx, salesSetFulfilmentStatus,
		arg.ID,
		arg.Status,
		arg.Reason,
		arg.AcceptBy,
		arg.PackBy,
	)
	var i SalesFulfilment
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.SellerID,
		&i.FulfilledBy,
		&i.Method,
		&i.WarehouseID,
		&i.CollectionStoreID,
		&i.Status,
		&i.DeliveryFeeKobo,
		&i.AcceptBy,
		&i.PackBy,
		&i.DeliveredAt,
		&i.CancelledReason,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const salesSetFulfilmentWarehouse = `-- name: SalesSetFulfilmentWarehouse :exec
update sales.fulfilments set warehouse_id = $2 where id = $1
`

type SalesSetFulfilmentWarehouseParams struct {
	ID          uuid.UUID  `json:"id"`
	WarehouseID *uuid.UUID `json:"warehouseId"`
}

func (q *Queries) SalesSetFulfilmentWarehouse(ctx context.Context, arg SalesSetFulfilmentWarehouseParams) error {
	_, err := q.db.Exec(ctx, salesSetFulfilmentWarehouse, arg.ID, arg.WarehouseID)
	return err
}

const salesSetOrderStatus = `-- name: SalesSetOrderStatus :one
update sales.orders set status = $2, cancelled_at = case when $2 = 'cancelled' then now() else cancelled_at end where id = $1 returning id, order_number, channel, customer_user_id, business_id, quote_id, pos_shift_id, status, subtotal_kobo, delivery_fee_kobo, discount_kobo, vat_kobo, total_kobo, currency, ship_to, contact_phone, price_hash, payment_due_at, attributed_notification_id, placed_at, cancelled_at, created_at, updated_at
`

type SalesSetOrderStatusParams struct {
	ID     uuid.UUID `json:"id"`
	Status string    `json:"status"`
}

func (q *Queries) SalesSetOrderStatus(ctx context.Context, arg SalesSetOrderStatusParams) (SalesOrder, error) {
	row := q.db.QueryRow(ctx, salesSetOrderStatus, arg.ID, arg.Status)
	var i SalesOrder
	err := row.Scan(
		&i.ID,
		&i.OrderNumber,
		&i.Channel,
		&i.CustomerUserID,
		&i.BusinessID,
		&i.QuoteID,
		&i.PosShiftID,
		&i.Status,
		&i.SubtotalKobo,
		&i.DeliveryFeeKobo,
		&i.DiscountKobo,
		&i.VatKobo,
		&i.TotalKobo,
		&i.Currency,
		&i.ShipTo,
		&i.ContactPhone,
		&i.PriceHash,
		&i.PaymentDueAt,
		&i.AttributedNotificationID,
		&i.PlacedAt,
		&i.CancelledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const salesStaffListOrders = `-- name: SalesStaffListOrders :many
select o.id, o.order_number, o.channel, o.customer_user_id, o.business_id, o.quote_id, o.pos_shift_id, o.status, o.subtotal_kobo, o.delivery_fee_kobo, o.discount_kobo, o.vat_kobo, o.total_kobo, o.currency, o.ship_to, o.contact_phone, o.price_hash, o.payment_due_at, o.attributed_notification_id, o.placed_at, o.cancelled_at, o.created_at, o.updated_at, u.first_name, u.last_name from sales.orders o left join identity.users u on u.id = o.customer_user_id
where ($2::text is null or o.status = $2)
  and ($3::text is null or o.order_number ilike '%' || $3 || '%' or (u.first_name || ' ' || u.last_name) ilike '%' || $3 || '%')
  and ($4::timestamptz is null or o.placed_at < $4)
order by o.placed_at desc limit $1
`

type SalesStaffListOrdersParams struct {
	Limit  int32      `json:"limit"`
	Status *string    `json:"status"`
	Q      *string    `json:"q"`
	Before *time.Time `json:"before"`
}

type SalesStaffListOrdersRow struct {
	ID                       uuid.UUID       `json:"id"`
	OrderNumber              string          `json:"orderNumber"`
	Channel                  string          `json:"channel"`
	CustomerUserID           *uuid.UUID      `json:"customerUserId"`
	BusinessID               *uuid.UUID      `json:"businessId"`
	QuoteID                  *uuid.UUID      `json:"quoteId"`
	PosShiftID               *uuid.UUID      `json:"posShiftId"`
	Status                   string          `json:"status"`
	SubtotalKobo             int64           `json:"subtotalKobo"`
	DeliveryFeeKobo          int64           `json:"deliveryFeeKobo"`
	DiscountKobo             int64           `json:"discountKobo"`
	VatKobo                  int64           `json:"vatKobo"`
	TotalKobo                int64           `json:"totalKobo"`
	Currency                 string          `json:"currency"`
	ShipTo                   json.RawMessage `json:"shipTo"`
	ContactPhone             *string         `json:"contactPhone"`
	PriceHash                *string         `json:"priceHash"`
	PaymentDueAt             *time.Time      `json:"paymentDueAt"`
	AttributedNotificationID *uuid.UUID      `json:"attributedNotificationId"`
	PlacedAt                 time.Time       `json:"placedAt"`
	CancelledAt              *time.Time      `json:"cancelledAt"`
	CreatedAt                time.Time       `json:"createdAt"`
	UpdatedAt                time.Time       `json:"updatedAt"`
	FirstName                *string         `json:"firstName"`
	LastName                 *string         `json:"lastName"`
}

func (q *Queries) SalesStaffListOrders(ctx context.Context, arg SalesStaffListOrdersParams) ([]SalesStaffListOrdersRow, error) {
	rows, err := q.db.Query(ctx, salesStaffListOrders,
		arg.Limit,
		arg.Status,
		arg.Q,
		arg.Before,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SalesStaffListOrdersRow{}
	for rows.Next() {
		var i SalesStaffListOrdersRow
		if err := rows.Scan(
			&i.ID,
			&i.OrderNumber,
			&i.Channel,
			&i.CustomerUserID,
			&i.BusinessID,
			&i.QuoteID,
			&i.PosShiftID,
			&i.Status,
			&i.SubtotalKobo,
			&i.DeliveryFeeKobo,
			&i.DiscountKobo,
			&i.VatKobo,
			&i.TotalKobo,
			&i.Currency,
			&i.ShipTo,
			&i.ContactPhone,
			&i.PriceHash,
			&i.PaymentDueAt,
			&i.AttributedNotificationID,
			&i.PlacedAt,
			&i.CancelledAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.FirstName,
			&i.LastName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const salesTierPrice = `-- name: SalesTierPrice :one
select unit_price_kobo from catalog.price_tiers where listing_id = $1 and min_quantity <= $2 order by min_quantity desc limit 1
`

type SalesTierPriceParams struct {
	ListingID   uuid.UUID `json:"listingId"`
	MinQuantity int32     `json:"minQuantity"`
}

// Best wholesale tier unit price for a quantity (null when no tier applies).
func (q *Queries) SalesTierPrice(ctx context.Context, arg SalesTierPriceParams) (int64, error) {
	row := q.db.QueryRow(ctx, salesTierPrice, arg.ListingID, arg.MinQuantity)
	var unit_price_kobo int64
	err := row.Scan(&unit_price_kobo)
	return unit_price_kobo, err
}

const salesTouchCart = `-- name: SalesTouchCart :exec
update sales.carts set updated_at = now() where id = $1
`

func (q *Queries) SalesTouchCart(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, salesTouchCart, id)
	return err
}

const salesUnpaidExpiredOrders = `-- name: SalesUnpaidExpiredOrders :many
select id, order_number, channel, customer_user_id, business_id, quote_id, pos_shift_id, status, subtotal_kobo, delivery_fee_kobo, discount_kobo, vat_kobo, total_kobo, currency, ship_to, contact_phone, price_hash, payment_due_at, attributed_notification_id, placed_at, cancelled_at, created_at, updated_at from sales.orders where status = 'pending_payment' and payment_due_at < now() order by payment_due_at limit 50
`

func (q *Queries) SalesUnpaidExpiredOrders(ctx context.Context) ([]SalesOrder, error) {
	rows, err := q.db.Query(ctx, salesUnpaidExpiredOrders)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SalesOrder{}
	for rows.Next() {
		var i SalesOrder
		if err := rows.Scan(
			&i.ID,
			&i.OrderNumber,
			&i.Channel,
			&i.CustomerUserID,
			&i.BusinessID,
			&i.QuoteID,
			&i.PosShiftID,
			&i.Status,
			&i.SubtotalKobo,
			&i.DeliveryFeeKobo,
			&i.DiscountKobo,
			&i.VatKobo,
			&i.TotalKobo,
			&i.Currency,
			&i.ShipTo,
			&i.ContactPhone,
			&i.PriceHash,
			&i.PaymentDueAt,
			&i.AttributedNotificationID,
			&i.PlacedAt,
			&i.CancelledAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const salesUpsertCartItem = `-- name: SalesUpsertCartItem :one
insert into sales.cart_items (cart_id, listing_id, quantity) values ($1, $2, $3)
on conflict (cart_id, listing_id) do update set quantity = case when $4::bool then excluded.quantity else sales.cart_items.quantity + excluded.quantity end
returning id, cart_id, listing_id, quantity, added_at
`

type SalesUpsertCartItemParams struct {
	CartID    uuid.UUID `json:"cartId"`
	ListingID uuid.UUID `json:"listingId"`
	Quantity  int32     `json:"quantity"`
	Replace   bool      `json:"replace"`
}

func (q *Queries) SalesUpsertCartItem(ctx context.Context, arg SalesUpsertCartItemParams) (SalesCartItem, error) {
	row := q.db.QueryRow(ctx, salesUpsertCartItem,
		arg.CartID,
		arg.ListingID,
		arg.Quantity,
		arg.Replace,
	)
	var i SalesCartItem
	err := row.Scan(
		&i.ID,
		&i.CartID,
		&i.ListingID,
		&i.Quantity,
		&i.AddedAt,
	)
	return i, err
}
