// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: search.sql

package store

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

const searchActivePins = `-- name: SearchActivePins :many
select id, query_norm, product_id, action, position, starts_at, ends_at, created_by, created_at from search.search_pins where query_norm = $1 and now() between starts_at and ends_at
`

func (q *Queries) SearchActivePins(ctx context.Context, queryNorm string) ([]SearchSearchPin, error) {
	rows, err := q.db.Query(ctx, searchActivePins, queryNorm)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchSearchPin{}
	for rows.Next() {
		var i SearchSearchPin
		if err := rows.Scan(
			&i.ID,
			&i.QueryNorm,
			&i.ProductID,
			&i.Action,
			&i.Position,
			&i.StartsAt,
			&i.EndsAt,
			&i.CreatedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchCreatePin = `-- name: SearchCreatePin :one
insert into search.search_pins (query_norm, product_id, action, position, starts_at, ends_at, created_by)
values ($1, $2, $3, $4, $5, $6, $7) returning id, query_norm, product_id, action, position, starts_at, ends_at, created_by, created_at
`

type SearchCreatePinParams struct {
	QueryNorm string    `json:"queryNorm"`
	ProductID uuid.UUID `json:"productId"`
	Action    string    `json:"action"`
	Position  *int16    `json:"position"`
	StartsAt  time.Time `json:"startsAt"`
	EndsAt    time.Time `json:"endsAt"`
	CreatedBy uuid.UUID `json:"createdBy"`
}

func (q *Queries) SearchCreatePin(ctx context.Context, arg SearchCreatePinParams) (SearchSearchPin, error) {
	row := q.db.QueryRow(ctx, searchCreatePin,
		arg.QueryNorm,
		arg.ProductID,
		arg.Action,
		arg.Position,
		arg.StartsAt,
		arg.EndsAt,
		arg.CreatedBy,
	)
	var i SearchSearchPin
	err := row.Scan(
		&i.ID,
		&i.QueryNorm,
		&i.ProductID,
		&i.Action,
		&i.Position,
		&i.StartsAt,
		&i.EndsAt,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const searchCreateSynonym = `-- name: SearchCreateSynonym :one
insert into search.search_synonyms (terms, target, kind, created_by) values ($1, $2, $3, $4) returning id, terms, target, kind, active, created_by, created_at, updated_at
`

type SearchCreateSynonymParams struct {
	Terms     []string   `json:"terms"`
	Target    string     `json:"target"`
	Kind      string     `json:"kind"`
	CreatedBy *uuid.UUID `json:"createdBy"`
}

func (q *Queries) SearchCreateSynonym(ctx context.Context, arg SearchCreateSynonymParams) (SearchSearchSynonym, error) {
	row := q.db.QueryRow(ctx, searchCreateSynonym,
		arg.Terms,
		arg.Target,
		arg.Kind,
		arg.CreatedBy,
	)
	var i SearchSearchSynonym
	err := row.Scan(
		&i.ID,
		&i.Terms,
		&i.Target,
		&i.Kind,
		&i.Active,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const searchDeactivateSynonym = `-- name: SearchDeactivateSynonym :execrows
update search.search_synonyms set active = false where id = $1
`

func (q *Queries) SearchDeactivateSynonym(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, searchDeactivateSynonym, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const searchGetRedirect = `-- name: SearchGetRedirect :one
select query_norm, url, created_by, expires_at, created_at from search.search_redirects where query_norm = $1 and (expires_at is null or expires_at > now())
`

func (q *Queries) SearchGetRedirect(ctx context.Context, queryNorm string) (SearchSearchRedirect, error) {
	row := q.db.QueryRow(ctx, searchGetRedirect, queryNorm)
	var i SearchSearchRedirect
	err := row.Scan(
		&i.QueryNorm,
		&i.Url,
		&i.CreatedBy,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const searchListGaps = `-- name: SearchListGaps :many
select query_norm, searches_30d, status, owner_id, note, created_at, updated_at from search.catalogue_gaps order by searches_30d desc
`

func (q *Queries) SearchListGaps(ctx context.Context) ([]SearchCatalogueGap, error) {
	rows, err := q.db.Query(ctx, searchListGaps)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchCatalogueGap{}
	for rows.Next() {
		var i SearchCatalogueGap
		if err := rows.Scan(
			&i.QueryNorm,
			&i.Searches30d,
			&i.Status,
			&i.OwnerID,
			&i.Note,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchListRedirects = `-- name: SearchListRedirects :many
select query_norm, url, created_by, expires_at, created_at from search.search_redirects order by created_at desc
`

func (q *Queries) SearchListRedirects(ctx context.Context) ([]SearchSearchRedirect, error) {
	rows, err := q.db.Query(ctx, searchListRedirects)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchSearchRedirect{}
	for rows.Next() {
		var i SearchSearchRedirect
		if err := rows.Scan(
			&i.QueryNorm,
			&i.Url,
			&i.CreatedBy,
			&i.ExpiresAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchListSynonyms = `-- name: SearchListSynonyms :many

select id, terms, target, kind, active, created_by, created_at, updated_at from search.search_synonyms where active order by created_at desc
`

// Search merchandising and analytics (docs/search-catalogue.md §4–§5).
func (q *Queries) SearchListSynonyms(ctx context.Context) ([]SearchSearchSynonym, error) {
	rows, err := q.db.Query(ctx, searchListSynonyms)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchSearchSynonym{}
	for rows.Next() {
		var i SearchSearchSynonym
		if err := rows.Scan(
			&i.ID,
			&i.Terms,
			&i.Target,
			&i.Kind,
			&i.Active,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchLogQuery = `-- name: SearchLogQuery :exec
insert into search.search_queries (session_id, user_id, query_norm, filters, results_count, corrected_to, latency_ms, channel)
values ($1, $2, $3, $4, $5, $6, $7, $8)
`

type SearchLogQueryParams struct {
	SessionID    *string         `json:"sessionId"`
	UserID       *uuid.UUID      `json:"userId"`
	QueryNorm    string          `json:"queryNorm"`
	Filters      json.RawMessage `json:"filters"`
	ResultsCount int32           `json:"resultsCount"`
	CorrectedTo  *string         `json:"correctedTo"`
	LatencyMs    *int32          `json:"latencyMs"`
	Channel      string          `json:"channel"`
}

func (q *Queries) SearchLogQuery(ctx context.Context, arg SearchLogQueryParams) error {
	_, err := q.db.Exec(ctx, searchLogQuery,
		arg.SessionID,
		arg.UserID,
		arg.QueryNorm,
		arg.Filters,
		arg.ResultsCount,
		arg.CorrectedTo,
		arg.LatencyMs,
		arg.Channel,
	)
	return err
}

const searchRebuildSuggestions = `-- name: SearchRebuildSuggestions :exec
with popular as (
  select query_norm, count(*) as n from search.search_queries
  where results_count > 0 and created_at >= now() - interval '30 days'
  group by query_norm having count(*) >= 2
), prefixes as (
  select left(query_norm, l) as prefix, query_norm as suggestion, n from popular, generate_series(1, 4) l
  where length(query_norm) >= l
)
insert into search.search_suggestions (prefix, suggestion, weight)
select prefix, suggestion, n from prefixes
on conflict (prefix, suggestion) do update set weight = excluded.weight
`

// Nightly: popular queries with results become autocomplete entries keyed by 1–4 letter prefixes.
func (q *Queries) SearchRebuildSuggestions(ctx context.Context) error {
	_, err := q.db.Exec(ctx, searchRebuildSuggestions)
	return err
}

const searchStats = `-- name: SearchStats :one
select count(*)::int as searches,
       coalesce(avg((results_count = 0)::int), 0)::float8 as zero_rate,
       coalesce(percentile_cont(0.95) within group (order by latency_ms), 0)::float8 as p95_latency_ms
from search.search_queries where created_at >= now() - interval '7 days'
`

type SearchStatsRow struct {
	Searches     int32   `json:"searches"`
	ZeroRate     float64 `json:"zeroRate"`
	P95LatencyMs float64 `json:"p95LatencyMs"`
}

func (q *Queries) SearchStats(ctx context.Context) (SearchStatsRow, error) {
	row := q.db.QueryRow(ctx, searchStats)
	var i SearchStatsRow
	err := row.Scan(&i.Searches, &i.ZeroRate, &i.P95LatencyMs)
	return i, err
}

const searchTopQueries = `-- name: SearchTopQueries :many
select query_norm, count(*)::int as searches, avg(results_count)::float8 as avg_results, avg(latency_ms)::float8 as avg_latency_ms
from search.search_queries where created_at >= now() - interval '7 days'
group by query_norm order by searches desc limit $1
`

type SearchTopQueriesRow struct {
	QueryNorm    string  `json:"queryNorm"`
	Searches     int32   `json:"searches"`
	AvgResults   float64 `json:"avgResults"`
	AvgLatencyMs float64 `json:"avgLatencyMs"`
}

func (q *Queries) SearchTopQueries(ctx context.Context, limit int32) ([]SearchTopQueriesRow, error) {
	rows, err := q.db.Query(ctx, searchTopQueries, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchTopQueriesRow{}
	for rows.Next() {
		var i SearchTopQueriesRow
		if err := rows.Scan(
			&i.QueryNorm,
			&i.Searches,
			&i.AvgResults,
			&i.AvgLatencyMs,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchUpsertGap = `-- name: SearchUpsertGap :one
insert into search.catalogue_gaps (query_norm, searches_30d, status, owner_id, note) values ($1, $2, $3, $4, $5)
on conflict (query_norm) do update set status = excluded.status, note = excluded.note, owner_id = excluded.owner_id
returning query_norm, searches_30d, status, owner_id, note, created_at, updated_at
`

type SearchUpsertGapParams struct {
	QueryNorm   string     `json:"queryNorm"`
	Searches30d int32      `json:"searches30d"`
	Status      string     `json:"status"`
	OwnerID     *uuid.UUID `json:"ownerId"`
	Note        *string    `json:"note"`
}

func (q *Queries) SearchUpsertGap(ctx context.Context, arg SearchUpsertGapParams) (SearchCatalogueGap, error) {
	row := q.db.QueryRow(ctx, searchUpsertGap,
		arg.QueryNorm,
		arg.Searches30d,
		arg.Status,
		arg.OwnerID,
		arg.Note,
	)
	var i SearchCatalogueGap
	err := row.Scan(
		&i.QueryNorm,
		&i.Searches30d,
		&i.Status,
		&i.OwnerID,
		&i.Note,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const searchUpsertRedirect = `-- name: SearchUpsertRedirect :one
insert into search.search_redirects (query_norm, url, created_by, expires_at) values ($1, $2, $3, $4)
on conflict (query_norm) do update set url = excluded.url, expires_at = excluded.expires_at
returning query_norm, url, created_by, expires_at, created_at
`

type SearchUpsertRedirectParams struct {
	QueryNorm string     `json:"queryNorm"`
	Url       string     `json:"url"`
	CreatedBy *uuid.UUID `json:"createdBy"`
	ExpiresAt *time.Time `json:"expiresAt"`
}

func (q *Queries) SearchUpsertRedirect(ctx context.Context, arg SearchUpsertRedirectParams) (SearchSearchRedirect, error) {
	row := q.db.QueryRow(ctx, searchUpsertRedirect,
		arg.QueryNorm,
		arg.Url,
		arg.CreatedBy,
		arg.ExpiresAt,
	)
	var i SearchSearchRedirect
	err := row.Scan(
		&i.QueryNorm,
		&i.Url,
		&i.CreatedBy,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const searchZeroResults = `-- name: SearchZeroResults :many
select query_norm, count(*)::int as searches, max(created_at) as last_seen
from search.search_queries
where results_count = 0 and created_at >= now() - interval '7 days'
group by query_norm order by searches desc limit $1
`

type SearchZeroResultsRow struct {
	QueryNorm string      `json:"queryNorm"`
	Searches  int32       `json:"searches"`
	LastSeen  interface{} `json:"lastSeen"`
}

func (q *Queries) SearchZeroResults(ctx context.Context, limit int32) ([]SearchZeroResultsRow, error) {
	rows, err := q.db.Query(ctx, searchZeroResults, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchZeroResultsRow{}
	for rows.Next() {
		var i SearchZeroResultsRow
		if err := rows.Scan(&i.QueryNorm, &i.Searches, &i.LastSeen); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
