// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sellers.sql

package store

import (
	"context"

	"github.com/google/uuid"
)

const sellersAddMember = `-- name: SellersAddMember :exec
insert into sellers.seller_members (seller_id, user_id, role) values ($1, $2, $3)
on conflict (seller_id, user_id) do update set role = excluded.role
`

type SellersAddMemberParams struct {
	SellerID uuid.UUID `json:"sellerId"`
	UserID   uuid.UUID `json:"userId"`
	Role     string    `json:"role"`
}

func (q *Queries) SellersAddMember(ctx context.Context, arg SellersAddMemberParams) error {
	_, err := q.db.Exec(ctx, sellersAddMember, arg.SellerID, arg.UserID, arg.Role)
	return err
}

const sellersCreate = `-- name: SellersCreate :one
insert into sellers.sellers (type, display_name, slug, owner_user_id, status, state_code, city, rating_avg, rating_count)
values ($1, $2, $3, $4, $5, $6, $7, $8, $9)
on conflict (slug) do update set display_name = excluded.display_name, status = excluded.status
returning id, type, display_name, slug, owner_user_id, status, state_code, city, rating_avg, rating_count, commission_override_bps, created_at, updated_at
`

type SellersCreateParams struct {
	Type        string     `json:"type"`
	DisplayName string     `json:"displayName"`
	Slug        string     `json:"slug"`
	OwnerUserID *uuid.UUID `json:"ownerUserId"`
	Status      string     `json:"status"`
	StateCode   *string    `json:"stateCode"`
	City        *string    `json:"city"`
	RatingAvg   *float64   `json:"ratingAvg"`
	RatingCount int32      `json:"ratingCount"`
}

func (q *Queries) SellersCreate(ctx context.Context, arg SellersCreateParams) (SellersSeller, error) {
	row := q.db.QueryRow(ctx, sellersCreate,
		arg.Type,
		arg.DisplayName,
		arg.Slug,
		arg.OwnerUserID,
		arg.Status,
		arg.StateCode,
		arg.City,
		arg.RatingAvg,
		arg.RatingCount,
	)
	var i SellersSeller
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.DisplayName,
		&i.Slug,
		&i.OwnerUserID,
		&i.Status,
		&i.StateCode,
		&i.City,
		&i.RatingAvg,
		&i.RatingCount,
		&i.CommissionOverrideBps,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const sellersGet = `-- name: SellersGet :one
select id, type, display_name, slug, owner_user_id, status, state_code, city, rating_avg, rating_count, commission_override_bps, created_at, updated_at from sellers.sellers where id = $1
`

func (q *Queries) SellersGet(ctx context.Context, id uuid.UUID) (SellersSeller, error) {
	row := q.db.QueryRow(ctx, sellersGet, id)
	var i SellersSeller
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.DisplayName,
		&i.Slug,
		&i.OwnerUserID,
		&i.Status,
		&i.StateCode,
		&i.City,
		&i.RatingAvg,
		&i.RatingCount,
		&i.CommissionOverrideBps,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const sellersGetBySlug = `-- name: SellersGetBySlug :one
select id, type, display_name, slug, owner_user_id, status, state_code, city, rating_avg, rating_count, commission_override_bps, created_at, updated_at from sellers.sellers where slug = $1
`

func (q *Queries) SellersGetBySlug(ctx context.Context, slug string) (SellersSeller, error) {
	row := q.db.QueryRow(ctx, sellersGetBySlug, slug)
	var i SellersSeller
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.DisplayName,
		&i.Slug,
		&i.OwnerUserID,
		&i.Status,
		&i.StateCode,
		&i.City,
		&i.RatingAvg,
		&i.RatingCount,
		&i.CommissionOverrideBps,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const sellersGetFirstParty = `-- name: SellersGetFirstParty :one

select id, type, display_name, slug, owner_user_id, status, state_code, city, rating_avg, rating_count, commission_override_bps, created_at, updated_at from sellers.sellers where type = 'first_party'
`

// Sellers (marketplace shops, members, KYC, bank accounts). Plan: trust-safety.md §2.
func (q *Queries) SellersGetFirstParty(ctx context.Context) (SellersSeller, error) {
	row := q.db.QueryRow(ctx, sellersGetFirstParty)
	var i SellersSeller
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.DisplayName,
		&i.Slug,
		&i.OwnerUserID,
		&i.Status,
		&i.StateCode,
		&i.City,
		&i.RatingAvg,
		&i.RatingCount,
		&i.CommissionOverrideBps,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
