// Package httpx holds the HTTP conventions every module uses: RFC 9457 problem+json errors with a
// stable code, the authenticated principal, route guards (audience, permission, step-up),
// signed cursors and Gin middleware (request ID, security headers).
package httpx

import (
	"errors"
	"fmt"
	"log/slog"
	"net/http"
	"strings"

	"github.com/danielgtaylor/huma/v2"
	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgconn"
)

// Problem is the error body (application/problem+json) with a machine-readable code.
type Problem struct {
	Type     string              `json:"type,omitempty" doc:"Problem type URI"`
	Title    string              `json:"title,omitempty" doc:"Short summary"`
	Status   int                 `json:"status,omitempty" doc:"HTTP status"`
	Code     string              `json:"code" doc:"Stable machine-readable error code, e.g. out_of_stock"`
	Detail   string              `json:"detail,omitempty" doc:"Human-readable explanation"`
	Instance string              `json:"instance,omitempty"`
	Errors   []*huma.ErrorDetail `json:"errors,omitempty" doc:"Field-level errors"`
}

func (p *Problem) Error() string                { return p.Detail }
func (p *Problem) GetStatus() int               { return p.Status }
func (p *Problem) ContentType(ct string) string { return "application/problem+json" }

// Install replaces Huma's default error constructors so every error, including validation
// errors generated by Huma itself, is a Problem with a code. 5xx errors are logged with the
// request ID and never expose internal details to the client.
func Install(logger *slog.Logger) {
	huma.NewErrorWithContext = func(ctx huma.Context, status int, msg string, errs ...error) huma.StatusError {
		if status >= 500 {
			rid := ""
			if ctx != nil {
				rid = MetaFrom(ctx.Context()).RequestID
			}
			logger.Error("request failed", slog.String("request_id", rid), slog.Int("status", status), slog.Any("errors", errs))
			return &Problem{Status: status, Title: http.StatusText(status), Code: codeForStatus(status),
				Detail: "Something went wrong on our side. Quote request ID " + rid + " if you contact support."}
		}
		return huma.NewError(status, msg, errs...)
	}
	huma.NewError = func(status int, msg string, errs ...error) huma.StatusError {
		p := &Problem{Status: status, Title: http.StatusText(status), Detail: msg, Code: codeForStatus(status)}
		for _, e := range errs {
			var d *huma.ErrorDetail
			if errors.As(e, &d) {
				p.Errors = append(p.Errors, d)
			} else if e != nil {
				p.Errors = append(p.Errors, &huma.ErrorDetail{Message: e.Error()})
			}
		}
		if status == http.StatusUnprocessableEntity && len(p.Errors) > 0 {
			p.Code = "validation_failed"
		}
		return p
	}
}

func codeForStatus(status int) string {
	switch status {
	case 400:
		return "bad_request"
	case 401:
		return "unauthenticated"
	case 403:
		return "forbidden"
	case 404:
		return "not_found"
	case 405:
		return "method_not_allowed"
	case 409:
		return "conflict"
	case 413:
		return "payload_too_large"
	case 422:
		return "unprocessable"
	case 429:
		return "rate_limited"
	case 503:
		return "unavailable"
	}
	if status >= 500 {
		return "internal_error"
	}
	return "error"
}

// E builds a Problem with an explicit code.
func E(status int, code, detail string) *Problem {
	return &Problem{Status: status, Title: http.StatusText(status), Code: code, Detail: detail}
}

// Field adds a field-level error and returns the problem (for chaining).
func (p *Problem) Field(location, message string, value any) *Problem {
	p.Errors = append(p.Errors, &huma.ErrorDetail{Location: location, Message: message, Value: value})
	return p
}

// Common errors.
func NotFound(what string) *Problem          { return E(404, "not_found", what+" not found") }
func Forbidden(detail string) *Problem       { return E(403, "forbidden", detail) }
func Conflict(code, detail string) *Problem  { return E(409, code, detail) }
func Invalid(code, detail string) *Problem   { return E(422, code, detail) }
func Unauthenticated(detail string) *Problem { return E(401, "unauthenticated", detail) }
func StepUpRequired() *Problem {
	return E(401, "step_up_required", "This action needs a recent authenticator check. Confirm your code and retry.")
}

// DB maps database errors to problems: no rows → 404, unique → 409, check/foreign key → 422.
// Anything else becomes a 500 that never leaks SQL (the request ID links it to the logs).
func DB(err error, what string) error {
	if err == nil {
		return nil
	}
	var p *Problem
	if errors.As(err, &p) {
		return p
	}
	if errors.Is(err, pgx.ErrNoRows) {
		return NotFound(what)
	}
	var pg *pgconn.PgError
	if errors.As(err, &pg) {
		switch pg.Code {
		case "23505":
			return Conflict("already_exists", fmt.Sprintf("%s already exists (%s)", what, constraintHint(pg.ConstraintName)))
		case "23514":
			return Invalid("rule_violated", fmt.Sprintf("%s breaks a business rule (%s)", what, constraintHint(pg.ConstraintName)))
		case "23503":
			return Invalid("reference_not_found", fmt.Sprintf("%s refers to something that doesn't exist", what))
		case "23502":
			return Invalid("missing_value", fmt.Sprintf("%s is missing a required value (%s)", what, pg.ColumnName))
		case "P0001":
			return Invalid("rule_violated", pg.Message)
		case "40001", "40P01":
			return E(409, "retry", "The request conflicted with another one; please retry.")
		}
	}
	return err
}

func constraintHint(name string) string {
	if name == "" {
		return "constraint"
	}
	return strings.ReplaceAll(name, "_", " ")
}
